#include <stdio.h>
#include <stdlib.h>
"test_common.h"
"test_define.c"
#include <pcie.h>

#define CNT 775
#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST_REG_DATA 0x00000000

/* Impacted Registers (from Meta Impacted Registers) */
const unsigned long int impacted_registers[] = {
    mizar_PCIE1_DBI_USP_TYPE1_DEV ID VEND ID REG,
    mizar_PCIE1_DBI_USP_TYPE1_STATUS COMMAND REG,
    mizar_PCIE1_DBI_USP_TYPE1_CLASS CODE REV ID REG,
    mizar_PCIE1_DBI_USP_TYPE1_BIST HDR TYPE LAT CACHE LINE SIZE REG,
    mizar_PCIE1_DBI_USP_BAR0 REG,
    mizar_PCIE1_DBI_USP_CAP ID NXT PTR REG,
    mizar_PCIE1_DBI_USP_DEVICE CONTROL DEVICE STATUS,
    mizar_PCIE1_DBI_USP_PL_DEBUG1_OFF
};

/* Arrays (from Meta Arrays - unchanged) */
const unsigned long int addr_array[20]={mizar_PCIE1_DBI_USP_TYPE1_DEV ID VEND ID REG,mizar_PCIE1_DBI_USP_TYPE1_STATUS COMMAND REG,mizar_PCIE1_DBI_USP_TYPE1_CLASS CODE REV ID REG,mizar_PCIE1_DBI_USP_TYPE1_BIST HDR TYPE LAT CACHE LINE SIZE REG,mizar_PCIE1_DBI_USP_BAR0 REG,};

const int default_value_array[20]={PCIE1_DBI_USP_TYPE1_DEV ID VEND ID REG DEFAULT VAL,PCIE1_DBI_USP_TYPE1_STATUS COMMAND REG DEFAULT VAL,PCIE1_DBI_USP_TYPE1_CLASS CODE REV ID REG DEFAULT VAL,PCIE1_DBI_USP_TYPE1_BIST HDR TYPE LAT CACHE LINE SIZE REG DEFAULT VAL,PCIE1_DBI_USP_BAR0 REG DEFAULT VAL,};

const int read_mask_array[20]={PCIE1_DBI_USP_TYPE1_DEV ID VEND ID REG READ MASK,PCIE1_DBI_USP_TYPE1_STATUS COMMAND REG READ MASK,PCIE1_DBI_USP_TYPE1_CLASS CODE REV ID REG READ MASK,PCIE1_DBI_USP_TYPE1_BIST HDR TYPE LAT CACHE LINE SIZE REG READ MASK,PCIE1_DBI_USP_BAR0 REG READ MASK,};

const int write_mask_array[20]={PCIE1_DBI_USP_TYPE1_DEV ID VEND ID REG WRITE MASK,PCIE1_DBI_USP_TYPE1_STATUS COMMAND REG WRITE MASK,PCIE1_DBI_USP_TYPE1_CLASS CODE REV ID REG WRITE MASK,PCIE1_DBI_USP_TYPE1_BIST HDR TYPE LAT CACHE LINE SIZE REG WRITE MASK,PCIE1_DBI_USP_BAR0 REG WRITE MASK,};

const int skip_array[20]={0,0,0,0,1,1,0,0,0,1,1,1,0,0,1,1,0,0,0,0,};
