#!/usr/bin/env python3
"""Ethernet0 Test Plan Excel Generator - Auto-generated by Agentic Pipeline"""
import json, os, sys
from datetime import datetime, timezone, timedelta

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
except ImportError:
    print("Installing openpyxl...")
    os.system(f"{sys.executable} -m pip install openpyxl")
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp = now_ist.strftime("%Y%m%d_%H%M%S")
filename = f"Ethernet_TestPlan_{timestamp}.xlsx"

# ── Test Plan Data ──
testplan_rows = [
    {
        "Index": "1",
        "SS / Module": "Ethernet",
        "Test Case Name": "ethernet0_reg_wr_rd_test",
        "Feature": "Register Write-Read Verification",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"test_define.c\"; <test_common.h>; <ethernet0/ethernet0_def.h>; <ethernet0/ethernet0_offset.h>",
        "Meta Macros": "#define SOFT_RST_REG_ADDRESS 0x00000000\n#define SOFT_RST_REG_DATA 0x00000000\n#define CNT 434",
        "Meta Arrays": "addr_array[434] = {mizar_ETHERNET0_MAC_CONFIGURATION, mizar_ETHERNET0_MAC_EXT_CONFIGURATION, mizar_ETHERNET0_MAC_PACKET_FILTER, mizar_ETHERNET0_MAC_WD_JB_TIMEOUT, mizar_ETHERNET0_MAC_HASH_TABLE_REG0}; default_value_array[434]; read_mask_array[434]; write_mask_array[434]; skip_array[434]; skip_rst_array[434]; chk_val[6]={0xffffffff,0xaaaaaaaa,0x55555555,0x00000000,0xA5A5A5A5,0xffff0000}",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase performs a comprehensive register write-read verification for the Ethernet0 MAC IP block. It operates in two phases: Phase 1 (chk_rst_val) reads each register and compares against default values. Phase 2 (chk_rd_wr) writes six test patterns (0xffffffff, 0xaaaaaaaa, 0x55555555, 0x00000000, 0xA5A5A5A5, 0xffff0000) and reads back with expected value computation using read/write masks. The soft_reset_chk() function is commented out.",
        "Test Description": "This test verifies the default reset values and write-read accessibility of Ethernet0 MAC registers. It first reads each register and compares against its expected default value. Then it writes six distinct test patterns to each writable register, reads back, and validates the result using the register's read and write masks. The test passes only if all default value checks and all write-read checks succeed.",
        "Meta Test Steps / Procedure": "1. Initialize def_fail_cnt=0, wr_fail_cnt=0.\n2. Call chk_rst_val(): loop i=0 to CNT-1, skip if read_mask==0 or skip_rst==1, read_reg(addr_array[i]), compare to default_value_array[i].\n3. Call chk_rd_wr(): outer loop j=0..5 over chk_val[], inner write loop writes data_wr to all writable registers, inner read loop reads back and computes exp_val=((data_wr & read_mask & write_mask) | ((write_mask^0xffffffff) & read_mask & default_value)).\n4. If def_fail_cnt>0 || wr_fail_cnt>0: finish(1) FAIL, else finish(0) PASS.",
        "Test Steps / Procedure": "1. Initialize fail counters to zero.\n2. Read each register and compare against expected default reset values, skipping non-readable registers.\n3. For each of six test patterns, write to all writable registers, read back, and validate using read/write masks and default values.\n4. Report PASS if zero mismatches, FAIL otherwise.",
        "Meta Impacted Registers": "mizar_ETHERNET0_MAC_CONFIGURATION; mizar_ETHERNET0_MAC_EXT_CONFIGURATION; mizar_ETHERNET0_MAC_PACKET_FILTER; mizar_ETHERNET0_MAC_WD_JB_TIMEOUT; mizar_ETHERNET0_MAC_HASH_TABLE_REG0",
        "Impacted Registers": "MAC_Configuration; MAC_Ext_Configuration; MAC_Packet_Filter; MAC_WD_JB_Timeout; MAC_Hash_Table_Reg0",
        "Meta Validation / Acceptance Criteria": "Phase 1: data_rd == default_value_array[i] for each readable register.\nPhase 2: data_rd == exp_val for each writable/readable register with each test pattern.\nFinal: def_fail_cnt==0 && wr_fail_cnt==0 => finish(0).",
        "Validation / Acceptance Criteria": "1. All registers must return expected default reset values.\n2. All write-read pattern checks must match expected values computed from masks.\n3. Test passes only if zero mismatches across both phases.",
        "Remarks": "addr_array declared [434] but only 5 entries initialized. soft_reset_chk() is commented out. SOFT_RST_REG_ADDRESS excluded per instructions."
    },
    {
        "Index": "2",
        "SS / Module": "Ethernet",
        "Test Case Name": "ethernet0_rx_basic_test",
        "Feature": "Basic RX DMA Reception",
        "Meta Headers": "<stdio.h>; <stdlib.h>; <math.h>; <ethernet0/ethernet0_def.h>; <test_common.h>; <ethernet0/ethernet0_offset.h>; <ethernet0/ethernet0_funcs.h>; <ethernet0/ethernet0_programming_sequence.h>",
        "Meta Macros": "NA",
        "Meta Arrays": "NA",
        "Speed": "1Gbps (default); 100Mbps (ETH_100M); 10Mbps (ETH_10M)",
        "Mode": "Full Duplex (default); Half Duplex (HALF_DUPLEX)",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase verifies basic Ethernet0 RX DMA reception across 4 DMA channels. Configures MAC (TX/RX enable, speed, duplex, address filtering, VLAN, packet filter), MTL (TX/RX queue operation modes, store-and-forward, queue-to-DMA mapping), and DMA (channel control, descriptor addresses, ring lengths, burst sizes, system bus mode, interrupts). RX descriptors preloaded via preload_descriptor_rx(). Starts RX on CH0, triggers VIP, waits for transfer-complete interrupts. ISR reads DMA status, clears channel status registers, clears GIC IRQ.",
        "Test Description": "This test verifies basic Ethernet0 receive DMA operation. It configures MAC, MTL, and DMA layers for all four channels. RX descriptors are preloaded, RX is started on channel 0, and an external VIP sequencer is triggered. The test waits for multiple transfer-complete interrupts. The test passes if all expected transfers complete successfully.",
        "Meta Test Steps / Procedure": "1. GIC_Set(), GIC_EnableAllIRQ().\n2. Configure speed/duplex, interface selection.\n3. Write MAC_CONFIGURATION, MAC_RXQ_CTRL0-2, MAC_RXQ_CTRL4, MAC_VLAN_TAG_CTRL, MAC_PACKET_FILTER.\n4. Program MAC addresses (Address0-3 High/Low).\n5. Configure MTL TX/RX queue operation modes, quantum/weights, interrupt control, RXQ_DMA_MAP0.\n6. Configure DMA CH0-3 TX/RX control, descriptor addresses, ring lengths, system bus mode.\n7. preload_descriptor_rx().\n8. Enable DMA/MAC interrupts.\n9. Start RX on CH0, signal VIP.\n10. Loop waiting for trns_count interrupts.\n11. ISR: read CH0-3 current RX desc/buffer, read/clear DMA status, clear GIC IRQ.",
        "Test Steps / Procedure": "1. Configure GIC and enable interrupts.\n2. Configure MAC layer (speed, duplex, addresses, filters).\n3. Configure MTL layer (queue modes, mapping, interrupts).\n4. Configure DMA layer (channels, descriptors, bus mode).\n5. Preload RX descriptors, start RX, trigger VIP.\n6. Wait for all transfer-complete interrupts.\n7. ISR clears status and GIC IRQ.\n8. Report PASS after all transfers complete.",
        "Meta Impacted Registers": "mizar_ETHERNET0_MAC_CONFIGURATION; mizar_ETHERNET0_MAC_RXQ_CTRL0; mizar_ETHERNET0_MAC_RXQ_CTRL1; mizar_ETHERNET0_MAC_RXQ_CTRL2; mizar_ETHERNET0_MAC_RXQ_CTRL4; mizar_ETHERNET0_MAC_VLAN_TAG_CTRL; mizar_ETHERNET0_MAC_PACKET_FILTER; mizar_ETHERNET0_MAC_ADDRESS0-3_HIGH/LOW; mizar_ETHERNET0_MAC_EXT_CONFIGURATION; mizar_ETHERNET0_MTL_TXQ0-3_OPERATION_MODE; mizar_ETHERNET0_MTL_TXQ0-3_QUANTUM_WEIGHT; mizar_ETHERNET0_MTL_OPERATION_MODE; mizar_ETHERNET0_MTL_RXQ0-3_OPERATION_MODE; mizar_ETHERNET0_MTL_RXQ_DMA_MAP0; mizar_ETHERNET0_MTL_Q0-3_INTERRUPT_CONTROL_STATUS; mizar_ETHERNET0_MTL_RXQ0-3_CONTROL; mizar_ETHERNET0_DMA_CH0-3_TX_CONTROL; mizar_ETHERNET0_DMA_CH0-3_TXDESC_LIST_ADDRESS; mizar_ETHERNET0_DMA_CH0-3_TXDESC_RING_LENGTH; mizar_ETHERNET0_DMA_CH0-3_CONTROL; mizar_ETHERNET0_DMA_CH0-3_RX_CONTROL; mizar_ETHERNET0_DMA_SYSBUS_MODE; mizar_ETHERNET0_DMA_CH0-3_RXDESC_LIST_ADDRESS; mizar_ETHERNET0_DMA_CH0-3_RX_CONTROL2; mizar_ETHERNET0_DMA_CH0-3_INTERRUPT_ENABLE; mizar_ETHERNET0_MAC_INTERRUPT_ENABLE; mizar_ETHERNET0_DMA_MODE; mizar_ETHERNET0_DMA_CH0_RXDESC_TAIL_POINTER; mizar_ETHERNET0_DMA_CH0-3_CURRENT_APP_RXDESC/RXBUFFER; mizar_ETHERNET0_DMA_INTERRUPT_STATUS; mizar_ETHERNET0_DMA_CH0-3_STATUS",
        "Impacted Registers": "MAC_Configuration; MAC_RxQ_Ctrl0; MAC_RxQ_Ctrl1; MAC_RxQ_Ctrl2; MAC_RxQ_Ctrl4; MAC_VLAN_Tag_Ctrl; MAC_Packet_Filter; MAC_Address0-3_High/Low; MAC_Ext_Configuration; MTL_TxQ0-3_Operation_Mode; MTL_TxQ0-3_Quantum_Weight; MTL_Operation_Mode; MTL_RxQ0-3_Operation_Mode; MTL_RxQ_DMA_Map0; MTL_Q0-3_Interrupt_Control_Status; MTL_RxQ0-3_Control; DMA_CH0-3_Tx_Control; DMA_CH0-3_TxDesc_List_Address; DMA_CH0-3_TxDesc_Ring_Length; DMA_CH0-3_Control; DMA_CH0-3_Rx_Control; DMA_SysBus_Mode; DMA_CH0-3_RxDesc_List_Address; DMA_CH0-3_Rx_Control2; DMA_CH0-3_Interrupt_Enable; MAC_Interrupt_Enable; DMA_Mode; DMA_CH0_RxDesc_Tail_Pointer; DMA_CH0-3_Current_App_RxDesc/RxBuffer; DMA_Interrupt_Status; DMA_CH0-3_Status",
        "Meta Validation / Acceptance Criteria": "Interrupt-driven: waits for trns_count (10 default, 6 for 10M) interrupts. ISR reads CH0-3 current RX desc/buffer addresses, reads DMA interrupt status, clears all 4 channel status registers with 0xffffffff, clears GIC IRQ. Final: finish(0) after all interrupts received.",
        "Validation / Acceptance Criteria": "1. DMA RX engine must generate all expected transfer-complete interrupts.\n2. ISR must read DMA channel status and clear successfully.\n3. GIC IRQ must be acknowledged.\n4. Test passes after all transfers complete.",
        "Remarks": "Conditional compilation for speed, duplex, interface selection. Some registers written multiple times. External hex addresses (0XE68C2058, 0xA0243ffc, 0xA0243ff8, 0XE68C2050) used for VIP/external control."
    },
    {
        "Index": "3",
        "SS / Module": "Ethernet",
        "Test Case Name": "ethernet0_tx_basic_test",
        "Feature": "Basic TX DMA Transmission",
        "Meta Headers": "<stdio.h>; <stdlib.h>; <math.h>; <test_common.h>; <ethernet0/ethernet0_def.h>; <ethernet0/ethernet0_offset.h>; <ethernet0/ethernet0_funcs.h>; <ethernet0/ethernet0_programming_sequence.h>",
        "Meta Macros": "NA",
        "Meta Arrays": "NA",
        "Speed": "1Gbps (default); 100Mbps (ETH_100M); 10Mbps (ETH_10M)",
        "Mode": "Full Duplex (default); Half Duplex (HALF_DUPLEX)",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase verifies basic Ethernet0 TX DMA transmission on DMA channel 0. Programs MAC addresses, packet filter, MAC configuration (speed/duplex), signals VIP, configures MTL TX queues (store-and-forward, all queues enabled), DMA system bus mode, preloads TX descriptors via two calls to preload_descriptor(), programs DMA TX descriptor ring lengths/list addresses/tail pointers/control for all 4 channels, enables DMA interrupts, starts TX on CH0 only. ISR reads DMA interrupt status, clears CH0 status, clears GIC IRQ.",
        "Test Description": "This test verifies basic Ethernet0 transmit DMA operation. It configures MAC, MTL, and DMA layers. TX descriptors are preloaded and TX is started on channel 0. The test waits for multiple transfer-complete interrupts. The test passes if all expected transfers complete successfully.",
        "Meta Test Steps / Procedure": "1. GIC_Set(), GIC_EnableAllIRQ().\n2. Configure speed, interface, non_secure_prot_nic().\n3. Program MAC addresses, packet filter, MAC configuration.\n4. Signal VIP (0xA0243ffc, 0xA0243ff8).\n5. Configure MTL TX queue operation modes (all enabled), quantum/weights, interrupt control.\n6. Configure DMA system bus mode.\n7. preload_descriptor() x2.\n8. Program DMA TX desc ring lengths, list addresses, tail pointers, channel control for all 4 channels.\n9. Enable DMA interrupts, write power to 0XE68C2058.\n10. Start TX on CH0 (DMA_CH0_TX_CONTROL=0x00100007).\n11. Loop waiting for trns_count interrupts.\n12. ISR: read DMA_INTERRUPT_STATUS, clear CH0_STATUS, clear GIC IRQ.",
        "Test Steps / Procedure": "1. Configure GIC and enable interrupts.\n2. Configure MAC layer (addresses, filter, speed/duplex).\n3. Signal VIP sequencer.\n4. Configure MTL TX queues and DMA channels.\n5. Preload TX descriptors, start TX on CH0.\n6. Wait for all transfer-complete interrupts.\n7. ISR clears status and GIC IRQ.\n8. Report PASS after all transfers complete.",
        "Meta Impacted Registers": "mizar_ETHERNET0_MAC_ADDRESS0-3_HIGH/LOW; mizar_ETHERNET0_MAC_PACKET_FILTER; mizar_ETHERNET0_MAC_CONFIGURATION; mizar_ETHERNET0_MAC_EXT_CONFIGURATION; mizar_ETHERNET0_MTL_TXQ0-3_OPERATION_MODE; mizar_ETHERNET0_MTL_TXQ0-3_QUANTUM_WEIGHT; mizar_ETHERNET0_MTL_Q0-3_INTERRUPT_CONTROL_STATUS; mizar_ETHERNET0_DMA_SYSBUS_MODE; mizar_ETHERNET0_DMA_CH0-3_TXDESC_RING_LENGTH; mizar_ETHERNET0_DMA_CH0-3_TXDESC_LIST_ADDRESS; mizar_ETHERNET0_DMA_CH0-3_TXDESC_TAIL_POINTER; mizar_ETHERNET0_DMA_CH0-3_CONTROL; mizar_ETHERNET0_DMA_CH0-3_INTERRUPT_ENABLE; mizar_ETHERNET0_DMA_CH0_TX_CONTROL; mizar_ETHERNET0_DMA_INTERRUPT_STATUS; mizar_ETHERNET0_DMA_CH0_STATUS",
        "Impacted Registers": "MAC_Address0-3_High/Low; MAC_Packet_Filter; MAC_Configuration; MAC_Ext_Configuration; MTL_TxQ0-3_Operation_Mode; MTL_TxQ0-3_Quantum_Weight; MTL_Q0-3_Interrupt_Control_Status; DMA_SysBus_Mode; DMA_CH0-3_TxDesc_Ring_Length; DMA_CH0-3_TxDesc_List_Address; DMA_CH0-3_TxDesc_Tail_Pointer; DMA_CH0-3_Control; DMA_CH0-3_Interrupt_Enable; DMA_CH0_Tx_Control; DMA_Interrupt_Status; DMA_CH0_Status",
        "Meta Validation / Acceptance Criteria": "Interrupt-driven: waits for trns_count (10 default, 6 for 10M) interrupts. ISR reads DMA_INTERRUPT_STATUS twice (before/after clear), clears CH0_STATUS with 0xffffffff, writes to 0XE68C2050, clears GIC IRQ. Final: finish(0) after all interrupts.",
        "Validation / Acceptance Criteria": "1. DMA TX engine must generate all expected transfer-complete interrupts.\n2. DMA CH0 status must be cleared successfully.\n3. GIC IRQ must be acknowledged.\n4. Test passes after all transfers complete.",
        "Remarks": "Only CH0 TX started; CH1-3 TX_CONTROL writes commented out. ISR only clears CH0 status. Two preload_descriptor() calls with different parameters. non_secure_prot_nic() called before MAC programming."
    },
    {
        "Index": "4",
        "SS / Module": "Ethernet",
        "Test Case Name": "ethernet0_tx_rx_multi_chnl_test",
        "Feature": "Multi-Channel TX/RX DMA Transfer",
        "Meta Headers": "<stdio.h>; <stdlib.h>; <math.h>; <test_common.h>; <ethernet0/ethernet0_def.h>; <ethernet0/ethernet0_offset.h>; <ethernet0/ethernet0_funcs.h>; <ethernet0/ethernet0_programming_sequence.h>",
        "Meta Macros": "NA",
        "Meta Arrays": "NA",
        "Speed": "1Gbps (default); 100Mbps (ETH_100M); 10Mbps (ETH_10M)",
        "Mode": "Full Duplex (default); Half Duplex (HALF_DUPLEX)",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase verifies Ethernet0 multi-channel TX and RX DMA operation across all four DMA channels (CH0-CH3). Channels are activated sequentially (CH3 first, then CH2, CH1, CH0). Each phase has its own polling loop checking MMC RX/TX packet counts (10, 20, 30, 40). MTL_RXQ_DMA_MAP0 is updated at each phase. 8 calls to preload_descriptor() and 4 calls to preload_descriptor_rx(). ISR manages RX descriptor tail pointer advancement with wrap-around for all 4 channels. MAC addresses programmed with readback verification. MMC_IPC_RX_INTERRUPT_MASK configured.",
        "Test Description": "This test verifies multi-channel Ethernet0 TX and RX DMA operation by sequentially activating all four DMA channels. It configures MAC, MTL, and DMA layers. TX and RX descriptors are preloaded for all channels. Each channel is started in sequence with RX queue mapping updated. The test polls MMC packet counters until expected counts are reached. The test passes when all 40 TX and 40 RX packets complete.",
        "Meta Test Steps / Procedure": "1. GIC_Set(), GIC_EnableAllIRQ(), enet_intf_sel().\n2. Configure MAC (speed/duplex, ext config, RXQ ctrl, VLAN, packet filter, MMC IPC mask).\n3. Program MAC addresses with readback verification.\n4. Configure MTL TX queues (1KB, store-and-forward), RX queues (4096B), interrupt control, RXQ_DMA_MAP0, RXQ control.\n5. Configure DMA TX/RX control, descriptor addresses, ring lengths, system bus mode for all 4 channels.\n6. preload_descriptor() x8, preload_descriptor_rx() x4.\n7. Enable DMA interrupts, configure DMA mode.\n8. Phase 1 (CH3): Start TX/RX, set MAP0=0x83, signal VIP, poll until rxpkt==10 && txpkt==10.\n9. Phase 2 (CH2): Start TX/RX, set MAP0=0x82, poll until rxpkt==20 && txpkt==20.\n10. Phase 3 (CH1): Start TX/RX, set MAP0=0x81, poll until rxpkt==30 && txpkt==30.\n11. Phase 4 (CH0): Start TX/RX, set MAP0=0x80, poll until rxpkt==40 && txpkt==40.\n12. ISR: manage RX desc tail pointers with wrap-around, read/clear DMA status, clear GIC IRQ.",
        "Test Steps / Procedure": "1. Configure GIC, MAC, MTL, DMA for all 4 channels.\n2. Preload TX/RX descriptors for all channels.\n3. Phase 1: Start CH3, poll until 10 TX+RX packets.\n4. Phase 2: Start CH2, poll until 20 TX+RX packets.\n5. Phase 3: Start CH1, poll until 30 TX+RX packets.\n6. Phase 4: Start CH0, poll until 40 TX+RX packets.\n7. ISR manages descriptor tail pointers and clears status.\n8. Report PASS after all phases complete.",
        "Meta Impacted Registers": "mizar_ETHERNET0_MAC_CONFIGURATION; mizar_ETHERNET0_MAC_EXT_CONFIGURATION; mizar_ETHERNET0_MAC_RXQ_CTRL0-2; mizar_ETHERNET0_MAC_VLAN_TAG_CTRL; mizar_ETHERNET0_MAC_PACKET_FILTER; mizar_ETHERNET0_MMC_IPC_RX_INTERRUPT_MASK; mizar_ETHERNET0_MAC_ADDRESS0-3_HIGH/LOW; mizar_ETHERNET0_MTL_TXQ0-3_OPERATION_MODE; mizar_ETHERNET0_MTL_TXQ0-3_QUANTUM_WEIGHT; mizar_ETHERNET0_MTL_OPERATION_MODE; mizar_ETHERNET0_MTL_RXQ0-3_OPERATION_MODE; mizar_ETHERNET0_MTL_Q0-3_INTERRUPT_CONTROL_STATUS; mizar_ETHERNET0_MTL_RXQ_DMA_MAP0; mizar_ETHERNET0_MTL_RXQ0-3_CONTROL; mizar_ETHERNET0_DMA_CH0-3_TX_CONTROL; mizar_ETHERNET0_DMA_CH0-3_TXDESC_LIST_ADDRESS; mizar_ETHERNET0_DMA_CH0-3_TXDESC_RING_LENGTH; mizar_ETHERNET0_DMA_CH0-3_CONTROL; mizar_ETHERNET0_DMA_SYSBUS_MODE; mizar_ETHERNET0_DMA_CH0-3_RX_CONTROL; mizar_ETHERNET0_DMA_CH0-3_RXDESC_LIST_ADDRESS; mizar_ETHERNET0_DMA_CH0-3_RX_CONTROL2; mizar_ETHERNET0_DMA_CH0-3_INTERRUPT_ENABLE; mizar_ETHERNET0_DMA_MODE; mizar_ETHERNET0_DMA_CH0-3_RXDESC_TAIL_POINTER; mizar_ETHERNET0_DMA_CH0-3_TXDESC_TAIL_POINTER; mizar_ETHERNET0_RX_PACKETS_COUNT_GOOD_BAD; mizar_ETHERNET0_TX_PACKET_COUNT_GOOD_BAD; mizar_ETHERNET0_DMA_CH0-3_CURRENT_APP_RXDESC; mizar_ETHERNET0_DMA_INTERRUPT_STATUS; mizar_ETHERNET0_DMA_CH0-3_STATUS",
        "Impacted Registers": "MAC_Configuration; MAC_Ext_Configuration; MAC_RxQ_Ctrl0-2; MAC_VLAN_Tag_Ctrl; MAC_Packet_Filter; MMC_IPC_Rx_Interrupt_Mask; MAC_Address0-3_High/Low; MTL_TxQ0-3_Operation_Mode; MTL_TxQ0-3_Quantum_Weight; MTL_Operation_Mode; MTL_RxQ0-3_Operation_Mode; MTL_Q0-3_Interrupt_Control_Status; MTL_RxQ_DMA_Map0; MTL_RxQ0-3_Control; DMA_CH0-3_Tx_Control; DMA_CH0-3_TxDesc_List_Address; DMA_CH0-3_TxDesc_Ring_Length; DMA_CH0-3_Control; DMA_SysBus_Mode; DMA_CH0-3_Rx_Control; DMA_CH0-3_RxDesc_List_Address; DMA_CH0-3_Rx_Control2; DMA_CH0-3_Interrupt_Enable; DMA_Mode; DMA_CH0-3_RxDesc_Tail_Pointer; DMA_CH0-3_TxDesc_Tail_Pointer; Rx_Packets_Count_Good_Bad; Tx_Packet_Count_Good_Bad; DMA_CH0-3_Current_App_RxDesc; DMA_Interrupt_Status; DMA_CH0-3_Status",
        "Meta Validation / Acceptance Criteria": "Phase 1: rxpkt==10 && txpkt==10. Phase 2: rxpkt==20 && txpkt==20. Phase 3: rxpkt==30 && txpkt==30. Phase 4: rxpkt==40 && txpkt==40. ISR manages RX desc tail pointer wrap-around, clears all 4 channel status registers, clears GIC IRQ. MAC address readback verification. Final: finish(0) after all phases.",
        "Validation / Acceptance Criteria": "1. After each phase, MMC counters must reach expected cumulative counts (10/20/30/40).\n2. ISR must correctly manage RX descriptor tail pointers with wrap-around.\n3. All DMA channel status registers must be cleared.\n4. MAC addresses verified via readback.\n5. Test passes after all 4 phases complete.",
        "Remarks": "Channels activated in reverse order (CH3 first). MTL_RXQ_DMA_MAP0 dynamically updated per phase. enet_sel randomized via rand(). Conditional PRELOAD_AGAIN in ISR. Some commented-out code blocks excluded from analysis."
    }
]

# ── Column definitions ──
testplan_columns = [
    "Index", "SS / Module", "Test Case Name", "Feature",
    "Meta Headers", "Meta Macros", "Meta Arrays",
    "Speed", "Mode", "Memory Start Offset", "Memory End Offset",
    "Meta Test Description", "Test Description",
    "Meta Test Steps / Procedure", "Test Steps / Procedure",
    "Meta Impacted Registers", "Impacted Registers",
    "Meta Validation / Acceptance Criteria", "Validation / Acceptance Criteria",
    "Remarks"
]

metadata_columns = [
    "Index", "Test Case Name", "IP Name", "Base Address",
    "Source Repository", "Source Branch", "Source Path",
    "Total Registers Accessed", "Resolved Count", "Unresolved Count",
    "Generation Timestamp (IST)"
]

metadata_rows = [
    {"Index": "1", "Test Case Name": "ethernet0_reg_wr_rd_test", "IP Name": "Ethernet", "Base Address": "0xE6B00000",
     "Source Repository": "titusbspgit/PSVValidation", "Source Branch": "main",
     "Source Path": "TestRepo/ethernet/ethernet0/ethernet0_reg_wr_rd_test",
     "Total Registers Accessed": "5", "Resolved Count": "5", "Unresolved Count": "0",
     "Generation Timestamp (IST)": now_ist.strftime("%Y-%m-%d %H:%M:%S IST")},
    {"Index": "2", "Test Case Name": "ethernet0_rx_basic_test", "IP Name": "Ethernet", "Base Address": "0xE6B00000",
     "Source Repository": "titusbspgit/PSVValidation", "Source Branch": "main",
     "Source Path": "TestRepo/ethernet/ethernet0/ethernet0_rx_basic_test",
     "Total Registers Accessed": "91", "Resolved Count": "87", "Unresolved Count": "4",
     "Generation Timestamp (IST)": now_ist.strftime("%Y-%m-%d %H:%M:%S IST")},
    {"Index": "3", "Test Case Name": "ethernet0_tx_basic_test", "IP Name": "Ethernet", "Base Address": "0xE6B00000",
     "Source Repository": "titusbspgit/PSVValidation", "Source Branch": "main",
     "Source Path": "TestRepo/ethernet/ethernet0/ethernet0_tx_basic_test",
     "Total Registers Accessed": "51", "Resolved Count": "47", "Unresolved Count": "4",
     "Generation Timestamp (IST)": now_ist.strftime("%Y-%m-%d %H:%M:%S IST")},
    {"Index": "4", "Test Case Name": "ethernet0_tx_rx_multi_chnl_test", "IP Name": "Ethernet", "Base Address": "0xE6B00000",
     "Source Repository": "titusbspgit/PSVValidation", "Source Branch": "main",
     "Source Path": "TestRepo/ethernet/ethernet0/ethernet0_tx_rx_multi_chnl_test",
     "Total Registers Accessed": "96", "Resolved Count": "91", "Unresolved Count": "5",
     "Generation Timestamp (IST)": now_ist.strftime("%Y-%m-%d %H:%M:%S IST")}
]

# ── Generate Excel ──
wb = Workbook()

# -- TestPlan Sheet --
ws1 = wb.active
ws1.title = "TestPlan"

header_font = Font(name='Calibri', bold=True, size=11, color='FFFFFF')
header_fill = PatternFill(start_color='2F5496', end_color='2F5496', fill_type='solid')
cell_font = Font(name='Calibri', size=10)
wrap_align = Alignment(wrap_text=True, vertical='top')
thin_border = Border(
    left=Side(style='thin'), right=Side(style='thin'),
    top=Side(style='thin'), bottom=Side(style='thin')
)

for col_idx, col_name in enumerate(testplan_columns, 1):
    cell = ws1.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(wrap_text=True, vertical='center', horizontal='center')
    cell.border = thin_border

for row_idx, row_data in enumerate(testplan_rows, 2):
    for col_idx, col_name in enumerate(testplan_columns, 1):
        cell = ws1.cell(row=row_idx, column=col_idx, value=row_data.get(col_name, ""))
        cell.font = cell_font
        cell.alignment = wrap_align
        cell.border = thin_border

for col_idx in range(1, len(testplan_columns) + 1):
    ws1.column_dimensions[ws1.cell(row=1, column=col_idx).column_letter].width = 30

ws1.auto_filter.ref = ws1.dimensions
ws1.freeze_panes = 'A2'

# -- Metadata Sheet --
ws2 = wb.create_sheet(title="Metadata")

meta_fill = PatternFill(start_color='4472C4', end_color='4472C4', fill_type='solid')

for col_idx, col_name in enumerate(metadata_columns, 1):
    cell = ws2.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = meta_fill
    cell.alignment = Alignment(wrap_text=True, vertical='center', horizontal='center')
    cell.border = thin_border

for row_idx, row_data in enumerate(metadata_rows, 2):
    for col_idx, col_name in enumerate(metadata_columns, 1):
        cell = ws2.cell(row=row_idx, column=col_idx, value=row_data.get(col_name, ""))
        cell.font = cell_font
        cell.alignment = wrap_align
        cell.border = thin_border

for col_idx in range(1, len(metadata_columns) + 1):
    ws2.column_dimensions[ws2.cell(row=1, column=col_idx).column_letter].width = 25

ws2.auto_filter.ref = ws2.dimensions
ws2.freeze_panes = 'A2'

# -- Save --
output_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(output_dir, filename)
wb.save(output_path)
print(f"Generated: {filename}")
print(f"Path: {output_path}")
print(f"Timestamp (IST): {now_ist.strftime('%Y-%m-%d %H:%M:%S IST')}")
print(f"TestPlan rows: {len(testplan_rows)}")
print(f"Metadata rows: {len(metadata_rows)}")
