#!/usr/bin/env python3
"""PCIE TestPlan XLSX Generator

Generates PCIE_TestPlan_<YYYYMMDD>_<HHMMSS>.xlsx from the JSON data file.
Requires: pip install openpyxl

Usage: python generate_pcie_testplan_xlsx.py
"""
import json
import os
from datetime import datetime, timezone, timedelta

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip install openpyxl")
    exit(1)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILE = os.path.join(SCRIPT_DIR, "PCIE_TestPlan_20250716_120000_data.json")
META_FILE = os.path.join(SCRIPT_DIR, "PCIE_TestPlan_20250716_120000_metadata.json")

IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp_str = now_ist.strftime("%Y%m%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"PCIE_TestPlan_{timestamp_str}.xlsx")

COLUMNS = [
    "Index", "SS / Module", "Test Case Name", "Feature",
    "Meta Headers", "Meta Macros", "Meta Arrays",
    "Speed", "Mode", "Memory Start Offset", "Memory End Offset",
    "Meta Test Description", "Test Description",
    "Meta Test Steps / Procedure", "Test Steps / Procedure",
    "Meta Impacted Registers", "Impacted Registers",
    "Meta Validation / Acceptance Criteria", "Validation / Acceptance Criteria",
    "Remarks"
]

def create_xlsx():
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        testcases = json.load(f)
    with open(META_FILE, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    wb = Workbook()

    # --- TestPlan Sheet ---
    ws = wb.active
    ws.title = "TestPlan"

    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_align = Alignment(vertical="top", wrap_text=True)
    thin_border = Border(
        left=Side(style="thin"), right=Side(style="thin"),
        top=Side(style="thin"), bottom=Side(style="thin")
    )

    for col_idx, col_name in enumerate(COLUMNS, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        cell.border = thin_border

    for row_idx, tc in enumerate(testcases, 2):
        for col_idx, col_name in enumerate(COLUMNS, 1):
            value = tc.get(col_name, "NA")
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.alignment = cell_align
            cell.border = thin_border

    col_widths = {
        1: 8, 2: 14, 3: 32, 4: 22,
        5: 30, 6: 20, 7: 25,
        8: 12, 9: 16, 10: 20, 11: 20,
        12: 60, 13: 60,
        14: 60, 15: 60,
        16: 50, 17: 50,
        18: 60, 19: 60,
        20: 50
    }
    for col_idx, width in col_widths.items():
        ws.column_dimensions[get_column_letter(col_idx)].width = width

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLUMNS))}1"

    # --- Metadata Sheet ---
    ws_meta = wb.create_sheet(title="Metadata")
    meta_header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    meta_header_fill = PatternFill(start_color="548235", end_color="548235", fill_type="solid")

    ws_meta.cell(row=1, column=1, value="Property").font = meta_header_font
    ws_meta.cell(row=1, column=1).fill = meta_header_fill
    ws_meta.cell(row=1, column=1).border = thin_border
    ws_meta.cell(row=1, column=2, value="Value").font = meta_header_font
    ws_meta.cell(row=1, column=2).fill = meta_header_fill
    ws_meta.cell(row=1, column=2).border = thin_border

    meta_rows = [
        ("IP Name", metadata.get("ip_name", "PCIE")),
        ("Generation Timestamp (IST)", now_ist.strftime("%Y-%m-%d %H:%M:%S IST")),
        ("Timezone", metadata.get("timezone", "IST (GMT+05:30)")),
        ("Source Repository", metadata.get("source_repository", "")),
        ("Source Branch", metadata.get("source_branch", "")),
        ("Source Subdirectory", metadata.get("source_subdirectory", "")),
        ("Testcase Count", str(metadata.get("testcase_count", 4))),
        ("Fields Per Testcase", str(metadata.get("fields_per_testcase", 20))),
        ("Testcases", ", ".join(metadata.get("testcases", []))),
        ("Spec Document", metadata.get("spec_document", "")),
        ("Generated By", metadata.get("generated_by", "")),
        ("Output Filename", os.path.basename(OUTPUT_FILE)),
    ]
    for row_idx, (prop, val) in enumerate(meta_rows, 2):
        ws_meta.cell(row=row_idx, column=1, value=prop).border = thin_border
        ws_meta.cell(row=row_idx, column=2, value=val).border = thin_border

    ws_meta.column_dimensions["A"].width = 30
    ws_meta.column_dimensions["B"].width = 80

    wb.save(OUTPUT_FILE)
    print(f"SUCCESS: Generated {OUTPUT_FILE}")
    print(f"  - TestPlan sheet: {len(testcases)} rows x {len(COLUMNS)} columns")
    print(f"  - Metadata sheet: {len(meta_rows)} properties")
    print(f"  - Timestamp (IST): {now_ist.strftime('%Y-%m-%d %H:%M:%S')}")
    return OUTPUT_FILE

if __name__ == "__main__":
    create_xlsx()
