#!/usr/bin/env python3
"""PCIE TestPlan XLSX Generator - Auto-generated by Agent 7
Generates: PCIE_TestPlan_20250716_174500.xlsx
Run: pip install openpyxl && python PCIE_TestPlan_20250716_174500_generator.py
"""
import json
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ============================================================
# EMBEDDED TEST PLAN DATA
# ============================================================
JSON_DATA = [
    {
        "Index": "1",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_device_enumerate_test",
        "Feature": "Device Enumeration",
        "Meta Headers": "<stdlib.h>; <stdio.h>; <test_common.h>; \"pcie.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "NA",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase performs PCIe device enumeration. It begins by writing 0x0 to 0xE6004100, then initiates link training via link_training_dm0_x4 or link_training_dm1_x4 depending on compile-time defines (DM0_RC, DM1_RC, DM0_EP, DM1_EP). Cache coherency programming is performed by read-modify-write sequences on mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF and mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF, setting bit fields [11:14], [3:6], [27:30], and [19:22] to 0xf using set_data(). After wait_on(20), the same coherency registers are programmed again with all four bit fields set to 0xf. The test then polls read_sii0_reg(0xC0) in a while loop until (data_rd & 0xD1) == 0xD1, and similarly polls read_sii1_reg(0xC0). Under DM0_RC, the Vendor ID is read from read_pcie_slv0_reg(0x0), the command register is written via write_pcie_slv0_reg(0x4, 0x7), and memory base programming is invoked via mem_base_program_dm0_x4() and mem_base_program_dm1_x4(). System registers at 0xE690000C, 0xE6900010, 0xE6900014, 0xE6900018, 0xE6900030, 0xE6900034 are written with 0x1. Cache disable programming follows by read-modify-write on both coherency control registers. BAR registers (offsets 0x10-0x24) on both PCIe slave ports are written with 0xFFFFFFFF, read back, then written with specific address values and read back again. Finally, the test polls 0xE6004100 until data_rd equals 0x12345678, then calls finish(0).",
        "Test Description": "This test validates PCIe device enumeration. It initializes the PCIe link by performing link training for x4 configuration. Cache coherency control is programmed on both PCIE0 and PCIE1 instances by modifying specific bit fields in the COHERENCY_CONTROL_3_OFF register. The test polls a link status register on both SII0 and SII1 interfaces until the link reaches the expected ready state. Under Root Complex mode, the Vendor ID is read from the TYPE1_DEV_ID_VEND_ID_REG, and the TYPE1_STATUS_COMMAND_REG is configured to enable memory and bus master access. Memory base address programming is then performed for both dual-mode ports. System-level configuration registers are written to enable specific functions. The cache coherency settings are then disabled. BAR sizing is performed on both PCIe slave ports by writing all-ones to BAR0_REG through PREF_MEM_LIMIT_PREF_MEM_BASE_REG, reading back the size masks, then programming the actual base addresses. The test concludes by polling a synchronization register until a specific completion pattern is received.",
        "Meta Test Steps / Procedure": "1. write_reg(0xE6004100, 0x0). 2. Conditional link training. 3. CACHE PROGRAMMING: read_reg(mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF), set_data, write_reg back. 4-8. Repeat for PCIE1 and re-apply. 9. read_sii0_reg(0xC0) poll. 10. non_secure_prot_nic(). 11. read_sii1_reg(0xC0) poll. 12. read_pcie_slv0_reg(0x0), write_pcie_slv0_reg(0x4, 0x7). 13. mem_base_program. 14. System register writes. 15-18. Disable cache. 19-23. BAR sizing on slv0 and slv1. 24. Poll 0xE6004100 until 0x12345678. 25. finish(0).",
        "Test Steps / Procedure": "1. Clear synchronization register. 2. Initiate PCIe link training in x4 configuration. 3. Program cache coherency on COHERENCY_CONTROL_3_OFF for both instances. 4. Wait for coherency settings. 5. Re-apply coherency. 6. Poll SII0 link status. 7. Configure NIC. 8. Poll SII1 link status. 9. Read Vendor ID from TYPE1_DEV_ID_VEND_ID_REG. 10. Write TYPE1_STATUS_COMMAND_REG. 11. Memory base programming. 12. System register writes. 13. Disable cache coherency. 14. BAR sizing on both ports. 15. Poll synchronization register. 16. Complete test.",
        "Meta Impacted Registers": "0xE6004100; mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF; mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF; 0xC0; 0x0; 0x4; 0xE690000C; 0xE6900010; 0xE6900014; 0xE6900018; 0xE6900030; 0xE6900034; 0x10; 0x14; 0x18; 0x1c; 0x20; 0x24",
        "Impacted Registers": "COHERENCY_CONTROL_3_OFF; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG; BAR0_REG; BAR1_REG; SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG; SEC_STAT_IO_LIMIT_IO_BASE_REG; MEM_LIMIT_MEM_BASE_REG; PREF_MEM_LIMIT_PREF_MEM_BASE_REG",
        "Meta Validation / Acceptance Criteria": "1. Poll read_sii0_reg(0xC0): (data_rd & 0xD1) == 0xD1. 2. Poll read_sii1_reg(0xC0): same. 3. Vendor ID read verified. 4. BAR registers written and read back. 5. Final poll: 0xE6004100 == 0x12345678. 6. finish(0).",
        "Validation / Acceptance Criteria": "1. SII0 link status ready. 2. SII1 link status ready. 3. Valid Vendor ID from TYPE1_DEV_ID_VEND_ID_REG. 4. BAR registers accept writes and read back correctly. 5. Synchronization register returns completion pattern. 6. Test completes with pass.",
        "Remarks": "Duplicated link training block. Conditional compilation selects path. PCIE1 coherency macro unresolved. System registers unmapped. SII link status register unmapped."
    },
    {
        "Index": "2",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_dma_write_test",
        "Feature": "DMA Write and Read",
        "Meta Headers": "<stdlib.h>; <stdio.h>; <test_common.h>; \"pcie.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "NA",
        "Speed": "NA",
        "Mode": "Interrupt Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates PCIe DMA write and read operations across all four DMA channels on both PCIE0 and PCIE1 instances. Source memory is preloaded with 0xC0DEBEED and 0xF00DDEAF patterns. GIC interrupt controller is initialized. DMA interrupt masks are cleared. For each of 4 write channels, the channel is programmed and DMA_WRITE_DOORBELL_OFF is written to trigger transfer. IRQ handler reads DMA_WRITE_INT_STATUS_OFF and clears via DMA_WRITE_INT_CLEAR_OFF. Same for 4 read channels using DMA_READ_DOORBELL_OFF, DMA_READ_INT_STATUS_OFF, DMA_READ_INT_CLEAR_OFF.",
        "Test Description": "This test validates PCIe DMA write and read operations across all four DMA channels on both PCIE0 and PCIE1 controller instances. Link training, Vendor ID read, command register configuration, BAR and memory base programming are performed. Source memory is preloaded with known patterns. GIC is initialized. DMA masks are cleared via DMA_WRITE_INT_MASK_OFF and DMA_READ_INT_MASK_OFF. Each write channel is triggered via DMA_WRITE_DOORBELL_OFF with interrupt-based completion. Each read channel is triggered via DMA_READ_DOORBELL_OFF. Interrupts are serviced by reading DMA_WRITE_INT_STATUS_OFF / DMA_READ_INT_STATUS_OFF and cleared via DMA_WRITE_INT_CLEAR_OFF / DMA_READ_INT_CLEAR_OFF.",
        "Meta Test Steps / Procedure": "1. Clear sync register. 2. Link training. 3. Poll link status. 4. Read Vendor ID, configure command register. 5. BAR and memory base programming. 6. Preload source memory. 7. GIC init. 8. Clear DMA masks. 9-12. DMA write channels 0-3 via doorbell. 13-16. DMA read channels 0-3 via doorbell. 17. IRQ handler reads status and clears. 18. finish(0).",
        "Test Steps / Procedure": "1. Clear synchronization register. 2. Link training x4. 3. Poll link status. 4. Read TYPE1_DEV_ID_VEND_ID_REG. 5. Write TYPE1_STATUS_COMMAND_REG. 6. BAR and memory base programming. 7. Poll sync register. 8. Preload source memory. 9. Init GIC. 10. Unmask DMA interrupts. 11. For each write channel: program, trigger via DMA_WRITE_DOORBELL_OFF, wait for interrupt. 12. For each read channel: program, trigger via DMA_READ_DOORBELL_OFF, wait for interrupt. 13. IRQ handler reads status and clears. 14. Complete test.",
        "Meta Impacted Registers": "0xE6004100; 0xC0; 0x0; 0x4; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_MASK_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_MASK_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_DOORBELL_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_DOORBELL_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_MASK_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_MASK_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_DOORBELL_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_DOORBELL_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_STATUS_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_STATUS_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_CLEAR_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_STATUS_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_STATUS_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_CLEAR_OFF",
        "Impacted Registers": "TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG; DMA_WRITE_INT_MASK_OFF; DMA_READ_INT_MASK_OFF; DMA_WRITE_DOORBELL_OFF; DMA_READ_DOORBELL_OFF; DMA_WRITE_INT_STATUS_OFF; DMA_READ_INT_STATUS_OFF; DMA_WRITE_INT_CLEAR_OFF; DMA_READ_INT_CLEAR_OFF",
        "Meta Validation / Acceptance Criteria": "1. Link status poll passes. 2. Vendor ID valid. 3. Sync register == 0x12345678. 4. Each DMA write channel completes via interrupt. 5. Each DMA read channel completes via interrupt. 6. Status registers show completion. 7. Interrupts cleared. 8. finish(0).",
        "Validation / Acceptance Criteria": "1. Link status ready. 2. Valid Vendor ID. 3. Sync register completion. 4. All 4 write channels complete with interrupt. 5. All 4 read channels complete with interrupt. 6. DMA status registers confirm completion. 7. Interrupts properly cleared. 8. Test passes.",
        "Remarks": "Interrupt-driven DMA via GIC. All PCIE1 DMA macros unresolved. Sync register and SII link status unmapped. Transfer length 0x40 bytes per channel. Data patterns 0xC0DEBEED and 0xF00DDEAF."
    },
    {
        "Index": "3",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_mem_wr_rd_test",
        "Feature": "Memory Write and Read",
        "Meta Headers": "<stdlib.h>; <stdio.h>; <test_common.h>; \"pcie.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "NA",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates PCIe memory space write and read operations through PCIe slave ports. Cache coherency is programmed via COHERENCY_CONTROL_3_OFF. Link status is polled. Vendor ID read, command register configured. Memory write-read operations at multiple addresses via pcie_slv0_mem_wr_rd and pcie_slv1_mem_wr_rd with known data patterns. Cache coherency disabled in staged sequence. Sync register polled for completion.",
        "Test Description": "This test validates PCIe memory space write and read operations through the PCIe slave ports. Cache coherency is programmed on both instances via COHERENCY_CONTROL_3_OFF. Link status is polled. TYPE1_DEV_ID_VEND_ID_REG and TYPE1_STATUS_COMMAND_REG are configured. Memory write-read operations verify data integrity across the PCIe link at multiple addresses. Cache coherency is disabled. Sync register confirms completion.",
        "Meta Test Steps / Procedure": "1. Clear sync register. 2. Link training. 3. Cache programming on COHERENCY_CONTROL_3_OFF. 4-8. Re-apply and poll link status. 9-15. Configure, BAR program, signal readiness. 16-22. Disable cache in stages. 23-27. Memory write-read operations. 28. Poll sync register. 29. finish(0).",
        "Test Steps / Procedure": "1. Clear sync register. 2. Link training x4. 3. Program cache coherency. 4. Wait and re-apply. 5. Poll link status. 6. Read Vendor ID. 7. Write command register. 8. BAR and memory base programming. 9. Signal readiness. 10. Disable cache coherency. 11. Perform memory write-read operations. 12. Poll sync register. 13. Complete test.",
        "Meta Impacted Registers": "0xE6004100; mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF; mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF; 0xC0; 0x0; 0x4",
        "Impacted Registers": "COHERENCY_CONTROL_3_OFF; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG",
        "Meta Validation / Acceptance Criteria": "1. Link status polls pass. 2. Vendor ID valid. 3. Memory write-read data integrity verified. 4. Sync register == 0x12345678. 5. finish(0).",
        "Validation / Acceptance Criteria": "1. Link status ready. 2. Valid Vendor ID. 3. Memory write-read data matches. 4. Sync register completion. 5. Test passes.",
        "Remarks": "Conditional compilation selects paths. PCIE1 coherency macro unresolved. Sync register and SII link status unmapped. Endpoint mode uses long wait. Cache disable is staged."
    },
    {
        "Index": "4",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_reg_wr_rd_test",
        "Feature": "Register Write and Read",
        "Meta Headers": "<stdlib.h>; <stdio.h>; <test_common.h>; <pcie.h>",
        "Meta Macros": "NA",
        "Meta Arrays": "rc0_ctl_addr[5]; rc1_ctl_addr[5]; ctl_default[5]; sii0_addr[3]; sii1_addr[3]; sii_default[3]; phy0_addr[3]; phy1_addr[3]; chk_val[6]; chk_val_phy[3]",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates register reset default values and write-read functionality across DBI DSP registers, SII registers, and PHY registers on both PCIE0 and PCIE1. Phase 1 reads all registers and compares against expected defaults (0x0). PHY reset control is written to bring PHY out of reset. Phase 2 writes multiple data patterns (0xffffffff, 0xaaaaaaaa, 0x55555555) and reads back with write mask verification. PHY uses 16-bit extraction and 13-bit write masks.",
        "Test Description": "This test validates register reset default values and register write-read functionality across multiple PCIe register groups on both PCIE0 and PCIE1. DBI DSP registers (MSI_CAP_OFF_08H_REG, MSI_CAP_OFF_10H_REG, FILTER_MASK_2_OFF, AXI_MSTR_MSG_ADDR_HIGH_OFF, UTILITY_OFF), SII registers, and PHY registers are tested. Reset defaults are verified. Multiple data patterns are written and read back with write mask application.",
        "Meta Test Steps / Procedure": "1. chk_rst_val(): Read rc0_ctl_addr, rc1_ctl_addr, sii0_addr, sii1_addr vs defaults. 2. Write PHY RST control. 3. Read PHY registers with 16-bit extraction. 4. chk_rd_wr(): For j=0..2, write chk_val[j] to all register groups, read back and compare. 5. SII uses write masks. 6. PHY uses 13-bit masks. 7. finish(err2 || err1).",
        "Test Steps / Procedure": "1. Read DBI DSP registers on PCIE0 and verify reset defaults. 2. Read DBI DSP registers on PCIE1 and verify. 3. Read SII registers and verify defaults. 4. Write PHY reset control. 5. Read PHY registers and verify defaults. 6. Write-read verify with three data patterns. 7. Verify SII with write masks. 8. Verify PHY with 13-bit masks. 9. Check error count is zero. 10. Complete test.",
        "Meta Impacted Registers": "mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_08H_REG; mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_10H_REG; mizar_PCIE0_DBI_DSP_FILTER_MASK_2_OFF; mizar_PCIE0_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF; mizar_PCIE0_DBI_DSP_UTILITY_OFF; mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_08H_REG; mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_10H_REG; mizar_PCIE1_DBI_DSP_FILTER_MASK_2_OFF; mizar_PCIE1_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF; mizar_PCIE1_DBI_DSP_UTILITY_OFF; mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER2; mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER3; mizar_PCIE0_SII_PHY_CONTROL_23; mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER2; mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER3; mizar_PCIE1_SII_PHY_CONTROL_23; mizar_PCIE0_SII_PHY_RST_CONTROL; mizar_PCIE1_SII_PHY_RST_CONTROL; 0xE68860B8; 0xE68862B8; 0xE68864B8; 0xE68A60B8; 0xE68A62B8; 0xE68A64B8",
        "Impacted Registers": "MSI_CAP_OFF_08H_REG; MSI_CAP_OFF_10H_REG; FILTER_MASK_2_OFF; AXI_MSTR_MSG_ADDR_HIGH_OFF; UTILITY_OFF",
        "Meta Validation / Acceptance Criteria": "1. All registers read reset default 0x0. 2. Write-read with 0xffffffff, 0xaaaaaaaa, 0x55555555 matches. 3. SII write-mask applied correctly. 4. PHY 13-bit mask and 16-bit extraction correct. 5. finish(err2 || err1) == finish(0).",
        "Validation / Acceptance Criteria": "1. All reset defaults verified as zero. 2. All write-read patterns match expected values. 3. SII write masks applied correctly. 4. PHY write masks applied correctly. 5. Zero errors for pass.",
        "Remarks": "Three register groups with different behaviors. PHY uses 16-bit extraction. SII has per-register write masks. All PCIE1 DBI/SII macros unresolved. All PHY hex addresses unresolved. Write-read loop iterates 3 of 6 defined patterns."
    }
]

# ============================================================
# SHEET COLUMN DEFINITIONS
# ============================================================
TESTPLAN_COLUMNS = [
    "Index", "SS / Module", "Feature", "Test Case Name",
    "Test Description", "Speed", "Mode", "Memory Start Offset",
    "Memory End Offset", "Remarks", "Test Steps / Procedure",
    "Impacted Registers", "Validation / Acceptance Criteria",
    "Code Generation"
]

METADATA_COLUMNS = [
    "Index", "Test Case Name", "Meta Test Description",
    "Meta Test Steps / Procedure", "Meta Impacted Registers",
    "Meta Validation / Acceptance Criteria", "Meta Headers",
    "Meta Macros", "Meta Arrays"
]

def create_workbook():
    wb = Workbook()

    # ---- TestPlan Sheet ----
    ws_tp = wb.active
    ws_tp.title = "TestPlan"

    # ---- MetaData Sheet ----
    ws_md = wb.create_sheet(title="MetaData")
    ws_md.sheet_state = "veryHidden"

    # ---- Styles ----
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_alignment = Alignment(vertical="top", wrap_text=True)
    thin_border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin")
    )

    def write_sheet(ws, columns, data):
        # Write header
        for col_idx, col_name in enumerate(columns, 1):
            cell = ws.cell(row=1, column=col_idx, value=col_name)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment
            cell.border = thin_border

        # Write data rows
        for row_idx, row_data in enumerate(data, 2):
            for col_idx, col_name in enumerate(columns, 1):
                value = row_data.get(col_name, "")
                if value is None:
                    value = ""
                cell = ws.cell(row=row_idx, column=col_idx, value=str(value))
                cell.alignment = cell_alignment
                cell.border = thin_border

        # Auto-size columns
        for col_idx, col_name in enumerate(columns, 1):
            max_len = len(col_name)
            for row_idx in range(2, len(data) + 2):
                cell_val = str(ws.cell(row=row_idx, column=col_idx).value or "")
                lines = cell_val.split("\n")
                for line in lines:
                    max_len = max(max_len, len(line))
            # Cap width at 60 for readability
            adjusted_width = min(max_len + 4, 60)
            adjusted_width = max(adjusted_width, 12)
            ws.column_dimensions[get_column_letter(col_idx)].width = adjusted_width

        # Freeze first row
        ws.freeze_panes = "A2"

        # Auto-filter
        ws.auto_filter.ref = f"A1:{get_column_letter(len(columns))}{len(data) + 1}"

    # Populate TestPlan sheet
    write_sheet(ws_tp, TESTPLAN_COLUMNS, JSON_DATA)

    # Populate MetaData sheet
    write_sheet(ws_md, METADATA_COLUMNS, JSON_DATA)

    # Save
    output_dir = os.path.dirname(os.path.abspath(__file__))
    filename = "PCIE_TestPlan_20250716_174500.xlsx"
    filepath = os.path.join(output_dir, filename)
    wb.save(filepath)
    print(f"Workbook saved: {filepath}")
    print(f"File size: {os.path.getsize(filepath)} bytes")

    # Validate
    from openpyxl import load_workbook
    wb_check = load_workbook(filepath)
    assert "TestPlan" in wb_check.sheetnames, "TestPlan sheet missing"
    assert "MetaData" in wb_check.sheetnames, "MetaData sheet missing"
    tp_rows = wb_check["TestPlan"].max_row - 1
    md_rows = wb_check["MetaData"].max_row - 1
    print(f"Validation PASSED: TestPlan={tp_rows} rows, MetaData={md_rows} rows")
    return filepath

if __name__ == "__main__":
    create_workbook()
