#include <stdio.h>
#include <stdlib.h>
"test_common.h"
"test_define.c"
#include <pcie.h>

#define SOFT_RST REG ADDRESS 0x00000000
#define SOFT_RST REG DATA 0x00000000
#define CNT 775

/* Impacted Registers array (mapped via RAG) */
const unsigned long int addr_array[] = {
    mizar_PCIE1_DBI_USP_TYPE1_DEV_ID_VEND_ID_REG,
    mizar_PCIE1_DBI_USP_TYPE1_STATUS_COMMAND_REG,
    mizar_PCIE1_DBI_USP_TYPE1_CLASS_CODE_REV_ID_REG,
    mizar_PCIE1_DBI_USP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG,
    mizar_PCIE1_DBI_USP_BAR0_REG,
    mizar_PCIE1_DBI_USP_CAP_ID_NXT_PTR_REG,
    mizar_PCIE1_DBI_USP_DEVICE_CONTROL_DEVICE_STATUS,
    mizar_PCIE1_DBI_USP_PL_DEBUG1_OFF
};

/* Default value, read mask, write mask and skip arrays as per Meta Arrays (unchanged) */
const int default_value_array[20] = {
    PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG DEFAULT VAL,
    PCIE1_DBI_USP TYPE1 STATUS COMMAND REG DEFAULT VAL,
    PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG DEFAULT VAL,
    PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG DEFAULT VAL,
    PCIE1_DBI_USP BAR0 REG DEFAULT VAL,
};

const int read_mask_array[20] = {
    PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG READ MASK,
    PCIE1_DBI_USP TYPE1 STATUS COMMAND REG READ MASK,
    PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG READ MASK,
    PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG READ MASK,
    PCIE1_DBI_USP BAR0 REG READ MASK,
};

const int write_mask_array[20] = {
    PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG WRITE MASK,
    PCIE1_DBI_USP TYPE1 STATUS COMMAND REG WRITE MASK,
    PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG WRITE MASK,
    PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG WRITE MASK,
    PCIE1_DBI_USP BAR0 REG WRITE MASK,
};

const int skip_array[20] = {0,0,0,0,1,1,0,0,0,1,1,1,0,0,1,1,0,0,0,0};

int chk_val[6] = {0xffffffff,0xaaaaaaaa,0x55555555,0x00000000,0xA5A5A5A5,0xffff0000};
