/* Auto-generated test define file for pcie1_dbi_usp_reg_wr_rd_test */
#ifndef TEST_DEFINE_C_FILE
#define TEST_DEFINE_C_FILE

/* Headers from Meta Headers (unchanged) */
#include <stdio.h>
#include <stdlib.h>
"test_common.h"
"test_define.c"
#include <pcie.h>

/* Macros from Meta Macros (unchanged) */
#define SOFT_RST REG ADDRESS 0x00000000
#define SOFT_RST REG DATA 0x00000000
#define CNT 775

/* Impacted Registers RAG mapping (comments only; no behavioral change) */
/*
- mizar_PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG -> TYPE1_DEV_ID_VEND_ID_REG, Offset 0x0, Width 32
- mizar_PCIE1_DBI_USP TYPE1 STATUS COMMAND REG -> TYPE1_STATUS_COMMAND_REG, Offset 0x4, Width 32
- mizar_PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG -> TYPE1_CLASS_CODE_REV_ID_REG, Offset 0x8, Width 32
- mizar_PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG -> TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG, Offset 0xC, Width 32
- mizar_PCIE1_DBI_USP BAR0 REG -> BAR0_REG, Offset 0x10, Width 32
- mizar_PCIE1_DBI_USP CAP ID NXT PTR REG -> CAP_ID_NXT_PTR_REG, Offset 0x0, Width 32
- mizar_PCIE1_DBI_USP DEVICE CONTROL DEVICE STATUS -> Spec Not Found
- mizar_PCIE1_DBI_USP PL DEBUG1 OFF -> Spec Not Found
*/

/* Arrays from Meta Arrays (verbatim) */
const unsigned long int addr_array[20]={mizar_PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG,mizar_PCIE1_DBI_USP TYPE1 STATUS COMMAND REG,mizar_PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG,mizar_PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG,mizar_PCIE1_DBI_USP BAR0 REG,};

const int default_value_array[20]={PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG DEFAULT VAL,PCIE1_DBI_USP TYPE1 STATUS COMMAND REG DEFAULT VAL,PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG DEFAULT VAL,PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG DEFAULT VAL,PCIE1_DBI_USP BAR0 REG DEFAULT VAL,};

const int read_mask_array[20]={PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG READ MASK,PCIE1_DBI_USP TYPE1 STATUS COMMAND REG READ MASK,PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG READ MASK,PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG READ MASK,PCIE1_DBI_USP BAR0 REG READ MASK,};

const int write_mask_array[20]={PCIE1_DBI_USP TYPE1 DEV ID VEND ID REG WRITE MASK,PCIE1_DBI_USP TYPE1 STATUS COMMAND REG WRITE MASK,PCIE1_DBI_USP TYPE1 CLASS CODE REV ID REG WRITE MASK,PCIE1_DBI_USP TYPE1 BIST HDR TYPE LAT CACHE LINE SIZE REG WRITE MASK,PCIE1_DBI_USP BAR0 REG WRITE MASK,};

const int skip_array[20]={0,0,0,0,1,1,0,0,0,1,1,1,0,0,1,1,0,0,0,0,};

int chk_val[6]={0xffffffff,0xaaaaaaaa,0x55555555,0x00000000,0xA5A5A5A5,0xffff0000};

#endif /* TEST_DEFINE_C_FILE */
