#!/usr/bin/env python3
"""Generate PCIE TestPlan Excel workbook and commit it to the repository."""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from datetime import datetime, timezone, timedelta
import os
import sys

IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp_str = now_ist.strftime("%Y%m%d_%H%M%S")
filename = f"PCIE_TestPlan_{timestamp_str}.xlsx"
output_dir = "Test_Output/PCIE/TestPlan"
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, filename)

# Column definitions
testplan_columns = [
    "Index", "SS / Module", "Feature", "Test Case Name", "Test Description",
    "Speed", "Mode", "Memory Start Offset", "Memory End Offset", "Remarks",
    "Test Steps / Procedure", "Impacted Registers", "Validation / Acceptance Criteria",
    "Code Generation"
]

metadata_columns = [
    "Index", "Test Case Name", "Meta Test Description", "Meta Test Steps / Procedure",
    "Meta Impacted Registers", "Meta Validation / Acceptance Criteria",
    "Meta Headers", "Meta Macros", "Meta Arrays"
]

# Full JSON data
json_data = [
    {
        "Index": "1",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_device_enumerate_test",
        "Feature": "Device Enumeration",
        "Meta Headers": '<stdlib.h>; <stdio.h>; <test_common.h>; \"pcie.h\"',
        "Meta Macros": "DM0_RC; DM1_RC; DM0_EP; DM1_EP; DEBUG_DISPLAY",
        "Meta Arrays": "NA",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase performs PCIe device enumeration. It begins by writing 0x0 to 0xE6004100, then conditionally invokes link training (link_training_dm0_x4 or link_training_dm1_x4) based on DM0_RC, DM1_RC, DM0_EP, or DM1_EP compile-time defines. Cache programming is performed by reading mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF and mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF, modifying specific bit fields (bits 11-14, 3-6, 27-30, 19-22) using set_data(), and writing back. After wait_on(20), the same cache programming is repeated. The test then polls read_sii0_reg(0xC0) until (data_rd & 0xD1) == 0xD1, and similarly polls read_sii1_reg(0xC0). Under DM0_RC, the Vendor ID is read from read_pcie_slv0_reg(0x0), command register is written via write_pcie_slv0_reg(0x4, 0x7), and memory base programming is invoked for dm0 and dm1. Six system-level registers at 0xE690000C through 0xE6900034 are written with 0x1. Cache disable programming follows by read-modify-writing the coherency control registers with 0x0 for bits 19-22 and 27-30. After wait_on(30), BAR registers (0x10-0x24) on pcie_slv1 and pcie_slv0 are written with 0xFFFFFFFF, read back, then programmed with specific address values (0x0, 0x4, 0x20000000, 0x40000000, 0x60000000, 0x80000000) and read back again. Finally, 0xE6004100 is polled until it equals 0x12345678, then finish(0) is called.",
        "Test Description": "This testcase validates PCIe device enumeration by performing link training, programming coherency control registers for cache enable and disable, polling the GIC register for link status readiness, reading the device Vendor ID, configuring the command register, programming memory base addresses, writing system-level configuration registers, and performing BAR sizing and assignment on both PCIe slave interfaces. The test concludes by polling a synchronization register until a completion handshake value is received.",
        "Meta Test Steps / Procedure": "1. write_reg(0xE6004100, 0x0) to initialize synchronization register. 2. Conditionally call link_training_dm0_x4(4) or link_training_dm1_x4(4) based on DM0_RC/DM1_RC/DM0_EP/DM1_EP defines. 3. Cache programming: read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set_data bits [11:14]=0xf, [3:6]=0xf, write back. 4. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF again, set_data bits [27:30]=0xf, [19:22]=0xf, write back. 5. Repeat steps 3-4 for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 6. wait_on(20). 7. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set_data bits [11:14]=0xf, [3:6]=0xf, [27:30]=0xf, [19:22]=0xf, write back. 8. Repeat step 7 for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 9. Repeat link training and cache programming sequence (duplicate block in source). 10. Read read_sii0_reg(0xC0) into data_rd. 11. Call non_secure_prot_nic(). 12. Poll read_sii0_reg(0xC0) in while loop until (data_rd & 0xD1) == 0xD1. 13. Read read_sii1_reg(0xC0) and poll until (data_rd & 0xD1) == 0xD1. 14. Under DM0_RC: read_pcie_slv0_reg(0x0) to get Vendor ID. 15. write_pcie_slv0_reg(0x4, 0x7) to enable command register. 16. Call mem_base_program_dm0_x4() and mem_base_program_dm1_x4(). 17. wait_on(10). 18. Write 0x1 to 0xE690000C, 0xE6900010, 0xE6900014, 0xE6900018, 0xE6900030, 0xE6900034. 19. Cache disable: read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set_data bits [11:14]=0xf, [3:6]=0xf, write back; then set bits [27:30]=0xf, [19:22]=0x0, write back. 20. Repeat cache disable for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 21. wait_on(10), then combined cache disable for both PCIE0 and PCIE1 with bits [27:30]=0x0, [19:22]=0x0. 22. wait_on(30). 23. Write 0xFFFFFFFF to pcie_slv1 registers at offsets 0x10, 0x14, 0x18, 0x1c, 0x20, 0x24 (BAR sizing). 24. Read back pcie_slv1 registers at same offsets. 25. Write specific address values to pcie_slv1 BAR registers: 0x0, 0x4, 0x20000000, 0x40000000, 0x60000000, 0x80000000. 26. Read back pcie_slv1 BAR registers. 27. Repeat steps 23-26 for pcie_slv0. 28. wait_on(10). 29. Poll read_reg(0xE6004100) until data_rd == 0x12345678, with wait_on(5) between iterations. 30. Call finish(0).",
        "Test Steps / Procedure": "1. Initialize the synchronization register by writing zero to clear it. 2. Perform PCIe link training for the configured dual-mode controller (x4 width). 3. Program the COHERENCY_CONTROL_3_OFF register for PCIE0 by reading, setting cache-enable bit fields (bits 11-14, 3-6, 27-30, 19-22 to 0xF), and writing back. 4. Repeat coherency control cache-enable programming for PCIE1. 5. Wait for stabilization, then re-apply combined cache-enable programming for both PCIE0 and PCIE1 COHERENCY_CONTROL_3_OFF registers. 6. Repeat the link training and cache programming sequence. 7. Read the gic register on SII0 interface and poll until link status bits (mask 0xD1) indicate readiness. 8. Configure non-secure protection via NIC. 9. Poll the gic register on SII1 interface until link status bits indicate readiness. 10. Read the TYPE1_DEV_ID_VEND_ID_REG on PCIe slave 0 to retrieve the Vendor ID. 11. Write to TYPE1_STATUS_COMMAND_REG on PCIe slave 0 to enable bus master, memory space, and I/O space access. 12. Invoke memory base programming for both dual-mode controllers. 13. Write enable values to six system-level configuration registers. 14. Perform cache-disable programming on COHERENCY_CONTROL_3_OFF for both PCIE0 and PCIE1 by clearing bits 19-22 and 27-30. 15. Wait, then finalize cache-disable by clearing all cache fields in COHERENCY_CONTROL_3_OFF for both controllers. 16. Perform BAR sizing on PCIe slave 1 by writing all-ones to BAR0_REG through PREF_MEM_LIMIT_PREF_MEM_BASE_REG and reading back. 17. Assign BAR address values on PCIe slave 1 and verify by reading back. 18. Repeat BAR sizing and address assignment on PCIe slave 0. 19. Poll the synchronization register until the expected completion handshake value is received. 20. Complete the test.",
        "Meta Impacted Registers": "0xE6004100; mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF; mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF; 0xC0; 0x0; 0x4; 0xE690000C; 0xE6900010; 0xE6900014; 0xE6900018; 0xE6900030; 0xE6900034; 0x10; 0x14; 0x18; 0x1c; 0x20; 0x24",
        "Impacted Registers": "COHERENCY_CONTROL_3_OFF; gic; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG; BAR0_REG; BAR1_REG; SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG; SEC_STAT_IO_LIMIT_IO_BASE_REG; MEM_LIMIT_MEM_BASE_REG; PREF_MEM_LIMIT_PREF_MEM_BASE_REG",
        "Meta Validation / Acceptance Criteria": "1. Poll read_sii0_reg(0xC0): while loop checks (data_rd & 0xD1) != 0xD1, exits when all required link status bits are set. 2. Poll read_sii1_reg(0xC0): same condition (data_rd & 0xD1) == 0xD1. 3. read_pcie_slv0_reg(0x0) returns Vendor ID which is printed. 4. BAR sizing: write 0xFFFFFFFF to offsets 0x10-0x24 on pcie_slv1 and pcie_slv0, read back to determine BAR sizes. 5. BAR assignment: write specific address values (0x0, 0x4, 0x20000000, 0x40000000, 0x60000000, 0x80000000) to offsets 0x10-0x24, read back to verify. 6. Final poll: read_reg(0xE6004100) must equal 0x12345678 to exit the while loop and call finish(0). 7. finish(0) indicates test pass.",
        "Validation / Acceptance Criteria": "1. The gic register on SII0 must be polled until link status bits (mask 0xD1) are all set, confirming PCIE0 link readiness. 2. The gic register on SII1 must similarly indicate link readiness. 3. The TYPE1_DEV_ID_VEND_ID_REG must return a valid Vendor ID when read. 4. BAR sizing on both PCIe slave interfaces must return valid size masks when all-ones are written to BAR0_REG, BAR1_REG, SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG, SEC_STAT_IO_LIMIT_IO_BASE_REG, MEM_LIMIT_MEM_BASE_REG, and PREF_MEM_LIMIT_PREF_MEM_BASE_REG. 5. BAR address assignment must be verified by reading back the programmed values from both slave interfaces. 6. The synchronization register must eventually return the expected completion handshake value to indicate successful enumeration. 7. The test must complete with a pass status via finish(0).",
        "Remarks": "The source contains a duplicated block of link training and cache programming code. Conditional compilation (DM0_RC, DM1_RC, DM0_EP, DM1_EP) controls which link training path is taken. The test uses two PCIe slave interfaces (slv0 and slv1) and two SII interfaces (sii0 and sii1). Six system-level registers at absolute addresses could not be mapped to named registers. The macro mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF could not be resolved. The polling on the synchronization register uses wait_on(5) delays between iterations. The non_secure_prot_nic() call configures NIC security settings before enumeration proceeds."
    },
    {
        "Index": "2",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_dma_write_test",
        "Feature": "DMA Write and Read",
        "Meta Headers": '<stdlib.h>; <stdio.h>; <test_common.h>; \"pcie.h\"',
        "Meta Macros": "DM0_RC; DM1_RC; DM0_EP; DM1_EP; DEBUG_DISPLAY",
        "Meta Arrays": "NA",
        "Speed": "NA",
        "Mode": "Interrupt Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates PCIe DMA write and read operations across all four DMA channels (0-3) for both dual-mode controllers (DM0 and DM1). It begins by writing 0x0 to 0xE6004100 to initialize a synchronization register. Conditional link training is performed via link_training_dm0_x4 or link_training_dm1_x4 based on DM0_RC/DM1_RC/DM0_EP/DM1_EP defines. Under DM0_RC, read_sii0_reg(0xC0) is polled until (data_rd & 0xD1) == 0xD1 to confirm link readiness. The Vendor ID is read from read_pcie_slv0_reg(0x0), and write_pcie_slv0_reg(0x4, 0x7) enables the command register. bar_program_dm0_x4() and mem_base_program_dm0_x4() are called for BAR and memory base setup. Under DM1_RC, the same sequence is performed using sii1, pcie_slv1, and dm1 variants. The test then polls read_reg(0xE6004100) until it equals 0x12345678 for synchronization. Source memory at src_addr0 (0xE6000000) is preloaded with 128 words of 0xC0DEBEED and 128 words of 0xF00DDEAF. GIC_Set() and GIC_EnableAllIRQ() enable interrupt handling. Under DM0_RC, mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_MASK_OFF and mizar_PCIE0_DBI_DSP_DMA_READ_INT_MASK_OFF are written with 0x0 to unmask DMA interrupts. DMA write channels 0-3 are programmed via program_dma_wch0-wch3 and triggered by writing channel numbers to mizar_PCIE0_DBI_DSP_DMA_WRITE_DOORBELL_OFF. After each channel, the test waits on int_pend flag (set to 0 by IRQ handler). DMA read channels 0-3 are similarly programmed via program_dma_rch0-rch3 and triggered via mizar_PCIE0_DBI_DSP_DMA_READ_DOORBELL_OFF. Under DM1_RC, the same DMA write/read sequence uses mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_MASK_OFF, mizar_PCIE1_DBI_DSP_DMA_READ_INT_MASK_OFF, mizar_PCIE1_DBI_DSP_DMA_WRITE_DOORBELL_OFF, and mizar_PCIE1_DBI_DSP_DMA_READ_DOORBELL_OFF with program_dma1_wchX/rchX functions. The Default_IRQHandler reads mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_STATUS_OFF and mizar_PCIE0_DBI_DSP_DMA_READ_INT_STATUS_OFF, masks with 0x0000000F, and clears interrupts by writing to mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF and mizar_PCIE0_DBI_DSP_DMA_READ_INT_CLEAR_OFF. For DM1_RC, the handler uses the PCIE1 variants. GIC_ClearIRQ(0x20) or GIC_ClearIRQ(0x23) clears the GIC interrupt. The test concludes with finish(0).",
        "Test Description": "This testcase validates PCIe DMA write and read operations across all four DMA channels for both dual-mode controllers. After link training and polling the gic register for link readiness, the Vendor ID is read from TYPE1_DEV_ID_VEND_ID_REG and the TYPE1_STATUS_COMMAND_REG is configured to enable bus master and memory access. BAR and memory base programming are performed. Source memory is preloaded with known data patterns. GIC interrupts are enabled, and DMA write and read interrupt masks are cleared via DMA_WRITE_INT_MASK_OFF and DMA_READ_INT_MASK_OFF. For each of the four DMA channels, the write channel is programmed and triggered via DMA_WRITE_DOORBELL_OFF, with the test waiting for an interrupt completion signal after each channel. The same sequence is repeated for DMA read channels using DMA_READ_DOORBELL_OFF. The interrupt handler reads DMA_WRITE_INT_STATUS_OFF and DMA_READ_INT_STATUS_OFF to determine which channels completed, then clears the interrupts via DMA_WRITE_INT_CLEAR_OFF and DMA_READ_INT_CLEAR_OFF. The test completes successfully after all channels finish.",
        "Meta Test Steps / Procedure": "1. write_reg(0xE6004100, 0x0) to initialize synchronization register. 2. Conditionally call link_training_dm0_x4(4) or link_training_dm1_x4(4) based on DM0_RC/DM1_RC/DM0_EP/DM1_EP defines. 3. Under DM0_RC: read_sii0_reg(0xC0) into data_rd, then poll in while loop until (data_rd & 0xD1) == 0xD1. 4. Under DM0_RC: read_pcie_slv0_reg(0x0) to get Vendor ID, write_pcie_slv0_reg(0x4, 0x7) to enable command register. 5. Call bar_program_dm0_x4(), wait_on(10), mem_base_program_dm0_x4(). 6. Under DM1_RC: read_sii1_reg(0xC0) and poll until (data_rd & 0xD1) == 0xD1. 7. Under DM1_RC: read_pcie_slv1_reg(0x0) for Vendor ID, write_pcie_slv1_reg(0x4, 0x7), bar_program_dm1_x4(), wait_on(10), mem_base_program_dm1_x4(). 8. Call non_secure_prot_nic(). 9. Poll read_reg(0xE6004100) until data_rd == 0x12345678 with wait_on(5) between iterations. 10. Set len=0x40, src_addr0=0xE6000000, configure wr_addr0/rd_addr0 through wr_addr3/rd_addr3 based on DM0_RC (0xA7xxxxxx) or DM1_RC (0xC7xxxxxx), set dst_addr0-dst_addr3. 11. Preload source memory: write 128 words of 0xC0DEBEED at src_addr0, then 128 words of 0xF00DDEAF at src_addr0+400. 12. Set int_pend=1, call GIC_Set() and GIC_EnableAllIRQ(). 13. Under DM0_RC: write_reg(mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_MASK_OFF, 0x0) and write_reg(mizar_PCIE0_DBI_DSP_DMA_READ_INT_MASK_OFF, 0x0) to unmask interrupts. 14. Program DMA write channel 0: program_dma_wch0(0x0, src_addr0, 0x0, wr_addr0, 0x0, len), write_reg(mizar_PCIE0_DBI_DSP_DMA_WRITE_DOORBELL_OFF, 0x0), wait on int_pend, reset int_pend=1. 15. Repeat step 14 for channels 1-3 with respective program_dma_wch1-wch3 and doorbell values 0x1-0x3. 16. Program DMA read channel 0: program_dma_rch0(0x0, rd_addr0, 0x0, dst_addr0, 0x0, len), write_reg(mizar_PCIE0_DBI_DSP_DMA_READ_DOORBELL_OFF, 0x0), wait on int_pend, reset int_pend=1. 17. Repeat step 16 for channels 1-3 with respective program_dma_rch1-rch3 and doorbell values 0x1-0x3. 18. Under DM1_RC: write_reg(mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_MASK_OFF, 0x0) and write_reg(mizar_PCIE1_DBI_DSP_DMA_READ_INT_MASK_OFF, 0x0). 19. Repeat DMA write channels 0-3 using program_dma1_wch0-wch3 and mizar_PCIE1_DBI_DSP_DMA_WRITE_DOORBELL_OFF. 20. Repeat DMA read channels 0-3 using program_dma1_rch0-rch3 and mizar_PCIE1_DBI_DSP_DMA_READ_DOORBELL_OFF. 21. Default_IRQHandler: Under DM0_RC: read mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_STATUS_OFF, mask with 0x0000000F to get dma_wr_int_sts; read mizar_PCIE0_DBI_DSP_DMA_READ_INT_STATUS_OFF, mask with 0x0000000F to get dma_rd_int_sts; write dma_wr_int_sts to mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; write dma_rd_int_sts to mizar_PCIE0_DBI_DSP_DMA_READ_INT_CLEAR_OFF; call GIC_ClearIRQ(0x20). 22. Under DM1_RC in IRQ handler: same sequence using PCIE1 variants; call GIC_ClearIRQ(0x23). 23. Set int_pend=0 in IRQ handler to signal completion. 24. wait_on(10), then call finish(0).",
        "Test Steps / Procedure": "1. Initialize the synchronization register by writing zero. 2. Perform PCIe link training for the configured dual-mode controller at x4 width. 3. Poll the gic register on the appropriate SII interface until link status bits (mask 0xD1) confirm link readiness. 4. Read the TYPE1_DEV_ID_VEND_ID_REG to retrieve the Vendor ID. 5. Write to TYPE1_STATUS_COMMAND_REG to enable bus master, memory space, and I/O space access. 6. Perform BAR programming and memory base programming for the active controller. 7. Configure non-secure protection via NIC. 8. Poll the synchronization register until the expected handshake value is received. 9. Preload source memory with known data patterns (two blocks of 128 words each). 10. Enable GIC interrupts and configure interrupt handling. 11. Unmask DMA write and read interrupts by writing to DMA_WRITE_INT_MASK_OFF and DMA_READ_INT_MASK_OFF. 12. For each DMA write channel (0 through 3): program the channel with source address, destination address, and transfer length, then trigger the transfer by writing the channel number to DMA_WRITE_DOORBELL_OFF and wait for interrupt completion. 13. For each DMA read channel (0 through 3): program the channel with source address, destination address, and transfer length, then trigger the transfer by writing the channel number to DMA_READ_DOORBELL_OFF and wait for interrupt completion. 14. In the interrupt handler, read DMA_WRITE_INT_STATUS_OFF and DMA_READ_INT_STATUS_OFF to identify completed channels, then clear the interrupts by writing to DMA_WRITE_INT_CLEAR_OFF and DMA_READ_INT_CLEAR_OFF. 15. Complete the test after all DMA channels finish successfully.",
        "Meta Impacted Registers": "0xE6004100; 0xC0; 0x0; 0x4; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_MASK_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_MASK_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_DOORBELL_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_DOORBELL_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_MASK_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_MASK_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_DOORBELL_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_DOORBELL_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_STATUS_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_STATUS_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_CLEAR_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_STATUS_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_STATUS_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_CLEAR_OFF",
        "Impacted Registers": "gic; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG; DMA_WRITE_INT_MASK_OFF; DMA_READ_INT_MASK_OFF; DMA_WRITE_DOORBELL_OFF; DMA_READ_DOORBELL_OFF; DMA_WRITE_INT_STATUS_OFF; DMA_READ_INT_STATUS_OFF; DMA_WRITE_INT_CLEAR_OFF; DMA_READ_INT_CLEAR_OFF",
        "Meta Validation / Acceptance Criteria": "1. Poll read_sii0_reg(0xC0) (DM0_RC) or read_sii1_reg(0xC0) (DM1_RC): while loop checks (data_rd & 0xD1) != 0xD1, exits when all required link status bits are set. 2. read_pcie_slv0_reg(0x0) or read_pcie_slv1_reg(0x0) returns Vendor ID which is printed. 3. Poll read_reg(0xE6004100) until data_rd == 0x12345678 for synchronization. 4. For each DMA write channel (0-3): after writing doorbell, the test waits in while(int_pend) loop; the IRQ handler sets int_pend=0 upon interrupt, confirming DMA write completion. 5. For each DMA read channel (0-3): same int_pend mechanism confirms DMA read completion. 6. In Default_IRQHandler: read_reg(mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_STATUS_OFF) & 0x0000000F must be non-zero for write interrupt; read_reg(mizar_PCIE0_DBI_DSP_DMA_READ_INT_STATUS_OFF) & 0x0000000F must be non-zero for read interrupt. 7. Interrupts are cleared by writing status to mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF and mizar_PCIE0_DBI_DSP_DMA_READ_INT_CLEAR_OFF (or PCIE1 variants for DM1_RC). 8. GIC_ClearIRQ(0x20) for DM0 or GIC_ClearIRQ(0x23) for DM1 clears the GIC-level interrupt. 9. finish(0) indicates test pass.",
        "Validation / Acceptance Criteria": "1. The gic register must be polled until link status bits (mask 0xD1) are all set, confirming PCIe link readiness. 2. The TYPE1_DEV_ID_VEND_ID_REG must return a valid Vendor ID when read. 3. The synchronization register must return the expected handshake value before DMA operations begin. 4. For each of the four DMA write channels, the DMA_WRITE_INT_STATUS_OFF register must indicate completion via interrupt, and the interrupt must be successfully cleared via DMA_WRITE_INT_CLEAR_OFF. 5. For each of the four DMA read channels, the DMA_READ_INT_STATUS_OFF register must indicate completion via interrupt, and the interrupt must be successfully cleared via DMA_READ_INT_CLEAR_OFF. 6. The interrupt-pending flag must transition from set to cleared for each DMA channel operation, confirming the IRQ handler executed correctly. 7. The test must complete with a pass status via finish(0) after all eight DMA channel operations (four write, four read) complete successfully.",
        "Remarks": "The test operates in interrupt-driven mode using a global int_pend flag toggled between the main test loop and the Default_IRQHandler. Conditional compilation via DM0_RC and DM1_RC selects between PCIE0 and PCIE1 controller paths. All PCIE1 DMA register macros could not be resolved by upstream agents. The synchronization register at absolute address could not be mapped to a named register. Source memory is preloaded at two separate address ranges with distinct data patterns. The DMA transfer length is 0x40 (64 bytes). Four DMA write channels and four DMA read channels are exercised sequentially. GIC interrupt IDs differ between DM0 (0x20) and DM1 (0x23)."
    },
    {
        "Index": "3",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_mem_wr_rd_test",
        "Feature": "Memory Write and Read",
        "Meta Headers": '<stdlib.h>; <stdio.h>; <test_common.h>; \"pcie.h\"',
        "Meta Macros": "DM0_RC; DM1_RC; DM0_EP; DM1_EP; DM0; DM1; DEBUG_DISPLAY",
        "Meta Arrays": "NA",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates PCIe memory write and read operations through the PCIe slave interfaces. It begins by writing 0x0 to 0xE6004100 to initialize a synchronization register. Conditional link training is performed via link_training_dm0_x4(4) or link_training_dm1_x4(4) based on DM0_RC/DM1_RC/DM0_EP/DM1_EP defines. Cache programming is performed by reading mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, modifying bit fields (bits 11-14, 3-6, 27-30, 19-22) using set_data() with value 0xf, and writing back. The same is repeated for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. After wait_on(20), the combined cache programming is re-applied for both PCIE0 and PCIE1. The test reads read_sii0_reg(0xC0) and under DM0 polls in a while loop until (data_rd & 0xD1) == 0xD1. Under DM1, read_sii1_reg(0xC0) is polled similarly. Under DM0_RC, the Vendor ID is read from read_pcie_slv0_reg(0x0), write_pcie_slv0_reg(0x4, 0x7) enables the command register, bar_program_dm0_x4() and mem_base_program_dm0_x4() are called. Under DM1_RC, the same sequence uses pcie_slv1 and dm1 variants. Under DM0_EP and DM1_EP, EP-specific BAR programming (bar_program_dm0_EP_x4/bar_program_dm1_EP_x4) and memory base programming are performed. non_secure_prot_nic() configures NIC security. write_reg(0xE6004100, 0x11111111) signals readiness. Cache disable programming follows: mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF is read-modify-written with bits 11-14=0xf, 3-6=0xf, then bits 27-30=0xf, 19-22=0x0. The same is done for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. After wait_on(10), combined cache disable sets bits 27-30=0x0, 19-22=0x0 for both controllers. After wait_on(30), under DM0_RC, pcie_slv0_mem_wr_rd() is called three times with addresses 0x01040000, 0x01000020, 0x01004000 and data patterns 0xa5a5a5a5, 0xa6a6a6a6, 0xa7a7a7a7. Under DM1_RC, pcie_slv1_mem_wr_rd() is called with addresses 0x01040000, 0x01000020, 0x01004000 and data 0xb5b5b5b5, 0xb5b5b6b6, 0xb7b7b5b5. Under DM0_EP, pcie_slv0_mem_wr_rd() is called five times at addresses 0x10100, 0x20100, 0x1B100, 0x2B100, 0x30100 with data 0x5a5a5a5a. Under DM1_EP, pcie_slv1_mem_wr_rd() is called with the same addresses and data. Finally, read_reg(0xE6004100) is polled until it equals 0x12345678, then finish(0) is called.",
        "Test Description": "This testcase validates PCIe memory write and read operations through the PCIe slave interfaces. After link training and polling the gic register for link readiness, the Vendor ID is read from TYPE1_DEV_ID_VEND_ID_REG and the TYPE1_STATUS_COMMAND_REG is configured to enable bus master, memory space, and I/O space access. BAR programming and memory base programming are performed. Cache coherency is enabled by programming the COHERENCY_CONTROL_3_OFF register for both PCIE0 and PCIE1 controllers. Non-secure protection is configured via NIC, and a readiness signal is written to the synchronization register. Cache coherency is then disabled by clearing specific bit fields in COHERENCY_CONTROL_3_OFF for both controllers. Memory write-read verification is performed at multiple addresses through the PCIe slave interfaces using known data patterns. The test concludes by polling the synchronization register until a completion handshake value is received.",
        "Meta Test Steps / Procedure": "1. write_reg(0xE6004100, 0x0) to initialize synchronization register. 2. Conditionally call link_training_dm0_x4(4) or link_training_dm1_x4(4) based on DM0_RC/DM1_RC/DM0_EP/DM1_EP defines. 3. Cache enable programming: read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set_data bits [11:14]=0xf, [3:6]=0xf, write back. 4. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF again, set_data bits [27:30]=0xf, [19:22]=0xf, write back. 5. Repeat steps 3-4 for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 6. wait_on(20). 7. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set_data bits [11:14]=0xf, [3:6]=0xf, [27:30]=0xf, [19:22]=0xf, write back. 8. Repeat step 7 for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 9. Read read_sii0_reg(0xC0) into data_rd. 10. Under DM0: poll read_sii0_reg(0xC0) in while loop until (data_rd & 0xD1) == 0xD1. 11. Under DM1: read read_sii1_reg(0xC0) and poll until (data_rd & 0xD1) == 0xD1. 12. Under DM0_EP: wait_on(30000). 13. Under DM0_RC: read_pcie_slv0_reg(0x0) for Vendor ID, write_pcie_slv0_reg(0x4, 0x7), call bar_program_dm0_x4(), wait_on(10), mem_base_program_dm0_x4(). 14. Under DM1_RC: read_pcie_slv1_reg(0x0) for Vendor ID, write_pcie_slv1_reg(0x4, 0x7), call bar_program_dm1_x4(), wait_on(10), mem_base_program_dm1_x4(). 15. Under DM0_EP: bar_program_dm0_EP_x4(), wait_on(10), mem_base_program_dm0_x4(). 16. Under DM1_EP: bar_program_dm1_EP_x4(), wait_on(10), mem_base_program_dm1_x4(). 17. Call non_secure_prot_nic(). 18. write_reg(0xE6004100, 0x11111111) to signal readiness. 19. Cache disable: read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set_data bits [11:14]=0xf, [3:6]=0xf, write back; then set bits [27:30]=0xf, [19:22]=0x0, write back. 20. Repeat cache disable for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 21. wait_on(10), then combined cache disable for both PCIE0 and PCIE1 with bits [27:30]=0x0, [19:22]=0x0. 22. wait_on(30). 23. Under DM0_RC: pcie_slv0_mem_wr_rd(0x01040000, 0xa5a5a5a5), pcie_slv0_mem_wr_rd(0x01000020, 0xa6a6a6a6), pcie_slv0_mem_wr_rd(0x01004000, 0xa7a7a7a7). 24. Under DM1_RC: pcie_slv1_mem_wr_rd(0x01040000, 0xb5b5b5b5), pcie_slv1_mem_wr_rd(0x01000020, 0xb5b5b6b6), pcie_slv1_mem_wr_rd(0x01004000, 0xb7b7b5b5). 25. Under DM0_EP: pcie_slv0_mem_wr_rd at addresses 0x10100, 0x20100, 0x1B100, 0x2B100, 0x30100 with data 0x5a5a5a5a. 26. Under DM1_EP: pcie_slv1_mem_wr_rd at same addresses with data 0x5a5a5a5a. 27. wait_on(10). 28. Poll read_reg(0xE6004100) until data_rd == 0x12345678, with wait_on(5) between iterations. 29. Call finish(0).",
        "Test Steps / Procedure": "1. Initialize the synchronization register by writing zero to clear it. 2. Perform PCIe link training for the configured dual-mode controller at x4 width. 3. Program the COHERENCY_CONTROL_3_OFF register for PCIE0 by reading, setting cache-enable bit fields (bits 11-14, 3-6, 27-30, 19-22 to 0xF), and writing back. 4. Repeat coherency control cache-enable programming for PCIE1. 5. Wait for stabilization, then re-apply combined cache-enable programming for both PCIE0 and PCIE1 COHERENCY_CONTROL_3_OFF registers. 6. Poll the gic register on the appropriate SII interface until link status bits (mask 0xD1) indicate readiness. 7. Read the TYPE1_DEV_ID_VEND_ID_REG to retrieve the Vendor ID. 8. Write to TYPE1_STATUS_COMMAND_REG to enable bus master, memory space, and I/O space access. 9. Perform BAR programming and memory base programming for the active controller. 10. Configure non-secure protection via NIC. 11. Write a readiness signal to the synchronization register. 12. Perform cache-disable programming on COHERENCY_CONTROL_3_OFF for both PCIE0 and PCIE1 by clearing bits 19-22 and 27-30. 13. Wait, then finalize cache-disable by clearing all cache fields in COHERENCY_CONTROL_3_OFF for both controllers. 14. Execute memory write-read verification at multiple addresses through the PCIe slave interface using known data patterns. 15. Poll the synchronization register until the expected completion handshake value is received. 16. Complete the test.",
        "Meta Impacted Registers": "0xE6004100; mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF; mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF; 0xC0; 0x0; 0x4",
        "Impacted Registers": "COHERENCY_CONTROL_3_OFF; gic; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG",
        "Meta Validation / Acceptance Criteria": "1. Poll read_sii0_reg(0xC0) (DM0) or read_sii1_reg(0xC0) (DM1): while loop checks (data_rd & 0xD1) != 0xD1, exits when all required link status bits are set. 2. read_pcie_slv0_reg(0x0) or read_pcie_slv1_reg(0x0) returns Vendor ID which is printed. 3. Under DM0_RC: pcie_slv0_mem_wr_rd() is called with address 0x01040000 and data 0xa5a5a5a5, address 0x01000020 and data 0xa6a6a6a6, address 0x01004000 and data 0xa7a7a7a7. The mem_wr_rd function performs write followed by read-back verification. 4. Under DM1_RC: pcie_slv1_mem_wr_rd() is called with address 0x01040000 and data 0xb5b5b5b5, address 0x01000020 and data 0xb5b5b6b6, address 0x01004000 and data 0xb7b7b5b5. 5. Under DM0_EP: pcie_slv0_mem_wr_rd() is called five times at addresses 0x10100, 0x20100, 0x1B100, 0x2B100, 0x30100 with data 0x5a5a5a5a. 6. Under DM1_EP: pcie_slv1_mem_wr_rd() at same addresses with data 0x5a5a5a5a. 7. Final poll: read_reg(0xE6004100) must equal 0x12345678 to exit the while loop and call finish(0). 8. finish(0) indicates test pass.",
        "Validation / Acceptance Criteria": "1. The gic register must be polled until link status bits (mask 0xD1) are all set, confirming PCIe link readiness. 2. The TYPE1_DEV_ID_VEND_ID_REG must return a valid Vendor ID when read. 3. Memory write-read operations through the PCIe slave interface must succeed at multiple target addresses, with read-back data matching the written data patterns. 4. Under Root Complex mode, three memory locations are verified with distinct data patterns per controller. 5. Under Endpoint mode, five memory locations targeting different BAR regions are verified with a common data pattern. 6. The synchronization register must return the expected completion handshake value to indicate successful test completion. 7. The test must complete with a pass status via finish(0).",
        "Remarks": "The test supports four conditional compilation modes: DM0_RC, DM1_RC, DM0_EP, and DM1_EP. Link readiness polling is controlled by separate DM0 and DM1 defines. Under DM0_EP, a long wait_on(30000) is used instead of polling for link readiness. The pcie_slv0_mem_wr_rd and pcie_slv1_mem_wr_rd functions encapsulate write followed by read-back verification. The synchronization register at absolute address could not be mapped to a named register. The macro mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF could not be resolved by upstream agents. Cache coherency is enabled before memory operations and disabled afterward. The test writes a readiness signal value before performing cache disable and memory operations."
    },
    {
        "Index": "4",
        "SS / Module": "PCIE",
        "Test Case Name": "pcie_reg_wr_rd_test",
        "Feature": "Register Write and Read",
        "Meta Headers": "<stdlib.h>; <stdio.h>; <test_common.h>; <pcie.h>",
        "Meta Macros": "NA",
        "Meta Arrays": "rc0_ctl_addr[5] = {mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_08H_REG, mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_10H_REG, mizar_PCIE0_DBI_DSP_FILTER_MASK_2_OFF, mizar_PCIE0_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF, mizar_PCIE0_DBI_DSP_UTILITY_OFF}; rc1_ctl_addr[5] = {mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_08H_REG, mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_10H_REG, mizar_PCIE1_DBI_DSP_FILTER_MASK_2_OFF, mizar_PCIE1_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF, mizar_PCIE1_DBI_DSP_UTILITY_OFF}; ctl_default[5] = {0x0, 0x0, 0x0, 0x0, 0x0}; sii0_addr[3] = {mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER2, mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER3, mizar_PCIE0_SII_PHY_CONTROL_23}; sii1_addr[3] = {mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER2, mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER3, mizar_PCIE1_SII_PHY_CONTROL_23}; sii_default[3] = {0x0, 0x0, 0x0}; sii0_write_mask[3] = {0xFFFFFFFF, 0xFFFFFFFF, 0xF000F}; sii1_write_mask[3] = {0xFFFFFFFF, 0xFFFFFFFF, 0xF000F}; phy0_addr[3] = {0xE68860B8, 0xE68862B8, 0xE68864B8}; phy1_addr[3] = {0xE68A60B8, 0xE68A62B8, 0xE68A64B8}; phy0_default[3] = {0x0, 0x0, 0x0}; phy1_default[3] = {0x0, 0x0, 0x0}; phy0_write_mask[3] = {0x1FFF, 0x1FFF, 0x1FFF}; phy1_write_mask[3] = {0x1FFF, 0x1FFF, 0x1FFF}; chk_val[6] = {0xffffffff, 0xaaaaaaaa, 0x55555555, 0x00000000, 0xA5A5A5A5, 0xffff0000}; chk_val_phy[3] = {0x7baf, 0x1, 0x003b}",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates register reset default values and write-read integrity for PCIe DBI DSP controller registers, SII registers, and PHY registers across both PCIE0 and PCIE1 controllers. The test_case() function calls chk_rst_val() followed by chk_rd_wr(). In chk_rst_val(), the test reads five DBI DSP registers from rc0_ctl_addr[] (mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_08H_REG, mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_10H_REG, mizar_PCIE0_DBI_DSP_FILTER_MASK_2_OFF, mizar_PCIE0_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF, mizar_PCIE0_DBI_DSP_UTILITY_OFF) and compares against ctl_default[] (all 0x0). The same is done for rc1_ctl_addr[] (PCIE1 variants). Three SII registers from sii0_addr[] (mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER2, mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER3, mizar_PCIE0_SII_PHY_CONTROL_23) are read and compared against sii_default[] (all 0x0), and similarly for sii1_addr[] (PCIE1 variants). Then write_reg(mizar_PCIE0_SII_PHY_RST_CONTROL, 0x01203000) and write_reg(mizar_PCIE1_SII_PHY_RST_CONTROL, 0x01203000) are called to release PHY reset. Three PHY registers from phy0_addr[] (0xE68860B8, 0xE68862B8, 0xE68864B8) are read, with 16-bit extraction based on address alignment (if addr%4 non-zero, shift right 16; else mask with 0x0000FFFF), and compared against phy0_default[] (all 0x0). The same is done for phy1_addr[] (0xE68A60B8, 0xE68A62B8, 0xE68A64B8). In chk_rd_wr(), a loop iterates over three test patterns from chk_val[] (0xffffffff, 0xaaaaaaaa, 0x55555555). For each pattern: all five rc0_ctl_addr[] registers are written with chk_val[j], then all five rc1_ctl_addr[] registers. Three sii0_addr[] registers are written with (chk_val[j] & sii0_write_mask[i]), and sii1_addr[] similarly. PHY reset is re-applied via mizar_PCIE0_SII_PHY_RST_CONTROL and mizar_PCIE1_SII_PHY_RST_CONTROL. Three phy0_addr[] registers are written with (chk_val_phy[j] & phy0_write_mask[i]), and phy1_addr[] similarly. Then all registers are read back and compared: rc0/rc1 against chk_val[j], sii0/sii1 against (chk_val[j] & write_mask[i]), phy0/phy1 with 16-bit extraction and mask comparison against (chk_val_phy[j] & 0x00001FFF). Mismatches increment err1 or err2. The test concludes with finish(err2 || err1), passing 0 if no errors.",
        "Test Description": "This testcase validates register reset default values and write-read integrity for PCIe controller registers, SII registers, and PHY registers across both PCIE0 and PCIE1 controllers. The test first reads all target registers and verifies they contain expected reset default values. It then writes the PHY reset control registers to release PHY from reset. PHY registers are read with 16-bit extraction based on address alignment and verified against defaults. In the write-read phase, multiple test patterns are written to all registers and read back to verify data integrity. DBI DSP registers (MSI_CAP_OFF_08H_REG, MSI_CAP_OFF_10H_REG, FILTER_MASK_2_OFF, AXI_MSTR_MSG_ADDR_HIGH_OFF, UTILITY_OFF) are verified with full 32-bit patterns. SII registers are verified with write-mask-applied patterns. PHY registers are verified with 13-bit masked patterns. The test passes only if all reset default checks and write-read checks produce zero mismatches.",
        "Meta Test Steps / Procedure": "1. test_case() calls chk_rst_val(). 2. chk_rst_val(): for i=0 to 4, read_reg(rc0_ctl_addr[i]), compare data_rd against ctl_default[i] (0x0), increment err1 on mismatch. 3. for i=0 to 4, read_reg(rc1_ctl_addr[i]), compare data_rd against ctl_default[i] (0x0), increment err2 on mismatch. 4. for i=0 to 2, read_reg(sii0_addr[i]), compare data_rd against sii_default[i] (0x0), increment err2 on mismatch. 5. for i=0 to 2, read_reg(sii1_addr[i]), compare data_rd against sii_default[i] (0x0), increment err2 on mismatch. 6. write_reg(mizar_PCIE0_SII_PHY_RST_CONTROL, 0x01203000) to release PCIE0 PHY reset. 7. write_reg(mizar_PCIE1_SII_PHY_RST_CONTROL, 0x01203000) to release PCIE1 PHY reset. 8. for i=0 to 2, read_reg(phy0_addr[i]), extract 16-bit value based on address alignment (if phy0_addr[i]%4 non-zero: data_rd >> 16, else: data_rd & 0x0000FFFF), compare against phy0_default[i] (0x0), increment err2 on mismatch. 9. for i=0 to 2, read_reg(phy1_addr[i]), same 16-bit extraction, compare against phy1_default[i] (0x0), increment err2 on mismatch. 10. test_case() calls chk_rd_wr(). 11. chk_rd_wr(): for j=0 to 2 (patterns: 0xffffffff, 0xaaaaaaaa, 0x55555555): 12. for i=0 to 4, write_reg(rc0_ctl_addr[i], chk_val[j]). 13. for i=0 to 4, write_reg(rc1_ctl_addr[i], chk_val[j]). 14. for i=0 to 2, write_reg(sii0_addr[i], chk_val[j] & sii0_write_mask[i]). 15. for i=0 to 2, write_reg(sii1_addr[i], chk_val[j] & sii1_write_mask[i]). 16. write_reg(mizar_PCIE0_SII_PHY_RST_CONTROL, 0x01203000). 17. write_reg(mizar_PCIE1_SII_PHY_RST_CONTROL, 0x01203000). 18. for i=0 to 2, write_reg(phy0_addr[i], chk_val_phy[j] & phy0_write_mask[i]). 19. for i=0 to 2, write_reg(phy1_addr[i], chk_val_phy[j] & phy1_write_mask[i]). 20. for i=0 to 4, read_reg(rc0_ctl_addr[i]), compare data_rd against chk_val[j], increment err1 on mismatch. 21. for i=0 to 4, read_reg(rc1_ctl_addr[i]), compare data_rd against chk_val[j], increment err1 on mismatch. 22. for i=0 to 2, read_reg(sii0_addr[i]), compare data_rd against (chk_val[j] & sii0_write_mask[i]), increment err1 on mismatch. 23. for i=0 to 2, read_reg(sii1_addr[i]), compare data_rd against (chk_val[j] & sii1_write_mask[i]), increment err1 on mismatch. 24. for i=0 to 2, read_reg(phy0_addr[i]), 16-bit extraction, compare (data_rd & phy0_write_mask[i]) against (chk_val_phy[j] & 0x00001FFF), increment err1 on mismatch. 25. for i=0 to 2, read_reg(phy1_addr[i]), 16-bit extraction, compare (data_rd & phy1_write_mask[i]) against (chk_val_phy[j] & 0x00001FFF), increment err1 on mismatch. 26. finish(err2 || err1): pass 0 if no errors, non-zero otherwise.",
        "Test Steps / Procedure": "1. Read all five PCIE0 DBI DSP registers (MSI_CAP_OFF_08H_REG, MSI_CAP_OFF_10H_REG, FILTER_MASK_2_OFF, AXI_MSTR_MSG_ADDR_HIGH_OFF, UTILITY_OFF) and verify they contain reset default values of zero. 2. Read all five PCIE1 DBI DSP registers and verify they contain reset default values of zero. 3. Read three PCIE0 SII registers and verify they contain reset default values of zero. 4. Read three PCIE1 SII registers and verify they contain reset default values of zero. 5. Write to the PCIE0 and PCIE1 PHY reset control registers to release PHY from reset. 6. Read three PCIE0 PHY registers with 16-bit extraction based on address alignment and verify they contain reset default values of zero. 7. Read three PCIE1 PHY registers with 16-bit extraction and verify reset default values. 8. For each of three test patterns (all-ones, alternating 0xAA, alternating 0x55): write the pattern to all five PCIE0 DBI DSP registers and all five PCIE1 DBI DSP registers. 9. Write the pattern with write-mask applied to all three PCIE0 SII registers and all three PCIE1 SII registers. 10. Re-apply PHY reset release, then write PHY-specific test patterns with 13-bit mask to all three PCIE0 PHY registers and all three PCIE1 PHY registers. 11. Read back all DBI DSP registers and verify the read data matches the written pattern. 12. Read back all SII registers and verify the read data matches the write-mask-applied pattern. 13. Read back all PHY registers with 16-bit extraction and verify the read data matches the 13-bit masked PHY pattern. 14. Verify the test completes with zero error count indicating all checks passed.",
        "Meta Impacted Registers": "mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_08H_REG; mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_10H_REG; mizar_PCIE0_DBI_DSP_FILTER_MASK_2_OFF; mizar_PCIE0_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF; mizar_PCIE0_DBI_DSP_UTILITY_OFF; mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_08H_REG; mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_10H_REG; mizar_PCIE1_DBI_DSP_FILTER_MASK_2_OFF; mizar_PCIE1_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF; mizar_PCIE1_DBI_DSP_UTILITY_OFF; mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER2; mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER3; mizar_PCIE0_SII_PHY_CONTROL_23; mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER2; mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER3; mizar_PCIE1_SII_PHY_CONTROL_23; mizar_PCIE0_SII_PHY_RST_CONTROL; mizar_PCIE1_SII_PHY_RST_CONTROL; 0xE68860B8; 0xE68862B8; 0xE68864B8; 0xE68A60B8; 0xE68A62B8; 0xE68A64B8",
        "Impacted Registers": "MSI_CAP_OFF_08H_REG; MSI_CAP_OFF_10H_REG; FILTER_MASK_2_OFF; AXI_MSTR_MSG_ADDR_HIGH_OFF; UTILITY_OFF",
        "Meta Validation / Acceptance Criteria": "1. Reset default check: for each register in rc0_ctl_addr[], rc1_ctl_addr[], sii0_addr[], sii1_addr[], data_rd must equal the corresponding default value (0x0). If mismatch, err1 or err2 is incremented and failure is printed. 2. PHY reset default check: for each register in phy0_addr[] and phy1_addr[], 16-bit extracted value (data_rd >> 16 if addr%4 non-zero, else data_rd & 0x0000FFFF) must equal phy0_default[i] or phy1_default[i] (0x0). 3. Write-read check for DBI DSP registers: for each pattern in chk_val[] (0xffffffff, 0xaaaaaaaa, 0x55555555), data_rd from read_reg(rc0_ctl_addr[i]) and read_reg(rc1_ctl_addr[i]) must equal chk_val[j]. 4. Write-read check for SII registers: data_rd from read_reg(sii0_addr[i]) must equal (chk_val[j] & sii0_write_mask[i]), and similarly for sii1_addr[]. 5. Write-read check for PHY registers: (data_rd & phy0_write_mask[i]) must equal (chk_val_phy[j] & 0x00001FFF), and similarly for phy1. 6. finish(err2 || err1): test passes only if both err1 and err2 are zero, meaning all reset default and write-read checks succeeded.",
        "Validation / Acceptance Criteria": "1. All five PCIE0 DBI DSP registers (MSI_CAP_OFF_08H_REG, MSI_CAP_OFF_10H_REG, FILTER_MASK_2_OFF, AXI_MSTR_MSG_ADDR_HIGH_OFF, UTILITY_OFF) must read back their expected reset default value of zero. 2. All five PCIE1 DBI DSP registers must read back their expected reset default value of zero. 3. All SII registers on both PCIE0 and PCIE1 must read back their expected reset default value of zero. 4. All PHY registers on both PCIE0 and PCIE1 must read back their expected reset default value of zero after 16-bit extraction. 5. For each of three write-read test patterns, all DBI DSP registers must read back the exact written value. 6. For each test pattern, all SII registers must read back the written value masked by their respective write masks. 7. For each PHY-specific test pattern, all PHY registers must read back the written value within the 13-bit write mask after 16-bit extraction. 8. The test must complete with zero total errors, indicating all reset default and write-read integrity checks passed.",
        "Remarks": "The test exercises registers across three distinct register domains: DBI DSP controller registers (5 per controller), SII registers (3 per controller), and PHY registers (3 per controller). SII registers have per-register write masks (0xFFFFFFFF or 0xF000F) that limit writable bits. PHY registers use 16-bit access with address-alignment-based extraction (upper or lower 16 bits) and a 13-bit write mask (0x1FFF). PHY-specific test patterns (0x7baf, 0x1, 0x003b) differ from the DBI DSP and SII patterns. PHY reset must be released via the PHY reset control registers before PHY register access. All PCIE1 DBI DSP macros, all SII macros, and all PHY reset control macros could not be resolved by upstream agents. Six PHY register addresses at absolute hex values could not be mapped to named registers. The chk_val[] array contains six patterns but only the first three are used in the write-read loop (j=0 to 2). Two separate error counters (err1 and err2) track failures across different check phases."
    }
]

# Create workbook
wb = openpyxl.Workbook()

# --- TestPlan Sheet ---
ws_tp = wb.active
ws_tp.title = "TestPlan"

header_font = Font(bold=True, color="FFFFFF")
header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
wrap_alignment = Alignment(wrap_text=True, vertical="top")

# Write headers
for col_idx, col_name in enumerate(testplan_columns, 1):
    cell = ws_tp.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = wrap_alignment

# Write data rows
for row_idx, row_data in enumerate(json_data, 2):
    ws_tp.cell(row=row_idx, column=1, value=row_data.get("Index", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=2, value=row_data.get("SS / Module", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=3, value=row_data.get("Feature", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=4, value=row_data.get("Test Case Name", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=5, value=row_data.get("Test Description", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=6, value=row_data.get("Speed", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=7, value=row_data.get("Mode", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=8, value=row_data.get("Memory Start Offset", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=9, value=row_data.get("Memory End Offset", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=10, value=row_data.get("Remarks", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=11, value=row_data.get("Test Steps / Procedure", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=12, value=row_data.get("Impacted Registers", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=13, value=row_data.get("Validation / Acceptance Criteria", "")).alignment = wrap_alignment
    ws_tp.cell(row=row_idx, column=14, value="").alignment = wrap_alignment

# Freeze first row
ws_tp.freeze_panes = "A2"

# Auto-size columns
for col_idx in range(1, len(testplan_columns) + 1):
    max_length = len(str(ws_tp.cell(row=1, column=col_idx).value))
    for row_idx in range(2, len(json_data) + 2):
        cell_val = str(ws_tp.cell(row=row_idx, column=col_idx).value or "")
        max_length = max(max_length, min(len(cell_val), 80))
    ws_tp.column_dimensions[get_column_letter(col_idx)].width = min(max_length + 2, 60)

# --- MetaData Sheet ---
ws_md = wb.create_sheet("MetaData")

for col_idx, col_name in enumerate(metadata_columns, 1):
    cell = ws_md.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = wrap_alignment

for row_idx, row_data in enumerate(json_data, 2):
    ws_md.cell(row=row_idx, column=1, value=row_data.get("Index", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=2, value=row_data.get("Test Case Name", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=3, value=row_data.get("Meta Test Description", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=4, value=row_data.get("Meta Test Steps / Procedure", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=5, value=row_data.get("Meta Impacted Registers", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=6, value=row_data.get("Meta Validation / Acceptance Criteria", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=7, value=row_data.get("Meta Headers", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=8, value=row_data.get("Meta Macros", "")).alignment = wrap_alignment
    ws_md.cell(row=row_idx, column=9, value=row_data.get("Meta Arrays", "")).alignment = wrap_alignment

ws_md.freeze_panes = "A2"
ws_md.sheet_state = "veryHidden"

for col_idx in range(1, len(metadata_columns) + 1):
    max_length = len(str(ws_md.cell(row=1, column=col_idx).value))
    for row_idx in range(2, len(json_data) + 2):
        cell_val = str(ws_md.cell(row=row_idx, column=col_idx).value or "")
        max_length = max(max_length, min(len(cell_val), 80))
    ws_md.column_dimensions[get_column_letter(col_idx)].width = min(max_length + 2, 60)

# Save workbook
wb.save(output_path)
print(f"FILENAME={filename}")
print(f"OUTPUT_PATH={output_path}")
print(f"ROWS_TESTPLAN={len(json_data)}")
print(f"ROWS_METADATA={len(json_data)}")

# Validate
wb2 = openpyxl.load_workbook(output_path)
assert "TestPlan" in wb2.sheetnames
assert "MetaData" in wb2.sheetnames
print("VALIDATION=PASSED")
