#include<ethernet2/ethernet2_def.h>
#include<ethernet2/ethernet2_offset.h>

#define CNT 434
int data_rd,data_wr,rst_val;


const unsigned long int addr_array[434]={mizar_ETHERNET2_MAC_CONFIGURATION,mizar_ETHERNET2_MAC_EXT_CONFIGURATION,mizar_ETHERNET2_MAC_PACKET_FILTER,mizar_ETHERNET2_MAC_WD_JB_TIMEOUT,};


const int default_value_array[434]={ETHERNET2_MAC_CONFIGURATION_DEFAULT_VAL,ETHERNET2_MAC_EXT_CONFIGURATION_DEFAULT_VAL,ETHERNET2_MAC_PACKET_FILTER_DEFAULT_VAL,ETHERNET2_MAC_WD_JB_TIMEOUT_DEFAULT_VAL,ETHERNET2_MAC_HASH_TABLE_REG0_DEFAULT_VAL,};


const int read_mask_array[434]={ETHERNET2_MAC_CONFIGURATION_READ_MASK,ETHERNET2_MAC_EXT_CONFIGURATION_READ_MASK,ETHERNET2_MAC_PACKET_FILTER_READ_MASK,ETHERNET2_MAC_WD_JB_TIMEOUT_READ_MASK,};


const int write_mask_array[434]={ETHERNET2_MAC_CONFIGURATION_WRITE_MASK,ETHERNET2_MAC_EXT_CONFIGURATION_WRITE_MASK,ETHERNET2_MAC_PACKET_FILTER_WRITE_MASK,ETHERNET2_MAC_WD_JB_TIMEOUT_WRITE_MASK,ETHERNET2_MAC_HASH_TABLE_REG0_WRITE_MASK,};


const int skip_array[434]={0,0,0,0,0,};

const int skip_rst_array[434]={0,0,0,0,0,};
