"""
MIPI_DSI TestPlan Excel Generator
Auto-generated by Ag_Excel_Generator Agent.
Run this script locally to (re)generate the .xlsx workbook.
Requires: openpyxl
"""
import json
from datetime import datetime, timezone, timedelta
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

JSON_DATA = [
  {"Index":"1","SS / Module":"MIPI_DSI","Test Case Name":"mipi_dsi_basic_test","Feature":"NA","Meta Headers":"NA","Meta Macros":"MIZAR_MIPI_DSI_DMAC_INTEN; MIZAR_MIPI_DSI_SUBSYS_INTERRUPT_ENABLE; MIZAR_MIPI_DSI_HOST_PHY_IF_CFG; MIZAR_MIPI_DSI_HOST_PCKHDL_CFG; MIZAR_MIPI_DSI_HOST_CLKMGR_CFG; MIZAR_MIPI_DSI_SUBSYS_DPI_CONTROL; MIZAR_MIPI_DSI_DMAC_DBGINST0; MIZAR_MIPI_DSI_DMAC_DBGINST1; MIZAR_MIPI_DSI_DMAC_DBGCMD; MIZAR_MIPI_DSI_SUBSYS_INTERRUPT_MASK; MIZAR_MIPI_DSI_DMAC_INTMIS; MIZAR_MIPI_DSI_DMAC_INTCLR; MIZAR_MIPI_DSI_SUBSYS_INTERRUPT_RAW","Meta Arrays":"NA","Speed":"NA","Mode":"NA","Memory Start Offset":"NA","Memory End Offset":"NA"},
]

TESTPLAN_COLS = ["Index","SS / Module","Feature","Test Case Name","Test Description","Speed","Mode","Memory Start Offset","Memory End Offset","Remarks","Test Steps / Procedure","Impacted Registers","Validation / Acceptance Criteria","Code Generation"]
METADATA_COLS = ["Index","Test Case Name","Meta Test Description","Meta Test Steps / Procedure","Meta Impacted Registers","Meta Validation / Acceptance Criteria","Meta Headers","Meta Macros","Meta Arrays"]

def build():
    ist = timezone(timedelta(hours=5, minutes=30))
    ts = datetime.now(ist).strftime("%Y%m%d_%H%M%S")
    fname = f"MIPI_DSI_TestPlan_{ts}.xlsx"
    wb = Workbook()
    tp = wb.active
    tp.title = "TestPlan"
    md = wb.create_sheet("MetaData")
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="4472C4")
    wrap = Alignment(wrap_text=True, vertical="top")
    for sheet, cols in [(tp, TESTPLAN_COLS), (md, METADATA_COLS)]:
        sheet.append(cols)
        for c in sheet[1]:
            c.font = header_font
            c.fill = header_fill
            c.alignment = wrap
        sheet.freeze_panes = "A2"
    for row in JSON_DATA:
        tp.append([row.get(k, "") for k in TESTPLAN_COLS])
        md.append([row.get(k, "") for k in METADATA_COLS])
    for sheet in [tp, md]:
        for r in sheet.iter_rows(min_row=2):
            for c in r:
                c.alignment = wrap
        for i, col in enumerate(sheet.columns, 1):
            mx = max((len(str(c.value)) for c in col if c.value), default=10)
            sheet.column_dimensions[get_column_letter(i)].width = min(max(mx + 2, 12), 60)
    md.sheet_state = "veryHidden"
    wb.save(fname)
    print("Saved:", fname)

if __name__ == "__main__":
    build()
