#!/usr/bin/env python3
"""
MIPI TestPlan Excel Generator
Generates MIPI_TestPlan_<YYYYMMDD>_<HHMMSS>.xlsx using openpyxl
Run: python generate_mipi_testplan.py
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from datetime import datetime, timezone, timedelta
import os, sys

# ============================================================
# IST TIMESTAMP
# ============================================================
IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp = now_ist.strftime('%Y%m%d_%H%M%S')
filename = f'MIPI_TestPlan_{timestamp}.xlsx'
script_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(script_dir, filename)

# ============================================================
# FULL INPUT JSON DATA - ALL 4 TESTCASES
# ============================================================
json_data = [
    {
        "Index": "1",
        "SS / Module": "MIPI",
        "Test Case Name": "mipi_csi2_dphy_lanes_test",
        "Feature": "DPHY Lane Configuration and CSI2 Data Transfer",
        "Test Description": "This test validates MIPI CSI-2 DPHY lane configuration by iterating through all supported lane counts (4 lanes down to 1 lane). For each lane configuration, the test enables all CSI-2 host interrupts, configures the virtual channel, initializes the D-PHY, waits for PHY stop state, sets the number of active lanes, and performs a complete CSI-2 data reception sequence using DMA. Control packets and image data packets are transferred via two DMA channels, with DMA interrupt polling used to detect transfer completion. The test verifies that CSI-2 data reception works correctly across all lane configurations.",
        "Test Steps / Procedure": "1. Enable all CSI-2 host interrupts by reading the main interrupt status register to clear pending interrupts, then writing appropriate mask values to all interrupt mask registers (PHY fatal, packet fatal, PHY, line, boundary frame fatal, sequence frame fatal, CRC frame fatal, payload CRC fatal, data ID, ECC corrected). 2. Configure the virtual channel register based on the selected GDMA path and enable control data transfer. 3. Initialize the D-PHY by calling the PHY initialization sequence. 4. Poll the PHY stop state register until the PHY enters stop state on all lanes (clock and data lanes). 5. For each lane configuration from 4 lanes down to 1 lane, write the number of active lanes to the N_LANES register. 6. Trigger the CSI-2 sequence for the current lane count. 7. For each expected control and data packet in the frame, enable DMA interrupts and program DMA channel 0 to transfer the 8-byte control packet. 8. Poll the DMA interrupt status to detect control packet transfer completion, then clear the DMA interrupt. 9. Read the control data to determine the data type and word count. 10. If the data type indicates image data, compute the aligned transfer size and program DMA channel 1 to transfer the CSI image data. 11. Poll the DMA interrupt status to detect image data transfer completion, then clear the DMA interrupt. 12. Repeat steps 5-11 for all lane configurations. 13. Verify the test completes successfully with finish(0).",
        "Impacted Registers": "virtual_channel; control_data; PHY_STOPSTATE; N_LANES; INT_ST_MAIN; INT_MSK_PHY_FATAL; INT_MSK_PKT_FATAL; INT_MSK_PHY; INT_MSK_LINE; INT_MSK_BNDRY_FRAME_FATAL; INT_MSK_SEQ_FRAME_FATAL; INT_MSK_CRC_FRAME_FATAL; INT_MSK_PLD_CRC_FATAL; INT_MSK_DATA_ID; INT_MSK_ECC_CORRECTED",
        "Validation / Acceptance Criteria": "1. The PHY stop state register must indicate all data lanes and the clock lane have entered stop state before lane configuration begins. 2. For each lane configuration (4 lanes down to 1 lane), DMA control packet transfers must complete successfully as indicated by the DMA interrupt status register. 3. When image data packets are present (data type greater than short packet threshold), DMA image data transfers must also complete successfully. 4. The test must iterate through all four lane configurations without stalling in any polling loop and must terminate successfully via finish(0).",
        "Remarks": "The test uses conditional compilation (GDMA0_PATH, GDMA1_PATH, GDMA2_PATH, GDMA3_PATH) to select the GDMA path, which determines the virtual channel bit position. Default configuration uses VC_ID=3, TOTAL_FRAME=1, LS_LE_EN=1, and DATA_TYPE=CSI2_RGB888. Resolution dimensions default to 64x3 (or 1920x1080 when GDMA0_FULL_MEM is defined). Two hardcoded hex addresses (used for CSI-2 sequence trigger and control data destination) could not be mapped to named registers. DMA-related offset registers (MIPI_CSI2_DMA_INTEN_OFFSET, MIPI_CSI2_DMA_INTMIS_OFFSET, MIPI_CSI2_DMA_INTCLR_OFFSET) are accessed via variable base plus offset and are used for DMA interrupt management.",
        "Speed": "NA",
        "Mode": "DMA Mode",
        "Memory Start Offset": "0xE6000000",
        "Memory End Offset": "0xE6002000",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"test_common.h\"; \"mipi_csi2.h\"",
        "Meta Macros": "GDMA_CSI2_DATA_DEST_ADDR2; GDMA_CTRL_DATA_DEST_ADDR2; LS_LE_EN; TOTAL_FRAME; VC_ID; VRES; HRES; DATA_TYPE",
        "Meta Arrays": "NA",
        "Meta Test Description": "This testcase validates MIPI CSI-2 DPHY lane configuration by iterating through lane counts from 4 lanes down to 1 lane. For each lane configuration, it performs a complete CSI-2 data reception sequence. The test begins by calling csi2_enable_interrupt() which reads MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN to clear pending interrupts, then writes all CSI-2 host interrupt mask registers (INT_MSK_PHY_FATAL with 0x0000000f, INT_MSK_PKT_FATAL with 0x00000003, INT_MSK_PHY with 0x000f000f, INT_MSK_LINE with 0x000f000f, INT_MSK_BNDRY_FRAME_FATAL with 0x0000ffff, INT_MSK_SEQ_FRAME_FATAL with 0x0000ffff, INT_MSK_CRC_FRAME_FATAL with 0x0000ffff, INT_MSK_PLD_CRC_FATAL with 0x0000ffff, INT_MSK_DATA_ID with 0x0000ffff, INT_MSK_ECC_CORRECTED with 0x0000ffff). The virtual channel ID is configured via MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL based on the selected GDMA path (GDMA0/1/2/3), and control data transfer is enabled by writing 1 to MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA. D-PHY initialization is performed via snps_phy_init(), then MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE is polled until it equals 0x1000f. A for loop iterates lane_num from 3 down to 0, writing MIZAR_MIPI_CSI2_HOST_N_LANES with lane_num and writing (lane_num+1) to 0xa0243ffc to trigger the CSI-2 sequence. For each lane configuration, an inner loop processes (VRES*3)+2 control packets using DMA channel 0 for control data (8-byte transfers) and DMA channel 1 for CSI data (variable size based on word_count extracted from control data read at 0xE6001000). DMA completion is detected by polling gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET and cleared via gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET.",
        "Meta Test Steps / Procedure": "1. Call csi2_enable_interrupt(): read MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN to clear pending interrupts. 2. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL with 0x0000000f. 3. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL with 0x00000003. 4. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY with 0x000f000f. 5. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE with 0x000f000f. 6. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL with 0x0000ffff. 7. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL with 0x0000ffff. 8. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL with 0x0000ffff. 9. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL with 0x0000ffff. 10. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID with 0x0000ffff. 11. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED with 0x0000ffff. 12. Compute vcid_csi2_wrap_reg based on GDMA path selection (GDMA0: VC_ID<<12, GDMA1: VC_ID<<8, GDMA2: VC_ID<<4, GDMA3: VC_ID). Set gdma_reg_base = 0xE6A00000. 13. Write MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL with vcid_csi2_wrap_reg. 14. Write MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA with 1 to enable control data transfer. 15. Write MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL again with vcid_csi2_wrap_reg. 16. Write MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA again with 1. 17. Call snps_phy_init() for D-PHY initialization. 18. Poll MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE until value equals 0x1000f. 19. Set ch0_pc = 0xE6000000, ch1_pc = 0xE6000500. 20. For lane_num = 3 down to 0: write MIZAR_MIPI_CSI2_HOST_N_LANES with lane_num. 21. Write 0xa0243ffc with (lane_num+1) to trigger CSI-2 sequence. 22. Compute cntrl_pkt_cnt = (VRES*3) + 2. 23. For each packet i in 0..cntrl_pkt_cnt-1: enable DMA interrupts by writing gdma_reg_base+MIPI_CSI2_DMA_INTEN_OFFSET with 0x3. 24. Program DMA channel 0 for control data transfer (src=0x8000, dest=0xE6001000, size=8). 25. Issue DMAGO for channel 0. 26. Poll gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 0 is set. 27. Clear DMA interrupt by writing gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET with 0x1. 28. Read gdma_reg_base+0x28 for debug status. 29. Read 0xE6001000 to get csi_ctrl_data. 30. If (csi_ctrl_data & 0x3f) > 0xf: extract word_count = (csi_ctrl_data >> 6) & 0xffff, compute csi_data_size aligned to 8 bytes. 31. Program DMA channel 1 for CSI data transfer (src=0x0000, dest=0xE6002000, size=csi_data_size). 32. Issue DMAGO for channel 1. 33. Poll gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 1 is set. 34. Clear DMA interrupt by writing gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET with 0x2. 35. Call finish(0) after all lane iterations complete.",
        "Meta Impacted Registers": "MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL; MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA; MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE; MIZAR_MIPI_CSI2_HOST_N_LANES; 0xa0243ffc; 0xE6001000; MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY; MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE; MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID; MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED",
        "Meta Validation / Acceptance Criteria": "1. MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE must be polled until it equals 0x1000f, confirming all data lanes and clock lane are in stop state. 2. For each lane configuration (lane_num 3 to 0), DMA channel 0 interrupt (bit 0 of gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET) must be set after control packet transfer. 3. When (csi_ctrl_data & 0x3f) > 0xf, DMA channel 1 interrupt (bit 1 of gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET) must be set after image data transfer. 4. The test must complete all lane iterations (4 lanes, 3 lanes, 2 lanes, 1 lane) and reach finish(0) without hanging in any polling loop."
    },
    {
        "Index": "2",
        "SS / Module": "MIPI",
        "Test Case Name": "mipi_csi2_rb_reg_wr_rd_test",
        "Feature": "CSI2 RB Register Write-Read Verification",
        "Test Description": "This test validates the MIPI CSI-2 RB register block by performing reset default value verification and write-read-back verification on 10 registers. In the first phase, each register is read and its value is compared against the expected reset default value. In the second phase, six different test data patterns are written to each writable register and then read back. The read-back value is compared against an expected value computed using the register's read mask and write mask to account for read-only and write-only bit fields. Registers marked in the skip array (interrupt_raw and flush) are excluded from write-read testing. The test passes only if all default value checks and all write-read-back comparisons succeed across all registers and all test patterns.",
        "Test Steps / Procedure": "1. Read each of the 10 CSI-2 RB registers and verify that the read value matches the expected reset default value for that register. Skip registers that are not readable based on their read mask. 2. For each of 6 test data patterns (all-ones, alternating 0xAA, alternating 0x55, all-zeros, 0xA5A5A5A5, 0xFFFF0000), write the pattern to each writable register. Skip registers marked in the skip array (interrupt_raw and flush) and registers with a zero write mask. 3. After writing, read back each register that was written. 4. Compute the expected read-back value by applying the register's write mask and read mask to account for read-only bits retaining their default values and write-only bits not being readable. 5. Compare the actual read-back value against the computed expected value. Record any mismatches. 6. Repeat steps 2-5 for all 6 test patterns. 7. Verify the test completes with no default value mismatches and no write-read mismatches. The test passes with finish(0) if all checks succeed, or fails with finish(1) if any mismatch is detected.",
        "Impacted Registers": "virtual_channel; line_info; fifo_threshold_val; lane_clk; mem; interrupt_raw; interrupt_mask; interrupt_enable; control_data; flush",
        "Validation / Acceptance Criteria": "1. All readable registers must return their expected reset default values when read during the default value check phase. 2. For each of the 6 test data patterns, every writable and readable register (excluding interrupt_raw and flush which are in the skip list) must return the correct expected value after a write-read-back cycle. The expected value accounts for read-only bits retaining default values and writable bits reflecting the written pattern. 3. The test must complete with zero default value mismatches and zero write-read mismatches, terminating successfully via finish(0). Any mismatch causes the test to fail via finish(1).",
        "Remarks": "The addr_array is declared with size 60 but only 10 register entries are populated; the remaining entries are zero-initialized. The skip_array marks interrupt_raw (index 5) and flush (index 9) as skipped for write-read verification, likely because interrupt_raw is a status register with special read behavior and flush may trigger side effects on write. The soft_reset_chk() function is commented out in the test_case() function and is not executed. Six distinct bit patterns are used to exercise all bit positions across the writable register fields.",
        "Speed": "NA",
        "Mode": "NA",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"test_define.c\"; \"test_common.h\"; <mipi_csi2_rb_reg.h>",
        "Meta Macros": "SOFT_RST_REG_ADDRESS; SOFT_RST_REG_DATA; CNT",
        "Meta Arrays": "addr_array[60]; default_value_array[60]; read_mask_array[60]; write_mask_array[60]; skip_array[60]; chk_val[6]",
        "Meta Test Description": "This testcase validates the MIPI CSI-2 RB REG register block by performing two phases of verification across 10 registers stored in addr_array[60]. Phase 1 (chk_rst_val): Iterates through all CNT entries in addr_array. For each register, if read_mask_array[i] is not 0x00000000, reads the register via read_reg(addr) and compares the read value against default_value_array[i]. If the values match, the check passes; otherwise def_fail_cnt is incremented. Phase 2 (chk_rd_wr): Uses 6 test patterns from chk_val[6] = {0xffffffff, 0xaaaaaaaa, 0x55555555, 0x00000000, 0xA5A5A5A5, 0xffff0000}. For each pattern, iterates through all registers: if skip_array[i] == 1 or write_mask_array[i] == 0x00000000, the register is skipped for writing; otherwise write_reg(addr, data_wr) is called. Then for reading back, registers are skipped if skip_array[i] == 1, write_mask_array[i] == 0x00000000, or read_mask_array[i] == 0x00000000. For readable/writable registers, the expected value is computed as exp_val = ((data_wr & read_mask_array[i] & write_mask_array[i]) | (wr_n & read_mask_array[i] & default_value_array[i])) where wr_n = (write_mask_array[i] ^ 0xffffffff). The read value is compared against exp_val; mismatches increment wr_fail_cnt. The test calls finish(1) if def_fail_cnt > 0 or wr_fail_cnt > 0, otherwise finish(0). The registers tested are: MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL, MIZAR_MIPI_CSI2_RB_REG_LINE_INFO, MIZAR_MIPI_CSI2_RB_REG_FIFO_THRESHOLD_VAL, MIZAR_MIPI_CSI2_RB_REG_LANE_CLK, MIZAR_MIPI_CSI2_RB_REG_MEM, MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_RAW, MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_MASK, MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_ENABLE, MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA, MIZAR_MIPI_CSI2_RB_REG_FLUSH. skip_array marks indices 5 (MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_RAW) and 9 (MIZAR_MIPI_CSI2_RB_REG_FLUSH) as skipped for write-read testing.",
        "Meta Test Steps / Procedure": "1. Call chk_rst_val(): iterate i from 0 to CNT-1. 2. For each i, set addr = addr_array[i]. 3. If read_mask_array[i] == 0x00000000, skip this register (not readable). 4. Call data_rd = read_reg(addr). 5. Compare data_rd against default_value_array[i]. If mismatch, increment def_fail_cnt. 6. Call chk_rd_wr(): initialize chk_val[6] = {0xffffffff, 0xaaaaaaaa, 0x55555555, 0x00000000, 0xA5A5A5A5, 0xffff0000}. 7. For each j from 0 to 5, set data_wr = chk_val[j]. 8. Writing phase: for each i from 0 to CNT-1, set addr = addr_array[i]. 9. If skip_array[i] == 1, skip writing. 10. If write_mask_array[i] == 0x00000000, skip writing (not writable). 11. Otherwise call write_reg(addr, data_wr). 12. Reading phase: for each i from 0 to CNT-1, set addr = addr_array[i]. 13. If skip_array[i] == 1, skip reading. 14. If write_mask_array[i] == 0x00000000, skip reading. 15. If read_mask_array[i] == 0x00000000, skip reading. 16. Otherwise call data_rd = read_reg(addr). 17. Compute wr_n = (write_mask_array[i] ^ 0xffffffff). 18. Compute exp_val = ((data_wr & read_mask_array[i] & write_mask_array[i]) | (wr_n & read_mask_array[i] & default_value_array[i])). 19. Compare data_rd against exp_val. If mismatch, increment wr_fail_cnt. 20. After both phases complete, if def_fail_cnt > 0 or wr_fail_cnt > 0, call finish(1); otherwise call finish(0).",
        "Meta Impacted Registers": "MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL; MIZAR_MIPI_CSI2_RB_REG_LINE_INFO; MIZAR_MIPI_CSI2_RB_REG_FIFO_THRESHOLD_VAL; MIZAR_MIPI_CSI2_RB_REG_LANE_CLK; MIZAR_MIPI_CSI2_RB_REG_MEM; MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_RAW; MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_MASK; MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_ENABLE; MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA; MIZAR_MIPI_CSI2_RB_REG_FLUSH",
        "Meta Validation / Acceptance Criteria": "1. In chk_rst_val(), for each register where read_mask_array[i] != 0x00000000, data_rd from read_reg(addr_array[i]) must equal default_value_array[i]. Any mismatch increments def_fail_cnt. 2. In chk_rd_wr(), for each of the 6 test patterns (0xffffffff, 0xaaaaaaaa, 0x55555555, 0x00000000, 0xA5A5A5A5, 0xffff0000), after write_reg(addr, data_wr), the subsequent read_reg(addr) must return a value equal to exp_val = ((data_wr & read_mask_array[i] & write_mask_array[i]) | (wr_n & read_mask_array[i] & default_value_array[i])). Any mismatch increments wr_fail_cnt. 3. Registers at skip_array indices 5 (MIZAR_MIPI_CSI2_RB_REG_INTERRUPT_RAW) and 9 (MIZAR_MIPI_CSI2_RB_REG_FLUSH) are skipped during write-read testing. 4. The test passes (finish(0)) only when both def_fail_cnt == 0 and wr_fail_cnt == 0."
    },
    {
        "Index": "3",
        "SS / Module": "MIPI",
        "Test Case Name": "mipi_csi2_test_pattern_generator",
        "Feature": "CSI2 Internal Test Pattern Generator and DMA Data Reception",
        "Test Description": "This test validates the MIPI CSI-2 host controller's internal test pattern generator functionality with DMA-based data reception. The test configures the virtual channel, enables all CSI-2 host interrupts, initializes the D-PHY, and waits for PHY stop state. DMA address registers are configured for channel 0 data and instruction paths. The internal pattern generator is configured with a vertical resolution of 16 lines, horizontal resolution of 320 pixels, 24 bits per pixel (RGB888), and then enabled. After a brief wait, the pattern generator is disabled. The test polls the DMA interrupt status to confirm that the generated test pattern data was successfully transferred via DMA. The test verifies end-to-end data flow from the internal pattern generator through the CSI-2 host to the DMA destination.",
        "Test Steps / Procedure": "1. Configure the virtual channel register based on the selected GDMA path with virtual channel ID 3 and disable control data transfer. 2. Enable all CSI-2 host interrupts by reading the main interrupt status register to clear pending interrupts, then writing appropriate mask values to all interrupt mask registers (PHY fatal, packet fatal, PHY, line, boundary frame fatal, sequence frame fatal, CRC frame fatal, payload CRC fatal, data ID, ECC corrected). 3. Initialize the D-PHY by calling the PHY initialization sequence. 4. Poll the PHY stop state register until the PHY enters stop state on all lanes (clock and data lanes). 5. Configure DMA address registers for channel 0 read and write data paths and instruction paths. 6. Enable fracdiv output to the CSI-2 subsystem. 7. Program DMA channel 0 for image data transfer with source from CSI-2 data port, destination memory address, and computed transfer size for 320x16 pixels at 24 bits per pixel (RGB888). 8. Issue DMAGO to start DMA channel 0 transfer. 9. Enable the internal test pattern generator by configuring vertical resolution (16 lines), horizontal resolution (320 pixels with 7 lines), pattern configuration, and setting the enable bit. 10. Wait briefly for pattern generation to complete, then disable the pattern generator. 11. Poll the DMA interrupt status register to detect DMA transfer completion (bit 0 set). 12. Wait for post-transfer settling time and verify the test completes successfully with finish(0).",
        "Impacted Registers": "PPI_PG_PATTERN_VRES; PPI_PG_PATTERN_HRES; PPI_PG_CONFIG; PPI_PG_ENABLE; virtual_channel; control_data; PHY_STOPSTATE; dma_m0_addr_ar_ch0_data; dma_m0_addr_ar_ch0_Instruction; dma_m0_addr_aw_ch0_data; dma_m0_addr_aw_ch0_Instruction; INT_ST_MAIN; INT_MSK_PHY_FATAL; INT_MSK_PKT_FATAL; INT_MSK_PHY; INT_MSK_LINE; INT_MSK_BNDRY_FRAME_FATAL; INT_MSK_SEQ_FRAME_FATAL; INT_MSK_CRC_FRAME_FATAL; INT_MSK_PLD_CRC_FATAL; INT_MSK_DATA_ID; INT_MSK_ECC_CORRECTED",
        "Validation / Acceptance Criteria": "1. The PHY stop state register must indicate all data lanes and the clock lane have entered stop state before the test pattern generator is activated. 2. The internal test pattern generator must successfully generate a 320x16 pixel RGB888 pattern when enabled via the pattern generator enable register. 3. DMA channel 0 must complete the data transfer of the generated test pattern, as indicated by the DMA interrupt status register bit 0 being set. 4. The test must complete without stalling in any polling loop and must terminate successfully via finish(0).",
        "Remarks": "The test uses conditional compilation (GDMA0_PATH, GDMA1_PATH, GDMA2_PATH, GDMA3_PATH) to select the GDMA path, which determines the virtual channel bit position and gdma_reg_base. Default configuration uses vcid=3. The pattern generator is configured for 16 vertical lines and 320 horizontal pixels at 24 bits per pixel (RGB888 format). The pattern generator configuration value 0xe401 encodes data type and pattern mode settings. Control data transfer is explicitly disabled (set to 0) unlike the DPHY lanes test. A write to an offset-based register (base + 0xf4) enables fracdiv output to the CSI-2 subsystem. DMA-related offset registers (MIPI_CSI2_DMA_INTMIS_OFFSET) are accessed via variable base plus offset for DMA interrupt polling. The FPS60 conditional compilation flag controls whether DMA destination address incrementing is enabled.",
        "Speed": "NA",
        "Mode": "DMA Mode",
        "Memory Start Offset": "0xE6000000",
        "Memory End Offset": "0xE6040080",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"test_common.h\"; \"mipi_csi2.h\"",
        "Meta Macros": "GDMA_CSI2_DATA_DEST_ADDR2; GDMA_CTRL_DATA_DEST_ADDR2",
        "Meta Arrays": "NA",
        "Meta Test Description": "This testcase validates the MIPI CSI-2 host controller's internal test pattern generator (PPI PG) functionality with DMA-based data reception. The test begins by configuring the virtual channel register (MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL) based on the selected GDMA path (GDMA0/1/2/3) using vcid=3 and vcid_unselected_path=((vcid+1)&0xf). Control data transfer is disabled by writing 0 to MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA. CSI-2 and DMA interrupts are enabled via csi2_subsys_enable_interrupt(). The csi2_enable_interrupt() function reads MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN to clear pending interrupts, then writes all 10 interrupt mask registers (INT_MSK_PHY_FATAL with 0x0000000f, INT_MSK_PKT_FATAL with 0x00000003, INT_MSK_PHY with 0x000f000f, INT_MSK_LINE with 0x000f000f, INT_MSK_BNDRY_FRAME_FATAL with 0x0000ffff, INT_MSK_SEQ_FRAME_FATAL with 0x0000ffff, INT_MSK_CRC_FRAME_FATAL with 0x0000ffff, INT_MSK_PLD_CRC_FATAL with 0x0000ffff, INT_MSK_DATA_ID with 0x0000ffff, INT_MSK_ECC_CORRECTED with 0x0000ffff). D-PHY initialization is performed via snps_phy_init(), then MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE is polled until it equals 0x1000f. The test configures hres=320, vres=16, valid_bits_per_pixel=24, and computes csi2_data_trnsfr_size as the total byte count aligned to 8 bytes. DMA address registers are configured: MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_DATA with 0x100, MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_INSTRUCTION with 0x0, MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_DATA with 0x0, MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_INSTRUCTION with 0x0. Fracdiv output is enabled by writing 0x1 to MIZAR_MIPI_CSI2_RB_REG_BASE + 0xf4. DMA channel 0 is programmed via dma_trnsfr_instn_preload_incr_addr() with src_addr=0x00, dest_addr=0xE6001000, and the computed transfer size. DMAGO is issued for channel 0. The pattern generator is then enabled via csi2_ctrlr_pg_enable() which writes MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_VRES with 0x10, MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_HRES with 0x70140, MIZAR_MIPI_CSI2_HOST_PPI_PG_CONFIG with 0xe401, and MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE with 1. After a wait_on(100), the pattern generator is disabled by writing 0 to MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE. The test then polls gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 0 is set, indicating DMA transfer completion. After wait_on(10000), finish(0) is called.",
        "Meta Test Steps / Procedure": "1. Set int_pend = 1, vcid = 3, vcid_unselected_path = ((vcid+1)&0xf). 2. Compute vcid_csi2_wrap_reg based on GDMA path selection (GDMA0: vcid<<12 + unselected for others; GDMA1: vcid<<8; GDMA2: vcid<<4; GDMA3: vcid). 3. Set gdma_reg_base = 0xE6A00000 + (gdma_path * 0x1000). 4. Write MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL with vcid_csi2_wrap_reg. 5. Write MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA with 0 to disable control data transfer. 6. Call csi2_subsys_enable_interrupt() to enable CSI-2 and DMA interrupts. 7. In csi2_enable_interrupt(): read MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN to clear pending interrupts. 8. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL with 0x0000000f. 9. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL with 0x00000003. 10. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY with 0x000f000f. 11. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE with 0x000f000f. 12. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL with 0x0000ffff. 13. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL with 0x0000ffff. 14. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL with 0x0000ffff. 15. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL with 0x0000ffff. 16. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID with 0x0000ffff. 17. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED with 0x0000ffff. 18. Call snps_phy_init() for D-PHY initialization. 19. Poll MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE until value equals 0x1000f. 20. Set hres=320, vres=16, valid_bits_per_pixel=24. 21. Compute csi2_data_trnsfr_size = aligned byte count for (valid_bits_per_pixel * hres / 8) * vres, aligned to 8 bytes. 22. Write MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_DATA with 0x100. 23. Write MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_INSTRUCTION with 0x0. 24. Write MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_DATA with 0x0. 25. Write MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_INSTRUCTION with 0x0. 26. Write MIZAR_MIPI_CSI2_RB_REG_BASE + 0xf4 with 0x1 to enable fracdiv output. 27. Set dma_ch0_pc = 0xE6000000. 28. Call dma_trnsfr_instn_preload_incr_addr(dma_ch0_pc, gdma_reg_base, 0x00, 0xE6001000, csi2_data_trnsfr_size, 0, dma_dest_addr_incr_flag, 0). 29. Call DMAGO_CSI(gdma_reg_base, dma_ch0_pc, 0) to start DMA channel 0. 30. Call csi2_ctrlr_pg_enable(): write MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_VRES with 0x10. 31. Write MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_HRES with 0x70140. 32. Write MIZAR_MIPI_CSI2_HOST_PPI_PG_CONFIG with 0xe401. 33. Write MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE with 1 to enable pattern generator. 34. Call wait_on(100). 35. Write MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE with 0 to disable pattern generator. 36. Poll gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 0 is set (DMA transfer complete). 37. Call wait_on(10000). 38. Call finish(0).",
        "Meta Impacted Registers": "MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_VRES; MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_HRES; MIZAR_MIPI_CSI2_HOST_PPI_PG_CONFIG; MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE; MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL; MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA; MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_DATA; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_INSTRUCTION; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_DATA; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_INSTRUCTION; MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY; MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE; MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID; MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED",
        "Meta Validation / Acceptance Criteria": "1. MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE must be polled until it equals 0x1000f, confirming all data lanes and clock lane are in stop state before pattern generation begins. 2. After enabling the pattern generator (MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE = 1) with VRES=0x10, HRES=0x70140, CONFIG=0xe401, and then disabling it (MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE = 0), the DMA must complete the data transfer. 3. DMA completion is validated by polling gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 0 is set, indicating DMA channel 0 transfer is complete. 4. The test must reach finish(0) without hanging in any polling loop (PHY stop state or DMA interrupt)."
    },
    {
        "Index": "4",
        "SS / Module": "MIPI",
        "Test Case Name": "mipi_dphy_idi_test",
        "Feature": "DPHY IDI Virtual Channel Data Transfer",
        "Test Description": "This test validates MIPI CSI-2 DPHY IDI data transfer across all 16 virtual channel IDs (0 through 15). The test initializes the D-PHY, enables all CSI-2 host interrupts, and waits for the PHY to enter stop state. Control data transfer and null/blanking data transfer are both enabled. For each of the 16 virtual channels, the virtual channel register is configured and 129 control packets are processed using DMA. For each packet, DMA channel 0 transfers the 8-byte control data. The control data is then read to determine the packet type. If the packet is a long packet (data type greater than short packet threshold), the word count is extracted and DMA channel 1 transfers the corresponding CSI image data. DMA completion is detected by polling the DMA interrupt status register. The test verifies that CSI-2 data reception works correctly across all 16 virtual channels.",
        "Test Steps / Procedure": "1. Initialize the D-PHY by calling the PHY initialization sequence. 2. Enable all CSI-2 host interrupts by reading the main interrupt status register to clear pending interrupts, then writing appropriate mask values to all interrupt mask registers (PHY fatal, packet fatal, PHY, line, boundary frame fatal, sequence frame fatal, CRC frame fatal, payload CRC fatal, data ID, ECC corrected). 3. Poll the PHY stop state register until the PHY enters stop state on all lanes (clock and data lanes). 4. Enable control data transfer by writing to the control data register. 5. Enable null and blanking data transfer by writing to the null blank register. 6. For each virtual channel ID from 0 to 15, configure the virtual channel register with the current vcid shifted to the appropriate bit position. 7. Trigger the external test environment to start packet transfer on the selected virtual channel. 8. For each of the 129 control packets, enable DMA interrupts and program DMA channel 0 to transfer the 8-byte control packet from the CSI-2 control data port to the destination memory. 9. Poll the DMA interrupt status to detect control packet transfer completion, then clear the DMA interrupt. 10. Read the control data from the destination memory to determine the packet data type and word count. 11. If the packet is a long packet (data type indicates image data), compute the aligned transfer size from the word count and program DMA channel 1 to transfer the CSI image data. 12. Poll the DMA interrupt status to detect image data transfer completion, then clear the DMA interrupt. 13. Repeat steps 6-12 for all 16 virtual channels. 14. Verify the test completes successfully with finish(0).",
        "Impacted Registers": "PHY_STOPSTATE; control_data; null_blank; virtual_channel; INT_ST_MAIN; INT_MSK_PHY_FATAL; INT_MSK_PKT_FATAL; INT_MSK_PHY; INT_MSK_LINE; INT_MSK_BNDRY_FRAME_FATAL; INT_MSK_SEQ_FRAME_FATAL; INT_MSK_CRC_FRAME_FATAL; INT_MSK_PLD_CRC_FATAL; INT_MSK_DATA_ID; INT_MSK_ECC_CORRECTED",
        "Validation / Acceptance Criteria": "1. The PHY stop state register must indicate all data lanes and the clock lane have entered stop state before data transfer begins. 2. For each of the 16 virtual channels (0 through 15), all 129 DMA control packet transfers must complete successfully as indicated by the DMA interrupt status register. 3. When long packets are detected (data type greater than short packet threshold), DMA image data transfers must also complete successfully for each such packet. 4. The test must iterate through all 16 virtual channels without stalling in any polling loop and must terminate successfully via finish(0).",
        "Remarks": "This test exercises all 16 virtual channel IDs (0-15) unlike the DPHY lanes test which iterates lane counts. The virtual channel ID is shifted left by 12 bits when written to the virtual channel register, indicating GDMA0 path usage. Both control data and null/blanking data transfers are enabled. The test processes 129 control packets per virtual channel, totaling 2064 packet processing iterations. Two hardcoded hex addresses (used for UVM test trigger and control data destination) could not be mapped to named registers. DMA-related offset registers (MIPI_CSI2_DMA_INTEN_OFFSET, MIPI_CSI2_DMA_INTMIS_OFFSET, MIPI_CSI2_DMA_INTCLR_OFFSET) are accessed via variable base plus offset and are used for DMA interrupt management. The DMA interrupt enable write (0x3) is performed twice per packet iteration in the source code.",
        "Speed": "NA",
        "Mode": "DMA Mode",
        "Memory Start Offset": "0xE6000000",
        "Memory End Offset": "0xE6002000",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"test_common.h\"; \"mipi_csi2.h\"",
        "Meta Macros": "GDMA_CSI2_DATA_DEST_ADDR2; GDMA_CTRL_DATA_DEST_ADDR2",
        "Meta Arrays": "NA",
        "Meta Test Description": "This testcase validates MIPI CSI-2 DPHY IDI (Image Data Interface) data transfer across all 16 virtual channel IDs (vcid 0 to 15). The test begins by calling snps_phy_init() for D-PHY initialization, then calls csi2_enable_interrupt() which reads MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN to clear pending interrupts and writes all 10 CSI-2 host interrupt mask registers (INT_MSK_PHY_FATAL with 0x0000000f, INT_MSK_PKT_FATAL with 0x00000003, INT_MSK_PHY with 0x000f000f, INT_MSK_LINE with 0x000f000f, INT_MSK_BNDRY_FRAME_FATAL with 0x0000ffff, INT_MSK_SEQ_FRAME_FATAL with 0x0000ffff, INT_MSK_CRC_FRAME_FATAL with 0x0000ffff, INT_MSK_PLD_CRC_FATAL with 0x0000ffff, INT_MSK_DATA_ID with 0x0000ffff, INT_MSK_ECC_CORRECTED with 0x0000ffff). MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE is polled until it equals 0x1000f. Control data transfer is enabled by writing 1 to MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA. Null and blanking data transfer is enabled by writing 1 to MIZAR_MIPI_CSI2_RB_REG_NULL_BLANK. The test sets cntrl_pkt_cnt = 129, ch0_pc = 0xE6000000, ch1_pc = 0xE6000500, gdma_reg_base = 0xE6A00000. An outer for loop iterates vcid from 0 to 15. For each vcid, vcid_csi2_wrap_reg = (vcid<<12) is computed and written to MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL. The vcid value is written to 0xa0243ffc to trigger the UVM test to start packet transfer on the selected virtual channel. An inner for loop iterates i from 0 to cntrl_pkt_cnt-1 (129 packets). For each packet: DMA interrupts are enabled by writing 0x3 to gdma_reg_base+MIPI_CSI2_DMA_INTEN_OFFSET. DMA channel 0 is programmed for control data transfer (src=0x8000, dest=0xE6001000, size=8) via dma_trnsfr_instn_preload(). DMAGO is issued for channel 0. gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET is polled until bit 0 is set. DMA interrupt is cleared by writing 0x1 to gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET. Debug status is read from gdma_reg_base+0x28. Control data is read from 0xE6001000 into csi_ctrl_data. If (csi_ctrl_data & 0x3f) > 0xf (long packet), word_count = (csi_ctrl_data >> 6) & 0xffff is extracted, csi_data_size is computed aligned to 8 bytes, DMA channel 1 is programmed for CSI data transfer (src=0x0000, dest=0xE6002000, size=csi_data_size), DMAGO is issued for channel 1, gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET is polled until bit 1 is set, and DMA interrupt is cleared by writing 0x2 to gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET. After all 16 virtual channels and 129 packets each, finish(0) is called.",
        "Meta Test Steps / Procedure": "1. Call snps_phy_init() for D-PHY initialization. 2. Call csi2_enable_interrupt(): read MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN to clear pending interrupts. 3. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL with 0x0000000f. 4. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL with 0x00000003. 5. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY with 0x000f000f. 6. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE with 0x000f000f. 7. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL with 0x0000ffff. 8. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL with 0x0000ffff. 9. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL with 0x0000ffff. 10. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL with 0x0000ffff. 11. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID with 0x0000ffff. 12. Write MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED with 0x0000ffff. 13. Poll MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE until value equals 0x1000f. 14. Write MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA with 1 to enable control data transfer. 15. Write MIZAR_MIPI_CSI2_RB_REG_NULL_BLANK with 1 to enable null and blanking data transfer. 16. Set cntrl_pkt_cnt = 129, ch0_pc = 0xE6000000, ch1_pc = 0xE6000500, gdma_reg_base = 0xE6A00000. 17. For vcid = 0 to 15: compute vcid_csi2_wrap_reg = (vcid << 12). 18. Write MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL with vcid_csi2_wrap_reg. 19. Write 0xa0243ffc with vcid to trigger UVM test to start packet transfer on the selected virtual channel. 20. For each packet i from 0 to 128: write gdma_reg_base+MIPI_CSI2_DMA_INTEN_OFFSET with 0x3 (enable DMA interrupts, done twice). 21. Program DMA channel 0 for control data transfer via dma_trnsfr_instn_preload(ch0_preload_loc, gdma_reg_base, 0x8000, 0xE6001000, 8, 0). 22. Issue DMAGO_CSI(gdma_reg_base, ch0_pc, 0x0) for channel 0. 23. Poll gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 0 is set. 24. Write gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET with 0x1 to clear DMA interrupt. 25. Read gdma_reg_base+0x28 for debug status. 26. Read 0xE6001000 to get csi_ctrl_data. 27. If (csi_ctrl_data & 0x3f) > 0xf: extract word_count = (csi_ctrl_data >> 6) & 0xffff. 28. Compute csi_data_size = aligned to 8 bytes from word_count. 29. Program DMA channel 1 via dma_trnsfr_instn_preload(ch1_preload_loc, gdma_reg_base, 0x0000, 0xE6002000, csi_data_size, 1). 30. Issue DMAGO_CSI(gdma_reg_base, ch1_pc, 0x1) for channel 1. 31. Poll gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET until bit 1 is set. 32. Read gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET again. 33. Write gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET with 0x2 to clear DMA interrupt. 34. After all 16 virtual channels and 129 packets each complete, call finish(0).",
        "Meta Impacted Registers": "MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE; MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA; MIZAR_MIPI_CSI2_RB_REG_NULL_BLANK; MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL; 0xa0243ffc; 0xE6001000; MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY; MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE; MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID; MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED",
        "Meta Validation / Acceptance Criteria": "1. MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE must be polled until it equals 0x1000f, confirming all data lanes and clock lane are in stop state. 2. For each of the 16 virtual channels (vcid 0 to 15), and for each of the 129 packets, DMA channel 0 interrupt (bit 0 of gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET) must be set after control packet transfer. 3. When (csi_ctrl_data & 0x3f) > 0xf (long packet detected), DMA channel 1 interrupt (bit 1 of gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET) must be set after image data transfer. 4. The test must complete all 16 virtual channel iterations with 129 packets each and reach finish(0) without hanging in any polling loop."
    }
]

# ============================================================
# CREATE WORKBOOK
# ============================================================
wb = openpyxl.Workbook()

# ============================================================
# STYLES
# ============================================================
header_font = Font(name='Calibri', bold=True, color='FFFFFF', size=11)
header_fill = PatternFill(start_color='4472C4', end_color='4472C4', fill_type='solid')
header_alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
cell_alignment = Alignment(vertical='top', wrap_text=True)

# ============================================================
# TESTPLAN SHEET
# ============================================================
ws_tp = wb.active
ws_tp.title = 'TestPlan'

tp_columns = [
    'Index', 'SS / Module', 'Feature', 'Test Case Name',
    'Test Description', 'Speed', 'Mode',
    'Memory Start Offset', 'Memory End Offset', 'Remarks',
    'Test Steps / Procedure', 'Impacted Registers',
    'Validation / Acceptance Criteria', 'Code Generation'
]

# Write headers
for col_idx, col_name in enumerate(tp_columns, 1):
    cell = ws_tp.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = header_alignment

# Write data rows
for row_idx, row_data in enumerate(json_data, 2):
    for col_idx, col_name in enumerate(tp_columns, 1):
        if col_name == 'Code Generation':
            value = ''
        else:
            value = row_data.get(col_name, '')
        cell = ws_tp.cell(row=row_idx, column=col_idx, value=value)
        cell.alignment = cell_alignment

# Freeze first row
ws_tp.freeze_panes = 'A2'

# Auto-size columns
for col_idx, col_name in enumerate(tp_columns, 1):
    max_length = len(col_name)
    for row in range(2, len(json_data) + 2):
        cell_value = str(ws_tp.cell(row=row, column=col_idx).value or '')
        max_length = max(max_length, min(len(cell_value), 80))
    adjusted_width = min(max_length + 4, 60)
    ws_tp.column_dimensions[get_column_letter(col_idx)].width = adjusted_width

# ============================================================
# METADATA SHEET
# ============================================================
ws_md = wb.create_sheet('MetaData')

md_columns = [
    'Index', 'Test Case Name',
    'Meta Test Description', 'Meta Test Steps / Procedure',
    'Meta Impacted Registers', 'Meta Validation / Acceptance Criteria',
    'Meta Headers', 'Meta Macros', 'Meta Arrays'
]

# Write headers
for col_idx, col_name in enumerate(md_columns, 1):
    cell = ws_md.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = header_alignment

# Write data rows
for row_idx, row_data in enumerate(json_data, 2):
    for col_idx, col_name in enumerate(md_columns, 1):
        value = row_data.get(col_name, '')
        cell = ws_md.cell(row=row_idx, column=col_idx, value=value)
        cell.alignment = cell_alignment

# Freeze first row
ws_md.freeze_panes = 'A2'

# Auto-size columns
for col_idx, col_name in enumerate(md_columns, 1):
    max_length = len(col_name)
    for row in range(2, len(json_data) + 2):
        cell_value = str(ws_md.cell(row=row, column=col_idx).value or '')
        max_length = max(max_length, min(len(cell_value), 80))
    adjusted_width = min(max_length + 4, 60)
    ws_md.column_dimensions[get_column_letter(col_idx)].width = adjusted_width

# Set MetaData sheet to veryHidden
ws_md.sheet_state = 'veryHidden'

# ============================================================
# SAVE WORKBOOK
# ============================================================
wb.save(output_path)
print(f'SUCCESS: {filename}')
print(f'Path: {output_path}')
print(f'Rows TestPlan: {len(json_data)}')
print(f'Rows MetaData: {len(json_data)}')
print(f'Sheets: {wb.sheetnames}')

# Validate
import os
if os.path.exists(output_path) and os.path.getsize(output_path) > 0:
    vwb = openpyxl.load_workbook(output_path)
    assert 'TestPlan' in vwb.sheetnames
    assert 'MetaData' in vwb.sheetnames
    print('VALIDATION: PASSED')
else:
    print('VALIDATION: FAILED')
