#!/usr/bin/env python3
"""MIPI_CSI TestPlan Excel Generator - Auto-generated by Ag_Excel_Generator Agent"""
import json
import os
from datetime import datetime, timezone, timedelta
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp = now_ist.strftime('%Y%m%d_%H%M%S')
FILENAME = f'MIPI_CSI_TestPlan_{timestamp}.xlsx'

json_data = [
  {
    "Index": "1",
    "SS / Module": "MIPI_CSI",
    "Test Case Name": "mipi_csi2_dphy_lanes_test",
    "Feature": "DPHY Lane Configuration and CSI-2 Data Transfer",
    "Meta Headers": '<stdio.h>; <stdlib.h>; \"test_common.h\"; \"mipi_csi2.h\"',
    "Meta Macros": "GDMA_CSI2_DATA_DEST_ADDR2; GDMA_CTRL_DATA_DEST_ADDR2; LS_LE_EN; TOTAL_FRAME; VC_ID; VRES; HRES; DATA_TYPE",
    "Meta Arrays": "NA",
    "Speed": "NA",
    "Mode": "NA",
    "Memory Start Offset": "NA",
    "Memory End Offset": "NA",
    "Meta Test Description": "This testcase validates MIPI CSI-2 DPHY lane configuration by iterating through all supported lane counts (4 lanes down to 1 lane). For each lane configuration, the test performs the following: 1) Calls csi2_enable_interrupt() to clear pending interrupts by reading MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN and then enables all CSI-2 interrupt masks (PHY_FATAL, PKT_FATAL, PHY, LINE, BNDRY_FRAME_FATAL, SEQ_FRAME_FATAL, CRC_FRAME_FATAL, PLD_CRC_FATAL, DATA_ID, ECC_CORRECTED). 2) Configures the virtual channel ID via MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL based on the selected GDMA path (GDMA0/1/2/3), with VC_ID shifted by 12/8/4/0 bits respectively. 3) Enables control data transfer by writing 1 to MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA. 4) Initializes the D-PHY via snps_phy_init(). 5) Polls MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE until it reads 0x1000f, confirming PHY has entered stop state. 6) Iterates lane_num from 3 down to 0, writing each lane_num to MIZAR_MIPI_CSI2_HOST_N_LANES and writing (lane_num+1) to 0xa0243ffc to trigger the CSI-2 sequence. 7) For each lane configuration, loops through cntrl_pkt_cnt = (VRES*3)+2 packets. Each iteration programs DMA channel 0 for control data transfer (8 bytes from 0x8000 to 0xE6001000) using dma_trnsfr_instn_preload() and DMAGO_CSI(), polls gdma_reg_base+MIPI_CSI2_DMA_INTMIS_OFFSET for bit 0, clears the interrupt via gdma_reg_base+MIPI_CSI2_DMA_INTCLR_OFFSET, reads control data from 0xE6001000, and if data_type > 0xf, calculates word_count and programs DMA channel 1 for CSI data transfer using dma_trnsfr_instn_preload() and DMAGO_CSI(), polls for bit 1 completion, and clears the interrupt. 8) Calls finish(0) upon completion.",
    "Test Description": "This test validates MIPI CSI-2 DPHY lane configuration by iterating through all supported lane counts from 4 lanes down to 1 lane. For each lane configuration, the test enables all CSI-2 host interrupt masks, configures the virtual channel ID, enables control data transfer, initializes the D-PHY, and waits for the PHY to enter stop state. It then configures the number of active lanes in the N_LANES register and triggers the CSI-2 sequence. For each packet in the frame, the test programs DMA channel 0 for control data transfer, polls for DMA completion, reads the control packet data, and if the data type indicates image data, programs DMA channel 1 for CSI image data transfer and polls for its completion. The test verifies correct operation across all lane configurations.",
    "Meta Test Steps / Procedure": "Step 1: Call csi2_enable_interrupt() which internally performs: Step 1a: rd_data = read_reg(MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN) to clear pending interrupts. Step 1b: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL, 0x0000000f). Step 1c: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL, 0x00000003). Step 1d: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY, 0x000f000f). Step 1e: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE, 0x000f000f). Step 1f: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL, 0x0000ffff). Step 1g: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL, 0x0000ffff). Step 1h: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL, 0x0000ffff). Step 1i: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL, 0x0000ffff). Step 1j: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID, 0x0000ffff). Step 1k: write_reg(MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED, 0x0000ffff). Step 2: Set vcid_csi2_wrap_reg based on GDMA path preprocessor define. Step 3: Set gdma_reg_base = 0xE6A00000. Step 4: write_reg(MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL, vcid_csi2_wrap_reg). Step 5: write_reg(MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA, 1). Step 6-8: Duplicate VC and control data writes. Step 9: Call snps_phy_init(). Step 10-11: Poll MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE until 0x1000f. Step 12-13: Set DMA PCs. Step 14: Loop lane_num 3 to 0. Step 15: write_reg(MIZAR_MIPI_CSI2_HOST_N_LANES, lane_num). Step 16-17: Compute cntrl_pkt_cnt. Step 18: write_reg(0xa0243ffc, lane_num+1). Step 19-43: Inner loop for DMA transfers. Step 44: End outer loop. Step 45: finish(0).",
    "Test Steps / Procedure": "1. Enable all CSI-2 host interrupts by reading the main interrupt status register to clear pending interrupts, then writing enable masks to the PHY fatal, packet fatal, PHY, line, boundary frame fatal, sequence frame fatal, CRC frame fatal, payload CRC fatal, data ID, and ECC corrected interrupt mask registers. 2. Configure the virtual channel ID in the virtual_channel register based on the selected GDMA path. 3. Enable control data transfer by writing to the control_data register. 4. Initialize the D-PHY by calling the PHY initialization routine. 5. Poll the PHY_STOPSTATE register until the PHY enters stop state. 6. Loop through lane configurations from 4 lanes down to 1 lane by writing the lane count to the N_LANES register. 7. Trigger the CSI-2 sequence for the current lane configuration. 8. For each control packet in the frame, program DMA channel 0 for control data transfer, start the DMA transfer, and poll the DMA interrupt status for channel 0 completion. 9. Clear the DMA channel 0 interrupt after completion. 10. Read the control packet data from the destination address. 11. If the data type indicates image data, calculate the word count and data size, program DMA channel 1 for CSI image data transfer, start the DMA transfer, and poll the DMA interrupt status for channel 1 completion. 12. Clear the DMA channel 1 interrupt after completion. 13. Repeat steps 7-12 for all packets in the frame. 14. Repeat steps 6-13 for all lane configurations. 15. Call finish to indicate test completion.",
    "Meta Impacted Registers": "MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL; MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA; MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE; MIZAR_MIPI_CSI2_HOST_N_LANES; 0xa0243ffc; 0xE6001000; MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY; MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE; MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID; MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED",
    "Impacted Registers": "virtual_channel; control_data; PHY_STOPSTATE; N_LANES; INT_ST_MAIN; INT_MSK_PHY_FATAL; INT_MSK_PKT_FATAL; INT_MSK_PHY; INT_MSK_LINE; INT_MSK_BNDRY_FRAME_FATAL; INT_MSK_SEQ_FRAME_FATAL; INT_MSK_CRC_FRAME_FATAL; INT_MSK_PLD_CRC_FATAL; INT_MSK_DATA_ID; INT_MSK_ECC_CORRECTED",
    "Meta Validation / Acceptance Criteria": "1. PHY stop state validation: Poll read_reg(MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE) in a while loop until rd_data == 0x1000f, confirming all lanes and clock lane have entered stop state. 2. DMA channel 0 completion: Poll read_reg(gdma_reg_base + MIPI_CSI2_DMA_INTMIS_OFFSET) in a while loop until (rd_data & 0x1) != 0x0, confirming control data DMA transfer is complete. 3. Control data type check: After reading csi_ctrl_data = read_reg(0xE6001000), check if (csi_ctrl_data & 0x3f) > 0xf to determine if the packet contains image data requiring a second DMA transfer. 4. DMA channel 1 completion: Poll read_reg(gdma_reg_base + MIPI_CSI2_DMA_INTMIS_OFFSET) in a while loop until (rd_data & 0x2) != 0x0, confirming CSI image data DMA transfer is complete. 5. Test completion: finish(0) is called indicating successful test execution with exit code 0.",
    "Validation / Acceptance Criteria": "1. The PHY_STOPSTATE register must read back a value confirming all data lanes and the clock lane have entered stop state before proceeding with lane configuration. 2. DMA channel 0 interrupt status must indicate transfer completion for each control packet before clearing the interrupt and proceeding. 3. The control data read from the destination must be checked for valid data type; if the data type indicates image data, a second DMA transfer on channel 1 must be initiated. 4. DMA channel 1 interrupt status must indicate transfer completion for each image data packet before clearing the interrupt. 5. The test must iterate through all four lane configurations (4 lanes, 3 lanes, 2 lanes, 1 lane) and process all packets for each configuration. 6. The test must complete successfully by calling the finish routine with a pass indicator of 0.",
    "Remarks": "The test iterates lane_num from 3 down to 0, testing 4-lane, 3-lane, 2-lane, and 1-lane DPHY configurations. The virtual channel ID and GDMA path are selected at compile time via preprocessor defines (GDMA0_PATH, GDMA1_PATH, GDMA2_PATH, GDMA3_PATH). The number of control packets per lane configuration is calculated as (VRES*3)+2. Two unresolved hex addresses are used: one for triggering the CSI-2 sequence and one as a DMA destination for control data readback. DMA interrupt-based polling is used for transfer completion on both channels."
  },
  {
    "Index": "2",
    "SS / Module": "MIPI_CSI",
    "Test Case Name": "mipi_csi2_test_pattern_generator",
    "Feature": "CSI-2 Internal Test Pattern Generator and DMA Data Transfer",
    "Meta Headers": '<stdio.h>; <stdlib.h>; \"test_common.h\"; \"mipi_csi2.h\"',
    "Meta Macros": "GDMA_CSI2_DATA_DEST_ADDR2; GDMA_CTRL_DATA_DEST_ADDR2",
    "Meta Arrays": "NA",
    "Speed": "NA",
    "Mode": "NA",
    "Memory Start Offset": "NA",
    "Memory End Offset": "NA",
    "Meta Test Description": "This testcase validates the MIPI CSI-2 host internal test pattern generator (PPI PG) functionality combined with DMA-based data transfer. The test performs the following: 1) Configures the virtual channel ID via MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL based on the selected GDMA path (GDMA0/1/2/3), with vcid=3 and vcid_unselected_path=((vcid+1)&0xf). 2) Disables control data transfer by writing 0 to MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA. 3) Calls csi2_subsys_enable_interrupt() which internally calls csi2_enable_interrupt() to clear pending interrupts by reading MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN and enables all CSI-2 interrupt masks. 4) Initializes the D-PHY via snps_phy_init(). 5) Polls MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE until it reads 0x1000f. 6) Calculates csi2_data_trnsfr_size based on hres=320, vres=16, valid_bits_per_pixel=24, with 8-byte alignment. 7) Programs DMA address registers. 8) Enables pattern generator. 9) Polls DMA completion. 10) Calls finish(0).",
    "Test Description": "This test validates the MIPI CSI-2 host internal test pattern generator functionality combined with DMA-based data transfer. The test configures the virtual channel ID based on the selected GDMA path, disables control data transfer, and enables all CSI-2 host interrupt masks. It then initializes the D-PHY and waits for the PHY to enter stop state. The test calculates the data transfer size based on resolution parameters (320x16 at 24 bits per pixel with 8-byte alignment), programs the DMA higher-order address registers for channel 0 data and instruction paths, enables the fractional divider output, and programs the DMA channel 0 transfer. The internal test pattern generator is then enabled with configured vertical resolution, horizontal resolution, and pattern configuration. After a wait period, the pattern generator is disabled, and the test polls the DMA interrupt status for channel 0 completion. The test verifies that the internally generated test pattern data is successfully transferred via DMA.",
    "Meta Test Steps / Procedure": "Step 1: Set int_pend = 1. Step 2: Set vcid = 3. Step 3: Compute vcid_unselected_path = ((vcid + 1) & 0xf). Step 4: Set vcid_csi2_wrap_reg based on GDMA path. Step 5: Set gdma_reg_base. Step 6: Print vcid_csi2_wrap_reg. Step 7: write_reg(MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL, vcid_csi2_wrap_reg). Step 8: write_reg(MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA, 0). Step 9: Call csi2_subsys_enable_interrupt(). Step 10: Call snps_phy_init(). Step 11-12: Poll PHY_STOPSTATE. Step 13-16: Calculate transfer size. Step 17-20: Program DMA address registers. Step 21: Enable fracdiv. Step 22-26: Program and start DMA. Step 27: Enable pattern generator. Step 28: wait_on(100). Step 29: Disable pattern generator. Step 30-31: Poll DMA completion. Step 32: wait_on(10000). Step 33: finish(0).",
    "Test Steps / Procedure": "1. Configure the virtual channel ID in the virtual_channel register based on the selected GDMA path with vcid=3. 2. Disable control data transfer by writing 0 to the control_data register. 3. Enable all CSI-2 host interrupts by reading the INT_ST_MAIN register to clear pending interrupts, then writing enable masks to the INT_MSK_PHY_FATAL, INT_MSK_PKT_FATAL, INT_MSK_PHY, INT_MSK_LINE, INT_MSK_BNDRY_FRAME_FATAL, INT_MSK_SEQ_FRAME_FATAL, INT_MSK_CRC_FRAME_FATAL, INT_MSK_PLD_CRC_FATAL, INT_MSK_DATA_ID, and INT_MSK_ECC_CORRECTED registers. 4. Initialize the D-PHY by calling the PHY initialization routine. 5. Poll the PHY_STOPSTATE register until the PHY enters stop state confirming all lanes and clock lane are ready. 6. Calculate the data transfer size based on resolution parameters (320x16 pixels at 24 bits per pixel with 8-byte alignment). 7. Program the DMA higher-order address registers for channel 0 by writing to dma_m0_addr_ar_ch0_data, dma_m0_addr_ar_ch0_Instruction, dma_m0_addr_aw_ch0_data, and dma_m0_addr_aw_ch0_Instruction registers. 8. Enable the fractional divider output to the CSI-2 subsystem. 9. Program DMA channel 0 transfer instructions with source address, destination address, and calculated transfer size, then start the DMA transfer. 10. Enable the internal test pattern generator by configuring the PPI_PG_PATTERN_VRES register with vertical resolution, PPI_PG_PATTERN_HRES register with horizontal resolution, PPI_PG_CONFIG register with pattern configuration, and PPI_PG_ENABLE register to enable. 11. Wait for the pattern generation period, then disable the pattern generator by writing 0 to the PPI_PG_ENABLE register. 12. Poll the DMA interrupt status for channel 0 completion until the transfer complete bit is set. 13. Wait for a settling period and call finish to indicate test completion.",
    "Meta Impacted Registers": "MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_VRES; MIZAR_MIPI_CSI2_HOST_PPI_PG_PATTERN_HRES; MIZAR_MIPI_CSI2_HOST_PPI_PG_CONFIG; MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE; MIZAR_MIPI_CSI2_RB_REG_VIRTUAL_CHANNEL; MIZAR_MIPI_CSI2_RB_REG_CONTROL_DATA; MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_DATA; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AR_CH0_INSTRUCTION; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_DATA; MIZAR_MIPI_CSI2_RB_REG_DMA_M0_ADDR_AW_CH0_INSTRUCTION; MIZAR_MIPI_CSI2_HOST_INT_ST_MAIN; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PKT_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PHY; MIZAR_MIPI_CSI2_HOST_INT_MSK_LINE; MIZAR_MIPI_CSI2_HOST_INT_MSK_BNDRY_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_SEQ_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_CRC_FRAME_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_PLD_CRC_FATAL; MIZAR_MIPI_CSI2_HOST_INT_MSK_DATA_ID; MIZAR_MIPI_CSI2_HOST_INT_MSK_ECC_CORRECTED",
    "Impacted Registers": "PPI_PG_PATTERN_VRES; PPI_PG_PATTERN_HRES; PPI_PG_CONFIG; PPI_PG_ENABLE; virtual_channel; control_data; PHY_STOPSTATE; dma_m0_addr_ar_ch0_data; dma_m0_addr_ar_ch0_Instruction; dma_m0_addr_aw_ch0_data; dma_m0_addr_aw_ch0_Instruction; INT_ST_MAIN; INT_MSK_PHY_FATAL; INT_MSK_PKT_FATAL; INT_MSK_PHY; INT_MSK_LINE; INT_MSK_BNDRY_FRAME_FATAL; INT_MSK_SEQ_FRAME_FATAL; INT_MSK_CRC_FRAME_FATAL; INT_MSK_PLD_CRC_FATAL; INT_MSK_DATA_ID; INT_MSK_ECC_CORRECTED",
    "Meta Validation / Acceptance Criteria": "1. PHY stop state validation: Poll read_reg(MIZAR_MIPI_CSI2_HOST_PHY_STOPSTATE) in a while loop until rd_data == 0x1000f, confirming all data lanes and clock lane have entered stop state. 2. DMA channel 0 completion: Poll read_reg(gdma_reg_base + MIPI_CSI2_DMA_INTMIS_OFFSET) in a while loop until (rd_data & 0x1) != 0, confirming the DMA data transfer of the pattern generator output is complete. 3. Pattern generator enable/disable sequence: MIZAR_MIPI_CSI2_HOST_PPI_PG_ENABLE is written with 1 to enable and then 0 to disable after wait_on(100), confirming the pattern generator produces data for a controlled duration. 4. Test completion: finish(0) is called indicating successful test execution with exit code 0.",
    "Validation / Acceptance Criteria": "1. The PHY_STOPSTATE register must read back a value confirming all data lanes and the clock lane have entered stop state before proceeding with DMA programming and pattern generation. 2. The DMA channel 0 interrupt status must indicate transfer completion, confirming that the internally generated test pattern data was successfully transferred via DMA to the destination. 3. The pattern generator must be enabled and then disabled in a controlled sequence, producing data for the configured resolution (320x16 at 24bpp). 4. The test must complete successfully by calling the finish routine with a pass indicator of 0.",
    "Remarks": "The test uses the CSI-2 host internal test pattern generator (PPI PG) instead of an external DPHY source. The pattern generator is configured with vertical resolution 0x10 (16 lines), horizontal resolution 0x70140 (7 lines spacing, 320 pixels), and pattern config 0xe401. The virtual channel ID is set to 3 and the GDMA path is selected at compile time via preprocessor defines (GDMA0_PATH, GDMA1_PATH, GDMA2_PATH, GDMA3_PATH). The DMA destination address increment behavior is controlled by the FPS60 compile-time flag. Control data transfer is explicitly disabled for this test. A base+offset register write to enable fracdiv output is used but could not be mapped to a named register. DMA interrupt-based polling is used for transfer completion on channel 0."
  }
]

# TestPlan sheet columns
tp_cols = ['Index', 'SS / Module', 'Feature', 'Test Case Name', 'Test Description',
           'Speed', 'Mode', 'Memory Start Offset', 'Memory End Offset', 'Remarks',
           'Test Steps / Procedure', 'Impacted Registers', 'Validation / Acceptance Criteria',
           'Code Generation']

# MetaData sheet columns
md_cols = ['Index', 'Test Case Name', 'Meta Test Description', 'Meta Test Steps / Procedure',
           'Meta Impacted Registers', 'Meta Validation / Acceptance Criteria',
           'Meta Headers', 'Meta Macros', 'Meta Arrays']

HEADER_FILL = PatternFill(start_color='003366', end_color='003366', fill_type='solid')
HEADER_FONT = Font(bold=True, color='FFFFFF', size=11)
WRAP = Alignment(wrap_text=True, vertical='top')

def auto_width(ws, max_w=60):
    for col_cells in ws.columns:
        lengths = []
        for cell in col_cells:
            v = str(cell.value) if cell.value else ''
            lengths.append(min(len(v), max_w))
        best = max(lengths, default=10) + 4
        ws.column_dimensions[get_column_letter(col_cells[0].column)].width = min(best, max_w)

wb = Workbook()
ws_tp = wb.active
ws_tp.title = 'TestPlan'

# Write TestPlan headers
for ci, h in enumerate(tp_cols, 1):
    c = ws_tp.cell(row=1, column=ci, value=h)
    c.fill = HEADER_FILL
    c.font = HEADER_FONT
    c.alignment = WRAP

# Write TestPlan data
for ri, row in enumerate(json_data, 2):
    for ci, col in enumerate(tp_cols, 1):
        val = row.get(col, '')
        c = ws_tp.cell(row=ri, column=ci, value=val)
        c.alignment = WRAP

ws_tp.freeze_panes = 'A2'
auto_width(ws_tp)

# Create MetaData sheet
ws_md = wb.create_sheet('MetaData')
for ci, h in enumerate(md_cols, 1):
    c = ws_md.cell(row=1, column=ci, value=h)
    c.fill = HEADER_FILL
    c.font = HEADER_FONT
    c.alignment = WRAP

for ri, row in enumerate(json_data, 2):
    for ci, col in enumerate(md_cols, 1):
        val = row.get(col, '')
        c = ws_md.cell(row=ri, column=ci, value=val)
        c.alignment = WRAP

ws_md.freeze_panes = 'A2'
auto_width(ws_md)
ws_md.sheet_state = 'veryHidden'

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), FILENAME)
wb.save(out_path)
print(f'SUCCESS: {FILENAME}')
print(f'PATH: {out_path}')

# Verify
wb2 = load_workbook(out_path)
assert 'TestPlan' in wb2.sheetnames
assert 'MetaData' in wb2.sheetnames
assert wb2['MetaData'].sheet_state == 'veryHidden'
print(f'VALIDATION: PASSED')
print(f'ROWS_TESTPLAN: {ws_tp.max_row - 1}')
print(f'ROWS_METADATA: {ws_md.max_row - 1}')
