#ifndef TEST_DEFINE_C
#define TEST_DEFINE_C

#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include "test_define.c"
#include<spi/spi_def.h>
#include<spi/spi_offset.h>

/* Provided testcase macros (unchanged) */
#define SOFT_RST_REG_ADDRESS	0x00000000
#define SOFT_RST_REG_DATA	0x00000000
#define CNT 22

/* Provided arrays (verbatim, unchanged) */
const unsigned long int addr_array[22]={MIZAR_SPI_RSM_CR0,MIZAR_SPI_RSM_CR1,MIZAR_SPI_RSM_DMA_CR,MIZAR_SPI_RSM_BAUD_RATE,MIZAR_SPI_RSM_TIMEOUT,MIZAR_SPI_RSM_FIFO,MIZAR_SPI_RSM_DMA,MIZAR_SPI_TX_FIFO_LEVEL_REG,MIZAR_SPI_RX_FIFO_LEVEL_REG,MIZAR_SPI_TRQ_LEVEL_REG,MIZAR_SPI_STS,MIZAR_SPI_IMSC,MIZAR_SPI_RIS,MIZAR_SPI_MIS,MIZAR_SPI_IC,MIZAR_SPI_RSM_TRQ_DATA_REG,MIZAR_SPI_RSM_TXTEST_DATA_REG,MIZAR_SPI_DATA_REG,MIZAR_SPI_RSM_TS_CTRL,MIZAR_SPI_SPI_TLEAD,MIZAR_SPI_SPI_TTRAIL,MIZAR_SPI_SPI_TIDLE,};
const unsigned int default_value_array[22]={SPI_RSM_CR0_DEFAULT_VAL,SPI_RSM_CR1_DEFAULT_VAL,SPI_RSM_DMA_CR_DEFAULT_VAL,SPI_RSM_BAUD_RATE_DEFAULT_VAL,SPI_RSM_TIMEOUT_DEFAULT_VAL,SPI_RSM_FIFO_DEFAULT_VAL,SPI_RSM_DMA_DEFAULT_VAL,SPI_TX_FIFO_LEVEL_REG_DEFAULT_VAL,SPI_RX_FIFO_LEVEL_REG_DEFAULT_VAL,SPI_TRQ_LEVEL_REG_DEFAULT_VAL,SPI_STS_DEFAULT_VAL,SPI_IMSC_DEFAULT_VAL,SPI_RIS_DEFAULT_VAL,SPI_MIS_DEFAULT_VAL,SPI_IC_DEFAULT_VAL,SPI_RSM_TRQ_DATA_REG_DEFAULT_VAL,SPI_RSM_TXTEST_DATA_REG_DEFAULT_VAL,SPI_DATA_REG_DEFAULT_VAL,SPI_RSM_TS_CTRL_DEFAULT_VAL,SPI_SPI_TLEAD_DEFAULT_VAL,SPI_SPI_TTRAIL_DEFAULT_VAL,SPI_SPI_TIDLE_DEFAULT_VAL,};
const unsigned int read_mask_array[22]={SPI_RSM_CR0_READ_MASK,SPI_RSM_CR1_READ_MASK,SPI_RSM_DMA_CR_READ_MASK,SPI_RSM_BAUD_RATE_READ_MASK,SPI_RSM_TIMEOUT_READ_MASK,SPI_RSM_FIFO_READ_MASK,SPI_RSM_DMA_READ_MASK,SPI_TX_FIFO_LEVEL_REG_READ_MASK,SPI_RX_FIFO_LEVEL_REG_READ_MASK,SPI_TRQ_LEVEL_REG_READ_MASK,SPI_STS_READ_MASK,SPI_IMSC_READ_MASK,SPI_RIS_READ_MASK,SPI_MIS_READ_MASK,SPI_IC_READ_MASK,SPI_RSM_TRQ_DATA_REG_READ_MASK,SPI_RSM_TXTEST_DATA_REG_READ_MASK,SPI_DATA_REG_READ_MASK,SPI_RSM_TS_CTRL_READ_MASK,SPI_SPI_TLEAD_READ_MASK,SPI_SPI_TTRAIL_READ_MASK,SPI_SPI_TIDLE_READ_MASK,};
const unsigned int write_mask_array[22]={SPI_RSM_CR0_WRITE_MASK,SPI_RSM_CR1_WRITE_MASK,SPI_RSM_DMA_CR_WRITE_MASK,SPI_RSM_BAUD_RATE_WRITE_MASK,SPI_RSM_TIMEOUT_WRITE_MASK,SPI_RSM_FIFO_WRITE_MASK,SPI_RSM_DMA_WRITE_MASK,SPI_TX_FIFO_LEVEL_REG_WRITE_MASK,SPI_RX_FIFO_LEVEL_REG_WRITE_MASK,SPI_TRQ_LEVEL_REG_WRITE_MASK,SPI_STS_WRITE_MASK,SPI_IMSC_WRITE_MASK,SPI_RIS_WRITE_MASK,SPI_MIS_WRITE_MASK,SPI_IC_WRITE_MASK,SPI_RSM_TRQ_DATA_REG_WRITE_MASK,SPI_RSM_TXTEST_DATA_REG_WRITE_MASK,SPI_DATA_REG_WRITE_MASK,SPI_RSM_TS_CTRL_WRITE_MASK,SPI_SPI_TLEAD_WRITE_MASK,SPI_SPI_TTRAIL_WRITE_MASK,SPI_SPI_TIDLE_WRITE_MASK,};
const unsigned int skip_array[22]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,};
unsigned int chk_val[6]={0xffffffff,0xaaaaaaaa,0x55555555,0x00000000,0xA5A5A5A5,0xffff0000};

/* Impacted registers list (for reference) */
static const unsigned long impacted_regs[] = {
    MIZAR_SPI_RSM_CR0, MIZAR_SPI_RSM_CR1, MIZAR_SPI_RSM_DMA_CR, MIZAR_SPI_RSM_BAUD_RATE,
    MIZAR_SPI_RSM_TIMEOUT, MIZAR_SPI_RSM_FIFO, MIZAR_SPI_RSM_DMA, MIZAR_SPI_TX_FIFO_LEVEL_REG,
    MIZAR_SPI_RX_FIFO_LEVEL_REG, MIZAR_SPI_TRQ_LEVEL_REG, MIZAR_SPI_STS, MIZAR_SPI_IMSC,
    MIZAR_SPI_RIS, MIZAR_SPI_MIS, MIZAR_SPI_IC, MIZAR_SPI_RSM_TRQ_DATA_REG,
    MIZAR_SPI_RSM_TXTEST_DATA_REG, MIZAR_SPI_DATA_REG, MIZAR_SPI_RSM_TS_CTRL, MIZAR_SPI_SPI_TLEAD,
    MIZAR_SPI_SPI_TTRAIL, MIZAR_SPI_SPI_TIDLE
};

/* Skip registers: none provided. Keep count as 0 and provide a placeholder array. */
#define NUM_SKIP_REGS 0u
static const unsigned long skip_regs[1] = { 0u }; /* placeholder, count is NUM_SKIP_REGS */

#endif /* TEST_DEFINE_C */
