/***********************************************************************
 * Program     : FV_uart_rx_fifo_en.c
 * Description : FV Structured Test - UART RX FIFO Enable Test
 *               Transformed from DV to FV style with init/run/teardown
 *               phase separation.
 * Auto-generated by Ag-FV-DV-Transition Agent
 ***********************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <test_common.h>
#include <uart/uart_def.h>
#include <uart/uart_offset.h>
#include "../common/uart_defines.h"
#include "../common/uart_functions.h"
#include <uart_rx_fifo_en.h>

extern int int_pend;
unsigned int i, j;
unsigned int err1;

/***********************************************************************
 * Function    : uart_rx_fifo_en_init
 * Description : Initialization phase - sets up UART RX FIFO test
 *               environment, enables interrupts, configures FIFO and
 *               UART parameters.
 * Parameters  : cfg - pointer to test configuration structure
 * Returns     : 0 on success
 ***********************************************************************/
int uart_rx_fifo_en_init(const TestsItem *cfg)
{
    (void)cfg;
    printf("[Test Init] UART RX FIFO Enable test: %s\n", cfg->test_name);
    LOGI("[Test Init]   UART RX FIFO Enable test: %s\n", cfg->test_name);

    return 0;
}

/***********************************************************************
 * Function    : uart_rx_fifo_en_run
 * Description : Execution phase - performs the UART RX FIFO Enable
 *               test by configuring interrupts, enabling FIFO,
 *               setting up UART, and processing RX transfers.
 * Parameters  : cfg - pointer to test configuration structure
 *               out - pointer to test output structure
 * Returns     : test status via out->status
 ***********************************************************************/
int uart_rx_fifo_en_run(const TestsItem *cfg, TestOutput *out)
{
    LOGI("[Test Run] UART RX FIFO Enable test: %s\n", cfg->test_name);

    int rcnt, arcnt;

    int nbytes[10] = {
        0xaa,
        0xbb,
        0xcc,
        0xdd,
        0xee,
        0x33,
        0xa1,
        0x43,
        0x45,
        0x66
    };

    LOGI("Started the RX FIFO Enable test\n");
    err1 = 0;

    // random define
    #ifdef RAND
        rand_inst = uart_if_rand();
    #endif

    // sysreg intr enable
    #ifdef UART0
        write_reg(0xA000001C, 0x00004000);
        GIC_EnableIRQ(66);
    #endif

    #ifdef UART1
        write_reg(0xA000001C, 0x00008000);
        GIC_EnableIRQ(67);
    #endif

    #ifdef UART2
        write_reg(0xA000001C, 0x00010000);
        GIC_EnableIRQ(68);
    #endif

    #ifdef UART3
        write_reg(0xA000001C, 0x00020000);
        GIC_EnableIRQ(69);
    #endif

    #ifdef UART4
        write_reg(0xA000001C, 0x00040000);
        GIC_EnableIRQ(70);
    #endif

    #ifdef UART5
        write_reg(0xA000001C, 0x00080000);
        GIC_EnableIRQ(71);
    #endif

    #ifdef UART6
        write_reg(0xA000001C, 0x00100000);
        GIC_EnableIRQ(72);
    #endif

    #ifdef UART7
        write_reg(0xA000001C, 0x00200000);
        GIC_EnableIRQ(73);
    #endif

    #ifdef UART8
        write_reg(0xA000001C, 0x00400000);
        GIC_EnableIRQ(74);
    #endif

    #ifdef UART9
        write_reg(0xA000001C, 0x00800000);
        GIC_EnableIRQ(75);
    #endif

    // 8bit word and fifo enable
    write_reg(MIZAR_UART_FIFO_CONTROL_REGISTER, 0x1);

    uart_config();

    write_reg(MIZAR_UART_INTERRUPT_ENABLE_REGISTER, UART_IER_RX_DATA);

    write_reg(0xA0243FFC, 0x963);

    for (i = 0; i < NO_OF_TRANSFERS; i++)
    {
        int_pend = 1;
        //while((read_reg(MIZAR_UART_LINE_STATUS_REGISTER) & 0x60) != 0x60);
        while (int_pend)
        {
            LOGI("Waiting for interrupt\n");
            wait_on(5);
        }

        //while((read_reg(MIZAR_UART_LINE_STATUS_REGISTER) & 0x1) != 0x1);

        //while(rcnt != (i+1)){
        //    rcnt = read_reg(MIZAR_UART_SRACTH_PAD_REGISTER);
        //}
    }

    /*
    printf("SCR: No. of received bytes count in scratch pad were %d\n", rcnt);

    for (j = 0; j < NO_OF_TRANSFERS; j++)
    {
        rx_data = read_reg(MIZAR_UART_RHR);
        printf("RX: Recieved byte%d = %x\n", i, rx_data);
    }

    arcnt = read_reg(MIZAR_UART_SRACTH_PAD_REGISTER);
    printf("SCR: No. of received bytes in fifo after read of RHR %d\n", arcnt);

    //write_reg(0xA0240200,0x369); // VIP handshake sequence end
    if (rcnt != i)
    {
        printf("No. of transfres %d is not equal to received %d", i, rcnt);
        err1 = 1;
    }
    */

    //write_reg(0xA0243FFC,0xdeaddead);
    err1 = uart_vip_scbd_status();

    return out->status = err1;
}

/***********************************************************************
 * Function    : Default_IRQHandler
 * Description : Interrupt handler for UART RX data ready interrupt.
 *               Reads ISR, validates RX line status, reads received
 *               data, and clears interrupt sources.
 ***********************************************************************/
void Default_IRQHandler()
{
    unsigned int rd_data, mis_addr, rx_data;
    int_pend = 0;

    mis_addr = MIZAR_UART_INTERRUPT_STATUS_REGISTER;
    rd_data = read_reg(mis_addr);

    if (rd_data & 0x4 != 0x4)
    {
        //printf("RX-%d: RX line is not ready: %d\n", i, rd_data);
        LOGI("RX-%d: RX line is not ready: %d\n", i, rd_data);
        err1 = 1;
    }
    else
    {
        #ifdef DEBUG_DISPLAY
            //printf("Scratchpad register transfer%d = %x\n", i, read_reg(MIZAR_UART_SRACTH_PAD_REGISTER));
            LOGI("Scratchpad register transfer%d = %x\n", i, read_reg(MIZAR_UART_SRACTH_PAD_REGISTER));
        #endif

        rx_data = read_reg(MIZAR_UART_RHR);

        #ifdef DEBUG_DISPLAY
            //printf("RX: Recieved byte%d = %x\n", i, rx_data);
            LOGI("RX: Recieved byte%d = %x\n", i, rx_data);
            //printf("Scratchpad register afetr transfer%d read = %x\n", i, read_reg(MIZAR_UART_SRACTH_PAD_REGISTER));
            LOGI("Scratchpad register afetr transfer%d read = %x\n", i, read_reg(MIZAR_UART_SRACTH_PAD_REGISTER));
        #endif

        #ifdef RAND
            rand_gic_disable(rand_inst);
        #endif

        #ifdef UART0
            write_reg(0xA0000018, 0x00004000);
            GIC_ClearIRQ(66);
        #endif

        #ifdef UART1
            write_reg(0xA0000018, 0x00008000);
            GIC_ClearIRQ(67);
        #endif

        #ifdef UART2
            write_reg(0xA0000018, 0x00010000);
            GIC_ClearIRQ(68);
        #endif

        #ifdef UART3
            write_reg(0xA0000018, 0x00020000);
            GIC_ClearIRQ(69);
        #endif

        #ifdef UART4
            write_reg(0xA0000018, 0x00040000);
            GIC_ClearIRQ(70);
        #endif

        #ifdef UART5
            write_reg(0xA0000018, 0x00080000);
            GIC_ClearIRQ(71);
        #endif

        #ifdef UART6
            write_reg(0xA0000018, 0x00100000);
            GIC_ClearIRQ(72);
        #endif

        #ifdef UART7
            write_reg(0xA0000018, 0x00200000);
            GIC_ClearIRQ(73);
        #endif

        #ifdef UART8
            write_reg(0xA0000018, 0x00400000);
            GIC_ClearIRQ(74);
        #endif

        #ifdef UART9
            write_reg(0xA0000018, 0x00800000);
            GIC_ClearIRQ(75);
        #endif
    }
}

/***********************************************************************
 * Function    : uart_rx_fifo_en_teardown
 * Description : Teardown phase - performs final validation, cleanup,
 *               and reports test completion status.
 * Parameters  : cfg - pointer to test configuration structure
 * Returns     : 0 on success
 ***********************************************************************/
int uart_rx_fifo_en_teardown(const TestsItem *cfg)
{
    (void)cfg;
    //printf("[DONE] UART RX FIFO Enable teardown: %s\n", cfg->test_name);
    LOGI("[TEARDOWN] UART RX FIFO Enable teardown: %s\n", cfg->test_name);

    return 0;
}
