#include<mipi_dsi_subsys.h>
#define CNT 52
int data_rd,data_wr,rst_val;


const unsigned long int addr_array[52]={MIZAR_MIPI_DSI_SUBSYS_DATA_FIFO_THRESHOLD_VAL,MIZAR_MIPI_DSI_SUBSYS_LOW_PWR,MIZAR_MIPI_DSI_SUBSYS_DBITE,MIZAR_MIPI_DSI_SUBSYS_DBI_FDIV,MIZAR_MIPI_DSI_SUBSYS_INTERRUPT_RAW,};


const int default_value_array[52]={MIPI_DSI_SUBSYS_DATA_FIFO_THRESHOLD_VAL_DEFAULT_VAL,MIPI_DSI_SUBSYS_LOW_PWR_DEFAULT_VAL,MIPI_DSI_SUBSYS_DBITE_DEFAULT_VAL,MIPI_DSI_SUBSYS_DBI_FDIV_DEFAULT_VAL,MIPI_DSI_SUBSYS_INTERRUPT_RAW_DEFAULT_VAL,};


const int read_mask_array[52]={MIPI_DSI_SUBSYS_DATA_FIFO_THRESHOLD_VAL_READ_MASK,MIPI_DSI_SUBSYS_LOW_PWR_READ_MASK,MIPI_DSI_SUBSYS_DBITE_READ_MASK,MIPI_DSI_SUBSYS_DBI_FDIV_READ_MASK,MIPI_DSI_SUBSYS_INTERRUPT_RAW_READ_MASK,};


const int write_mask_array[52]={MIPI_DSI_SUBSYS_DATA_FIFO_THRESHOLD_VAL_WRITE_MASK,MIPI_DSI_SUBSYS_LOW_PWR_WRITE_MASK,MIPI_DSI_SUBSYS_DBITE_WRITE_MASK,MIPI_DSI_SUBSYS_DBI_FDIV_WRITE_MASK,MIPI_DSI_SUBSYS_INTERRUPT_RAW_WRITE_MASK,};


const int skip_array[52]={0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0};


