/* Auto-generated by Test_Stage3 Agent
 * Testcase: dmac_reg_wr_rd_test
 * Objective: Verify DMA controller register defaults and masked write/read behavior
 * across the full register map defined in test_define.c.
 * Procedure:
 *   1) Check reset/default values for readable registers (read_mask != 0).
 *   2) For six data patterns, write to writable registers (write_mask != 0, not skipped),
 *      then read and compare masked expected values.
 * Pass/fail:
 *   - PASS finish(0) if both default and write/read checks have zero failures.
 *   - FAIL finish(1) otherwise.
 */

#include "test_define.c"

static int chk_rst_val(void) {
    int def_fail_cnt = 0;
    for (int i = 0; i < CNT; i++) {
        unsigned long addr = addr_array[i];
        unsigned int rmask = (unsigned int)read_mask_array[i];
        if (rmask == 0x00000000u) {
#ifdef DEBUG_DISPLAY
            printf("[RST] Skip read (rmask=0) idx=%d addr=0x%08lx\n", i, addr);
#endif
            continue;
        }
        unsigned int data_rd = read_reg(addr);
        unsigned int exp = (unsigned int)default_value_array[i];
        if (data_rd != exp) {
            def_fail_cnt++;
#ifdef DEBUG_DISPLAY
            printf("[RST][FAIL] idx=%d addr=0x%08lx exp=0x%08x rd=0x%08x\n", i, addr, exp, data_rd);
#endif
        } else {
#ifdef DEBUG_DISPLAY
            printf("[RST][PASS] idx=%d addr=0x%08lx val=0x%08x\n", i, addr, data_rd);
#endif
        }
    }
    return def_fail_cnt;
}

static int chk_rd_wr(void) {
    int wr_fail_cnt = 0;
    for (int p = 0; p < 6; p++) {
        unsigned int data_wr = (unsigned int)chk_val[p];
#ifdef DEBUG_DISPLAY
        printf("[WR] Pattern %d = 0x%08x\n", p, data_wr);
#endif
        /* Write phase */
        for (int i = 0; i < CNT; i++) {
            if (skip_array[i] == 1) {
#ifdef DEBUG_DISPLAY
                printf("[WR] Skip index %d (skip_array)\n", i);
#endif
                continue;
            }
            unsigned int wmask = (unsigned int)write_mask_array[i];
            if (wmask == 0x00000000u) {
#ifdef DEBUG_DISPLAY
                printf("[WR] Skip write (wmask=0) idx=%d\n", i);
#endif
                continue;
            }
            unsigned long addr = addr_array[i];
            write_reg(addr, data_wr);
#ifdef DEBUG_DISPLAY
            printf("[WR] Wrote idx=%d addr=0x%08lx data=0x%08x\n", i, addr, data_wr);
#endif
        }
        /* Read/verify phase */
        for (int i = 0; i < CNT; i++) {
            if (skip_array[i] == 1) continue;
            unsigned int wmask = (unsigned int)write_mask_array[i];
            unsigned int rmask = (unsigned int)read_mask_array[i];
            if (wmask == 0x00000000u) continue;
            if (rmask == 0x00000000u) continue;
            unsigned long addr = addr_array[i];
            unsigned int data_rd = read_reg(addr);
            unsigned int wr_n = (wmask ^ 0xffffffffu);
            unsigned int exp_val = ((data_wr & rmask & wmask) | (wr_n & rmask & (unsigned int)default_value_array[i]));
            if (data_rd != exp_val) {
                wr_fail_cnt++;
#ifdef DEBUG_DISPLAY
                printf("[RD][FAIL] idx=%d addr=0x%08lx exp=0x%08x rd=0x%08x rmask=0x%08x wmask=0x%08x\n",
                       i, addr, exp_val, data_rd, rmask, wmask);
#endif
            } else {
#ifdef DEBUG_DISPLAY
                printf("[RD][PASS] idx=%d addr=0x%08lx val=0x%08x\n", i, addr, data_rd);
#endif
            }
        }
    }
    return wr_fail_cnt;
}

void test_case(void) {
#ifdef DEBUG_DISPLAY
    printf("[TC] dmac_reg_wr_rd_test: start\n");
#endif
    int def_fail_cnt = chk_rst_val();
    int wr_fail_cnt = chk_rd_wr();
#ifdef DEBUG_DISPLAY
    printf("[TC] Results: def_fail_cnt=%d wr_fail_cnt=%d\n", def_fail_cnt, wr_fail_cnt);
#endif
    if (def_fail_cnt > 0 || wr_fail_cnt > 0) {
        finish(1);
    } else {
        finish(0);
    }
}
