// All headers and defines must be placed here before any other code.
#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include <dmac.h>

// Defines (unchanged from inputs)
#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST_REG_DATA    0x00000000
#define CNT 92

// Data patterns for masked write/read verification
int chk_val[6] = { 0xffffffff, 0xaaaaaaaa, 0x55555555, 0x00000000, 0xA5A5A5A5, 0xffff0000 };

// Addresses of impacted registers (symbolic; resolved via included headers)
const unsigned long int addr_array[92] = {
    MIZAR_DMA_DSR, MIZAR_DMA_DPC, MIZAR_DMA_INTEN, MIZAR_DMA_INT_EVENT_RIS, MIZAR_DMA_INTMIS, MIZAR_DMA_INTCLR,
    MIZAR_DMA_FSRD, MIZAR_DMA_FSRC, MIZAR_DMA_FTRD, MIZAR_DMA_FTR0, MIZAR_DMA_FTR1, MIZAR_DMA_FTR2, MIZAR_DMA_FTR3,
    MIZAR_DMA_FTR4, MIZAR_DMA_FTR5, MIZAR_DMA_FTR6, MIZAR_DMA_FTR7, MIZAR_DMA_CSR0, MIZAR_DMA_CSR1, MIZAR_DMA_CSR2,
    MIZAR_DMA_CSR3, MIZAR_DMA_CSR4, MIZAR_DMA_CSR5, MIZAR_DMA_CSR6, MIZAR_DMA_CSR7, MIZAR_DMA_CPC0, MIZAR_DMA_CPC1,
    MIZAR_DMA_CPC2, MIZAR_DMA_CPC3, MIZAR_DMA_CPC4, MIZAR_DMA_CPC5, MIZAR_DMA_CPC6, MIZAR_DMA_CPC7, MIZAR_DMA_SAR0,
    MIZAR_DMA_SAR1, MIZAR_DMA_SAR2, MIZAR_DMA_SAR3, MIZAR_DMA_SAR4, MIZAR_DMA_SAR5, MIZAR_DMA_SAR6, MIZAR_DMA_SAR7,
    MIZAR_DMA_DAR0, MIZAR_DMA_DAR1, MIZAR_DMA_DAR2, MIZAR_DMA_DAR3, MIZAR_DMA_DAR4, MIZAR_DMA_DAR5, MIZAR_DMA_DAR6,
    MIZAR_DMA_DAR7, MIZAR_DMA_CCR0, MIZAR_DMA_CCR1, MIZAR_DMA_CCR2, MIZAR_DMA_CCR3, MIZAR_DMA_CCR4, MIZAR_DMA_CCR5,
    MIZAR_DMA_CCR6, MIZAR_DMA_CCR7, MIZAR_DMA_LC0_0, MIZAR_DMA_LC0_1, MIZAR_DMA_LC0_2, MIZAR_DMA_LC0_3, MIZAR_DMA_LC0_4,
    MIZAR_DMA_LC0_5, MIZAR_DMA_LC0_6, MIZAR_DMA_LC0_7, MIZAR_DMA_LC1_0, MIZAR_DMA_LC1_1, MIZAR_DMA_LC1_2, MIZAR_DMA_LC1_3,
    MIZAR_DMA_LC1_4, MIZAR_DMA_LC1_5, MIZAR_DMA_LC1_6, MIZAR_DMA_LC1_7, MIZAR_DMA_DBGSTATUS, MIZAR_DMA_DBGCMD,
    MIZAR_DMA_DBGINST0, MIZAR_DMA_DBGINST1, MIZAR_DMA_CR0, MIZAR_DMA_CR1, MIZAR_DMA_CR2, MIZAR_DMA_CR3, MIZAR_DMA_CR4,
    MIZAR_DMA_CRD, MIZAR_DMA_WD, MIZAR_DMA_PERIPH_ID_0, MIZAR_DMA_PERIPH_ID_1, MIZAR_DMA_PERIPH_ID_2,
    MIZAR_DMA_PERIPH_ID_3, MIZAR_DMA_PCELL_ID_0, MIZAR_DMA_PCELL_ID_1, MIZAR_DMA_PCELL_ID_2, MIZAR_DMA_PCELL_ID_3
};

// Default/reset values (symbolic; expected to be provided by included headers)
const int default_value_array[92] = {
    DMA_DSR_DEFAULT_VAL, DMA_DPC_DEFAULT_VAL, DMA_INTEN_DEFAULT_VAL, DMA_INT_EVENT_RIS_DEFAULT_VAL,
    DMA_INTMIS_DEFAULT_VAL, DMA_INTCLR_DEFAULT_VAL, DMA_FSRD_DEFAULT_VAL, DMA_FSRC_DEFAULT_VAL,
    DMA_FTRD_DEFAULT_VAL, DMA_FTR0_DEFAULT_VAL, DMA_FTR1_DEFAULT_VAL, DMA_FTR2_DEFAULT_VAL, DMA_FTR3_DEFAULT_VAL,
    DMA_FTR4_DEFAULT_VAL, DMA_FTR5_DEFAULT_VAL, DMA_FTR6_DEFAULT_VAL, DMA_FTR7_DEFAULT_VAL, DMA_CSR0_DEFAULT_VAL,
    DMA_CSR1_DEFAULT_VAL, DMA_CSR2_DEFAULT_VAL, DMA_CSR3_DEFAULT_VAL, DMA_CSR4_DEFAULT_VAL, DMA_CSR5_DEFAULT_VAL,
    DMA_CSR6_DEFAULT_VAL, DMA_CSR7_DEFAULT_VAL, DMA_CPC0_DEFAULT_VAL, DMA_CPC1_DEFAULT_VAL, DMA_CPC2_DEFAULT_VAL,
    DMA_CPC3_DEFAULT_VAL, DMA_CPC4_DEFAULT_VAL, DMA_CPC5_DEFAULT_VAL, DMA_CPC6_DEFAULT_VAL, DMA_CPC7_DEFAULT_VAL,
    DMA_SAR0_DEFAULT_VAL, DMA_SAR1_DEFAULT_VAL, DMA_SAR2_DEFAULT_VAL, DMA_SAR3_DEFAULT_VAL, DMA_SAR4_DEFAULT_VAL,
    DMA_SAR5_DEFAULT_VAL, DMA_SAR6_DEFAULT_VAL, DMA_SAR7_DEFAULT_VAL, DMA_DAR0_DEFAULT_VAL, DMA_DAR1_DEFAULT_VAL,
    DMA_DAR2_DEFAULT_VAL, DMA_DAR3_DEFAULT_VAL, DMA_DAR4_DEFAULT_VAL, DMA_DAR5_DEFAULT_VAL, DMA_DAR6_DEFAULT_VAL,
    DMA_DAR7_DEFAULT_VAL, DMA_CCR0_DEFAULT_VAL, DMA_CCR1_DEFAULT_VAL, DMA_CCR2_DEFAULT_VAL, DMA_CCR3_DEFAULT_VAL,
    DMA_CCR4_DEFAULT_VAL, DMA_CCR5_DEFAULT_VAL, DMA_CCR6_DEFAULT_VAL, DMA_CCR7_DEFAULT_VAL, DMA_LC0_0_DEFAULT_VAL,
    DMA_LC0_1_DEFAULT_VAL, DMA_LC0_2_DEFAULT_VAL, DMA_LC0_3_DEFAULT_VAL, DMA_LC0_4_DEFAULT_VAL, DMA_LC0_5_DEFAULT_VAL,
    DMA_LC0_6_DEFAULT_VAL, DMA_LC0_7_DEFAULT_VAL, DMA_LC1_0_DEFAULT_VAL, DMA_LC1_1_DEFAULT_VAL, DMA_LC1_2_DEFAULT_VAL,
    DMA_LC1_3_DEFAULT_VAL, DMA_LC1_4_DEFAULT_VAL, DMA_LC1_5_DEFAULT_VAL, DMA_LC1_6_DEFAULT_VAL, DMA_LC1_7_DEFAULT_VAL,
    DMA_DBGSTATUS_DEFAULT_VAL, DMA_DBGCMD_DEFAULT_VAL, DMA_DBGINST0_DEFAULT_VAL, DMA_DBGINST1_DEFAULT_VAL,
    DMA_CR0_DEFAULT_VAL, DMA_CR1_DEFAULT_VAL, DMA_CR2_DEFAULT_VAL, DMA_CR3_DEFAULT_VAL, DMA_CR4_DEFAULT_VAL,
    DMA_CRD_DEFAULT_VAL, DMA_WD_DEFAULT_VAL, DMA_PERIPH_ID_0_DEFAULT_VAL, DMA_PERIPH_ID_1_DEFAULT_VAL,
    DMA_PERIPH_ID_2_DEFAULT_VAL, DMA_PERIPH_ID_3_DEFAULT_VAL, DMA_PCELL_ID_0_DEFAULT_VAL, DMA_PCELL_ID_1_DEFAULT_VAL,
    DMA_PCELL_ID_2_DEFAULT_VAL, DMA_PCELL_ID_3_DEFAULT_VAL
};

// Read masks (symbolic)
const int read_mask_array[92] = {
    DMA_DSR_READ_MASK, DMA_DPC_READ_MASK, DMA_INTEN_READ_MASK, DMA_INT_EVENT_RIS_READ_MASK, DMA_INTMIS_READ_MASK,
    DMA_INTCLR_READ_MASK, DMA_FSRD_READ_MASK, DMA_FSRC_READ_MASK, DMA_FTRD_READ_MASK, DMA_FTR0_READ_MASK,
    DMA_FTR1_READ_MASK, DMA_FTR2_READ_MASK, DMA_FTR3_READ_MASK, DMA_FTR4_READ_MASK, DMA_FTR5_READ_MASK,
    DMA_FTR6_READ_MASK, DMA_FTR7_READ_MASK, DMA_CSR0_READ_MASK, DMA_CSR1_READ_MASK, DMA_CSR2_READ_MASK,
    DMA_CSR3_READ_MASK, DMA_CSR4_READ_MASK, DMA_CSR5_READ_MASK, DMA_CSR6_READ_MASK, DMA_CSR7_READ_MASK,
    DMA_CPC0_READ_MASK, DMA_CPC1_READ_MASK, DMA_CPC2_READ_MASK, DMA_CPC3_READ_MASK, DMA_CPC4_READ_MASK,
    DMA_CPC5_READ_MASK, DMA_CPC6_READ_MASK, DMA_CPC7_READ_MASK, DMA_SAR0_READ_MASK, DMA_SAR1_READ_MASK,
    DMA_SAR2_READ_MASK, DMA_SAR3_READ_MASK, DMA_SAR4_READ_MASK, DMA_SAR5_READ_MASK, DMA_SAR6_READ_MASK,
    DMA_SAR7_READ_MASK, DMA_DAR0_READ_MASK, DMA_DAR1_READ_MASK, DMA_DAR2_READ_MASK, DMA_DAR3_READ_MASK,
    DMA_DAR4_READ_MASK, DMA_DAR5_READ_MASK, DMA_DAR6_READ_MASK, DMA_DAR7_READ_MASK, DMA_CCR0_READ_MASK,
    DMA_CCR1_READ_MASK, DMA_CCR2_READ_MASK, DMA_CCR3_READ_MASK, DMA_CCR4_READ_MASK, DMA_CCR5_READ_MASK,
    DMA_CCR6_READ_MASK, DMA_CCR7_READ_MASK, DMA_LC0_0_READ_MASK, DMA_LC0_1_READ_MASK, DMA_LC0_2_READ_MASK,
    DMA_LC0_3_READ_MASK, DMA_LC0_4_READ_MASK, DMA_LC0_5_READ_MASK, DMA_LC0_6_READ_MASK, DMA_LC0_7_READ_MASK,
    DMA_LC1_0_READ_MASK, DMA_LC1_1_READ_MASK, DMA_LC1_2_READ_MASK, DMA_LC1_3_READ_MASK, DMA_LC1_4_READ_MASK,
    DMA_LC1_5_READ_MASK, DMA_LC1_6_READ_MASK, DMA_LC1_7_READ_MASK, DMA_DBGSTATUS_READ_MASK, DMA_DBGCMD_READ_MASK,
    DMA_DBGINST0_READ_MASK, DMA_DBGINST1_READ_MASK, DMA_CR0_READ_MASK, DMA_CR1_READ_MASK, DMA_CR2_READ_MASK,
    DMA_CR3_READ_MASK, DMA_CR4_READ_MASK, DMA_CRD_READ_MASK, DMA_WD_READ_MASK, DMA_PERIPH_ID_0_READ_MASK,
    DMA_PERIPH_ID_1_READ_MASK, DMA_PERIPH_ID_2_READ_MASK, DMA_PERIPH_ID_3_READ_MASK, DMA_PCELL_ID_0_READ_MASK,
    DMA_PCELL_ID_1_READ_MASK, DMA_PCELL_ID_2_READ_MASK, DMA_PCELL_ID_3_READ_MASK
};

// Write masks (symbolic)
const int write_mask_array[92] = {
    DMA_DSR_WRITE_MASK, DMA_DPC_WRITE_MASK, DMA_INTEN_WRITE_MASK, DMA_INT_EVENT_RIS_WRITE_MASK, DMA_INTMIS_WRITE_MASK,
    DMA_INTCLR_WRITE_MASK, DMA_FSRD_WRITE_MASK, DMA_FSRC_WRITE_MASK, DMA_FTRD_WRITE_MASK, DMA_FTR0_WRITE_MASK,
    DMA_FTR1_WRITE_MASK, DMA_FTR2_WRITE_MASK, DMA_FTR3_WRITE_MASK, DMA_FTR4_WRITE_MASK, DMA_FTR5_WRITE_MASK,
    DMA_FTR6_WRITE_MASK, DMA_FTR7_WRITE_MASK, DMA_CSR0_WRITE_MASK, DMA_CSR1_WRITE_MASK, DMA_CSR2_WRITE_MASK,
    DMA_CSR3_WRITE_MASK, DMA_CSR4_WRITE_MASK, DMA_CCR5_WRITE_MASK, DMA_CCR6_WRITE_MASK, DMA_CCR7_WRITE_MASK,
    DMA_CPC0_WRITE_MASK, DMA_CPC1_WRITE_MASK, DMA_CPC2_WRITE_MASK, DMA_CPC3_WRITE_MASK, DMA_CPC4_WRITE_MASK,
    DMA_CPC5_WRITE_MASK, DMA_CPC6_WRITE_MASK, DMA_CPC7_WRITE_MASK, DMA_SAR0_WRITE_MASK, DMA_SAR1_WRITE_MASK,
    DMA_SAR2_WRITE_MASK, DMA_SAR3_WRITE_MASK, DMA_SAR4_WRITE_MASK, DMA_SAR5_WRITE_MASK, DMA_SAR6_WRITE_MASK,
    DMA_SAR7_WRITE_MASK, DMA_DAR0_WRITE_MASK, DMA_DAR1_WRITE_MASK, DMA_DAR2_WRITE_MASK, DMA_DAR3_WRITE_MASK,
    DMA_DAR4_WRITE_MASK, DMA_DAR5_WRITE_MASK, DMA_DAR6_WRITE_MASK, DMA_DAR7_WRITE_MASK, DMA_CCR0_WRITE_MASK,
    DMA_CCR1_WRITE_MASK, DMA_CCR2_WRITE_MASK, DMA_CCR3_WRITE_MASK, DMA_CCR4_WRITE_MASK, DMA_CCR5_WRITE_MASK,
    DMA_CCR6_WRITE_MASK, DMA_CCR7_WRITE_MASK, DMA_LC0_0_WRITE_MASK, DMA_LC0_1_WRITE_MASK, DMA_LC0_2_WRITE_MASK,
    DMA_LC0_3_WRITE_MASK, DMA_LC0_4_WRITE_MASK, DMA_LC0_5_WRITE_MASK, DMA_LC0_6_WRITE_MASK, DMA_LC0_7_WRITE_MASK,
    DMA_LC1_0_WRITE_MASK, DMA_LC1_1_WRITE_MASK, DMA_LC1_2_WRITE_MASK, DMA_LC1_3_WRITE_MASK, DMA_LC1_4_WRITE_MASK,
    DMA_LC1_5_WRITE_MASK, DMA_LC1_6_WRITE_MASK, DMA_LC1_7_WRITE_MASK, DMA_DBGSTATUS_WRITE_MASK, DMA_DBGCMD_WRITE_MASK,
    DMA_DBGINST0_WRITE_MASK, DMA_DBGINST1_WRITE_MASK, DMA_CR0_WRITE_MASK, DMA_CR1_WRITE_MASK, DMA_CR2_WRITE_MASK,
    DMA_CR3_WRITE_MASK, DMA_CR4_WRITE_MASK, DMA_CRD_WRITE_MASK, DMA_WD_WRITE_MASK, DMA_PERIPH_ID_0_WRITE_MASK,
    DMA_PERIPH_ID_1_WRITE_MASK, DMA_PERIPH_ID_2_WRITE_MASK, DMA_PERIPH_ID_3_WRITE_MASK, DMA_PCELL_ID_0_WRITE_MASK,
    DMA_PCELL_ID_1_WRITE_MASK, DMA_PCELL_ID_2_WRITE_MASK, DMA_PCELL_ID_3_WRITE_MASK
};

// Per-address skip control (1 = skip). If skip_registers list is provided, set corresponding entries to 1.
const int skip_array[92] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
};
