#!/usr/bin/env python3
"""
GPIO TestPlan Excel Generator & GitHub Auto-Pusher
====================================================
Generated by Ag_Excel_Generator Agent on 2025-06-17 18:32:00 IST

Generates a real binary .xlsx workbook with two sheets:
  - TestPlan (visible) - 28 columns, 10 data rows
  - MetaData (veryHidden) - 11 columns, 2 data rows

Requirements:
  pip install openpyxl PyGithub

Usage:
  python generate_GPIO_TestPlan_20250617.py
  # Or with GitHub push:
  GITHUB_TOKEN=ghp_xxx python generate_GPIO_TestPlan_20250617.py
"""

import os
import sys
import json
import base64
from datetime import datetime, timezone, timedelta
from io import BytesIO

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip install openpyxl")
    sys.exit(1)

# ============================================================
# IST Timestamp
# ============================================================
IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
TIMESTAMP = now_ist.strftime("%Y%m%d_%H%M%S")
IP_NAME = "GPIO"
FILENAME = f"{IP_NAME}_TestPlan_{TIMESTAMP}.xlsx"
OUTPUT_DIR = "Test_Output/GPIO/TestPlan"
OUTPUT_PATH = f"{OUTPUT_DIR}/{FILENAME}"

# ============================================================
# GitHub Config
# ============================================================
GITHUB_OWNER = "titusbspgit"
GITHUB_REPO = "PSVValidation"
GITHUB_BRANCH = "main"

# ============================================================
# TestPlan Sheet - 28 Columns
# ============================================================
TESTPLAN_COLUMNS = [
    "SI No",
    "Test Case Name",
    "Test Case Description",
    "IP Name",
    "Test Folder Path",
    "Source File",
    "Register Name",
    "Register Offset",
    "Register Width",
    "Register Field Name",
    "Register Field Index",
    "Register Field Type",
    "Reset Value",
    "Register Description",
    "Register Token (Address Macro)",
    "Register Token (Default Value)",
    "Register Token (Read Mask)",
    "Register Token (Write Mask)",
    "Test Type",
    "Test Methodology",
    "Preconditions",
    "Test Steps",
    "Expected Result",
    "Pass/Fail Criteria",
    "Priority",
    "Coverage Area",
    "Applicable GPIO Pins",
    "Notes"
]

# ============================================================
# MetaData Sheet - 11 Columns
# ============================================================
METADATA_COLUMNS = [
    "Index",
    "SS / Module",
    "Feature",
    "Test Case Name",
    "Meta Test Description",
    "Meta Test Steps / Procedure",
    "Meta Impacted Registers",
    "Meta Validation / Acceptance Criteria",
    "Meta Headers",
    "Meta Macros",
    "Meta Arrays"
]

# ============================================================
# TestPlan Data - 10 Rows (9 from gpio_reg_wr_rd_test + 1 from test_gpio_level_sel_intr_en)
# ============================================================
TESTPLAN_ROWS = [
    {
        "SI No": 1,
        "Test Case Name": "gpio_reg_wr_rd_test_default_val_gp0_gpio_8",
        "Test Case Description": "Read register gp0_gpio_8 after reset and verify default value. Mask with 0xFFFFFFFE (bit 0 data_in is externally driven RO). Expected default: 0x00100000 (io_ctrl=1 at bit 20).",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8",
        "Register Offset": "0x0",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO pin 8 register - level detect, interrupt control, IO mode, data out",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Default Value Check",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible at base 0xA001A000",
        "Test Steps": "1. Read register at MIZAR_GPIO_GP0_GPIO_8. 2. Mask read data with 0xFFFFFFFE. 3. Compare with expected default value 0x00100000.",
        "Expected Result": "Read value masked with 0xFFFFFFFE equals 0x00100000",
        "Pass/Fail Criteria": "PASS if (read_data & 0xFFFFFFFE) == 0x00100000; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Default Value",
        "Applicable GPIO Pins": "GPIO 8",
        "Notes": "Bit 0 (data_in) is RO externally driven, excluded from default check via mask"
    },
    {
        "SI No": 2,
        "Test Case Name": "gpio_reg_wr_rd_test_default_val_gp0_gpio_9",
        "Test Case Description": "Read register gp0_gpio_9 after reset and verify default value. Mask with 0xFFFFFFFE. Expected default: 0x00100000.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_9",
        "Register Offset": "0x4",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO pin 9 register",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_9",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_9_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_9_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_9_WRITE_MASK",
        "Test Type": "Default Value Check",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible at base 0xA001A000",
        "Test Steps": "1. Read register at MIZAR_GPIO_GP0_GPIO_9. 2. Mask read data with 0xFFFFFFFE. 3. Compare with expected default value 0x00100000.",
        "Expected Result": "Read value masked with 0xFFFFFFFE equals 0x00100000",
        "Pass/Fail Criteria": "PASS if (read_data & 0xFFFFFFFE) == 0x00100000; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Default Value",
        "Applicable GPIO Pins": "GPIO 9",
        "Notes": "Bit 0 (data_in) is RO externally driven, excluded from default check via mask"
    },
    {
        "SI No": 3,
        "Test Case Name": "gpio_reg_wr_rd_test_default_val_gp0_gpio_10",
        "Test Case Description": "Read register gp0_gpio_10 after reset and verify default value. Mask with 0xFFFFFFFE. Expected default: 0x00100000.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_10",
        "Register Offset": "0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO pin 10 register",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_10_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_10_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_10_WRITE_MASK",
        "Test Type": "Default Value Check",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible at base 0xA001A000",
        "Test Steps": "1. Read register at MIZAR_GPIO_GP0_GPIO_10. 2. Mask read data with 0xFFFFFFFE. 3. Compare with expected default value 0x00100000.",
        "Expected Result": "Read value masked with 0xFFFFFFFE equals 0x00100000",
        "Pass/Fail Criteria": "PASS if (read_data & 0xFFFFFFFE) == 0x00100000; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Default Value",
        "Applicable GPIO Pins": "GPIO 10",
        "Notes": "Bit 0 (data_in) is RO externally driven, excluded from default check via mask"
    },
    {
        "SI No": 4,
        "Test Case Name": "gpio_reg_wr_rd_test_wr_rd_pattern1_0xFFFFFFFF",
        "Test Case Description": "Write pattern 0xFFFFFFFF to gp0_gpio_8, gp0_gpio_9, gp0_gpio_10 and read back. Expected value computed using formula: (pattern & read_mask & write_mask) | (~write_mask & read_mask & default_value).",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
        "Register Offset": "0x0; 0x4; 0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO per-pin registers write-read test",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Write-Read Test",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible; skip_array checked for VRRW registers",
        "Test Steps": "1. For each register (gp0_gpio_8, _9, _10): if skip_array[index]==0, write 0xFFFFFFFF. 2. Read back. 3. Compute expected value. 4. Compare.",
        "Expected Result": "Read-back matches computed expected value for each non-skipped register",
        "Pass/Fail Criteria": "PASS if read_data == expected_value for all registers; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Write-Read Integrity",
        "Applicable GPIO Pins": "GPIO 8; GPIO 9; GPIO 10",
        "Notes": "Pattern 1 of 6; VRRW registers with skip_array=1 are skipped"
    },
    {
        "SI No": 5,
        "Test Case Name": "gpio_reg_wr_rd_test_wr_rd_pattern2_0xAAAAAAAA",
        "Test Case Description": "Write pattern 0xAAAAAAAA to gp0_gpio_8, gp0_gpio_9, gp0_gpio_10 and read back.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
        "Register Offset": "0x0; 0x4; 0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO per-pin registers write-read test",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Write-Read Test",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible; skip_array checked",
        "Test Steps": "1. For each register: if skip_array[index]==0, write 0xAAAAAAAA. 2. Read back. 3. Compare.",
        "Expected Result": "Read-back matches computed expected value",
        "Pass/Fail Criteria": "PASS if read_data == expected_value; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Write-Read Integrity",
        "Applicable GPIO Pins": "GPIO 8; GPIO 9; GPIO 10",
        "Notes": "Pattern 2 of 6"
    },
    {
        "SI No": 6,
        "Test Case Name": "gpio_reg_wr_rd_test_wr_rd_pattern3_0x55555555",
        "Test Case Description": "Write pattern 0x55555555 to gp0_gpio_8, gp0_gpio_9, gp0_gpio_10 and read back.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
        "Register Offset": "0x0; 0x4; 0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO per-pin registers write-read test",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Write-Read Test",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible; skip_array checked",
        "Test Steps": "1. For each register: if skip_array[index]==0, write 0x55555555. 2. Read back. 3. Compare.",
        "Expected Result": "Read-back matches computed expected value",
        "Pass/Fail Criteria": "PASS if read_data == expected_value; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Write-Read Integrity",
        "Applicable GPIO Pins": "GPIO 8; GPIO 9; GPIO 10",
        "Notes": "Pattern 3 of 6"
    },
    {
        "SI No": 7,
        "Test Case Name": "gpio_reg_wr_rd_test_wr_rd_pattern4_0xF5F5F5F5",
        "Test Case Description": "Write pattern 0xF5F5F5F5 to gp0_gpio_8, gp0_gpio_9, gp0_gpio_10 and read back.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
        "Register Offset": "0x0; 0x4; 0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO per-pin registers write-read test",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Write-Read Test",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible; skip_array checked",
        "Test Steps": "1. For each register: if skip_array[index]==0, write 0xF5F5F5F5. 2. Read back. 3. Compare.",
        "Expected Result": "Read-back matches computed expected value",
        "Pass/Fail Criteria": "PASS if read_data == expected_value; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Write-Read Integrity",
        "Applicable GPIO Pins": "GPIO 8; GPIO 9; GPIO 10",
        "Notes": "Pattern 4 of 6"
    },
    {
        "SI No": 8,
        "Test Case Name": "gpio_reg_wr_rd_test_wr_rd_pattern5_0xA5A5A5A5",
        "Test Case Description": "Write pattern 0xA5A5A5A5 to gp0_gpio_8, gp0_gpio_9, gp0_gpio_10 and read back.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
        "Register Offset": "0x0; 0x4; 0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO per-pin registers write-read test",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Write-Read Test",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible; skip_array checked",
        "Test Steps": "1. For each register: if skip_array[index]==0, write 0xA5A5A5A5. 2. Read back. 3. Compare.",
        "Expected Result": "Read-back matches computed expected value",
        "Pass/Fail Criteria": "PASS if read_data == expected_value; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Write-Read Integrity",
        "Applicable GPIO Pins": "GPIO 8; GPIO 9; GPIO 10",
        "Notes": "Pattern 5 of 6"
    },
    {
        "SI No": 9,
        "Test Case Name": "gpio_reg_wr_rd_test_wr_rd_pattern6_0xFFFF0000",
        "Test Case Description": "Write pattern 0xFFFF0000 to gp0_gpio_8, gp0_gpio_9, gp0_gpio_10 and read back.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/gpio_reg_wr_rd_test",
        "Source File": "program.c",
        "Register Name": "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
        "Register Offset": "0x0; 0x4; 0x8",
        "Register Width": 32,
        "Register Field Name": "data_in; intr_raw_sts; intr_clr; pedge_intr_en; nedge_intr_en; level_sel; io_ctrl; dout",
        "Register Field Index": "0; 1; 16; 17; 18; 19; 20; 21",
        "Register Field Type": "RO; RO; WO; RW; RW; RW; RW2; RW2",
        "Reset Value": "0x00100000",
        "Register Description": "GPIO per-pin registers write-read test",
        "Register Token (Address Macro)": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Register Token (Default Value)": "MIZAR_GPIO_GP0_GPIO_8_DEFAULT_VAL",
        "Register Token (Read Mask)": "MIZAR_GPIO_GP0_GPIO_8_READ_MASK",
        "Register Token (Write Mask)": "MIZAR_GPIO_GP0_GPIO_8_WRITE_MASK",
        "Test Type": "Write-Read Test",
        "Test Methodology": "Polling",
        "Preconditions": "System reset completed; GPIO0 block accessible; skip_array checked",
        "Test Steps": "1. For each register: if skip_array[index]==0, write 0xFFFF0000. 2. Read back. 3. Compare.",
        "Expected Result": "Read-back matches computed expected value",
        "Pass/Fail Criteria": "PASS if read_data == expected_value; FAIL otherwise",
        "Priority": "High",
        "Coverage Area": "Register Write-Read Integrity",
        "Applicable GPIO Pins": "GPIO 8; GPIO 9; GPIO 10",
        "Notes": "Pattern 6 of 6"
    },
    {
        "SI No": 10,
        "Test Case Name": "test_gpio_level_sel_intr_en",
        "Test Case Description": "This test validates the GPIO level-select interrupt functionality for all 32 GPIO pins (GPIO 8 through GPIO 39). It verifies that interrupts are correctly generated based on the programmed signal level (active-high and active-low) on each GPIO pin. The test runs in ISR mode using GIC IRQ 87.",
        "IP Name": "GPIO",
        "Test Folder Path": "TestRepo/gpio/test_gpio_level_sel_intr_en",
        "Source File": "program.c",
        "Register Name": "intr_en1; gp0_gpio_8; gp0_intr1_intr_en1; gp0_intr1_intr_sts1; raw_stcr1",
        "Register Offset": "0x28; 0x0; 0x84; 0x88; 0x24",
        "Register Width": 32,
        "Register Field Name": "gpio0_intr; data_in/intr_raw_sts/intr_clr/level_sel/io_ctrl/dout; G8-G39_intr_en; G8-G39_intr_sts; gpio0_intr",
        "Register Field Index": "1; 0/1/16/19/20/21; 0-31; 0-31; 1",
        "Register Field Type": "INTREN1; RO/RO/WO/RW/RW2/RW2; RW; RO; RAWSTCR1",
        "Reset Value": "0x0; 0x00100000; 0x0; 0x0; 0x0",
        "Register Description": "Sysreg interrupt enable; GPIO per-pin register; Group interrupt enable; Group interrupt status; Sysreg raw status clear",
        "Register Token (Address Macro)": "MIZAR_LSS_SYSREG_INTR_EN1; MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_INTR1_INTR_EN1; MIZAR_GPIO_GP0_INTR1_INTR_STS1; MIZAR_LSS_SYSREG_RAW_STCR1",
        "Register Token (Default Value)": "NA",
        "Register Token (Read Mask)": "NA",
        "Register Token (Write Mask)": "NA",
        "Test Type": "Interrupt Functional Test",
        "Test Methodology": "ISR",
        "Preconditions": "System reset completed; GIC IRQ 87 routable; GPIO0 block accessible at base 0xA001A000; External SRAM at 0xA0243ffc accessible",
        "Test Steps": "1. Enable GIC IRQ 87 for GPIO0 interrupt routing.\n2. Enable the GPIO0 interrupt bit in the sysreg interrupt enable register (intr_en1).\n3. For each of the 32 GPIO pins (active-high configuration):\n   a. Configure the per-pin GPIO register with input mode enabled and level-select set to active-high (write 0x00180000).\n   b. Enable the corresponding bit in the group interrupt enable register.\n   c. Write the stimulus value to the external SRAM trigger address (0xA0243ffc).\n   d. Wait for the ISR to fire and handle the interrupt.\n4. In the ISR: verify interrupt raw status, group status, clear interrupt, verify clear, disable group, clear sysreg, clear GIC.\n5. Repeat for active-low configuration (write 0x00100000).\n6. Verify zero errors across all 64 interrupt cycles.",
        "Expected Result": "All 64 interrupt cycles (32 active-high + 32 active-low) complete with zero errors",
        "Pass/Fail Criteria": "PASS: All checks pass - raw status set, group status set, interrupt clear succeeds (read-back 0x100001), group status clears to zero, sysreg status clears. FAIL: Any check fails.",
        "Priority": "High",
        "Coverage Area": "Interrupt Functional Verification",
        "Applicable GPIO Pins": "GPIO 8 through GPIO 39 (all 32 pins)",
        "Notes": "Requires GIC IRQ 87. External SRAM stimulus at 0xA0243ffc. Compiled with #define GPIO0 1."
    }
]

# ============================================================
# MetaData Rows - 2 Records
# ============================================================
METADATA_ROWS = [
    {
        "Index": "1",
        "SS / Module": "GPIO",
        "Feature": "Register Write-Read Verification",
        "Test Case Name": "gpio_reg_wr_rd_test",
        "Meta Test Description": "The testcase includes test_define.c which defines CNT=49 registers in addr_array[] using macros such as MIZAR_GPIO_GP0_GPIO_8, MIZAR_GPIO_GP0_GPIO_9, MIZAR_GPIO_GP0_GPIO_10 along with corresponding default_value_array[], read_mask_array[], write_mask_array[], skip_array[], and skip_rst_array[]. The main test_case() function calls chk_rst_val() to iterate over all CNT registers, reading each via read_reg(addr), masking with 0xfffffffe, and comparing against default_value_array[i]. Then chk_rd_wr() iterates over 6 check values {0xffffffff, 0xaaaaaaaa, 0x55555555, 0xf5f5f5f5, 0xA5A5A5A5, 0xffff0000}, writing (data_wr & write_mask_array[i]) to each register, then reading back with (read_reg(addr) & read_mask_array[i]) and comparing against expected value.",
        "Meta Test Steps / Procedure": "1. Include test_define.c which defines addr_array[49] with register macros. CNT=49.\n2. Call chk_rst_val(): for i=0 to CNT-1, get addr=addr_array[i]. If skip_rst_array[i]==1, skip. If read_mask_array[i]==0x00000000, skip. Else data_rd=read_reg(addr), data=(data_rd & 0xfffffffe). Compare data==default_value_array[i].\n3. Call chk_rd_wr(): define chk_val[6]={0xffffffff, 0xaaaaaaaa, 0x55555555, 0xf5f5f5f5, 0xA5A5A5A5, 0xffff0000}. For j=0 to 5: data_wr=chk_val[j]. For i=0 to CNT-1: if skip_array[i]==1, skip. Write and read back.\n4. Compare data_rd==exp_val. If mismatch, increment wr_fail_cnt.\n5. If def_fail_cnt>0 || wr_fail_cnt>0, call finish(1). Else call finish(0).",
        "Meta Impacted Registers": "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
        "Meta Validation / Acceptance Criteria": "PASS: For all i in 0..CNT-1 (non-skipped), (read_reg(addr_array[i]) & 0xfffffffe) == default_value_array[i]. For all 6 patterns, read_data == expected. finish(0) called. FAIL: def_fail_cnt > 0 || wr_fail_cnt > 0.",
        "Meta Headers": "#include <stdio.h>; #include <stdlib.h>; #include \"test_common.h\"; #include \"test_define.c\"; #include<gpio/gpio_def.h>; #include<gpio/gpio_offset.h>",
        "Meta Macros": "#define SOFT_RST_REG_ADDRESS 0x00000000; #define SOFT_RST_REG_DATA 0x00000000; #define CNT 49",
        "Meta Arrays": "addr_array[49], default_value_array[49], read_mask_array[49], write_mask_array[49], skip_array[49], skip_rst_array[49], chk_val[6]"
    },
    {
        "Index": "2",
        "SS / Module": "GPIO",
        "Feature": "Level Select Interrupt Enable",
        "Test Case Name": "test_gpio_level_sel_intr_en",
        "Meta Test Description": "This testcase validates GPIO level-select interrupt enable functionality across all 32 GPIO pins (GPIO_8 to GPIO_39). It uses ISR-driven execution via GIC_EnableIRQ(87) for GPIO0. The test_case() function runs two loops of 32 iterations each: (1) Active-high: writes 0x00180000 to MIZAR_GPIO_GP0_GPIO_8+(i*4) setting io_ctrl=1 (bit 20) and level_sel=1 (bit 19), enables group interrupt via write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 1<<i), triggers stimulus via write_reg(0xA0243ffc, 0xffffffff), then polls int_pend flag. (2) Active-low: writes 0x00100000 setting io_ctrl=1 and level_sel=0, enables group interrupt, triggers stimulus via write_reg(0xA0243ffc, ~(wr_val)), polls int_pend.",
        "Meta Test Steps / Procedure": "1. GIC_EnableIRQ(87). 2. write_reg(MIZAR_LSS_SYSREG_INTR_EN1, LSS_SYSREG_INTR_EN1_GPIO0_INTR). 3. Active-high loop (i=0 to 31): write_reg(MIZAR_GPIO_GP0_GPIO_8+(i*4), 0x00180000), write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 1<<i), write_reg(0xA0243ffc, 0xffffffff), poll int_pend. 4. Active-low loop: write_reg(MIZAR_GPIO_GP0_GPIO_8+(i*4), 0x00100000), write_reg(0xA0243ffc, ~(wr_val)). 5. ISR: read_reg checks, write_reg clears, GIC_ClearIRQ(87). 6. finish(test_err).",
        "Meta Impacted Registers": "MIZAR_LSS_SYSREG_INTR_EN1; MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_INTR1_INTR_EN1; 0xA0243ffc; MIZAR_GPIO_GP0_INTR1_INTR_STS1; MIZAR_LSS_SYSREG_RAW_STCR1",
        "Meta Validation / Acceptance Criteria": "PASS: (rdata & 0x2) != 0x0; (rdata_grp & (1<<i)) != 0; rdata == 0x100001; rdata_grp == 0x0; (rdata & LSS_SYSREG_RAW_STCR1_GPIO0_INTR) == 0. FAIL: test_err > 0.",
        "Meta Headers": "#include<lss_sysreg.h>; #include<stdio.h>; #include<test_define.c>; #include<test_common.h>; #include<gpio/gpio_def.h>; #include<gpio/gpio_offset.h>",
        "Meta Macros": "#define GPIO0 1; #define CNT 49",
        "Meta Arrays": "addr_array[49], default_value_array[49], read_mask_array[49], write_mask_array[49], skip_array[49]"
    }
]


def create_workbook():
    wb = Workbook()

    # ---- Styles ----
    header_font = Font(name="Calibri", bold=True, size=11, color="FFFFFF")
    data_font = Font(name="Calibri", size=10)
    header_fill_tp = PatternFill(start_color="003366", end_color="003366", fill_type="solid")
    header_fill_md = PatternFill(start_color="548235", end_color="548235", fill_type="solid")
    cell_alignment = Alignment(wrap_text=True, vertical="top")
    header_alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")
    thin_border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin")
    )

    TP_COL_WIDTHS = {
        "SI No": 8, "Test Case Name": 45, "Test Case Description": 60,
        "IP Name": 10, "Test Folder Path": 35, "Source File": 15,
        "Register Name": 35, "Register Offset": 18, "Register Width": 15,
        "Register Field Name": 50, "Register Field Index": 30,
        "Register Field Type": 30, "Reset Value": 20,
        "Register Description": 50, "Register Token (Address Macro)": 45,
        "Register Token (Default Value)": 40, "Register Token (Read Mask)": 40,
        "Register Token (Write Mask)": 40, "Test Type": 25,
        "Test Methodology": 15, "Preconditions": 50, "Test Steps": 60,
        "Expected Result": 50, "Pass/Fail Criteria": 55, "Priority": 10,
        "Coverage Area": 30, "Applicable GPIO Pins": 30, "Notes": 50
    }

    MD_COL_WIDTHS = {
        "Index": 8, "SS / Module": 15, "Feature": 30,
        "Test Case Name": 30, "Meta Test Description": 70,
        "Meta Test Steps / Procedure": 70, "Meta Impacted Registers": 45,
        "Meta Validation / Acceptance Criteria": 70, "Meta Headers": 50,
        "Meta Macros": 50, "Meta Arrays": 70
    }

    # ========== Sheet 1: TestPlan ==========
    ws_tp = wb.active
    ws_tp.title = "TestPlan"

    for col_idx, col_name in enumerate(TESTPLAN_COLUMNS, 1):
        cell = ws_tp.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill_tp
        cell.alignment = header_alignment
        cell.border = thin_border

    for row_idx, record in enumerate(TESTPLAN_ROWS, 2):
        for col_idx, col_name in enumerate(TESTPLAN_COLUMNS, 1):
            value = record.get(col_name, "")
            cell = ws_tp.cell(row=row_idx, column=col_idx, value=value)
            cell.font = data_font
            cell.alignment = cell_alignment
            cell.border = thin_border

    for col_idx, col_name in enumerate(TESTPLAN_COLUMNS, 1):
        col_letter = get_column_letter(col_idx)
        ws_tp.column_dimensions[col_letter].width = TP_COL_WIDTHS.get(col_name, 20)

    ws_tp.freeze_panes = "A2"

    # ========== Sheet 2: MetaData (veryHidden) ==========
    ws_md = wb.create_sheet(title="MetaData")

    for col_idx, col_name in enumerate(METADATA_COLUMNS, 1):
        cell = ws_md.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill_md
        cell.alignment = header_alignment
        cell.border = thin_border

    for row_idx, record in enumerate(METADATA_ROWS, 2):
        for col_idx, col_name in enumerate(METADATA_COLUMNS, 1):
            value = record.get(col_name, "")
            cell = ws_md.cell(row=row_idx, column=col_idx, value=value)
            cell.font = data_font
            cell.alignment = cell_alignment
            cell.border = thin_border

    for col_idx, col_name in enumerate(METADATA_COLUMNS, 1):
        col_letter = get_column_letter(col_idx)
        ws_md.column_dimensions[col_letter].width = MD_COL_WIDTHS.get(col_name, 20)

    ws_md.freeze_panes = "A2"
    ws_md.sheet_state = "veryHidden"

    return wb


def save_and_get_bytes(wb):
    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer.read()


def push_to_github(file_bytes, filepath):
    try:
        from github import Github
    except ImportError:
        print("WARNING: PyGithub not installed. Run: pip install PyGithub")
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "wb") as f:
            f.write(file_bytes)
        print(f"File saved locally: {filepath}")
        return False

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("WARNING: GITHUB_TOKEN not set. Saving locally.")
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "wb") as f:
            f.write(file_bytes)
        print(f"File saved locally: {filepath}")
        return False

    g = Github(token)
    repo = g.get_repo(f"{GITHUB_OWNER}/{GITHUB_REPO}")

    try:
        existing = repo.get_contents(filepath, ref=GITHUB_BRANCH)
        result = repo.update_file(
            path=filepath,
            message=f"Update {FILENAME} - GPIO TestPlan Excel (28-col, 10 rows)",
            content=file_bytes,
            sha=existing.sha,
            branch=GITHUB_BRANCH
        )
    except Exception:
        result = repo.create_file(
            path=filepath,
            message=f"Add {FILENAME} - GPIO TestPlan Excel (28-col, 10 rows)",
            content=file_bytes,
            branch=GITHUB_BRANCH
        )

    commit_sha = result['commit'].sha
    print(f"Pushed to GitHub. Commit: {commit_sha}")
    return True


def main():
    print("=" * 70)
    print("  GPIO TestPlan Excel Generator (28-Column Format)")
    print("=" * 70)
    print(f"  Timestamp (IST) : {now_ist.strftime('%Y-%m-%d %H:%M:%S IST')}")
    print(f"  Output filename  : {FILENAME}")
    print(f"  Output path      : {OUTPUT_PATH}")
    print(f"  TestPlan sheet   : 28 columns, 10 data rows")
    print(f"  MetaData sheet   : 11 columns, 2 data rows (veryHidden)")
    print()

    print("[1/3] Creating workbook...")
    wb = create_workbook()

    print("[2/3] Serializing to .xlsx...")
    file_bytes = save_and_get_bytes(wb)
    print(f"      File size: {len(file_bytes):,} bytes")

    print("[3/3] Pushing to GitHub...")
    success = push_to_github(file_bytes, OUTPUT_PATH)

    print()
    if success:
        url = f"https://github.com/{GITHUB_OWNER}/{GITHUB_REPO}/blob/{GITHUB_BRANCH}/{OUTPUT_PATH}"
        print(f"  STATUS: SUCCESS")
        print(f"  URL: {url}")
    else:
        print(f"  STATUS: LOCAL SAVE")
        print(f"  Path: {OUTPUT_PATH}")
    print("=" * 70)


if __name__ == "__main__":
    main()
