#!/usr/bin/env python3
"""
GPIO TestPlan Excel Generator
Auto-generated by Ag_Excel_Generator Agent
Generates: GPIO_TestPlan_<YYYYMMDD>_<HHMMSS>.xlsx
Target: Test_Output/GPIO/TestPlan/
"""

import os
import sys
import base64
import json
from datetime import datetime, timezone, timedelta

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("Installing openpyxl...")
    os.system(f"{sys.executable} -m pip install openpyxl")
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

# ============================================================
# IST Timestamp
# ============================================================
IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp_str = now_ist.strftime("%Y%m%d_%H%M%S")
filename = f"GPIO_TestPlan_{timestamp_str}.xlsx"

print(f"Generating: {filename}")
print(f"IST Time: {now_ist.strftime('%Y-%m-%d %H:%M:%S IST')}")

# ============================================================
# TestPlan Sheet Columns (14 columns)
# ============================================================
TP_HEADERS = [
    "Index",
    "SS / Module",
    "Feature",
    "Test Case Name",
    "Test Description",
    "Speed",
    "Mode",
    "Memory Start Offset",
    "Memory End Offset",
    "Remarks",
    "Test Steps",
    "Impacted Registers",
    "Validation",
    "Code Generation"
]

# ============================================================
# MetaData Sheet Columns (14 columns - mirrors + extras)
# ============================================================
MD_HEADERS = [
    "Index",
    "Test Case Name",
    "Meta Test Description",
    "Meta Test Steps",
    "Meta Expected Results",
    "Meta Impacted Registers (Macros)",
    "Meta Validation",
    "Meta Pre-Conditions",
    "Meta Test Type",
    "Meta Priority",
    "Meta GIC IRQ Number",
    "Meta Register Details",
    "Meta Source Folder",
    "Meta GitHub URL"
]

# ============================================================
# DATA — Testcase 1: gpio_reg_wr_rd_test
# ============================================================
tc1_reg_details = """Register 1: MIZAR_GPIO_GP0_GPIO_8
  Name: gp0_gpio_8 | Base: 0xA001A000 | Offset: 0x0 | Addr: 0xA001A000
  Ops: read, write
  Fields: data_in[0](RO,rst=0), intr_raw_sts[1](RO,rst=0), intr_clr[16](WO,rst=0), pedge_intr_en[17](RW,rst=0), nedge_intr_en[18](RW,rst=0), level_sel[19](RW,rst=0), io_ctrl[20](RW2,rst=1), dout[21](RW2,rst=0)

Register 2: MIZAR_GPIO_GP0_GPIO_9
  Name: gp0_gpio_9 | Base: 0xA001A000 | Offset: 0x4 | Addr: 0xA001A004
  Ops: read, write
  Fields: data_in[0](RO,rst=0), intr_raw_sts[1](RO,rst=0), intr_clr[16](WO,rst=0), pedge_intr_en[17](RW,rst=0), nedge_intr_en[18](RW,rst=0), level_sel[19](RW,rst=0), io_ctrl[20](RW2,rst=1), dout[21](RW2,rst=0)

Register 3: MIZAR_GPIO_GP0_GPIO_10
  Name: gp0_gpio_10 | Base: 0xA001A000 | Offset: 0x8 | Addr: 0xA001A008
  Ops: read, write
  Fields: data_in[0](RO,rst=0), intr_raw_sts[1](RO,rst=0), intr_clr[16](WO,rst=0), pedge_intr_en[17](RW,rst=0), nedge_intr_en[18](RW,rst=0), level_sel[19](RW,rst=0), io_ctrl[20](RW2,rst=1), dout[21](RW2,rst=0)"""

tc1_tp_row = [
    1,
    "GPIO",
    "Register Read/Write Verification",
    "gpio_reg_wr_rd_test",
    "Verify register read/write operations on GPIO registers gp0_gpio_8, gp0_gpio_9, gp0_gpio_10. Test performs reset value check by reading registers after reset and verifying default values, then performs write-read verification by writing data patterns to writable fields (pedge_intr_en, nedge_intr_en, level_sel, io_ctrl, dout) and reading back to verify.",
    "NA",  # Speed
    "NA",  # Mode
    "0xA001A000",  # Memory Start Offset
    "0xA001A008",  # Memory End Offset
    "Register test covers 3 GPIO pin registers (gp0_gpio_8/9/10). Each register has 8 fields with mixed access types (RO, WO, RW, RW2). Reset value for io_ctrl is 1 (input mode default).",
    "1. Initialize GPIO0 base address 0xA001A000.\n2. Read gp0_gpio_8 (offset 0x0) and verify reset value.\n3. Read gp0_gpio_9 (offset 0x4) and verify reset value.\n4. Read gp0_gpio_10 (offset 0x8) and verify reset value.\n5. Write test pattern to gp0_gpio_8 writable fields.\n6. Read back gp0_gpio_8 and compare with written value using write mask.\n7. Write test pattern to gp0_gpio_9 writable fields.\n8. Read back gp0_gpio_9 and compare with written value using write mask.\n9. Write test pattern to gp0_gpio_10 writable fields.\n10. Read back gp0_gpio_10 and compare with written value using write mask.",
    "gp0_gpio_8; gp0_gpio_9; gp0_gpio_10",
    "PASS: All register reset values match expected defaults AND all write-read comparisons match for writable fields. FAIL: Any reset value mismatch OR any write-read comparison mismatch.",
    "NA"  # Code Generation
]

tc1_md_row = [
    1,
    "gpio_reg_wr_rd_test",
    "Verify register read/write operations on GPIO registers gp0_gpio_8, gp0_gpio_9, gp0_gpio_10. Test performs reset value check by reading registers after reset and verifying default values, then performs write-read verification by writing data patterns to writable fields (pedge_intr_en, nedge_intr_en, level_sel, io_ctrl, dout) and reading back to verify.",
    "1. Initialize GPIO0 base address 0xA001A000.\n2. Read gp0_gpio_8 (offset 0x0) and verify reset value.\n3. Read gp0_gpio_9 (offset 0x4) and verify reset value.\n4. Read gp0_gpio_10 (offset 0x8) and verify reset value.\n5. Write test pattern to gp0_gpio_8 writable fields.\n6. Read back gp0_gpio_8 and compare with written value using write mask.\n7. Write test pattern to gp0_gpio_9 writable fields.\n8. Read back gp0_gpio_9 and compare with written value using write mask.\n9. Write test pattern to gp0_gpio_10 writable fields.\n10. Read back gp0_gpio_10 and compare with written value using write mask.",
    "1. Reset value read from gp0_gpio_8 matches expected default (io_ctrl=1 at bit20, all others 0). 2. Reset value read from gp0_gpio_9 matches expected default. 3. Reset value read from gp0_gpio_10 matches expected default. 4. Write-read verification: written data matches read-back data for all writable fields after applying read/write masks. 5. RO fields (data_in, intr_raw_sts) are not affected by writes. 6. WO fields (intr_clr) are not readable.",
    "MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_GPIO_9; MIZAR_GPIO_GP0_GPIO_10",
    "PASS: All register reset values match expected defaults AND all write-read comparisons match for writable fields. FAIL: Any reset value mismatch OR any write-read comparison mismatch.",
    "1. GPIO IP is powered on and clocked. 2. System reset has been de-asserted. 3. GPIO0 instance is selected (#define GPIO0 1). 4. Base address 0xA001A000 is accessible.",
    "Register Read/Write Verification",
    "P1 - High",
    "NA",
    tc1_reg_details,
    "TestRepo/gpio/gpio_reg_wr_rd_test",
    "https://github.com/titusbspgit/PSVValidation/tree/main/TestRepo/gpio/gpio_reg_wr_rd_test"
]

# ============================================================
# DATA — Testcase 2: test_gpio_level_sel_intr_en
# ============================================================
tc2_reg_details = """Register 1: MIZAR_GPIO_GP0_GPIO_8
  Name: gp0_gpio_8 | Base: 0xA001A000 | Offset: 0x0 | Addr: 0xA001A000
  Ops: read, write
  Fields: data_in[0](RO,rst=0), intr_raw_sts[1](RO,rst=0), intr_clr[16](WO,rst=0), pedge_intr_en[17](RW,rst=0), nedge_intr_en[18](RW,rst=0), level_sel[19](RW,rst=0), io_ctrl[20](RW2,rst=1), dout[21](RW2,rst=0)

Register 2: MIZAR_GPIO_GP0_INTR1_INTR_EN1
  Name: gp0_intr1_intr_en1 | Base: 0xA001A000 | Offset: 0x84 | Addr: 0xA001A084
  Ops: write
  Fields: G8_intr_en[0](RW,rst=0), G9_intr_en[1](RW,rst=0), G10_intr_en[2](RW,rst=0), G11_intr_en[3](RW,rst=0), G12_intr_en[4](RW,rst=0), G13_intr_en[5](RW,rst=0), G14_intr_en[6](RW,rst=0), G15_intr_en[7](RW,rst=0), G16_intr_en[8](RW,rst=0), G17_intr_en[9](RW,rst=0), G18_intr_en[10](RW,rst=0), G19_intr_en[11](RW,rst=0), G20_intr_en[12](RW,rst=0), G21_intr_en[13](RW,rst=0), G22_intr_en[14](RW,rst=0), G23_intr_en[15](RW,rst=0), G24_intr_en[16](RW,rst=0), G25_intr_en[17](RW,rst=0), G26_intr_en[18](RW,rst=0), G27_intr_en[19](RW,rst=0), G28_intr_en[20](RW,rst=0), G29_intr_en[21](RW,rst=0), G30_intr_en[22](RW,rst=0), G31_intr_en[23](RW,rst=0), G32_intr_en[24](RW,rst=0), G33_intr_en[25](RW,rst=0), G34_intr_en[26](RW,rst=0), G35_intr_en[27](RW,rst=0), G36_intr_en[28](RW,rst=0), G37_intr_en[29](RW,rst=0), G38_intr_en[30](RW,rst=0), G39_intr_en[31](RW,rst=0)

Register 3: MIZAR_GPIO_GP0_INTR1_INTR_STS1
  Name: gp0_intr1_intr_sts1 | Base: 0xA001A000 | Offset: 0x88 | Addr: 0xA001A088
  Ops: read
  Fields: G8_intr_sts[0](RO,rst=0), G9_intr_sts[1](RO,rst=0), G10_intr_sts[2](RO,rst=0), G11_intr_sts[3](RO,rst=0), G12_intr_sts[4](RO,rst=0), G13_intr_sts[5](RO,rst=0), G14_intr_sts[6](RO,rst=0), G15_intr_sts[7](RO,rst=0), G16_intr_sts[8](RO,rst=0), G17_intr_sts[9](RO,rst=0), G18_intr_sts[10](RO,rst=0), G19_intr_sts[11](RO,rst=0), G20_intr_sts[12](RO,rst=0), G21_intr_sts[13](RO,rst=0), G22_intr_sts[14](RO,rst=0), G23_intr_sts[15](RO,rst=0), G24_intr_sts[16](RO,rst=0), G25_intr_sts[17](RO,rst=0), G26_intr_sts[18](RO,rst=0), G27_intr_sts[19](RO,rst=0), G28_intr_sts[20](RO,rst=0), G29_intr_sts[21](RO,rst=0), G30_intr_sts[22](RO,rst=0), G31_intr_sts[23](RO,rst=0), G32_intr_sts[24](RO,rst=0), G33_intr_sts[25](RO,rst=0), G34_intr_sts[26](RO,rst=0), G35_intr_sts[27](RO,rst=0), G36_intr_sts[28](RO,rst=0), G37_intr_sts[29](RO,rst=0), G38_intr_sts[30](RO,rst=0), G39_intr_sts[31](RO,rst=0)

Register 4: MIZAR_LSS_SYSREG_INTR_EN1
  Name: intr_en1 | Base: 0xA0000000 | Offset: 0x28 | Addr: 0xA0000028
  Ops: write
  Fields: usb_phy_intr[0](INTREN1,rst=0), gpio0_intr[1](INTREN1,rst=0), gpio1_intr[2](INTREN1,rst=0)

Register 5: MIZAR_LSS_SYSREG_RAW_STCR1
  Name: raw_stcr1 | Base: 0xA0000000 | Offset: 0x24 | Addr: 0xA0000024
  Ops: read, write
  Fields: usb_phy_intr[0](RAWSTCR1,rst=0), gpio0_intr[1](RAWSTCR1,rst=0), gpio1_intr[2](RAWSTCR1,rst=0)

Register 6: 0xA0243ffc
  Name: NA (unresolved) | Base: NA | Offset: 0xA0243ffc | Addr: 0xA0243ffc
  Ops: write
  Fields: (none)"""

tc2_tp_row = [
    2,
    "GPIO",
    "Level Select Interrupt Enable",
    "test_gpio_level_sel_intr_en",
    "Verify GPIO level-select interrupt functionality. Test configures GPIO_8 pin in input mode, sets level_sel to generate interrupt on a specific level, enables interrupt at GPIO IP level (gp0_intr1_intr_en1) and system level (intr_en1 gpio0_intr bit[1]), then triggers the interrupt by driving the pin to the selected level. ISR reads raw_stcr1 to confirm gpio0_intr, reads gp0_intr1_intr_sts1 to identify the source GPIO pin, clears the interrupt via gp0_gpio_8 intr_clr field, and writes to raw_stcr1 to clear system-level status. GIC IRQ 87 is used for GPIO0 instance.",
    "NA",  # Speed
    "ISR",  # Mode
    "0xA001A000",  # Memory Start Offset
    "0xA001A088",  # Memory End Offset
    "Interrupt test covers level-select functionality on GPIO_8. Uses GIC IRQ 87 for GPIO0. Involves GPIO IP registers and LSS SYSREG registers. Unresolved register 0xA0243ffc used for test completion signaling.",
    "1. Configure gp0_gpio_8 (offset 0x0): set io_ctrl=1 (input mode), set level_sel=1 (interrupt on level 1).\n2. Enable GPIO_8 interrupt in gp0_intr1_intr_en1 (offset 0x84): write bit[0]=1 (G8_intr_en).\n3. Enable gpio0_intr in system-level intr_en1 (offset 0x28): write bit[1]=1.\n4. Enable GIC IRQ 87.\n5. Drive GPIO_8 pin to level 1 to trigger interrupt.\n6. Verify ISR is invoked on GIC IRQ 87.\n7. In ISR: read raw_stcr1 (offset 0x24) and verify gpio0_intr bit[1]=1.\n8. In ISR: read gp0_intr1_intr_sts1 (offset 0x88) and verify G8_intr_sts bit[0]=1.\n9. In ISR: read gp0_gpio_8 intr_raw_sts bit[1] and verify it is 1.\n10. In ISR: write gp0_gpio_8 intr_clr bit[16]=1 to clear interrupt.\n11. In ISR: write raw_stcr1 bit[1]=1 to clear gpio0_intr.\n12. Write 0xA0243ffc to signal test completion.\n13. Verify gp0_intr1_intr_sts1 G8_intr_sts bit[0]=0 after clear.\n14. Verify raw_stcr1 gpio0_intr bit[1]=0 after clear.",
    "gp0_gpio_8; gp0_intr1_intr_en1; gp0_intr1_intr_sts1; intr_en1; raw_stcr1",
    "PASS: ISR is invoked on GIC IRQ 87 AND raw_stcr1 gpio0_intr=1 AND gp0_intr1_intr_sts1 G8_intr_sts=1 AND gp0_gpio_8 intr_raw_sts=1 AND all interrupts clear successfully after writing intr_clr and raw_stcr1. FAIL: ISR not invoked OR any interrupt status bit mismatch OR interrupt not cleared after write.",
    "NA"  # Code Generation
]

tc2_md_row = [
    2,
    "test_gpio_level_sel_intr_en",
    "Verify GPIO level-select interrupt functionality. Test configures GPIO_8 pin in input mode, sets level_sel to generate interrupt on a specific level, enables interrupt at GPIO IP level (gp0_intr1_intr_en1) and system level (intr_en1 gpio0_intr bit[1]), then triggers the interrupt by driving the pin to the selected level. ISR reads raw_stcr1 to confirm gpio0_intr, reads gp0_intr1_intr_sts1 to identify the source GPIO pin, clears the interrupt via gp0_gpio_8 intr_clr field, and writes to raw_stcr1 to clear system-level status. GIC IRQ 87 is used for GPIO0 instance.",
    "1. Configure gp0_gpio_8 (offset 0x0): set io_ctrl=1 (input mode), set level_sel=1 (interrupt on level 1).\n2. Enable GPIO_8 interrupt in gp0_intr1_intr_en1 (offset 0x84): write bit[0]=1 (G8_intr_en).\n3. Enable gpio0_intr in system-level intr_en1 (offset 0x28): write bit[1]=1.\n4. Enable GIC IRQ 87.\n5. Drive GPIO_8 pin to level 1 to trigger interrupt.\n6. Verify ISR is invoked on GIC IRQ 87.\n7. In ISR: read raw_stcr1 (offset 0x24) and verify gpio0_intr bit[1]=1.\n8. In ISR: read gp0_intr1_intr_sts1 (offset 0x88) and verify G8_intr_sts bit[0]=1.\n9. In ISR: read gp0_gpio_8 intr_raw_sts bit[1] and verify it is 1.\n10. In ISR: write gp0_gpio_8 intr_clr bit[16]=1 to clear interrupt.\n11. In ISR: write raw_stcr1 bit[1]=1 to clear gpio0_intr.\n12. Write 0xA0243ffc to signal test completion.\n13. Verify gp0_intr1_intr_sts1 G8_intr_sts bit[0]=0 after clear.\n14. Verify raw_stcr1 gpio0_intr bit[1]=0 after clear.",
    "1. GPIO_8 is configured in input mode with level_sel=1. 2. Interrupt is enabled at GPIO IP level and system level. 3. Driving GPIO_8 pin to level 1 triggers GIC IRQ 87. 4. ISR reads raw_stcr1 and confirms gpio0_intr=1 at bit[1]. 5. ISR reads gp0_intr1_intr_sts1 and confirms G8_intr_sts=1 at bit[0]. 6. ISR reads gp0_gpio_8 intr_raw_sts=1 at bit[1]. 7. Writing intr_clr=1 clears the GPIO-level interrupt. 8. Writing raw_stcr1 bit[1]=1 clears the system-level interrupt. 9. After clearing, gp0_intr1_intr_sts1 G8_intr_sts=0 and raw_stcr1 gpio0_intr=0.",
    "MIZAR_LSS_SYSREG_INTR_EN1; MIZAR_GPIO_GP0_GPIO_8; MIZAR_GPIO_GP0_INTR1_INTR_EN1; 0xA0243ffc; MIZAR_GPIO_GP0_INTR1_INTR_STS1; MIZAR_LSS_SYSREG_RAW_STCR1",
    "PASS: ISR is invoked on GIC IRQ 87 AND raw_stcr1 gpio0_intr=1 AND gp0_intr1_intr_sts1 G8_intr_sts=1 AND gp0_gpio_8 intr_raw_sts=1 AND all interrupts clear successfully after writing intr_clr and raw_stcr1. FAIL: ISR not invoked OR any interrupt status bit mismatch OR interrupt not cleared after write.",
    "1. GPIO IP is powered on and clocked. 2. System reset has been de-asserted. 3. GPIO0 instance is selected (#define GPIO0 1). 4. GPIO base address 0xA001A000 is accessible. 5. LSS SYSREG base address 0xA0000000 is accessible. 6. GIC is configured and IRQ 87 is enabled. 7. ISR handler is registered for IRQ 87.",
    "Functional - Interrupt",
    "P1 - High",
    "87",
    tc2_reg_details,
    "TestRepo/gpio/test_gpio_level_sel_intr_en",
    "https://github.com/titusbspgit/PSVValidation/tree/main/TestRepo/gpio/test_gpio_level_sel_intr_en"
]

# ============================================================
# Create Workbook
# ============================================================
wb = Workbook()

# --- Styles ---
header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
cell_font = Font(name="Calibri", size=10)
cell_alignment = Alignment(wrap_text=True, vertical="top")
header_alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")
thin_border = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin")
)

def style_header(ws, headers):
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border

def style_data_row(ws, row_idx, data):
    for col_idx, value in enumerate(data, 1):
        cell = ws.cell(row=row_idx, column=col_idx, value=value)
        cell.font = cell_font
        cell.alignment = cell_alignment
        cell.border = thin_border

# ============================================================
# Sheet 1: TestPlan (visible)
# ============================================================
ws_tp = wb.active
ws_tp.title = "TestPlan"
style_header(ws_tp, TP_HEADERS)
style_data_row(ws_tp, 2, tc1_tp_row)
style_data_row(ws_tp, 3, tc2_tp_row)

# Column widths for TestPlan
tp_widths = [8, 14, 30, 32, 60, 8, 8, 18, 18, 45, 65, 45, 65, 15]
for i, w in enumerate(tp_widths, 1):
    ws_tp.column_dimensions[get_column_letter(i)].width = w

# Freeze first row
ws_tp.freeze_panes = "A2"

# ============================================================
# Sheet 2: MetaData (very hidden)
# ============================================================
ws_md = wb.create_sheet(title="MetaData")
style_header(ws_md, MD_HEADERS)
style_data_row(ws_md, 2, tc1_md_row)
style_data_row(ws_md, 3, tc2_md_row)

# Column widths for MetaData
md_widths = [8, 32, 60, 65, 60, 55, 65, 55, 25, 12, 15, 80, 40, 70]
for i, w in enumerate(md_widths, 1):
    ws_md.column_dimensions[get_column_letter(i)].width = w

# Freeze first row
ws_md.freeze_panes = "A2"

# Set MetaData sheet as very hidden
ws_md.sheet_state = "veryHidden"

# ============================================================
# Save
# ============================================================
output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)
wb.save(output_path)
print(f"\nFile saved: {output_path}")
print(f"File size: {os.path.getsize(output_path)} bytes")
print(f"\nSheets: {wb.sheetnames}")
print(f"TestPlan rows: {ws_tp.max_row} (1 header + {ws_tp.max_row - 1} data)")
print(f"MetaData rows: {ws_md.max_row} (1 header + {ws_md.max_row - 1} data)")
print(f"MetaData visibility: {ws_md.sheet_state}")
print(f"\n=== SUCCESS ===")
print(f"Output: {filename}")
print(f"Target: Test_Output/GPIO/TestPlan/{filename}")
print(f"\nTo push to GitHub, run:")
print(f"  git add '{output_path}'")
print(f"  git commit -m 'Add {filename}'")
print(f"  git push origin main")
