#include <stdio.h>
#include <lss_sysreg.h>
#include <test_common.h>
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

// Generated by Test_Stage3 Agent (IP: GPIO)
// Testcase: test_gpio_pedge_all_pads_en
// Description (from CSV):
// GPIO posedge interrupt on all pads (8..39): enables posedge detect and group interrupt,
// sequences a single rising edge per pad, validates group interrupt assertion and full clear,
// and verifies system-level interrupt status clear.
//
// Notes:
// - All register names used in program flow are taken from the CSV Impacted Registers list.
// - Any register/mask specifics defined here are based only on GP0_RAG/LSS_RAG data; none are invented.
// - For registers without detailed RAG field data, code uses safe write/read sequences with literal values
//   explicitly provided in the CSV procedure steps.

// Unchanged macro defines extracted from testcase context
#define CNT 49

// Optional debug print macro used by program.c
#ifdef DEBUG_DISPLAY
#define DBG_PRINTF(...) printf(__VA_ARGS__)
#else
#define DBG_PRINTF(...)
#endif

// Helper constants derived strictly from CSV procedure
#define GPIO_POSEDGE_EN_VAL      0x00020000u  // per-pin posedge enable value
#define GPIO_PERPIN_RAW_ICLR_VAL 0x00010000u  // per-pin raw clear value
#define GPIO_GROUP_IO_IN_MASK    0x000000FFu  // group IO control: configure 8 pads per group
#define GPIO_INT_EN_ALL          0xFFFFFFFFu  // enable all group interrupts

// Memory-mapped pad driver (from CSV Memory Start/End Offset)
#define PAD_DRIVER_ADDR 0xA0243ffcu

// Helper: per-pin register address for pads [8..39] using the CSV-specified stride
static inline unsigned long gpio_pin_addr(unsigned int i)
{
    // i in [0..31] maps to pad number (i + 8)
    return (unsigned long)(MIZAR_GPIO_GP0_GPIO_8 + (i * 4u));
}

// Impacted Registers array (order preserved from CSV row)
#define IMP_REG_COUNT 9u
static const unsigned long impacted_addr_array[IMP_REG_COUNT] = {
    MIZAR_LSS_SYSREG_INTR_EN1,
    MIZAR_GPIO_GP0_GPIO_8,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP1,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP2,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP3,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP4,
    MIZAR_GPIO_GP0_INTR1_INTR_EN1,
    MIZAR_GPIO_GP0_INTR1_INTR_STS1,
    MIZAR_LSS_SYSREG_RAW_STCR1,
};

// Skip array (no skip_registers provided for this testcase)
static const unsigned int skip_array[IMP_REG_COUNT] = { 0,0,0,0,0,0,0,0,0 };
