#include <stdio.h>
#include <lss_sysreg.h>
#include "test_common.h"
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

// Test: Enable posedge interrupts on all GPIO[8..39] pins, drive rising edges, wait for ISR ack/clear.
// Inputs: Registers and masks are referenced via included headers/macros. Only impacted registers are used.

#define CNT 49
#define PAD_DRIVE_REG 0xA0243ffcu  // External pad control to generate edges (from CSV input)

// Address list for impacted registers (order preserved)
const unsigned long int addr_array[CNT] = {
    MIZAR_GPIO_GP0_GPIO_8,  MIZAR_GPIO_GP0_GPIO_9,  MIZAR_GPIO_GP0_GPIO_10, MIZAR_GPIO_GP0_GPIO_11,
    MIZAR_GPIO_GP0_GPIO_12, MIZAR_GPIO_GP0_GPIO_13, MIZAR_GPIO_GP0_GPIO_14, MIZAR_GPIO_GP0_GPIO_15,
    MIZAR_GPIO_GP0_GPIO_16, MIZAR_GPIO_GP0_GPIO_17, MIZAR_GPIO_GP0_GPIO_18, MIZAR_GPIO_GP0_GPIO_19,
    MIZAR_GPIO_GP0_GPIO_20, MIZAR_GPIO_GP0_GPIO_21, MIZAR_GPIO_GP0_GPIO_22, MIZAR_GPIO_GP0_GPIO_23,
    MIZAR_GPIO_GP0_GPIO_24, MIZAR_GPIO_GP0_GPIO_25, MIZAR_GPIO_GP0_GPIO_26, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_28, MIZAR_GPIO_GP0_GPIO_29, MIZAR_GPIO_GP0_GPIO_30, MIZAR_GPIO_GP0_GPIO_31,
    MIZAR_GPIO_GP0_GPIO_32, MIZAR_GPIO_GP0_GPIO_33, MIZAR_GPIO_GP0_GPIO_34, MIZAR_GPIO_GP0_GPIO_35,
    MIZAR_GPIO_GP0_GPIO_36, MIZAR_GPIO_GP0_GPIO_37, MIZAR_GPIO_GP0_GPIO_38, MIZAR_GPIO_GP0_GPIO_39,
    MIZAR_GPIO_GPIO_INTR_RAW_STCLR1,
    MIZAR_GPIO_GP0_INTR1_INTR_EN1, MIZAR_GPIO_GP0_INTR1_INTR_STS1,
    MIZAR_GPIO_GP0_INTR2_INTR_EN1, MIZAR_GPIO_GP0_INTR2_INTR_STS1,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP1, MIZAR_GPIO_GPIO_IO_CTRL_GROUP2, MIZAR_GPIO_GPIO_IO_CTRL_GROUP3, MIZAR_GPIO_GPIO_IO_CTRL_GROUP4,
    MIZAR_GPIO_GPIO_DOUT_GROUP1,    MIZAR_GPIO_GPIO_DOUT_GROUP2,    MIZAR_GPIO_GPIO_DOUT_GROUP3,    MIZAR_GPIO_GPIO_DOUT_GROUP4,
    MIZAR_GPIO_GPIO_DIN_GROUP1,     MIZAR_GPIO_GPIO_DIN_GROUP2,     MIZAR_GPIO_GPIO_DIN_GROUP3,     MIZAR_GPIO_GPIO_DIN_GROUP4,
};

// Default values, read and write masks are resolved from design headers
const unsigned int default_value_array[CNT] = {
    GPIO_GP0_GPIO_8_DEFAULT_VAL,  GPIO_GP0_GPIO_9_DEFAULT_VAL,  GPIO_GP0_GPIO_10_DEFAULT_VAL, GPIO_GP0_GPIO_11_DEFAULT_VAL,
    GPIO_GP0_GPIO_12_DEFAULT_VAL, GPIO_GP0_GPIO_13_DEFAULT_VAL, GPIO_GP0_GPIO_14_DEFAULT_VAL, GPIO_GP0_GPIO_15_DEFAULT_VAL,
    GPIO_GP0_GPIO_16_DEFAULT_VAL, GPIO_GP0_GPIO_17_DEFAULT_VAL, GPIO_GP0_GPIO_18_DEFAULT_VAL, GPIO_GP0_GPIO_19_DEFAULT_VAL,
    GPIO_GP0_GPIO_20_DEFAULT_VAL, GPIO_GP0_GPIO_21_DEFAULT_VAL, GPIO_GP0_GPIO_22_DEFAULT_VAL, GPIO_GP0_GPIO_23_DEFAULT_VAL,
    GPIO_GP0_GPIO_24_DEFAULT_VAL, GPIO_GP0_GPIO_25_DEFAULT_VAL, GPIO_GP0_GPIO_26_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_28_DEFAULT_VAL, GPIO_GP0_GPIO_29_DEFAULT_VAL, GPIO_GP0_GPIO_30_DEFAULT_VAL, GPIO_GP0_GPIO_31_DEFAULT_VAL,
    GPIO_GP0_GPIO_32_DEFAULT_VAL, GPIO_GP0_GPIO_33_DEFAULT_VAL, GPIO_GP0_GPIO_34_DEFAULT_VAL, GPIO_GP0_GPIO_35_DEFAULT_VAL,
    GPIO_GP0_GPIO_36_DEFAULT_VAL, GPIO_GP0_GPIO_37_DEFAULT_VAL, GPIO_GP0_GPIO_38_DEFAULT_VAL, GPIO_GP0_GPIO_39_DEFAULT_VAL,
    GPIO_GPIO_INTR_RAW_STCLR1_DEFAULT_VAL,
    GPIO_GP0_INTR1_INTR_EN1_DEFAULT_VAL, GPIO_GP0_INTR1_INTR_STS1_DEFAULT_VAL,
    GPIO_GP0_INTR2_INTR_EN1_DEFAULT_VAL, GPIO_GP0_INTR2_INTR_STS1_DEFAULT_VAL,
    GPIO_GPIO_IO_CTRL_GROUP1_DEFAULT_VAL, GPIO_GPIO_IO_CTRL_GROUP2_DEFAULT_VAL, GPIO_GPIO_IO_CTRL_GROUP3_DEFAULT_VAL, GPIO_GPIO_IO_CTRL_GROUP4_DEFAULT_VAL,
    GPIO_GPIO_DOUT_GROUP1_DEFAULT_VAL,    GPIO_GPIO_DOUT_GROUP2_DEFAULT_VAL,    GPIO_GPIO_DOUT_GROUP3_DEFAULT_VAL,    GPIO_GPIO_DOUT_GROUP4_DEFAULT_VAL,
    GPIO_GPIO_DIN_GROUP1_DEFAULT_VAL,     GPIO_GPIO_DIN_GROUP2_DEFAULT_VAL,     GPIO_GPIO_DIN_GROUP3_DEFAULT_VAL,     GPIO_GPIO_DIN_GROUP4_DEFAULT_VAL,
};

const unsigned int read_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_READ_MASK,  GPIO_GP0_GPIO_9_READ_MASK,  GPIO_GP0_GPIO_10_READ_MASK, GPIO_GP0_GPIO_11_READ_MASK,
    GPIO_GP0_GPIO_12_READ_MASK, GPIO_GP0_GPIO_13_READ_MASK, GPIO_GP0_GPIO_14_READ_MASK, GPIO_GP0_GPIO_15_READ_MASK,
    GPIO_GP0_GPIO_16_READ_MASK, GPIO_GP0_GPIO_17_READ_MASK, GPIO_GP0_GPIO_18_READ_MASK, GPIO_GP0_GPIO_19_READ_MASK,
    GPIO_GP0_GPIO_20_READ_MASK, GPIO_GP0_GPIO_21_READ_MASK, GPIO_GP0_GPIO_22_READ_MASK, GPIO_GP0_GPIO_23_READ_MASK,
    GPIO_GP0_GPIO_24_READ_MASK, GPIO_GP0_GPIO_25_READ_MASK, GPIO_GP0_GPIO_26_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_28_READ_MASK, GPIO_GP0_GPIO_29_READ_MASK, GPIO_GP0_GPIO_30_READ_MASK, GPIO_GP0_GPIO_31_READ_MASK,
    GPIO_GP0_GPIO_32_READ_MASK, GPIO_GP0_GPIO_33_READ_MASK, GPIO_GP0_GPIO_34_READ_MASK, GPIO_GP0_GPIO_35_READ_MASK,
    GPIO_GP0_GPIO_36_READ_MASK, GPIO_GP0_GPIO_37_READ_MASK, GPIO_GP0_GPIO_38_READ_MASK, GPIO_GP0_GPIO_39_READ_MASK,
    GPIO_GPIO_INTR_RAW_STCLR1_READ_MASK,
    GPIO_GP0_INTR1_INTR_EN1_READ_MASK, GPIO_GP0_INTR1_INTR_STS1_READ_MASK,
    GPIO_GP0_INTR2_INTR_EN1_READ_MASK, GPIO_GP0_INTR2_INTR_STS1_READ_MASK,
    GPIO_GPIO_IO_CTRL_GROUP1_READ_MASK, GPIO_GPIO_IO_CTRL_GROUP2_READ_MASK, GPIO_GPIO_IO_CTRL_GROUP3_READ_MASK, GPIO_GPIO_IO_CTRL_GROUP4_READ_MASK,
    GPIO_GPIO_DOUT_GROUP1_READ_MASK,    GPIO_GPIO_DOUT_GROUP2_READ_MASK,    GPIO_GPIO_DOUT_GROUP3_READ_MASK,    GPIO_GPIO_DOUT_GROUP4_READ_MASK,
    GPIO_GPIO_DIN_GROUP1_READ_MASK,     GPIO_GPIO_DIN_GROUP2_READ_MASK,     GPIO_GPIO_DIN_GROUP3_READ_MASK,     GPIO_GPIO_DIN_GROUP4_READ_MASK,
};

const unsigned int write_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_WRITE_MASK,  GPIO_GP0_GPIO_9_WRITE_MASK,  GPIO_GP0_GPIO_10_WRITE_MASK, GPIO_GP0_GPIO_11_WRITE_MASK,
    GPIO_GP0_GPIO_12_WRITE_MASK, GPIO_GP0_GPIO_13_WRITE_MASK, GPIO_GP0_GPIO_14_WRITE_MASK, GPIO_GP0_GPIO_15_WRITE_MASK,
    GPIO_GP0_GPIO_16_WRITE_MASK, GPIO_GP0_GPIO_17_WRITE_MASK, GPIO_GP0_GPIO_18_WRITE_MASK, GPIO_GP0_GPIO_19_WRITE_MASK,
    GPIO_GP0_GPIO_20_WRITE_MASK, GPIO_GP0_GPIO_21_WRITE_MASK, GPIO_GP0_GPIO_22_WRITE_MASK, GPIO_GP0_GPIO_23_WRITE_MASK,
    GPIO_GP0_GPIO_24_WRITE_MASK, GPIO_GP0_GPIO_25_WRITE_MASK, GPIO_GP0_GPIO_26_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_28_WRITE_MASK, GPIO_GP0_GPIO_29_WRITE_MASK, GPIO_GP0_GPIO_30_WRITE_MASK, GPIO_GP0_GPIO_31_WRITE_MASK,
    GPIO_GP0_GPIO_32_WRITE_MASK, GPIO_GP0_GPIO_33_WRITE_MASK, GPIO_GP0_GPIO_34_WRITE_MASK, GPIO_GP0_GPIO_35_WRITE_MASK,
    GPIO_GP0_GPIO_36_WRITE_MASK, GPIO_GP0_GPIO_37_WRITE_MASK, GPIO_GP0_GPIO_38_WRITE_MASK, GPIO_GP0_GPIO_39_WRITE_MASK,
    GPIO_GPIO_INTR_RAW_STCLR1_WRITE_MASK,
    GPIO_GP0_INTR1_INTR_EN1_WRITE_MASK, GPIO_GP0_INTR1_INTR_STS1_WRITE_MASK,
    GPIO_GP0_INTR2_INTR_EN1_WRITE_MASK, GPIO_GP0_INTR2_INTR_STS1_WRITE_MASK,
    GPIO_GPIO_IO_CTRL_GROUP1_WRITE_MASK, GPIO_GPIO_IO_CTRL_GROUP2_WRITE_MASK, GPIO_GPIO_IO_CTRL_GROUP3_WRITE_MASK, GPIO_GPIO_IO_CTRL_GROUP4_WRITE_MASK,
    GPIO_GPIO_DOUT_GROUP1_WRITE_MASK,    GPIO_GPIO_DOUT_GROUP2_WRITE_MASK,    GPIO_GPIO_DOUT_GROUP3_WRITE_MASK,    GPIO_GPIO_DOUT_GROUP4_WRITE_MASK,
    GPIO_GPIO_DIN_GROUP1_WRITE_MASK,     GPIO_GPIO_DIN_GROUP2_WRITE_MASK,     GPIO_GPIO_DIN_GROUP3_WRITE_MASK,     GPIO_GPIO_DIN_GROUP4_WRITE_MASK,
};

// Skip array: mark any registers to skip (none for this testcase per context)
unsigned int skip_array[CNT] = {
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,
    0,0,
    0,0,
    0,0,0,0,
    0,0,0,0,
    0,0,0,0,
};
