#include <stdio.h>
#include <test_common.h>
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/*
  Test: test_gpio_pedge_all_pads_en
  Purpose: Provide per-pin GPIO address and masks for enabling posedge interrupt
           and validating via configuration read-backs only. LSS_SYSREG ignored.
*/

#define CNT 32 /* GPIO_8..GPIO_39 */

/* Per-pin address list */
const unsigned long int gpio_pin_addr_array[CNT] = {
    MIZAR_GPIO_GP0_GPIO_8,  MIZAR_GPIO_GP0_GPIO_9,  MIZAR_GPIO_GP0_GPIO_10, MIZAR_GPIO_GP0_GPIO_11,
    MIZAR_GPIO_GP0_GPIO_12, MIZAR_GPIO_GP0_GPIO_13, MIZAR_GPIO_GP0_GPIO_14, MIZAR_GPIO_GP0_GPIO_15,
    MIZAR_GPIO_GP0_GPIO_16, MIZAR_GPIO_GP0_GPIO_17, MIZAR_GPIO_GP0_GPIO_18, MIZAR_GPIO_GP0_GPIO_19,
    MIZAR_GPIO_GP0_GPIO_20, MIZAR_GPIO_GP0_GPIO_21, MIZAR_GPIO_GP0_GPIO_22, MIZAR_GPIO_GP0_GPIO_23,
    MIZAR_GPIO_GP0_GPIO_24, MIZAR_GPIO_GP0_GPIO_25, MIZAR_GPIO_GP0_GPIO_26, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_28, MIZAR_GPIO_GP0_GPIO_29, MIZAR_GPIO_GP0_GPIO_30, MIZAR_GPIO_GP0_GPIO_31,
    MIZAR_GPIO_GP0_GPIO_32, MIZAR_GPIO_GP0_GPIO_33, MIZAR_GPIO_GP0_GPIO_34, MIZAR_GPIO_GP0_GPIO_35,
    MIZAR_GPIO_GP0_GPIO_36, MIZAR_GPIO_GP0_GPIO_37, MIZAR_GPIO_GP0_GPIO_38, MIZAR_GPIO_GP0_GPIO_39
};

/* Default, read and write masks per pin */
const unsigned int gpio_pin_default_value_array[CNT] = {
    GPIO_GP0_GPIO_8_DEFAULT_VAL,  GPIO_GP0_GPIO_9_DEFAULT_VAL,  GPIO_GP0_GPIO_10_DEFAULT_VAL, GPIO_GP0_GPIO_11_DEFAULT_VAL,
    GPIO_GP0_GPIO_12_DEFAULT_VAL, GPIO_GP0_GPIO_13_DEFAULT_VAL, GPIO_GP0_GPIO_14_DEFAULT_VAL, GPIO_GP0_GPIO_15_DEFAULT_VAL,
    GPIO_GP0_GPIO_16_DEFAULT_VAL, GPIO_GP0_GPIO_17_DEFAULT_VAL, GPIO_GP0_GPIO_18_DEFAULT_VAL, GPIO_GP0_GPIO_19_DEFAULT_VAL,
    GPIO_GP0_GPIO_20_DEFAULT_VAL, GPIO_GP0_GPIO_21_DEFAULT_VAL, GPIO_GP0_GPIO_22_DEFAULT_VAL, GPIO_GP0_GPIO_23_DEFAULT_VAL,
    GPIO_GP0_GPIO_24_DEFAULT_VAL, GPIO_GP0_GPIO_25_DEFAULT_VAL, GPIO_GP0_GPIO_26_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_28_DEFAULT_VAL, GPIO_GP0_GPIO_29_DEFAULT_VAL, GPIO_GP0_GPIO_30_DEFAULT_VAL, GPIO_GP0_GPIO_31_DEFAULT_VAL,
    GPIO_GP0_GPIO_32_DEFAULT_VAL, GPIO_GP0_GPIO_33_DEFAULT_VAL, GPIO_GP0_GPIO_34_DEFAULT_VAL, GPIO_GP0_GPIO_35_DEFAULT_VAL,
    GPIO_GP0_GPIO_36_DEFAULT_VAL, GPIO_GP0_GPIO_37_DEFAULT_VAL, GPIO_GP0_GPIO_38_DEFAULT_VAL, GPIO_GP0_GPIO_39_DEFAULT_VAL
};

const unsigned int gpio_pin_read_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_READ_MASK,  GPIO_GP0_GPIO_9_READ_MASK,  GPIO_GP0_GPIO_10_READ_MASK, GPIO_GP0_GPIO_11_READ_MASK,
    GPIO_GP0_GPIO_12_READ_MASK, GPIO_GP0_GPIO_13_READ_MASK, GPIO_GP0_GPIO_14_READ_MASK, GPIO_GP0_GPIO_15_READ_MASK,
    GPIO_GP0_GPIO_16_READ_MASK, GPIO_GP0_GPIO_17_READ_MASK, GPIO_GP0_GPIO_18_READ_MASK, GPIO_GP0_GPIO_19_READ_MASK,
    GPIO_GP0_GPIO_20_READ_MASK, GPIO_GP0_GPIO_21_READ_MASK, GPIO_GP0_GPIO_22_READ_MASK, GPIO_GP0_GPIO_23_READ_MASK,
    GPIO_GP0_GPIO_24_READ_MASK, GPIO_GP0_GPIO_25_READ_MASK, GPIO_GP0_GPIO_26_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_28_READ_MASK, GPIO_GP0_GPIO_29_READ_MASK, GPIO_GP0_GPIO_30_READ_MASK, GPIO_GP0_GPIO_31_READ_MASK,
    GPIO_GP0_GPIO_32_READ_MASK, GPIO_GP0_GPIO_33_READ_MASK, GPIO_GP0_GPIO_34_READ_MASK, GPIO_GP0_GPIO_35_READ_MASK,
    GPIO_GP0_GPIO_36_READ_MASK, GPIO_GP0_GPIO_37_READ_MASK, GPIO_GP0_GPIO_38_READ_MASK, GPIO_GP0_GPIO_39_READ_MASK
};

const unsigned int gpio_pin_write_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_WRITE_MASK,  GPIO_GP0_GPIO_9_WRITE_MASK,  GPIO_GP0_GPIO_10_WRITE_MASK, GPIO_GP0_GPIO_11_WRITE_MASK,
    GPIO_GP0_GPIO_12_WRITE_MASK, GPIO_GP0_GPIO_13_WRITE_MASK, GPIO_GP0_GPIO_14_WRITE_MASK, GPIO_GP0_GPIO_15_WRITE_MASK,
    GPIO_GP0_GPIO_16_WRITE_MASK, GPIO_GP0_GPIO_17_WRITE_MASK, GPIO_GP0_GPIO_18_WRITE_MASK, GPIO_GP0_GPIO_19_WRITE_MASK,
    GPIO_GP0_GPIO_20_WRITE_MASK, GPIO_GP0_GPIO_21_WRITE_MASK, GPIO_GP0_GPIO_22_WRITE_MASK, GPIO_GP0_GPIO_23_WRITE_MASK,
    GPIO_GP0_GPIO_24_WRITE_MASK, GPIO_GP0_GPIO_25_WRITE_MASK, GPIO_GP0_GPIO_26_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_28_WRITE_MASK, GPIO_GP0_GPIO_29_WRITE_MASK, GPIO_GP0_GPIO_30_WRITE_MASK, GPIO_GP0_GPIO_31_WRITE_MASK,
    GPIO_GP0_GPIO_32_WRITE_MASK, GPIO_GP0_GPIO_33_WRITE_MASK, GPIO_GP0_GPIO_34_WRITE_MASK, GPIO_GP0_GPIO_35_WRITE_MASK,
    GPIO_GP0_GPIO_36_WRITE_MASK, GPIO_GP0_GPIO_37_WRITE_MASK, GPIO_GP0_GPIO_38_WRITE_MASK, GPIO_GP0_GPIO_39_WRITE_MASK
};

/* Target program value for posedge enable (from metadata) */
const unsigned int gpio_pin_peie_value = 0x00020000u;
