#ifndef TEST_DEFINE_C
#define TEST_DEFINE_C

// Headers (from context, unchanged)
#include<stdio.h>
#include<lss_sysreg/lss_sysreg_offset.h>
#include<lss_sysreg/lss_sysreg_def.h>
#include<test_common.h>
#include<dma/dma_def.h>
#include<dma/dma_offset.h>
#include<test_define.c>
#include<i2c/i2c0_def.h>
#include<i2c/i2c1_def.h>
#include<i2c/i2c_offset.h>

// Macros (from context, unchanged)
#define SRAM_ADDR_1 0xA0243FC0
#define SRAM_ADDR_2 0xA0243FE0
#define CNT 86

// Arrays (from context, unchanged)
int i,tx_data[5],rx_data[5];
const int addr_array[86]={
    MIZAR_I2C0_DEV_CTRL,MIZAR_I2C0_TSFR_CTRL,MIZAR_I2C0_SLV_ADDR,MIZAR_I2C0_TGT_SLV_ADDR,MIZAR_I2C0_I2C_MSTR_CODE,
    MIZAR_I2C0_I2C_BYTE_CNT,MIZAR_I2C0_SF_HCNT,MIZAR_I2C0_SF_LCNT,MIZAR_I2C0_I2C_HS_HCNT,MIZAR_I2C0_I2C_HS_LCNT,
    MIZAR_I2C0_RIS,MIZAR_I2C0_MASK_INTR,MIZAR_I2C0_INTR_STS,MIZAR_I2C0_INTR_CLR,MIZAR_I2C0_TAS,MIZAR_I2C0_TX_FIFO_THLD,
    MIZAR_I2C0_RX_FIFO_THLD,MIZAR_I2C0_DMA_CTRL,MIZAR_I2C0_FF,MIZAR_I2C0_TX_FIFO_LVL,MIZAR_I2C0_RX_FIFO_LVL,
    MIZAR_I2C0_I2C_MSTR_STS,MIZAR_I2C0_I2C_FLTR_SEL,MIZAR_I2C0_I2C_CURRENT_BYTECNT,MIZAR_I2C0_I2C_SMB_SFTRST,
    MIZAR_I2C0_SMB_HST_STS,MIZAR_I2C0_SMB_HST_CTRL,MIZAR_I2C0_SMB_HST_CMD,MIZAR_I2C0_SMB_HST_DATA0,
    MIZAR_I2C0_SMB_HST_DATA1,MIZAR_I2C0_SMB_HST_BLOCK_DATA,MIZAR_I2C0_SMB_PEC_DATA,MIZAR_I2C0_SMB_SLAVE_WDATA,
    MIZAR_I2C0_SMB_SLAVE_CMD,MIZAR_I2C0_SMB_SLAVE_CTS,MIZAR_I2C0_SMB_SLV,MIZAR_I2C0_SMB_NOTIFY_ADDR,
    MIZAR_I2C0_SMB_NOTIFY_LOW_BYTE,MIZAR_I2C0_SMB_NOTIFY_HIGH_BYTE,MIZAR_I2C0_SMB_DATA_HLDTIME,
    MIZAR_I2C0_SMB_TIMEOUT_CNT,MIZAR_I2C0_SMB_TMEXT_CNT,MIZAR_I2C0_I2CSMB_DATA_SETUP,
    MIZAR_I2C1_DEV_CTRL,MIZAR_I2C1_TSFR_CTRL,MIZAR_I2C1_SLV_ADDR,MIZAR_I2C1_TGT_SLV_ADDR,MIZAR_I2C1_I2C_MSTR_CODE,
    MIZAR_I2C1_I2C_BYTE_CNT,MIZAR_I2C1_SF_HCNT,MIZAR_I2C1_SF_LCNT,MIZAR_I2C1_I2C_HS_HCNT,MIZAR_I2C1_I2C_HS_LCNT,
    MIZAR_I2C1_RIS,MIZAR_I2C1_MASK_INTR,MIZAR_I2C1_INTR_STS,MIZAR_I2C1_INTR_CLR,MIZAR_I2C1_TAS,MIZAR_I2C1_TX_FIFO_THLD,
    MIZAR_I2C1_RX_FIFO_THLD,MIZAR_I2C1_DMA_CTRL,MIZAR_I2C1_FF,MIZAR_I2C1_TX_FIFO_LVL,MIZAR_I2C1_RX_FIFO_LVL,
    MIZAR_I2C1_I2C_MSTR_STS,MIZAR_I2C1_I2C_FLTR_SEL,MIZAR_I2C1_I2C_CURRENT_BYTECNT,MIZAR_I2C1_I2C_SMB_SFTRST,
    MIZAR_I2C1_SMB_HST_STS,MIZAR_I2C1_SMB_HST_CTRL,MIZAR_I2C1_SMB_HST_CMD,MIZAR_I2C1_SMB_HST_DATA0,
    MIZAR_I2C1_SMB_HST_DATA1,MIZAR_I2C1_SMB_HST_BLOCK_DATA,MIZAR_I2C1_SMB_PEC_DATA,MIZAR_I2C1_SMB_SLAVE_WDATA,
    MIZAR_I2C1_SMB_SLAVE_CMD,MIZAR_I2C1_SMB_SLAVE_CTS,MIZAR_I2C1_SMB_SLV,MIZAR_I2C1_SMB_NOTIFY_ADDR,
    MIZAR_I2C1_SMB_NOTIFY_LOW_BYTE,MIZAR_I2C1_SMB_NOTIFY_HIGH_BYTE,MIZAR_I2C1_SMB_DATA_HLDTIME,
    MIZAR_I2C1_SMB_TIMEOUT_CNT,MIZAR_I2C1_SMB_TMEXT_CNT,MIZAR_I2C1_I2CSMB_DATA_SETUP,
};

const int default_value_array[86]={
    I2C_DEV_CTRL_DEFAULT_VAL,I2C_TSFR_CTRL_DEFAULT_VAL,I2C_SLV_ADDR_DEFAULT_VAL,I2C_TGT_SLV_ADDR_DEFAULT_VAL,
    I2C_I2C_MSTR_CODE_DEFAULT_VAL,I2C_I2C_BYTE_CNT_DEFAULT_VAL,I2C_SF_HCNT_DEFAULT_VAL,I2C_SF_LCNT_DEFAULT_VAL,
    I2C_I2C_HS_HCNT_DEFAULT_VAL,I2C_I2C_HS_LCNT_DEFAULT_VAL,I2C_RIS_DEFAULT_VAL,I2C_MASK_INTR_DEFAULT_VAL,
    I2C_INTR_STS_DEFAULT_VAL,I2C_INTR_CLR_DEFAULT_VAL,I2C_TAS_DEFAULT_VAL,I2C_TX_FIFO_THLD_DEFAULT_VAL,
    I2C_RX_FIFO_THLD_DEFAULT_VAL,I2C_DMA_CTRL_DEFAULT_VAL,I2C_FF_DEFAULT_VAL,I2C_TX_FIFO_LVL_DEFAULT_VAL,
    I2C_RX_FIFO_LVL_DEFAULT_VAL,I2C_I2C_MSTR_STS_DEFAULT_VAL,I2C_I2C_FLTR_SEL_DEFAULT_VAL,
    I2C_I2C_CURRENT_BYTECNT_DEFAULT_VAL,I2C_I2C_SMB_SFTRST_DEFAULT_VAL,I2C_SMB_HST_STS_DEFAULT_VAL,
    I2C_SMB_HST_CTRL_DEFAULT_VAL,I2C_SMB_HST_CMD_DEFAULT_VAL,I2C_SMB_HST_DATA0_DEFAULT_VAL,
    I2C_SMB_HST_DATA1_DEFAULT_VAL,I2C_SMB_HST_BLOCK_DATA_DEFAULT_VAL,I2C_SMB_PEC_DATA_DEFAULT_VAL,
    I2C_SMB_SLAVE_WDATA_DEFAULT_VAL,I2C_SMB_SLAVE_CMD_DEFAULT_VAL,I2C_SMB_SLAVE_CTS_DEFAULT_VAL,
    I2C_SMB_SLV_DEFAULT_VAL,I2C_SMB_NOTIFY_ADDR_DEFAULT_VAL,I2C_SMB_NOTIFY_LOW_BYTE_DEFAULT_VAL,
    I2C_SMB_NOTIFY_HIGH_BYTE_DEFAULT_VAL,I2C_SMB_DATA_HLDTIME_DEFAULT_VAL,I2C_SMB_TIMEOUT_CNT_DEFAULT_VAL,
    I2C_SMB_TMEXT_CNT_DEFAULT_VAL,I2C_I2CSMB_DATA_SETUP_DEFAULT_VAL,
};

const int read_mask_array[86]={
    I2C_DEV_CTRL_READ_MASK,I2C_TSFR_CTRL_READ_MASK,I2C_SLV_ADDR_READ_MASK,I2C_TGT_SLV_ADDR_READ_MASK,
    I2C_I2C_MSTR_CODE_READ_MASK,I2C_I2C_BYTE_CNT_READ_MASK,I2C_SF_HCNT_READ_MASK,I2C_SF_LCNT_READ_MASK,
    I2C_I2C_HS_HCNT_READ_MASK,I2C_I2C_HS_LCNT_READ_MASK,I2C_RIS_READ_MASK,I2C_MASK_INTR_READ_MASK,
    I2C_INTR_STS_READ_MASK,I2C_INTR_CLR_READ_MASK,I2C_TAS_READ_MASK,I2C_TX_FIFO_THLD_READ_MASK,
    I2C_RX_FIFO_THLD_READ_MASK,I2C_DMA_CTRL_READ_MASK,I2C_FF_READ_MASK,I2C_TX_FIFO_LVL_READ_MASK,
    I2C_RX_FIFO_LVL_READ_MASK,I2C_I2C_MSTR_STS_READ_MASK,I2C_I2C_FLTR_SEL_READ_MASK,
    I2C_I2C_CURRENT_BYTECNT_READ_MASK,I2C_I2C_SMB_SFTRST_READ_MASK,I2C_SMB_HST_STS_READ_MASK,
    I2C_SMB_HST_CTRL_READ_MASK,I2C_SMB_HST_CMD_READ_MASK,I2C_SMB_HST_DATA0_READ_MASK,
    I2C_SMB_HST_DATA1_READ_MASK,I2C_SMB_HST_BLOCK_DATA_READ_MASK,I2C_SMB_PEC_DATA_READ_MASK,
    I2C_SMB_SLAVE_WDATA_READ_MASK,I2C_SMB_SLAVE_CMD_READ_MASK,I2C_SMB_SLAVE_CTS_READ_MASK,
    I2C_SMB_SLV_READ_MASK,I2C_SMB_NOTIFY_ADDR_READ_MASK,I2C_SMB_NOTIFY_LOW_BYTE_READ_MASK,
    I2C_SMB_NOTIFY_HIGH_BYTE_READ_MASK,I2C_SMB_DATA_HLDTIME_READ_MASK,I2C_SMB_TIMEOUT_CNT_READ_MASK,
    I2C_SMB_TMEXT_CNT_READ_MASK,I2C_I2CSMB_DATA_SETUP_READ_MASK,
};

const int write_mask_array[43]={
    I2C_DEV_CTRL_WRITE_MASK,I2C_TSFR_CTRL_WRITE_MASK,I2C_SLV_ADDR_WRITE_MASK,I2C_TGT_SLV_ADDR_WRITE_MASK,
    I2C_I2C_MSTR_CODE_WRITE_MASK,I2C_I2C_BYTE_CNT_WRITE_MASK,I2C_SF_HCNT_WRITE_MASK,I2C_SF_LCNT_WRITE_MASK,
    I2C_I2C_HS_HCNT_WRITE_MASK,I2C_I2C_HS_LCNT_WRITE_MASK,I2C_RIS_WRITE_MASK,I2C_MASK_INTR_WRITE_MASK,
    I2C_INTR_STS_WRITE_MASK,I2C_INTR_CLR_WRITE_MASK,I2C_TAS_WRITE_MASK,I2C_TX_FIFO_THLD_WRITE_MASK,
    I2C_RX_FIFO_THLD_WRITE_MASK,I2C_DMA_CTRL_WRITE_MASK,I2C_FF_WRITE_MASK,I2C_TX_FIFO_LVL_WRITE_MASK,
    I2C_RX_FIFO_LVL_WRITE_MASK,I2C_I2C_MSTR_STS_WRITE_MASK,I2C_I2C_FLTR_SEL_WRITE_MASK,
    I2C_I2C_CURRENT_BYTECNT_WRITE_MASK,I2C_I2C_SMB_SFTRST_WRITE_MASK,I2C_SMB_HST_STS_WRITE_MASK,
    I2C_SMB_HST_CTRL_WRITE_MASK,I2C_SMB_HST_CMD_WRITE_MASK,I2C_SMB_HST_DATA0_WRITE_MASK,
    I2C_SMB_HST_DATA1_WRITE_MASK,I2C_SMB_HST_BLOCK_DATA_WRITE_MASK,I2C_SMB_PEC_DATA_WRITE_MASK,
    I2C_SMB_SLAVE_WDATA_WRITE_MASK,I2C_SMB_SLAVE_CMD_WRITE_MASK,I2C_SMB_SLAVE_CTS_WRITE_MASK,
    I2C_SMB_SLV_WRITE_MASK,I2C_SMB_NOTIFY_ADDR_WRITE_MASK,I2C_SMB_NOTIFY_LOW_BYTE_WRITE_MASK,
    I2C_SMB_NOTIFY_HIGH_BYTE_WRITE_MASK,I2C_SMB_DATA_HLDTIME_WRITE_MASK,I2C_SMB_TIMEOUT_CNT_WRITE_MASK,
    I2C_SMB_TMEXT_CNT_WRITE_MASK,I2C_I2CSMB_DATA_SETUP_WRITE_MASK,
};

// Impacted registers array (from Hidden_Impacted_Registers)
const unsigned long impacted_registers_test_i2c0_mst_i2c1_slv_dma_st_md[] = {
    MIZAR_LSS_SYSREG_INTR_EN0, MIZAR_I2C0_FF, MIZAR_I2C1_FF, MIZAR_I2C0_INTR_CLR, MIZAR_I2C1_INTR_CLR,
    MIZAR_I2C0_DEV_CTRL, MIZAR_I2C1_DEV_CTRL, MIZAR_I2C1_SLV_ADDR, MIZAR_I2C0_TGT_SLV_ADDR,
    MIZAR_I2C0_I2C_BYTE_CNT, MIZAR_I2C1_I2C_BYTE_CNT, MIZAR_I2C0_SF_LCNT, MIZAR_I2C0_SF_HCNT,
    MIZAR_I2C0_MASK_INTR, MIZAR_I2C0_TX_FIFO_THLD, MIZAR_I2C1_TX_FIFO_THLD, MIZAR_I2C0_RX_FIFO_THLD,
    MIZAR_I2C1_RX_FIFO_THLD, MIZAR_I2C0_DMA_CTRL, MIZAR_I2C0_SMB_HST_BLOCK_DATA, MIZAR_DMA_CH0_CTRL,
    MIZAR_DMA_CH0_SRC_ADDR, MIZAR_DMA_CH0_DEST_ADDR, MIZAR_DMA_CH0_SRC_XCNT, MIZAR_DMA_CH0_SRC_XMDFY,
    MIZAR_DMA_CH0_DEST_XMDFY, MIZAR_DMA_CH0_SRC_REQ, MIZAR_DMA_DMA_CH_EN, MIZAR_I2C0_TSFR_CTRL,
    MIZAR_I2C0_I2C_CURRENT_BYTECNT, MIZAR_I2C1_DMA_CTRL, MIZAR_I2C1_SMB_HST_BLOCK_DATA, MIZAR_DMA_CH1_CTRL,
    MIZAR_DMA_CH1_SRC_ADDR, MIZAR_DMA_CH1_DEST_ADDR, MIZAR_DMA_CH1_SRC_XCNT, MIZAR_DMA_CH1_SRC_XMDFY,
    MIZAR_DMA_CH1_DEST_XMDFY, MIZAR_DMA_CH1_SRC_REQ, MIZAR_I2C0_INTR_STS, MIZAR_LSS_SYSREG_RAW_STCR0,
    MIZAR_I2C0_INTR_CLR
};

// No explicit skip list provided for this testcase
const unsigned long skip_registers_test_i2c0_mst_i2c1_slv_dma_st_md[] = { };

#endif // TEST_DEFINE_C
