/*
 * Test: gpio_reg_wr_rd_test
 * Description: Verify GPIO register default reset values and masked write/read behavior across the defined register set using per-register read/write masks and skip lists. Writes six data patterns, reads back with masks, and compares against expected values computed from masks and defaults.
 * Notes:
 *  - VRRW registers skipped per skip_array.
 *  - Default read masks applied clear bit0 (0xFFFFFFFE) in reset-value check.
 *  - When reading default values the DIN value may become 1 automatically if not forced; if we force zero to DIN bit level, SEL may become high causing read mismatch. This is accounted by masking bit0 in reset check.
 *  - soft_reset_chk present but disabled (#ifdef 0) in program.c.
 *  - Register addresses, default values, and masks are resolved via included GPIO headers.
 */

/* Header includes (unchanged) */
#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/* Macros (unchanged) */
#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST_REG_DATA    0x00000000
#define CNT 49

/* Data patterns used in chk_rd_wr() */
unsigned int chk_val[6] = {
    0xFFFFFFFFu, 0xAAAAAAAAu, 0x55555555u, 0xF5F5F5F5u, 0xA5A5A5A5u, 0xFFFF0000u
};

/*
 * Arrays constructed strictly from the impacted registers list (order preserved).
 * Address symbols (MIZAR_*) and mask/default symbols (GPIO_*) are expected to be
 * provided by the included GPIO header files.
 */
const unsigned long int addr_array[CNT] = {
    MIZAR_GPIO_GP0_GPIO_8,
    MIZAR_GPIO_GP0_GPIO_9,
    MIZAR_GPIO_GP0_GPIO_10,
    MIZAR_GPIO_GP0_GPIO_11,
    MIZAR_GPIO_GP0_GPIO_12,
    MIZAR_GPIO_GP0_GPIO_13,
    MIZAR_GPIO_GP0_GPIO_14,
    MIZAR_GPIO_GP0_GPIO_15,
    MIZAR_GPIO_GP0_GPIO_16,
    MIZAR_GPIO_GP0_GPIO_17,
    MIZAR_GPIO_GP0_GPIO_18,
    MIZAR_GPIO_GP0_GPIO_19,
    MIZAR_GPIO_GP0_GPIO_20,
    MIZAR_GPIO_GP0_GPIO_21,
    MIZAR_GPIO_GP0_GPIO_22,
    MIZAR_GPIO_GP0_GPIO_23,
    MIZAR_GPIO_GP0_GPIO_24,
    MIZAR_GPIO_GP0_GPIO_25,
    MIZAR_GPIO_GP0_GPIO_26,
    MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_28,
    MIZAR_GPIO_GP0_GPIO_29,
    MIZAR_GPIO_GP0_GPIO_30,
    MIZAR_GPIO_GP0_GPIO_31,
    MIZAR_GPIO_GP0_GPIO_32,
    MIZAR_GPIO_GP0_GPIO_33,
    MIZAR_GPIO_GP0_GPIO_34,
    MIZAR_GPIO_GP0_GPIO_35,
    MIZAR_GPIO_GP0_GPIO_36,
    MIZAR_GPIO_GP0_GPIO_37,
    MIZAR_GPIO_GP0_GPIO_38,
    MIZAR_GPIO_GP0_GPIO_39,
    MIZAR_GPIO_GPIO_INTR_RAW_STCLR1,
    MIZAR_GPIO_GP0_INTR1_INTR_EN1,
    MIZAR_GPIO_GP0_INTR1_INTR_STS1,
    MIZAR_GPIO_GP0_INTR2_INTR_EN1,
    MIZAR_GPIO_GP0_INTR2_INTR_STS1,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP1,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP2,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP3,
    MIZAR_GPIO_GPIO_IO_CTRL_GROUP4,
    MIZAR_GPIO_GPIO_DOUT_GROUP1,
    MIZAR_GPIO_GPIO_DOUT_GROUP2,
    MIZAR_GPIO_GPIO_DOUT_GROUP3,
    MIZAR_GPIO_GPIO_DOUT_GROUP4,
    MIZAR_GPIO_GPIO_DIN_GROUP1,
    MIZAR_GPIO_GPIO_DIN_GROUP2,
    MIZAR_GPIO_GPIO_DIN_GROUP3,
    MIZAR_GPIO_GPIO_DIN_GROUP4
};

const unsigned int default_value_array[CNT] = {
    GPIO_GP0_GPIO_8_DEFAULT_VAL,
    GPIO_GP0_GPIO_9_DEFAULT_VAL,
    GPIO_GP0_GPIO_10_DEFAULT_VAL,
    GPIO_GP0_GPIO_11_DEFAULT_VAL,
    GPIO_GP0_GPIO_12_DEFAULT_VAL,
    GPIO_GP0_GPIO_13_DEFAULT_VAL,
    GPIO_GP0_GPIO_14_DEFAULT_VAL,
    GPIO_GP0_GPIO_15_DEFAULT_VAL,
    GPIO_GP0_GPIO_16_DEFAULT_VAL,
    GPIO_GP0_GPIO_17_DEFAULT_VAL,
    GPIO_GP0_GPIO_18_DEFAULT_VAL,
    GPIO_GP0_GPIO_19_DEFAULT_VAL,
    GPIO_GP0_GPIO_20_DEFAULT_VAL,
    GPIO_GP0_GPIO_21_DEFAULT_VAL,
    GPIO_GP0_GPIO_22_DEFAULT_VAL,
    GPIO_GP0_GPIO_23_DEFAULT_VAL,
    GPIO_GP0_GPIO_24_DEFAULT_VAL,
    GPIO_GP0_GPIO_25_DEFAULT_VAL,
    GPIO_GP0_GPIO_26_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_28_DEFAULT_VAL,
    GPIO_GP0_GPIO_29_DEFAULT_VAL,
    GPIO_GP0_GPIO_30_DEFAULT_VAL,
    GPIO_GP0_GPIO_31_DEFAULT_VAL,
    GPIO_GP0_GPIO_32_DEFAULT_VAL,
    GPIO_GP0_GPIO_33_DEFAULT_VAL,
    GPIO_GP0_GPIO_34_DEFAULT_VAL,
    GPIO_GP0_GPIO_35_DEFAULT_VAL,
    GPIO_GP0_GPIO_36_DEFAULT_VAL,
    GPIO_GP0_GPIO_37_DEFAULT_VAL,
    GPIO_GP0_GPIO_38_DEFAULT_VAL,
    GPIO_GP0_GPIO_39_DEFAULT_VAL,
    GPIO_GPIO_INTR_RAW_STCLR1_DEFAULT_VAL,
    GPIO_GP0_INTR1_INTR_EN1_DEFAULT_VAL,
    GPIO_GP0_INTR1_INTR_STS1_DEFAULT_VAL,
    GPIO_GP0_INTR2_INTR_EN1_DEFAULT_VAL,
    GPIO_GP0_INTR2_INTR_STS1_DEFAULT_VAL,
    GPIO_GPIO_IO_CTRL_GROUP1_DEFAULT_VAL,
    GPIO_GPIO_IO_CTRL_GROUP2_DEFAULT_VAL,
    GPIO_GPIO_IO_CTRL_GROUP3_DEFAULT_VAL,
    GPIO_GPIO_IO_CTRL_GROUP4_DEFAULT_VAL,
    GPIO_GPIO_DOUT_GROUP1_DEFAULT_VAL,
    GPIO_GPIO_DOUT_GROUP2_DEFAULT_VAL,
    GPIO_GPIO_DOUT_GROUP3_DEFAULT_VAL,
    GPIO_GPIO_DOUT_GROUP4_DEFAULT_VAL,
    GPIO_GPIO_DIN_GROUP1_DEFAULT_VAL,
    GPIO_GPIO_DIN_GROUP2_DEFAULT_VAL,
    GPIO_GPIO_DIN_GROUP3_DEFAULT_VAL,
    GPIO_GPIO_DIN_GROUP4_DEFAULT_VAL
};

const unsigned int read_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_READ_MASK,
    GPIO_GP0_GPIO_9_READ_MASK,
    GPIO_GP0_GPIO_10_READ_MASK,
    GPIO_GP0_GPIO_11_READ_MASK,
    GPIO_GP0_GPIO_12_READ_MASK,
    GPIO_GP0_GPIO_13_READ_MASK,
    GPIO_GP0_GPIO_14_READ_MASK,
    GPIO_GP0_GPIO_15_READ_MASK,
    GPIO_GP0_GPIO_16_READ_MASK,
    GPIO_GP0_GPIO_17_READ_MASK,
    GPIO_GP0_GPIO_18_READ_MASK,
    GPIO_GP0_GPIO_19_READ_MASK,
    GPIO_GP0_GPIO_20_READ_MASK,
    GPIO_GP0_GPIO_21_READ_MASK,
    GPIO_GP0_GPIO_22_READ_MASK,
    GPIO_GP0_GPIO_23_READ_MASK,
    GPIO_GP0_GPIO_24_READ_MASK,
    GPIO_GP0_GPIO_25_READ_MASK,
    GPIO_GP0_GPIO_26_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_28_READ_MASK,
    GPIO_GP0_GPIO_29_READ_MASK,
    GPIO_GP0_GPIO_30_READ_MASK,
    GPIO_GP0_GPIO_31_READ_MASK,
    GPIO_GP0_GPIO_32_READ_MASK,
    GPIO_GP0_GPIO_33_READ_MASK,
    GPIO_GP0_GPIO_34_READ_MASK,
    GPIO_GP0_GPIO_35_READ_MASK,
    GPIO_GP0_GPIO_36_READ_MASK,
    GPIO_GP0_GPIO_37_READ_MASK,
    GPIO_GP0_GPIO_38_READ_MASK,
    GPIO_GP0_GPIO_39_READ_MASK,
    GPIO_GPIO_INTR_RAW_STCLR1_READ_MASK,
    GPIO_GP0_INTR1_INTR_EN1_READ_MASK,
    GPIO_GP0_INTR1_INTR_STS1_READ_MASK,
    GPIO_GP0_INTR2_INTR_EN1_READ_MASK,
    GPIO_GP0_INTR2_INTR_STS1_READ_MASK,
    GPIO_GPIO_IO_CTRL_GROUP1_READ_MASK,
    GPIO_GPIO_IO_CTRL_GROUP2_READ_MASK,
    GPIO_GPIO_IO_CTRL_GROUP3_READ_MASK,
    GPIO_GPIO_IO_CTRL_GROUP4_READ_MASK,
    GPIO_GPIO_DOUT_GROUP1_READ_MASK,
    GPIO_GPIO_DOUT_GROUP2_READ_MASK,
    GPIO_GPIO_DOUT_GROUP3_READ_MASK,
    GPIO_GPIO_DOUT_GROUP4_READ_MASK,
    GPIO_GPIO_DIN_GROUP1_READ_MASK,
    GPIO_GPIO_DIN_GROUP2_READ_MASK,
    GPIO_GPIO_DIN_GROUP3_READ_MASK,
    GPIO_GPIO_DIN_GROUP4_READ_MASK
};

const unsigned int write_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_WRITE_MASK,
    GPIO_GP0_GPIO_9_WRITE_MASK,
    GPIO_GP0_GPIO_10_WRITE_MASK,
    GPIO_GP0_GPIO_11_WRITE_MASK,
    GPIO_GP0_GPIO_12_WRITE_MASK,
    GPIO_GP0_GPIO_13_WRITE_MASK,
    GPIO_GP0_GPIO_14_WRITE_MASK,
    GPIO_GP0_GPIO_15_WRITE_MASK,
    GPIO_GP0_GPIO_16_WRITE_MASK,
    GPIO_GP0_GPIO_17_WRITE_MASK,
    GPIO_GP0_GPIO_18_WRITE_MASK,
    GPIO_GP0_GPIO_19_WRITE_MASK,
    GPIO_GP0_GPIO_20_WRITE_MASK,
    GPIO_GP0_GPIO_21_WRITE_MASK,
    GPIO_GP0_GPIO_22_WRITE_MASK,
    GPIO_GP0_GPIO_23_WRITE_MASK,
    GPIO_GP0_GPIO_24_WRITE_MASK,
    GPIO_GP0_GPIO_25_WRITE_MASK,
    GPIO_GP0_GPIO_26_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_28_WRITE_MASK,
    GPIO_GP0_GPIO_29_WRITE_MASK,
    GPIO_GP0_GPIO_30_WRITE_MASK,
    GPIO_GP0_GPIO_31_WRITE_MASK,
    GPIO_GP0_GPIO_32_WRITE_MASK,
    GPIO_GP0_GPIO_33_WRITE_MASK,
    GPIO_GP0_GPIO_34_WRITE_MASK,
    GPIO_GP0_GPIO_35_WRITE_MASK,
    GPIO_GP0_GPIO_36_WRITE_MASK,
    GPIO_GP0_GPIO_37_WRITE_MASK,
    GPIO_GP0_GPIO_38_WRITE_MASK,
    GPIO_GP0_GPIO_39_WRITE_MASK,
    GPIO_GPIO_INTR_RAW_STCLR1_WRITE_MASK,
    GPIO_GP0_INTR1_INTR_EN1_WRITE_MASK,
    GPIO_GP0_INTR1_INTR_STS1_WRITE_MASK,
    GPIO_GP0_INTR2_INTR_EN1_WRITE_MASK,
    GPIO_GP0_INTR2_INTR_STS1_WRITE_MASK,
    GPIO_GPIO_IO_CTRL_GROUP1_WRITE_MASK,
    GPIO_GPIO_IO_CTRL_GROUP2_WRITE_MASK,
    GPIO_GPIO_IO_CTRL_GROUP3_WRITE_MASK,
    GPIO_GPIO_IO_CTRL_GROUP4_WRITE_MASK,
    GPIO_GPIO_DOUT_GROUP1_WRITE_MASK,
    GPIO_GPIO_DOUT_GROUP2_WRITE_MASK,
    GPIO_GPIO_DOUT_GROUP3_WRITE_MASK,
    GPIO_GPIO_DOUT_GROUP4_WRITE_MASK,
    GPIO_GPIO_DIN_GROUP1_WRITE_MASK,
    GPIO_GPIO_DIN_GROUP2_WRITE_MASK,
    GPIO_GPIO_DIN_GROUP3_WRITE_MASK,
    GPIO_GPIO_DIN_GROUP4_WRITE_MASK
};

/*
 * Skipping rules:
 *  - skip_array: registers to skip for write/read loops (e.g., write-protected or VRRW).
 *  - skip_rst_array: registers to skip for reset-value verification.
 */
const unsigned int skip_array[CNT] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1, /* MIZAR_GPIO_GPIO_INTR_RAW_STCLR1 (write-to-clear) */
    0, /* MIZAR_GPIO_GP0_INTR1_INTR_EN1 */
    0, /* MIZAR_GPIO_GP0_INTR1_INTR_STS1 */
    0, /* MIZAR_GPIO_GP0_INTR2_INTR_EN1 */
    0, /* MIZAR_GPIO_GP0_INTR2_INTR_STS1 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP1 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP2 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP3 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP4 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP1 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP2 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP3 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP4 */
    0, /* MIZAR_GPIO_GPIO_DIN_GROUP1 */
    0, /* MIZAR_GPIO_GPIO_DIN_GROUP2 */
    0, /* MIZAR_GPIO_GPIO_DIN_GROUP3 */
    0  /* MIZAR_GPIO_GPIO_DIN_GROUP4 */
};

const unsigned int skip_rst_array[CNT] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0, /* MIZAR_GPIO_GPIO_INTR_RAW_STCLR1 */
    0, /* MIZAR_GPIO_GP0_INTR1_INTR_EN1 */
    0, /* MIZAR_GPIO_GP0_INTR1_INTR_STS1 */
    0, /* MIZAR_GPIO_GP0_INTR2_INTR_EN1 */
    0, /* MIZAR_GPIO_GP0_INTR2_INTR_STS1 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP1 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP2 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP3 */
    1, /* MIZAR_GPIO_GPIO_IO_CTRL_GROUP4 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP1 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP2 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP3 */
    1, /* MIZAR_GPIO_GPIO_DOUT_GROUP4 */
    1, /* MIZAR_GPIO_GPIO_DIN_GROUP1 */
    1, /* MIZAR_GPIO_GPIO_DIN_GROUP2 */
    1, /* MIZAR_GPIO_GPIO_DIN_GROUP3 */
    1  /* MIZAR_GPIO_GPIO_DIN_GROUP4 */
};
