#include <stdlib.h>
#include <stdio.h>
#include <test_common.h>
#include "pcie.h"

/*
 * Auto-generated by 3_Code_Generation Agent
 * Purpose: Provide meta-defined register arrays and test includes for pcie_enumerate_test
 * Notes:
 * - Headers and macros are included exactly as provided by meta_json.
 * - Impacted register arrays are built strictly from Meta Impacted Registers and RAG mapping.
 * - Skip array is generated from Meta Arrays (none specified), hence empty.
 */

/* Impacted register list (from Meta Impacted Registers) */
const uint32_t impacted_registers[] = {
    mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF,
    mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF
};

const size_t impacted_registers_count = (sizeof(impacted_registers) / sizeof(impacted_registers[0]));

/* Skip registers (none specified in Meta Arrays) */
const uint32_t skip_registers[] = { };
const size_t skip_registers_count = 0u;

/* RAG mapping notes (for reference only; not used as code symbols here):
 * - mizar_PCIE*_DBI_DSP_COHERENCY_CONTROL_3_OFF maps to PF0_PORT_LOGIC COHERENCY_CONTROL_3 (32-bit)
 *   Bit fields used in this test: [11:14], [3:6], [27:30], [19:22]
 */
