#include<i2c/i2c0_def.h>
#include<i2c/i2c1_def.h>
#include<i2c/i2c_offset.h>
#define CNT 86
int data_rd,data_wr,rst_val;


const int addr_array[86]={MIZAR_I2C0_DEV_CTRL,MIZAR_I2C0_TSFR_CTRL,MIZAR_I2C0_SLV_ADDR,MIZAR_I2C0_TGT_SLV_ADDR,MIZAR_I2C0_I2C_MSTR_CODE,MIZAR_I2C0_I2C_BYTE_CNT,MIZAR_I2C0_SF_HCNT,MIZAR_I2C0_SF_LCNT,MIZAR_I2C0_I2C_HS_HCNT,MIZAR_I2C0_I2C_HS_LCNT,MIZAR_I2C0_RIS,MIZAR_I2C0_MASK_INTR,MIZAR_I2C0_INTR_STS,MIZAR_I2C0_INTR_CLR,MIZAR_I2C0_TAS,MIZAR_I2C0_TX_FIFO_THLD,MIZAR_I2C0_RX_FIFO_THLD,MIZAR_I2C0_DMA_CTRL,MIZAR_I2C0_FF,MIZAR_I2C0_TX_FIFO_LVL,MIZAR_I2C0_RX_FIFO_LVL,MIZAR_I2C0_I2C_MSTR_STS,MIZAR_I2C0_I2C_FLTR_SEL,MIZAR_I2C0_I2C_CURRENT_BYTECNT,MIZAR_I2C0_I2C_SMB_SFTRST,MIZAR_I2C0_SMB_HST_STS,MIZAR_I2C0_SMB_HST_CTRL,MIZAR_I2C0_SMB_HST_CMD,MIZAR_I2C0_SMB_HST_DATA0,MIZAR_I2C0_SMB_HST_DATA1,MIZAR_I2C0_SMB_HST_BLOCK_DATA,MIZAR_I2C0_SMB_PEC_DATA,MIZAR_I2C0_SMB_SLAVE_WDATA,MIZAR_I2C0_SMB_SLAVE_CMD,MIZAR_I2C0_SMB_SLAVE_CTS,MIZAR_I2C0_SMB_SLV,MIZAR_I2C0_SMB_NOTIFY_ADDR,MIZAR_I2C0_SMB_NOTIFY_LOW_BYTE,MIZAR_I2C0_SMB_NOTIFY_HIGH_BYTE,MIZAR_I2C0_SMB_DATA_HLDTIME,MIZAR_I2C0_SMB_TIMEOUT_CNT,MIZAR_I2C0_SMB_TMEXT_CNT,MIZAR_I2C0_I2CSMB_DATA_SETUP,MIZAR_I2C1_DEV_CTRL,MIZAR_I2C1_TSFR_CTRL,MIZAR_I2C1_SLV_ADDR,MIZAR_I2C1_TGT_SLV_ADDR,MIZAR_I2C1_I2C_MSTR_CODE,MIZAR_I2C1_I2C_BYTE_CNT,MIZAR_I2C1_SF_HCNT,MIZAR_I2C1_SF_LCNT,MIZAR_I2C1_I2C_HS_HCNT,MIZAR_I2C1_I2C_HS_LCNT,MIZAR_I2C1_RIS,MIZAR_I2C1_MASK_INTR,MIZAR_I2C1_INTR_STS,MIZAR_I2C1_INTR_CLR,MIZAR_I2C1_TAS,MIZAR_I2C1_TX_FIFO_THLD,MIZAR_I2C1_RX_FIFO_THLD,MIZAR_I2C1_DMA_CTRL,MIZAR_I2C1_FF,MIZAR_I2C1_TX_FIFO_LVL,MIZAR_I2C1_RX_FIFO_LVL,MIZAR_I2C1_I2C_MSTR_STS,MIZAR_I2C1_I2C_FLTR_SEL,MIZAR_I2C1_I2C_CURRENT_BYTECNT,MIZAR_I2C1_I2C_SMB_SFTRST,MIZAR_I2C1_SMB_HST_STS,MIZAR_I2C1_SMB_HST_CTRL,MIZAR_I2C1_SMB_HST_CMD,MIZAR_I2C1_SMB_HST_DATA0,MIZAR_I2C1_SMB_HST_DATA1,MIZAR_I2C1_SMB_HST_BLOCK_DATA,MIZAR_I2C1_SMB_PEC_DATA,MIZAR_I2C1_SMB_SLAVE_WDATA,MIZAR_I2C1_SMB_SLAVE_CMD,MIZAR_I2C1_SMB_SLAVE_CTS,MIZAR_I2C1_SMB_SLV,MIZAR_I2C1_SMB_NOTIFY_ADDR,MIZAR_I2C1_SMB_NOTIFY_LOW_BYTE,MIZAR_I2C1_SMB_NOTIFY_HIGH_BYTE,MIZAR_I2C1_SMB_DATA_HLDTIME,MIZAR_I2C1_SMB_TIMEOUT_CNT,MIZAR_I2C1_SMB_TMEXT_CNT,MIZAR_I2C1_I2CSMB_DATA_SETUP,};


const int default_value_array[86]={I2C_DEV_CTRL_DEFAULT_VAL,I2C_TSFR_CTRL_DEFAULT_VAL,I2C_SLV_ADDR_DEFAULT_VAL,I2C_TGT_SLV_ADDR_DEFAULT_VAL,I2C_I2C_MSTR_CODE_DEFAULT_VAL,I2C_I2C_BYTE_CNT_DEFAULT_VAL,I2C_SF_HCNT_DEFAULT_VAL,I2C_SF_LCNT_DEFAULT_VAL,I2C_I2C_HS_HCNT_DEFAULT_VAL,I2C_I2C_HS_LCNT_DEFAULT_VAL,I2C_RIS_DEFAULT_VAL,I2C_MASK_INTR_DEFAULT_VAL,I2C_INTR_STS_DEFAULT_VAL,I2C_INTR_CLR_DEFAULT_VAL,I2C_TAS_DEFAULT_VAL,I2C_TX_FIFO_THLD_DEFAULT_VAL,I2C_RX_FIFO_THLD_DEFAULT_VAL,I2C_DMA_CTRL_DEFAULT_VAL,I2C_FF_DEFAULT_VAL,I2C_TX_FIFO_LVL_DEFAULT_VAL,I2C_RX_FIFO_LVL_DEFAULT_VAL,I2C_I2C_MSTR_STS_DEFAULT_VAL,I2C_I2C_FLTR_SEL_DEFAULT_VAL,I2C_I2C_CURRENT_BYTECNT_DEFAULT_VAL,I2C_I2C_SMB_SFTRST_DEFAULT_VAL,I2C_SMB_HST_STS_DEFAULT_VAL,I2C_SMB_HST_CTRL_DEFAULT_VAL,I2C_SMB_HST_CMD_DEFAULT_VAL,I2C_SMB_HST_DATA0_DEFAULT_VAL,I2C_SMB_HST_DATA1_DEFAULT_VAL,I2C_SMB_HST_BLOCK_DATA_DEFAULT_VAL,I2C_SMB_PEC_DATA_DEFAULT_VAL,I2C_SMB_SLAVE_WDATA_DEFAULT_VAL,I2C_SMB_SLAVE_CMD_DEFAULT_VAL,I2C_SMB_SLAVE_CTS_DEFAULT_VAL,I2C_SMB_SLV_DEFAULT_VAL,I2C_SMB_NOTIFY_ADDR_DEFAULT_VAL,I2C_SMB_NOTIFY_LOW_BYTE_DEFAULT_VAL,I2C_SMB_NOTIFY_HIGH_BYTE_DEFAULT_VAL,I2C_SMB_DATA_HLDTIME_DEFAULT_VAL,I2C_SMB_TIMEOUT_CNT_DEFAULT_VAL,I2C_SMB_TMEXT_CNT_DEFAULT_VAL,I2C_I2CSMB_DATA_SETUP_DEFAULT_VAL,};


const int read_mask_array[86]={I2C_DEV_CTRL_READ_MASK,I2C_TSFR_CTRL_READ_MASK,I2C_SLV_ADDR_READ_MASK,I2C_TGT_SLV_ADDR_READ_MASK,I2C_I2C_MSTR_CODE_READ_MASK,I2C_I2C_BYTE_CNT_READ_MASK,I2C_SF_HCNT_READ_MASK,I2C_SF_LCNT_READ_MASK,I2C_I2C_HS_HCNT_READ_MASK,I2C_I2C_HS_LCNT_READ_MASK,I2C_RIS_READ_MASK,I2C_MASK_INTR_READ_MASK,I2C_INTR_STS_READ_MASK,I2C_INTR_CLR_READ_MASK,I2C_TAS_READ_MASK,I2C_TX_FIFO_THLD_READ_MASK,I2C_RX_FIFO_THLD_READ_MASK,I2C_DMA_CTRL_READ_MASK,I2C_FF_READ_MASK,I2C_TX_FIFO_LVL_READ_MASK,I2C_RX_FIFO_LVL_READ_MASK,I2C_I2C_MSTR_STS_READ_MASK,I2C_I2C_FLTR_SEL_READ_MASK,I2C_I2C_CURRENT_BYTECNT_READ_MASK,I2C_I2C_SMB_SFTRST_READ_MASK,I2C_SMB_HST_STS_READ_MASK,I2C_SMB_HST_CTRL_READ_MASK,I2C_SMB_HST_CMD_READ_MASK,I2C_SMB_HST_DATA0_READ_MASK,I2C_SMB_HST_DATA1_READ_MASK,I2C_SMB_HST_BLOCK_DATA_READ_MASK,I2C_SMB_PEC_DATA_READ_MASK,I2C_SMB_SLAVE_WDATA_READ_MASK,I2C_SMB_SLAVE_CMD_READ_MASK,I2C_SMB_SLAVE_CTS_READ_MASK,I2C_SMB_SLV_READ_MASK,I2C_SMB_NOTIFY_ADDR_READ_MASK,I2C_SMB_NOTIFY_LOW_BYTE_READ_MASK,I2C_SMB_NOTIFY_HIGH_BYTE_READ_MASK,I2C_SMB_DATA_HLDTIME_READ_MASK,I2C_SMB_TIMEOUT_CNT_READ_MASK,I2C_SMB_TMEXT_CNT_READ_MASK,I2C_I2CSMB_DATA_SETUP_READ_MASK,};


const int write_mask_array[43]={I2C_DEV_CTRL_WRITE_MASK,I2C_TSFR_CTRL_WRITE_MASK,I2C_SLV_ADDR_WRITE_MASK,I2C_TGT_SLV_ADDR_WRITE_MASK,I2C_I2C_MSTR_CODE_WRITE_MASK,I2C_I2C_BYTE_CNT_WRITE_MASK,I2C_SF_HCNT_WRITE_MASK,I2C_SF_LCNT_WRITE_MASK,I2C_I2C_HS_HCNT_WRITE_MASK,I2C_I2C_HS_LCNT_WRITE_MASK,I2C_RIS_WRITE_MASK,I2C_MASK_INTR_WRITE_MASK,I2C_INTR_STS_WRITE_MASK,I2C_INTR_CLR_WRITE_MASK,I2C_TAS_WRITE_MASK,I2C_TX_FIFO_THLD_WRITE_MASK,I2C_RX_FIFO_THLD_WRITE_MASK,I2C_DMA_CTRL_WRITE_MASK,I2C_FF_WRITE_MASK,I2C_TX_FIFO_LVL_WRITE_MASK,I2C_RX_FIFO_LVL_WRITE_MASK,I2C_I2C_MSTR_STS_WRITE_MASK,I2C_I2C_FLTR_SEL_WRITE_MASK,I2C_I2C_CURRENT_BYTECNT_WRITE_MASK,I2C_I2C_SMB_SFTRST_WRITE_MASK,I2C_SMB_HST_STS_WRITE_MASK,I2C_SMB_HST_CTRL_WRITE_MASK,I2C_SMB_HST_CMD_WRITE_MASK,I2C_SMB_HST_DATA0_WRITE_MASK,I2C_SMB_HST_DATA1_WRITE_MASK,I2C_SMB_HST_BLOCK_DATA_WRITE_MASK,I2C_SMB_PEC_DATA_WRITE_MASK,I2C_SMB_SLAVE_WDATA_WRITE_MASK,I2C_SMB_SLAVE_CMD_WRITE_MASK,I2C_SMB_SLAVE_CTS_WRITE_MASK,I2C_SMB_SLV_WRITE_MASK,I2C_SMB_NOTIFY_ADDR_WRITE_MASK,I2C_SMB_NOTIFY_LOW_BYTE_WRITE_MASK,I2C_SMB_NOTIFY_HIGH_BYTE_WRITE_MASK,I2C_SMB_DATA_HLDTIME_WRITE_MASK,I2C_SMB_TIMEOUT_CNT_WRITE_MASK,I2C_SMB_TMEXT_CNT_WRITE_MASK,I2C_I2CSMB_DATA_SETUP_WRITE_MASK,};


const int skip_array[43]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,};

void dma_config(
		unsigned int ch_num,
		unsigned int src_addr,
		unsigned int dst_addr,
		unsigned int src_xcnt,
		unsigned int tx_rx,
		unsigned int tc_intr_en,unsigned src_req,unsigned int spi_mst) {

	//unsigned int src_req,dmac_base_addr;
	unsigned int ctrl_reg, src_addr_reg, dest_addr_reg, src_xcnt_reg;
  	unsigned int src_xmdf_reg, dest_xmdf_reg, src_req_reg,ch_en_reg,tc_en_reg;
	//src_req = get_spi_dma_src_req(spi_inst,tx_rx);
	//dmac_base_addr = get_spi_dma_base_addr(spi_inst);

switch(ch_num)
  {
    case 0 :  	ctrl_reg      = MIZAR_DMA_CH0_CTRL ; 
                src_addr_reg  = MIZAR_DMA_CH0_SRC_ADDR; 
                dest_addr_reg = MIZAR_DMA_CH0_DEST_ADDR;
                src_xcnt_reg  = MIZAR_DMA_CH0_SRC_XCNT;
                src_xmdf_reg  = MIZAR_DMA_CH0_SRC_XMDFY;
                dest_xmdf_reg = MIZAR_DMA_CH0_DEST_XMDFY;
                src_req_reg   = MIZAR_DMA_CH0_SRC_REQ;
                break;
   case 1 :  	ctrl_reg      = MIZAR_DMA_CH1_CTRL ; 
                src_addr_reg  = MIZAR_DMA_CH1_SRC_ADDR; 
                dest_addr_reg = MIZAR_DMA_CH1_DEST_ADDR;
                src_xcnt_reg  = MIZAR_DMA_CH1_SRC_XCNT;
                src_xmdf_reg  = MIZAR_DMA_CH1_SRC_XMDFY;
                dest_xmdf_reg = MIZAR_DMA_CH1_DEST_XMDFY;
                src_req_reg   = MIZAR_DMA_CH1_SRC_REQ;
                break;
   case 2:  	ctrl_reg      = MIZAR_DMA_CH2_CTRL ; 
                src_addr_reg  = MIZAR_DMA_CH2_SRC_ADDR; 
                dest_addr_reg = MIZAR_DMA_CH2_DEST_ADDR;
                src_xcnt_reg  = MIZAR_DMA_CH2_SRC_XCNT;
                src_xmdf_reg  = MIZAR_DMA_CH2_SRC_XMDFY;
                dest_xmdf_reg = MIZAR_DMA_CH2_DEST_XMDFY;
                src_req_reg   = MIZAR_DMA_CH2_SRC_REQ;
                break;
    }
	//Channel Enable Register
	ch_en_reg = MIZAR_DMA_DMA_CH_EN;

	//Enable PDMA for m2p transfer
	printf("Writing into cntrl reg 0\n");
	//if(spi_mst == 0) write_reg(ctrl_reg,0x80a8728);  // master or slave mode
//	else write_reg(ctrl_reg,0x8028028);/*write_reg(ctrl_reg,0x8225b28);*/
	printf("Writing the source address channel0\n");
	write_reg(src_addr_reg,src_addr);

	printf("Writing the destination address\n");
	write_reg(dest_addr_reg,dst_addr);

	printf("Writing the source x-count reg\n");
	write_reg(src_xcnt_reg,src_xcnt);
        
        if(tx_rx == 0) {
                write_reg(ctrl_reg,0x80a8728);
		printf("Write 4 into source x-modify reg\n");
		write_reg(src_xmdf_reg,0x4);
		printf("Write 0 into dest x-modify reg\n");
		write_reg(dest_xmdf_reg,0x0);
        } else if(tx_rx == 1) {
                write_reg(ctrl_reg,0x80a4728);
		printf("Write 0 into source x-modify reg\n");
		write_reg(src_xmdf_reg,0x0);
		printf("Write 4 into dest x-modify reg\n");
		write_reg(dest_xmdf_reg,0x4);
        }

        write_reg(src_req_reg,src_req);

        
	//Terminal Count intrpt En
	tc_en_reg = MIZAR_DMA_TC_INTR_EN; 
	if(tc_intr_en) write_reg(tc_en_reg,1<<ch_num);
	//Enabling Channel
	write_reg(ch_en_reg,1<<ch_num);

}

void dma_disable() {

	//unsigned int dmac_base_addr;
  	unsigned int ch_en_reg;
	//dmac_base_addr = get_spi_dma_base_addr(spi_inst);
	//Channel Enable Register
	ch_en_reg = MIZAR_DMA_DMA_CH_EN;
        while(read_reg(ch_en_reg))
        {
         printf("Waiting for DMA Transfers to be done\n");
         wait_on(100);
        }
}

