#ifndef TEST_DEFINE_C_GUARD
#define TEST_DEFINE_C_GUARD

// Auto-generated for testcase: gpio_reg_wr_rd_test
// Generated folder timestamp tag: GPIO_Code_1610_20260521

// Includes from Meta Headers (unchanged)
#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include "test_define.c"
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

// Macros from Meta Macros (unchanged)
#define CNT 49
#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST_REG_DATA 0x00000000

// Arrays from Meta Impacted Registers and Meta Arrays
// Note: Arrays are sized to CNT as provided in Meta Macros. Indices beyond the
// explicitly listed impacted registers are marked as skipped in skip arrays to
// preserve sequence without introducing new registers.

// Address array
unsigned int addr_array[CNT] = {
    MIZAR_GPIO_GP0_GPIO_8,
    MIZAR_GPIO_GP0_GPIO_9,
    MIZAR_GPIO_GP0_GPIO_10,
    MIZAR_GPIO_GP0_GPIO_11,
    MIZAR_GPIO_GP0_GPIO_12,
    MIZAR_GPIO_GP0_GPIO_13,
    MIZAR_GPIO_GP0_GPIO_14,
    MIZAR_GPIO_GP0_GPIO_15,
    MIZAR_GPIO_GP0_GPIO_16,
    MIZAR_GPIO_GP0_GPIO_17,
    MIZAR_GPIO_GP0_GPIO_18,
    MIZAR_GPIO_GP0_GPIO_19,
    MIZAR_GPIO_GP0_GPIO_20,
    MIZAR_GPIO_GP0_GPIO_21,
    MIZAR_GPIO_GP0_GPIO_22,
    MIZAR_GPIO_GP0_GPIO_23,
    MIZAR_GPIO_GP0_GPIO_24,
    MIZAR_GPIO_GP0_GPIO_25,
    MIZAR_GPIO_GP0_GPIO_26,
    MIZAR_GPIO_GP0_GPIO_27,
    // Duplicate last impacted register for remaining indices; these will be skipped
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27,
    MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27, MIZAR_GPIO_GP0_GPIO_27
};

// Default value array
unsigned int default_value_array[CNT] = {
    GPIO_GP0_GPIO_8_DEFAULT_VAL,
    GPIO_GP0_GPIO_9_DEFAULT_VAL,
    GPIO_GP0_GPIO_10_DEFAULT_VAL,
    GPIO_GP0_GPIO_11_DEFAULT_VAL,
    GPIO_GP0_GPIO_12_DEFAULT_VAL,
    GPIO_GP0_GPIO_13_DEFAULT_VAL,
    GPIO_GP0_GPIO_14_DEFAULT_VAL,
    GPIO_GP0_GPIO_15_DEFAULT_VAL,
    GPIO_GP0_GPIO_16_DEFAULT_VAL,
    GPIO_GP0_GPIO_17_DEFAULT_VAL,
    GPIO_GP0_GPIO_18_DEFAULT_VAL,
    GPIO_GP0_GPIO_19_DEFAULT_VAL,
    GPIO_GP0_GPIO_20_DEFAULT_VAL,
    GPIO_GP0_GPIO_21_DEFAULT_VAL,
    GPIO_GP0_GPIO_22_DEFAULT_VAL,
    GPIO_GP0_GPIO_23_DEFAULT_VAL,
    GPIO_GP0_GPIO_24_DEFAULT_VAL,
    GPIO_GP0_GPIO_25_DEFAULT_VAL,
    GPIO_GP0_GPIO_26_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL,
    // Duplicate last impacted macro for remaining indices; these will be skipped
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL,
    GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL, GPIO_GP0_GPIO_27_DEFAULT_VAL
};

// Read mask array
unsigned int read_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_READ_MASK,
    GPIO_GP0_GPIO_9_READ_MASK,
    GPIO_GP0_GPIO_10_READ_MASK,
    GPIO_GP0_GPIO_11_READ_MASK,
    GPIO_GP0_GPIO_12_READ_MASK,
    GPIO_GP0_GPIO_13_READ_MASK,
    GPIO_GP0_GPIO_14_READ_MASK,
    GPIO_GP0_GPIO_15_READ_MASK,
    GPIO_GP0_GPIO_16_READ_MASK,
    GPIO_GP0_GPIO_17_READ_MASK,
    GPIO_GP0_GPIO_18_READ_MASK,
    GPIO_GP0_GPIO_19_READ_MASK,
    GPIO_GP0_GPIO_20_READ_MASK,
    GPIO_GP0_GPIO_21_READ_MASK,
    GPIO_GP0_GPIO_22_READ_MASK,
    GPIO_GP0_GPIO_23_READ_MASK,
    GPIO_GP0_GPIO_24_READ_MASK,
    GPIO_GP0_GPIO_25_READ_MASK,
    GPIO_GP0_GPIO_26_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK,
    // Duplicate last impacted macro for remaining indices; these will be skipped
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK,
    GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK, GPIO_GP0_GPIO_27_READ_MASK
};

// Write mask array
unsigned int write_mask_array[CNT] = {
    GPIO_GP0_GPIO_8_WRITE_MASK,
    GPIO_GP0_GPIO_9_WRITE_MASK,
    GPIO_GP0_GPIO_10_WRITE_MASK,
    GPIO_GP0_GPIO_11_WRITE_MASK,
    GPIO_GP0_GPIO_12_WRITE_MASK,
    GPIO_GP0_GPIO_13_WRITE_MASK,
    GPIO_GP0_GPIO_14_WRITE_MASK,
    GPIO_GP0_GPIO_15_WRITE_MASK,
    GPIO_GP0_GPIO_16_WRITE_MASK,
    GPIO_GP0_GPIO_17_WRITE_MASK,
    GPIO_GP0_GPIO_18_WRITE_MASK,
    GPIO_GP0_GPIO_19_WRITE_MASK,
    GPIO_GP0_GPIO_20_WRITE_MASK,
    GPIO_GP0_GPIO_21_WRITE_MASK,
    GPIO_GP0_GPIO_22_WRITE_MASK,
    GPIO_GP0_GPIO_23_WRITE_MASK,
    GPIO_GP0_GPIO_24_WRITE_MASK,
    GPIO_GP0_GPIO_25_WRITE_MASK,
    GPIO_GP0_GPIO_26_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK,
    // Duplicate last impacted macro for remaining indices; these will be skipped
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK,
    GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK, GPIO_GP0_GPIO_27_WRITE_MASK
};

// Skip arrays (extracted from Meta Arrays; indices beyond 20 are set to 1 to skip)
unsigned int skip_array[CNT] = {
    // First 20 from Meta: all zeros
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    // Remaining indices skipped
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1
};

unsigned int skip_rst_array[CNT] = {
    // First 20 from Meta: all zeros
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    // Remaining indices skipped
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1
};

#endif // TEST_DEFINE_C_GUARD
