import json, re, os, io, zipfile
from datetime import datetime, timezone, timedelta
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.worksheet.datavalidation import DataValidation

# Embedded FULL_JSON_STRUCTURE (provided input) - Do NOT modify keys or values
FULL_JSON = [
  {
    "Index": 1,
    "SS / Module": "GPIO",
    "Feature": "Negative edge interrupt enable",
    "Test Case Name": "test_gpio_nedge_random_pads_en",
    "Test Description": "Configure random GPIO pins 8–39 for input with negative-edge interrupt, enable group interrupt, generate a falling edge via stimulus, and validate DIN, raw interrupt, group status, and clear sequences including system raw status.",
    "Speed": "NA",
    "Mode": "ISR",
    "Memory Start Offset": "0xA0243ffc",
    "Memory End Offset": "NA",
    "Remarks": "Uses GPIO block 0 or 1 (GIC IRQ 87 or 88). System interrupt enabled via MIZAR_LSS_SYSREG_INTR_EN1. Falling edge stimulus generated by writes to 0xA0243ffc. Tests random unique pads mapped to GPIOs 8–39. Interrupt raw status clear via per‑pin register write with the 16th bit set.",
    "Test Steps / Procedure": "Enable SYSREG/GIC; unique random pads; configure per-pin 0x00140000; enable group bit; generate falling edge via ~(1<<pad); ISR validates and clears per-pin/group/SYSREG.",
    "Impacted Registers": "MIZAR_LSS_SYSREG_INTR_EN1, MIZAR_GPIO_GP0_GPIO_8.., MIZAR_GPIO_GP0_INTR1_INTR_EN1, MIZAR_GPIO_GP0_INTR1_INTR_STS1, MIZAR_LSS_SYSREG_RAW_STCR1",
    "Validation / Acceptance Criteria": "DIN bit=1; raw bit=1; group bit set; after clear: per-pin=0x100001 and group=0; SYSREG raw cleared",
    "Code Generation (Required / Not)": "",
    "Hidden_Test_Case_Name": "test_gpio_nedge_random_pads_en"
  },
  {
    "Index": 2,
    "SS / Module": "GPIO",
    "Feature": "Interrupts can be generated based on negative edge detection at GPIO input",
    "Test Case Name": "test_gpio_nedge_walking_zeros_pattern",
    "Test Description": "Verify negative-edge interrupt behavior across GPIO pins using a walking-zeros stimulus pattern, enabling per‑pin negative-edge detection, group interrupts, and validating per‑pin, group, and system clear operations via the ISR.",
    "Speed": "NA",
    "Mode": "ISR",
    "Memory Start Offset": "0xA0243ffc",
    "Memory End Offset": "NA",
    "Remarks": "Stimulus toggled via 0xA0243ffc with walking zeros across pins 8–39; all group interrupts enabled; per-pin clear via 0x00110001.",
    "Test Steps / Procedure": "Enable SYSREG/GIC; configure per-pin negedge detects; set IO_CTRL groups; enable all group interrupts; for each pin: drive falling edge with walking-zeros; in ISR validate per-pin DIN/raw, group bit, clear per-pin and verify group=0; clear SYSREG raw.",
    "Impacted Registers": "IO_CTRL_GROUP1..4, MIZAR_GPIO_GP0_GPIO_8.., GP0_INTR1_INTR_EN1, GP0_INTR1_INTR_STS1, MIZAR_LSS_SYSREG_RAW_STCR1",
    "Validation / Acceptance Criteria": "Per-pin DIN and raw set, group set; after per-pin clear: per-pin=0x100001 and group=0; SYSREG raw cleared",
    "Code Generation (Required / Not)": "",
    "Hidden_Test_Case_Name": "test_gpio_nedge_walking_zeros_pattern"
  },
  {
    "Index": 3,
    "SS / Module": "GPIO",
    "Feature": "Interrupts can be generated based on negative edge detection at GPIO input",
    "Test Case Name": "test_gpio_negedge_intr_en",
    "Test Description": "Validate negative-edge interrupt by configuring input+negedge per-pin, enabling group bit, generating falling edge, and validating/clearing per-pin, group, and system status in ISR.",
    "Speed": "NA",
    "Mode": "ISR",
    "Memory Start Offset": "0xA0243ffc",
    "Memory End Offset": "NA",
    "Remarks": "Per-pin config value 0x00140000; per-pin clear value 0x00110001; group/RAW clears verified.",
    "Test Steps / Procedure": "Enable SYSREG/GIC; for each pin: program 0x00140000; enable its group bit; generate falling edge via ~(1<<i); in ISR validate DIN/raw/group; clear per-pin and verify group=0; clear SYSREG raw; clear GIC.",
    "Impacted Registers": "MIZAR_GPIO_GP0_GPIO_8.., GP0_INTR1_INTR_EN1, GP0_INTR1_INTR_STS1, MIZAR_LSS_SYSREG_RAW_STCR1",
    "Validation / Acceptance Criteria": "DIN=1; raw=1; group bit set; after clear: per-pin=0x100001; group=0",
    "Code Generation (Required / Not)": "",
    "Hidden_Test_Case_Name": "test_gpio_negedge_intr_en"
  },
  {
    "Index": 4,
    "SS / Module": "GPIO",
    "Feature": "doe field common io mode control register (Group IO control) along with mask bits",
    "Test Case Name": "test_gpio_op_mode_all_pad_en",
    "Test Description": "Verify output mode across GPIO pads by driving high and low values per pin and verifying the observed pad state matches the driven values.",
    "Speed": "NA",
    "Mode": "NA",
    "Memory Start Offset": "0xA0243ffc",
    "Memory End Offset": "NA",
    "Remarks": "Group IO control sets output mode for GPIOs 8–39; pad status read from 0xA0243ffc.",
    "Test Steps / Procedure": "Enable SYSREG/GIC; program IO_CTRL_GROUP1..4 to output mode; for each pin: drive high then low via per-pin register; check pad value; no ISR expected.",
    "Impacted Registers": "MIZAR_GPIO_GPIO_IO_CTRL_GROUP1..4, MIZAR_GPIO_GP0_GPIO_8..",
    "Validation / Acceptance Criteria": "Pad reads high after driving high and low after driving low; no unexpected interrupts",
    "Code Generation (Required / Not)": "",
    "Hidden_Test_Case_Name": "test_gpio_op_mode_all_pad_en"
  }
]

# Configuration
META_COLUMNS = [
    'Hidden_Test_Case_Name',
    'Hidden_Test_Description',
    'Hidden_Remarks',
    'Hidden_Test_Steps_Procedure',
    'Hidden_Impacted_Registers',
    'Hidden_Validation_Acceptance_Criteria',
]
MAIN_ORDER = [
    'Index',
    'SS / Module',
    'Feature',
    'Test Case Name',
    'Test Description',
    'Speed',
    'Mode',
    'Memory Start Offset',
    'Memory End Offset',
    'Remarks',
    'Test Steps / Procedure',
    'Impacted Registers',
    'Validation / Acceptance Criteria',
    'Code Generation (Required / Not)'
]

# Helpers
thin = Side(border_style='thin', color='000000')
BORDER_THIN = Border(left=thin, right=thin, top=thin, bottom=thin)
HEADER_FILL = PatternFill(fill_type='solid', start_color='4472C4', end_color='4472C4')
HEADER_FONT = Font(bold=True, color='FFFFFF')
CENTER = Alignment(horizontal='center', vertical='center', wrap_text=False)
CENTER_WRAP = Alignment(horizontal='center', vertical='center', wrap_text=True)
LEFT_TOP_WRAP = Alignment(horizontal='left', vertical='top', wrap_text=True)
LEFT_TOP = Alignment(horizontal='left', vertical='top', wrap_text=False)
RIGHT_TOP = Alignment(horizontal='right', vertical='top', wrap_text=False)


def validate_json(data):
    if not isinstance(data, list) or not data:
        raise ValueError('JSON input must be a non-empty array of objects')
    for i, rec in enumerate(data):
        if not isinstance(rec, dict):
            raise ValueError(f'Element at index {i} is not an object')


def compute_union_keys_preserve_order(data):
    seen = []
    sset = set()
    for rec in data:
        for k in rec.keys():
            if k not in sset:
                sset.add(k)
                seen.append(k)
    return seen


def numberify(text):
    if text is None:
        return ''
    s = str(text)
    parts = [p.strip() for p in re.split(r'[\n;]+', s) if p.strip()]
    if not parts:
        return s
    return "\n".join(f"{i+1}. {p}" for i, p in enumerate(parts))


def autosize(ws):
    from openpyxl.utils import get_column_letter
    dims = {}
    for r in ws.rows:
        for c in r:
            if c.value is None:
                val_len = 0
            else:
                val_len = len(str(c.value))
            dims[c.column] = max(dims.get(c.column, 0), val_len)
    for col_idx, width in dims.items():
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max(width + 2, 10), 80)


def apply_borders(ws):
    for row in ws.iter_rows(min_row=1, max_row=ws.max_row, min_col=1, max_col=ws.max_column):
        for cell in row:
            cell.border = BORDER_THIN


def main():
    validate_json(FULL_JSON)

    # Phase 1 — JSON to Excel (staging on 'Data')
    keys_union = compute_union_keys_preserve_order(FULL_JSON)
    wb = Workbook()
    ws = wb.active
    ws.title = 'Data'

    # Headers
    for j, key in enumerate(keys_union, start=1):
        cell = ws.cell(row=1, column=j, value=key)
        cell.font = HEADER_FONT
        cell.alignment = CENTER
        cell.fill = HEADER_FILL

    # Rows
    for i, rec in enumerate(FULL_JSON, start=2):
        for j, key in enumerate(keys_union, start=1):
            ws.cell(row=i, column=j, value=rec.get(key, ''))

    # Base formatting
    ws.freeze_panes = 'A2'
    autosize(ws)
    apply_borders(ws)

    # Phase 2 — Meta sheet
    ws_meta = wb.create_sheet('Meta_data_sheet')
    # Write META headers
    for j, key in enumerate(META_COLUMNS, start=1):
        cell = ws_meta.cell(row=1, column=j, value=key)
        cell.font = HEADER_FONT
        cell.alignment = CENTER
        cell.fill = HEADER_FILL
    # Rows
    for i, rec in enumerate(FULL_JSON, start=2):
        for j, key in enumerate(META_COLUMNS, start=1):
            ws_meta.cell(row=i, column=j, value=rec.get(key, ''))
    # Very hidden
    ws_meta.sheet_state = 'veryHidden'

    # Phase 2 — Normalize main sheet on the SAME worksheet
    # Remove META columns
    header_row = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
    meta_indices = [header_row.index(k) + 1 for k in META_COLUMNS if k in header_row]
    for idx in sorted(meta_indices, reverse=True):
        ws.delete_cols(idx)
    # Reorder to MAIN_ORDER
    # Build a mapping from current headers to column indices
    header_row = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
    # Ensure all MAIN_ORDER headers exist (fill columns if missing)
    for k in MAIN_ORDER:
        if k not in header_row:
            header_row.append(k)
            ws.cell(row=1, column=len(header_row), value=k)
            for r in range(2, ws.max_row + 1):
                ws.cell(row=r, column=len(header_row), value='')
    # Now reorder columns by reconstructing into a new grid in-place (copy values)
    new_cols = []
    for k in MAIN_ORDER:
        col_idx = [i+1 for i, name in enumerate(header_row) if name == k][0]
        col_vals = [ws.cell(row=r, column=col_idx).value for r in range(1, ws.max_row + 1)]
        new_cols.append((k, col_vals))
    # Overwrite sheet with reordered columns
    for c_idx, (k, col_vals) in enumerate(new_cols, start=1):
        for r_idx, val in enumerate(col_vals, start=1):
            ws.cell(row=r_idx, column=c_idx, value=val)
    # Trim any extra columns beyond MAIN_ORDER
    if ws.max_column > len(MAIN_ORDER):
        ws.delete_cols(len(MAIN_ORDER) + 1, ws.max_column - len(MAIN_ORDER))

    # Rename sheet to TestPlan (mandatory)
    ws.title = 'TestPlan'

    # Strict formatting on TestPlan
    # Header styling already applied, ensure alignment and fill
    for c in range(1, ws.max_column + 1):
        cell = ws.cell(row=1, column=c)
        cell.font = HEADER_FONT
        cell.alignment = CENTER
        cell.fill = HEADER_FILL
    # Data rows alignment
    headers = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
    idx_col = headers.index('Index') + 1 if 'Index' in headers else None
    wrap_cols = set([
        headers.index('Test Description') + 1,
        headers.index('Remarks') + 1,
        headers.index('Test Steps / Procedure') + 1,
        headers.index('Validation / Acceptance Criteria') + 1,
    ])

    # Numbering inside cells for two long-text columns
    def transform_cell_value(cname, value):
        if cname in ('Test Steps / Procedure', 'Validation / Acceptance Criteria'):
            return numberify(value)
        return value

    for r in range(2, ws.max_row + 1):
        for c in range(1, ws.max_column + 1):
            h = headers[c - 1]
            cell = ws.cell(row=r, column=c)
            cell.value = transform_cell_value(h, cell.value)
            if c in wrap_cols:
                cell.alignment = LEFT_TOP_WRAP
            else:
                if idx_col and c == idx_col:
                    cell.alignment = CENTER
                else:
                    cell.alignment = LEFT_TOP

    autosize(ws)
    apply_borders(ws)

    # Data validation ONLY on Code Generation (Required / Not)
    if 'Code Generation (Required / Not)' in headers:
        cg_col = headers.index('Code Generation (Required / Not)') + 1
        dv = DataValidation(type='list', formula1='"Required,Blank,Not Required"', allow_blank=True, showDropDown=True)
        ws.add_data_validation(dv)
        dv_range = f"{ws.cell(row=2, column=cg_col).coordinate}:{ws.cell(row=ws.max_row, column=cg_col).coordinate}"
        dv.add(dv_range)

    # Safety check: only TestPlan and Meta_data_sheet should exist
    names = [s.title for s in wb.worksheets]
    if 'Data' in names:
        # Attempt to remove any leftover 'Data'
        try:
            wb.remove(wb['Data'])
        except Exception:
            raise RuntimeError('Validation failed: Data sheet still present')

    # Phase 3 — Save and validate as true XLSX OOXML
    ist = timezone(timedelta(hours=5, minutes=30))
    now_ist = datetime.now(ist)
    ts = now_ist.strftime('%Y%m%d_%H%M%S')
    ip_name = os.environ.get('IP_NAME', 'IP')
    out_dir = os.environ.get('OUTPUT_DIR', 'Test_Output/GPIO/TestPlan')
    os.makedirs(out_dir, exist_ok=True)
    filename = f"{ip_name}_TestPlan_{ts}.xlsx"
    out_path = os.path.join(out_dir, filename)

    wb.save(out_path)

    # OOXML validation (ZIP structure)
    with open(out_path, 'rb') as f:
        data = f.read()
    try:
        with zipfile.ZipFile(io.BytesIO(data), 'r') as z:
            namelist = z.namelist()
            required = {'[Content_Types].xml', 'xl/workbook.xml'}
            if not required.issubset(set(namelist)):
                raise RuntimeError('XLSX validation failed: missing OOXML parts')
    except zipfile.BadZipFile as e:
        raise RuntimeError('XLSX validation failed: not a valid zip') from e

    # Write generated path for the workflow commit step
    with open('generated_path.txt', 'w') as fp:
        fp.write(out_path)

if __name__ == '__main__':
    main()
