#ifndef TEST_DEFINE_C_
#define TEST_DEFINE_C_

#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include "test_define.c"
#include <pcie.h>

#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST_REG_DATA 0x00000000
#define CNT 775

/* Impacted Registers (mapped via RAG where available) */
const unsigned long int addr_array[] = {
    mizar_PCIE1_DBI_DSP_TYPE1_DEV_ID_VEND_ID_REG,
    mizar_PCIE1_DBI_DSP_TYPE1_STATUS_COMMAND_REG,
    mizar_PCIE1_DBI_DSP_TYPE1_CLASS_CODE_REV_ID_REG,
    mizar_PCIE1_DBI_DSP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG,
    mizar_PCIE1_DBI_DSP_BAR0_REG,
    mizar_PCIE1_DBI_DSP_CAP_ID_NXT_PTR_REG,
    mizar_PCIE1_DBI_DSP_DEVICE_CONTROL_DEVICE_STATUS,
    mizar_PCIE1_DBI_DSP_PL_DEBUG1_OFF
};

/* Default values, read masks, and write masks are expected to be provided by included headers */
const unsigned int default_value_array[] = {
    PCIE1_DBI_DSP_TYPE1_DEV_ID_VEND_ID_REG_DEFAULT_VAL,
    PCIE1_DBI_DSP_TYPE1_STATUS_COMMAND_REG_DEFAULT_VAL,
    PCIE1_DBI_DSP_TYPE1_CLASS_CODE_REV_ID_REG_DEFAULT_VAL,
    PCIE1_DBI_DSP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG_DEFAULT_VAL,
    PCIE1_DBI_DSP_BAR0_REG_DEFAULT_VAL,
    PCIE1_DBI_DSP_CAP_ID_NXT_PTR_REG_DEFAULT_VAL,
    PCIE1_DBI_DSP_DEVICE_CONTROL_DEVICE_STATUS_DEFAULT_VAL,
    PCIE1_DBI_DSP_PL_DEBUG1_OFF_DEFAULT_VAL
};

const unsigned int read_mask_array[] = {
    PCIE1_DBI_DSP_TYPE1_DEV_ID_VEND_ID_REG_READ_MASK,
    PCIE1_DBI_DSP_TYPE1_STATUS_COMMAND_REG_READ_MASK,
    PCIE1_DBI_DSP_TYPE1_CLASS_CODE_REV_ID_REG_READ_MASK,
    PCIE1_DBI_DSP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG_READ_MASK,
    PCIE1_DBI_DSP_BAR0_REG_READ_MASK,
    PCIE1_DBI_DSP_CAP_ID_NXT_PTR_REG_READ_MASK,
    PCIE1_DBI_DSP_DEVICE_CONTROL_DEVICE_STATUS_READ_MASK,
    PCIE1_DBI_DSP_PL_DEBUG1_OFF_READ_MASK
};

const unsigned int write_mask_array[] = {
    PCIE1_DBI_DSP_TYPE1_DEV_ID_VEND_ID_REG_WRITE_MASK,
    PCIE1_DBI_DSP_TYPE1_STATUS_COMMAND_REG_WRITE_MASK,
    PCIE1_DBI_DSP_TYPE1_CLASS_CODE_REV_ID_REG_WRITE_MASK,
    PCIE1_DBI_DSP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG_WRITE_MASK,
    PCIE1_DBI_DSP_BAR0_REG_WRITE_MASK,
    PCIE1_DBI_DSP_CAP_ID_NXT_PTR_REG_WRITE_MASK,
    PCIE1_DBI_DSP_DEVICE_CONTROL_DEVICE_STATUS_WRITE_MASK,
    PCIE1_DBI_DSP_PL_DEBUG1_OFF_WRITE_MASK
};

/* Skip array extracted from Meta (limited to impacted registers). Ensure skips appear only here. */
const unsigned int skip_array[] = {
    0, /* TYPE1_DEV_ID_VEND_ID_REG */
    0, /* TYPE1_STATUS_COMMAND_REG */
    0, /* TYPE1_CLASS_CODE_REV_ID_REG */
    0, /* TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG */
    0, /* BAR0_REG */
    0, /* CAP_ID_NXT_PTR_REG (writes expected masked by write_mask) */
    0, /* DEVICE_CONTROL_DEVICE_STATUS */
    0  /* PL_DEBUG1_OFF */
};

#endif /* TEST_DEFINE_C_ */
