#!/usr/bin/env python3
"""
Standalone USB TestPlan XLSX Generator - Agent 7 Final
Generates USB_TestPlan_20260923_020526.xlsx with TestPlan and MetaData sheets.
Uses fixed IST timestamp derived from commit time 2026-09-22T20:35:26Z + 5:30 = 2026-09-23T02:05:26 IST
"""
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
import os, sys

FILENAME = "USB_TestPlan_20260923_020526.xlsx"

json_data = [
    {
        "Index": "1",
        "SS / Module": "USB",
        "Test Case Name": "USB_FS_Device_Bulk_Transfer_test",
        "Feature": "Full-Speed Device Bulk Transfer",
        "Meta Headers": '<stdio.h>; <stdlib.h>; "usb.h"',
        "Meta Macros": "NA",
        "Meta Arrays": "buf_data[16]",
        "Speed": "Full-Speed",
        "Mode": "Device Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates USB Full-Speed Device mode Bulk Transfer operation. It begins by calling nic_programming() and GIC_EnableAllIRQ(). It clears 20 DWORDs at Buffer_PointerLO and event_trb_addr. It performs a soft reset by writing 0x40f00000 to MIZAR_USB_DCTL and polling MIZAR_USB_DCTL until the value equals 0xf00000. It configures MIZAR_USB_GUSB2PHYCFG with 0x40002407, sets up the event ring by writing Default_Event_Ring_Array to MIZAR_USB_GEVNTADRLO, 0x0 to MIZAR_USB_GEVNTADRHI, 0x30 to MIZAR_USB_GEVNTSIZ, and 0x0 to MIZAR_USB_GEVNTCOUNT. It reads MIZAR_USB_GCTL, then writes 0x30c12214 for port direction. It reads MIZAR_USB_DCFG and writes 0x480801. It writes 0x1f to MIZAR_USB_DEVTEN. It reads MIZAR_USB_GUCTL and writes 0xa400010. It calls set_configuration() 9 times to configure endpoints using MIZAR_USB_DEPCMDPAR1, MIZAR_USB_DEPCMDPAR0, and MIZAR_USB_DEPCMD with various parameters, polling MIZAR_USB_DEPCMD until the command completes. It configures endpoint TX resources by looping 8 times, writing 0x1 to MIZAR_USB_DEPCMDPAR0+(i*0x10) and 0x402 to MIZAR_USB_DEPCMD+(i*0x10), polling until completion. It enables physical endpoints 0 and 1 by writing 0x3 to MIZAR_USB_DALEPENA, then writes 0x80f00000 to MIZAR_USB_DCTL. It enables interrupt at sysreg by writing 0x80000000 to MIZAR_LSS_SYSREG_INTR_EN0. It waits for link state connect/reset events via interrupt pending flags. It writes enumeration marker 0xdeadbee0 to 0xA0243ffc. It reads MIZAR_USB_DCFG and MIZAR_USB_DSTS, reconfigures MIZAR_USB_DCFG, writes 0x80f00a00 to MIZAR_USB_DCTL, enables all endpoints via MIZAR_USB_DALEPENA with 0xff. It calls setup_stage() which prepares TRBs at event_trb_addr and Buffer_PointerLO, issues DEPCMD start transfer command 0x506, and waits for interrupt. It reconfigures MIZAR_USB_GUSB2PHYCFG with 0x40002547. It sets device address by writing 0x480809 to MIZAR_USB_DCFG. It prepares TRBs and issues start transfer on endpoint 1. It polls 0xa0243ff4 until non-zero (handshake). It calls enumeration() which performs GET_DEVICE_DESCRIPTOR, GET_CONFIGURATION_DESCRIPTOR, SET_CONFIGURATION sequences. It polls 0xa0243ff8 until non-zero. It then performs two Bulk Transfer operations. The Default_IRQHandler reads MIZAR_LSS_SYSREG_MSK_STS0 and MIZAR_LSS_SYSREG_RAW_STCR0, reads MIZAR_USB_GEVNTCOUNT and writes back the count to clear, clears sysreg interrupt, and clears GIC IRQ 84. The test ends with finish(0).",
        "Test Description": "This test validates USB Full-Speed Device mode Bulk Transfer functionality. The test performs a controller soft reset via DCTL, configures the USB 2.0 PHY, sets up the event ring buffer, configures the global controller register for device-mode port direction, configures device speed and event enables via DCFG and DEVTEN, and sets up the utility control register GUCTL. It then configures all endpoints using endpoint command registers and enables them via DALEPENA. The test enables system-level interrupts and waits for link state connect and reset events. It performs USB enumeration including device descriptor, configuration descriptor retrieval, set address, and set configuration sequences. After enumeration, it executes two Bulk Transfer operations on bulk endpoints, issuing start transfer commands and waiting for transfer completion via interrupts. An interrupt handler reads system interrupt status, processes event counts via the event count register, clears interrupt status, and clears the GIC interrupt. The test completes successfully by calling finish.",
        "Meta Test Steps / Procedure": "1. Call nic_programming() for NIC initialization. 2. Call GIC_EnableAllIRQ() to enable all IRQs. 3. Clear 20 DWORDs at Buffer_PointerLO and event_trb_addr by writing 0x0 in a loop (j=0 to 19, offset j*DWORD). 4. Write 0x40f00000 to MIZAR_USB_DCTL to initiate soft reset. 5. Poll MIZAR_USB_DCTL with wait_on(5) until value equals 0xf00000 (soft reset complete). 6. Write 0x40002407 to MIZAR_USB_GUSB2PHYCFG for PHY configuration. 7. Write Default_Event_Ring_Array to MIZAR_USB_GEVNTADRLO. 8. Write 0x0 to MIZAR_USB_GEVNTADRHI. 9. Write 0x30 to MIZAR_USB_GEVNTSIZ. 10. Write 0x0 to MIZAR_USB_GEVNTCOUNT. 11. Read MIZAR_USB_GCTL, then write 0x30c12214 for port direction (device mode). 12. Read MIZAR_USB_DCFG, then write 0x480801 to configure device speed. 13. Write 0x1f to MIZAR_USB_DEVTEN to enable device events (disconnect, USB reset, connect done, link state change, wakeup). 14. Read MIZAR_USB_GUCTL, then write 0xa400010. 15. Call set_configuration() 9 times with varying parameters. 16. Loop i=0 to 7: write DEPXFERCFG commands. 17. Write 0x3 to MIZAR_USB_DALEPENA. 18. Write 0x80f00000 to MIZAR_USB_DCTL. 19. Write 0x80000000 to MIZAR_LSS_SYSREG_INTR_EN0. 20-36. Full enumeration and bulk transfer sequence. IRQ HANDLER: clear int_pend, read sysreg status, process event count, clear interrupts.",
        "Test Steps / Procedure": "1. Initialize NIC programming and enable all GIC IRQs. 2. Clear transfer buffer and event TRB memory regions (20 DWORDs each). 3. Perform USB controller soft reset via DCTL and poll until reset completes. 4. Configure USB 2.0 PHY settings. 5. Set up event ring by writing event address low, event address high, event size, and event count registers. 6. Read and configure GCTL for device-mode port direction. 7. Read and configure DCFG for device speed settings. 8. Enable device events (disconnect, USB reset, connect done, link state change, wakeup) via DEVTEN. 9. Read and configure GUCTL utility control register. 10. Issue Start New Configuration command followed by 8 Set Endpoint Configuration commands for all endpoints, polling each command for completion. 11. Configure transfer resources for 8 endpoints by issuing DEPXFERCFG commands and polling for completion. 12. Enable physical endpoints 0 and 1 via DALEPENA. 13. Set DCTL to run the controller and enable system-level interrupt via sysreg. 14. Wait for link state connect and reset event interrupts. 15. Reconfigure DCFG and wait for additional events as needed. 16. Read DCFG and DSTS to verify device status. Reconfigure DCTL and enable all endpoints via DALEPENA. 17. Execute setup stage: prepare control TRB and issue start transfer command on endpoint 0, wait for completion interrupt. 18. Reconfigure USB 2.0 PHY and wait for events. 19. Set device address by updating DCFG and issuing a start transfer on endpoint 1 with a status TRB. 20. Poll handshake location until host signals readiness. 21. Execute full USB enumeration sequence: Get Device Descriptor (setup, data with descriptor payload, status), Get Configuration Descriptor short read (setup, data, status), Set Configuration (setup, zero-length data, status), Get Configuration Descriptor full read (setup, 60-byte data with full descriptor payload, status). 22. Poll second handshake location until host signals readiness. 23. Execute Bulk Transfer 1: prepare bulk TRB with 64-byte size on bulk endpoint (offset 4), issue start transfer, poll for command completion, wait for transfer completion interrupt. 24. Execute Bulk Transfer 2: prepare bulk TRB with 64-byte size on bulk endpoint (offset 5), issue start transfer, poll for command completion, wait for transfer completion interrupt. 25. Verify test completion via finish call. Interrupt handler: read system interrupt mask and raw status, read and clear event count register, clear system interrupt status, clear GIC IRQ.",
        "Meta Impacted Registers": "Buffer_PointerLO; event_trb_addr; MIZAR_USB_DCTL; MIZAR_USB_GUSB2PHYCFG; MIZAR_USB_GEVNTADRLO; MIZAR_USB_GEVNTADRHI; MIZAR_USB_GEVNTSIZ; MIZAR_USB_GEVNTCOUNT; MIZAR_USB_GCTL; MIZAR_USB_DCFG; MIZAR_USB_DEVTEN; MIZAR_USB_GUCTL; MIZAR_USB_DEPCMDPAR0; MIZAR_USB_DEPCMD; MIZAR_USB_DALEPENA; MIZAR_LSS_SYSREG_INTR_EN0; 0xA0243ffc; MIZAR_USB_DSTS; MIZAR_USB_DEPCMDPAR1; 0xa0243ff4; 0xa0243ff8; Buffer_PointerLO_1; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0",
        "Impacted Registers": "DCTL; GCTL; DCFG; DEVTEN; GUCTL; DALEPENA; DSTS",
        "Meta Validation / Acceptance Criteria": "1. Soft reset validation: poll MIZAR_USB_DCTL until rd_data equals 0xf00000, confirming soft reset completion. 2. Endpoint command completion: for each set_configuration call and DEPXFERCFG command, poll MIZAR_USB_DEPCMD+(offset) until read_data != cmd value (command no longer active). 3. Start transfer command completion: poll MIZAR_USB_DEPCMD (various offsets) until rd_data != 0x506. 4. Interrupt-driven event processing: int_pend flag is set to 1 before waiting, Default_IRQHandler clears int_pend to 0 upon interrupt, confirming event was received and processed. 5. Event counter check: event_counter <= 0x4 condition gates additional interrupt waits, ensuring sufficient events are received. 6. Handshake polling: read 0xa0243ff4 until non-zero (host handshake for enumeration), read 0xa0243ff8 until non-zero (host handshake for bulk transfer readiness). 7. IRQ handler validation: reads MIZAR_LSS_SYSREG_MSK_STS0 and MIZAR_LSS_SYSREG_RAW_STCR0, reads MIZAR_USB_GEVNTCOUNT and writes back to clear event count, conditionally writes 0x80000000 to MIZAR_LSS_SYSREG_RAW_STCR0 if bit 31 set, calls GIC_ClearIRQ(84). 8. Test passes by reaching finish(0) after all bulk transfers complete successfully.",
        "Validation / Acceptance Criteria": "1. Controller soft reset completes successfully as confirmed by polling DCTL until the expected reset-done value is read. 2. All endpoint configuration commands complete as confirmed by polling the endpoint command register until the command value clears. 3. All start transfer commands complete as confirmed by polling the endpoint command register. 4. Device events (connect, reset, link state changes) are received and processed via the interrupt handler, confirmed by the interrupt pending flag clearing. 5. Event counter reaches expected thresholds to gate enumeration progress. 6. Host handshake signals are received at both polling locations before proceeding with enumeration and bulk transfers. 7. Interrupt handler correctly reads system interrupt status, processes and clears event counts, clears system interrupt raw status, and clears GIC IRQ. 8. Two bulk transfers of 64 bytes each complete successfully on separate bulk endpoints. 9. Test passes by reaching the finish call after all transfers complete.",
        "Remarks": "Test operates in USB Full-Speed Device mode with interrupt-driven event handling using GIC IRQ 84. Enumeration includes Get Device Descriptor, Get Configuration Descriptor (short and full), and Set Configuration sequences. Two bulk transfers are performed on separate bulk endpoints after enumeration. Several Agent 4 register mappings are unresolved including event buffer pointers, PHY config, event ring registers, endpoint command parameter registers, and system-level sysreg interrupt registers. Handshake polling locations are used for host-device synchronization. The test uses conditional waits based on event_counter to handle variable event timing."
    },
    {
        "Index": "2",
        "SS / Module": "USB",
        "Test Case Name": "USB_FS_Device_Interrupt_Transfer_test",
        "Feature": "Full-Speed Device Interrupt Transfer",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"usb.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "buf_data[16]",
        "Speed": "Full-Speed",
        "Mode": "Device Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates USB Full-Speed Device mode Interrupt Transfer operation. It begins by calling nic_programming() and GIC_EnableAllIRQ(). It clears 20 DWORDs at Buffer_PointerLO and event_trb_addr by writing 0x0 in a loop. It performs a soft reset by writing 0x40f00000 to MIZAR_USB_DCTL and polling MIZAR_USB_DCTL until the value equals 0xf00000. It configures MIZAR_USB_GUSB2PHYCFG with 0x40002407, sets up the event ring by writing Default_Event_Ring_Array to MIZAR_USB_GEVNTADRLO, 0x0 to MIZAR_USB_GEVNTADRHI, 0x30 to MIZAR_USB_GEVNTSIZ, and 0x0 to MIZAR_USB_GEVNTCOUNT. It reads MIZAR_USB_GCTL, then writes 0x30c12214 for port direction (device mode). It reads MIZAR_USB_DCFG and writes 0x480801 for device speed configuration. It writes 0x1f to MIZAR_USB_DEVTEN to enable device events. It reads MIZAR_USB_GUCTL and writes 0xa400010. It calls set_configuration() 9 times to configure endpoints. After enumeration, it executes two Interrupt Transfer operations on interrupt endpoints with different TRB control types (0x815 and 0x813). It then polls MIZAR_USB_DSTS for a valid frame number.",
        "Test Description": "This test validates USB Full-Speed Device mode Interrupt Transfer functionality. The test performs a controller soft reset via DCTL, configures the USB 2.0 PHY, sets up the event ring buffer, configures the global controller register GCTL for device-mode port direction, configures device speed and event enables via DCFG and DEVTEN, and sets up the utility control register GUCTL. It then configures all endpoints using endpoint command registers and enables them via DALEPENA. The test enables system-level interrupts and waits for link state connect and reset events. It performs USB enumeration including device descriptor retrieval, configuration descriptor retrieval (short and full), set address, and set configuration sequences. After enumeration, it executes two Interrupt Transfer operations on interrupt endpoints: the first with interrupt-type TRB control and the second with a normal-type TRB control, each with 64-byte size, issuing start transfer commands and waiting for transfer completion via interrupts. It then polls DSTS for a valid frame number to confirm active scheduling. An interrupt handler reads system interrupt status, processes event counts via the event count register, clears interrupt status, and clears the GIC interrupt. The test completes successfully by calling finish.",
        "Meta Test Steps / Procedure": "1. Call nic_programming() for NIC initialization. 2. Call GIC_EnableAllIRQ() to enable all IRQs. 3. Clear 20 DWORDs at Buffer_PointerLO and event_trb_addr by writing 0x0 in a loop (j=0 to 19, offset j*DWORD). 4. Write 0x40f00000 to MIZAR_USB_DCTL to initiate soft reset. 5. Poll MIZAR_USB_DCTL with wait_on(100) until value equals 0xf00000 (soft reset complete). 6-31. Full enumeration sequence same as bulk transfer test. 32. INTERRUPT TRANSFER 1: write TRB at event_trb_addr (Buffer_PointerLO_1, size=0x40, control=0x815), write DEPCMDPAR1+0x20=event_trb_addr, DEPCMDPAR0+0x20=0x0, DEPCMD+0x20=0x506, poll until complete, wait for interrupt. 33. Wait for another interrupt. 34. INTERRUPT TRANSFER 2: write TRB at event_trb_addr (Buffer_PointerLO_1, size=0x40, control=0x813), write DEPCMDPAR1+0x30=event_trb_addr, DEPCMDPAR0+0x30=0x0, DEPCMD+0x30=0x506, poll until complete, wait for interrupt. 35. Poll MIZAR_USB_DSTS with mask 0x00000FF8 until non-zero (wait for frame number). 36. Write 0xdeadbee7 to 0xA0243ffc. Wait for interrupt. 37. Call finish(0). IRQ HANDLER same as bulk transfer test.",
        "Test Steps / Procedure": "1. Initialize NIC programming and enable all GIC IRQs. 2. Clear transfer buffer and event TRB memory regions (20 DWORDs each). 3. Perform USB controller soft reset via DCTL and poll until reset completes. 4. Configure USB 2.0 PHY settings. 5. Set up event ring by writing event address low, event address high, event size, and event count registers. 6. Read and configure GCTL for device-mode port direction. 7. Read and configure DCFG for device speed settings. 8. Enable device events (disconnect, USB reset, connect done, link state change, wakeup) via DEVTEN. 9. Read and configure GUCTL utility control register. 10. Issue Start New Configuration command followed by 8 Set Endpoint Configuration commands for all endpoints, polling each command for completion. 11. Configure transfer resources for 8 endpoints by issuing DEPXFERCFG commands and polling for completion. 12. Enable physical endpoints 0 and 1 via DALEPENA. 13. Set DCTL to run the controller and enable system-level interrupt via sysreg. 14. Wait for link state connect and reset event interrupts. 15. Reconfigure DCFG and wait for additional events as needed. 16. Read DCFG and DSTS to verify device status. Reconfigure DCTL and enable all endpoints via DALEPENA. 17. Execute setup stage: prepare control TRB and issue start transfer command on endpoint 0, wait for completion interrupt. 18. Reconfigure USB 2.0 PHY and wait for events. 19. Set device address by updating DCFG and issuing a start transfer on endpoint 1 with a status TRB. 20. Poll handshake location until host signals readiness. 21. Execute full USB enumeration sequence: Get Device Descriptor (setup, data with descriptor payload, status), Get Configuration Descriptor short read (setup, data, status), Set Configuration (setup, zero-length data, status), Get Configuration Descriptor full read (setup, 60-byte data with full descriptor payload, status). 22. Poll second handshake location until host signals readiness. 23. Execute Interrupt Transfer 1: prepare interrupt TRB with 64-byte size and interrupt-type control on interrupt endpoint (offset 2), issue start transfer, poll for command completion, wait for transfer completion interrupt. 24. Execute Interrupt Transfer 2: prepare interrupt TRB with 64-byte size and normal-type control on interrupt endpoint (offset 3), issue start transfer, poll for command completion, wait for transfer completion interrupt. 25. Poll DSTS for a valid frame number to confirm active frame scheduling. 26. Verify test completion via finish call. Interrupt handler: read system interrupt mask and raw status, read and clear event count register, clear system interrupt status, clear GIC IRQ.",
        "Meta Impacted Registers": "Buffer_PointerLO; event_trb_addr; MIZAR_USB_DCTL; MIZAR_USB_GUSB2PHYCFG; MIZAR_USB_GEVNTADRLO; MIZAR_USB_GEVNTADRHI; MIZAR_USB_GEVNTSIZ; MIZAR_USB_GEVNTCOUNT; MIZAR_USB_GCTL; MIZAR_USB_DCFG; MIZAR_USB_DEVTEN; MIZAR_USB_GUCTL; MIZAR_USB_DEPCMDPAR0; MIZAR_USB_DEPCMD; MIZAR_USB_DALEPENA; MIZAR_LSS_SYSREG_INTR_EN0; 0xA0243ffc; MIZAR_USB_DSTS; MIZAR_USB_DEPCMDPAR1; 0xa0243ff4; 0xa0243ff8; Buffer_PointerLO_1; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0",
        "Impacted Registers": "DCTL; GCTL; DCFG; DEVTEN; GUCTL; DALEPENA; DSTS",
        "Meta Validation / Acceptance Criteria": "1. Soft reset validation: poll MIZAR_USB_DCTL until rd_data equals 0xf00000, confirming soft reset completion. 2. Endpoint command completion. 3. Start transfer command completion. 4. Interrupt-driven event processing. 5. Event counter check. 6. Handshake polling. 7. Frame number validation: poll MIZAR_USB_DSTS with mask 0x00000FF8 until non-zero. 8. IRQ handler validation. 9. Test passes by reaching finish(0).",
        "Validation / Acceptance Criteria": "1. Controller soft reset completes successfully as confirmed by polling DCTL until the expected reset-done value is read. 2. All endpoint configuration commands complete as confirmed by polling the endpoint command register until the command value clears. 3. All start transfer commands complete as confirmed by polling the endpoint command register. 4. Device events (connect, reset, link state changes) are received and processed via the interrupt handler, confirmed by the interrupt pending flag clearing. 5. Event counter reaches expected thresholds to gate enumeration and transfer progress. 6. Host handshake signals are received at both polling locations before proceeding with enumeration and interrupt transfers. 7. Two interrupt transfers of 64 bytes each complete successfully on separate interrupt endpoints with different TRB control types. 8. DSTS frame number field becomes non-zero, confirming active frame scheduling after interrupt transfers. 9. Interrupt handler correctly reads system interrupt status, processes and clears event counts, clears system interrupt raw status, and clears GIC IRQ. 10. Test passes by reaching the finish call after all transfers complete and frame number is validated.",
        "Remarks": "Test operates in USB Full-Speed Device mode with interrupt-driven event handling using GIC IRQ 84. The first interrupt transfer uses TRB control value 0x815 (interrupt transfer type) while the second uses 0x813 (normal type), testing different TRB configurations on interrupt endpoints at offsets 0x20 and 0x30. Unlike the bulk transfer test, this test additionally polls DSTS for a valid frame number (mask 0x00000FF8) after interrupt transfers to verify active frame scheduling. Enumeration includes Get Device Descriptor, Get Configuration Descriptor (short and full), Set Configuration, and Set Address sequences. Several Agent 4 register mappings are unresolved including event buffer pointers, PHY config, event ring registers, endpoint command parameter registers, and system-level sysreg interrupt registers. Handshake polling locations are used for host-device synchronization. The test uses conditional waits based on event_counter to handle variable event timing."
    },
    {
        "Index": "3",
        "SS / Module": "USB",
        "Test Case Name": "USB_FS_Device_Isochronous_Transfer_test",
        "Feature": "Full-Speed Device Isochronous Transfer",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"usb.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "buf_data[16]",
        "Speed": "Full-Speed",
        "Mode": "Device Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates USB Full-Speed Device mode Isochronous Transfer operation. After enumeration, it polls DSTS for a valid frame number, then executes two Isochronous OUT Transfer operations with 1023-byte transfer size and isochronous TRB control type (0x869). It polls DSTS for specific frame number values (2, 3, and 4) to synchronize transfers with the USB frame schedule. Start transfer commands include frame-number parameters (0x20506 and 0x40506).",
        "Test Description": "This test validates USB Full-Speed Device mode Isochronous Transfer functionality. The test performs a controller soft reset via DCTL, configures the USB 2.0 PHY, sets up the event ring buffer, configures the global controller register GCTL for device-mode port direction, configures device speed and event enables via DCFG and DEVTEN, and sets up the utility control register GUCTL. It then configures all endpoints including isochronous endpoint types using endpoint command registers and enables them via DALEPENA. The test enables system-level interrupts and waits for link state connect and reset events. It performs USB enumeration including device descriptor retrieval, configuration descriptor retrieval (short and full), set address, and set configuration sequences. After enumeration, it polls DSTS for a valid frame number to confirm active frame scheduling. It then executes two Isochronous OUT Transfer operations on isochronous endpoints with 1023-byte transfer size and isochronous TRB control type, issuing start transfer commands with frame-number-specific parameters and waiting for transfer completion via interrupts. Between and after isochronous transfers, it polls DSTS for specific frame number values (2, 3, and 4) to synchronize transfers with the USB frame schedule. An interrupt handler reads system interrupt status, processes event counts via the event count register, clears interrupt status, and clears the GIC interrupt. The test completes successfully by calling finish.",
        "Meta Test Steps / Procedure": "1-31. Same initialization, configuration, and enumeration as bulk transfer test. 31. Read MIZAR_USB_DSTS and poll with mask 0x00000FF8 until non-zero (wait for frame number 1). 32. Write 0xdeadbee6 to 0xA0243ffc. 33. ISOCHRONOUS OUT TRANSFER 1: write TRB at event_trb_addr (Buffer_PointerLO_1, size=0x3ff, control=0x869), write DEPCMDPAR1+0x60=event_trb_addr, DEPCMDPAR0+0x60=0x0, DEPCMD+0x60=0x20506, poll until rd_data != 0x20506, wait for interrupt. 34. Poll MIZAR_USB_DSTS with mask (rd_data & 0x00000038) >> 3 until equals 0x2 (wait for frame number 2). 35-37. Wait for frame numbers 3 and 4. 38. ISOCHRONOUS OUT TRANSFER 2: write TRB, DEPCMD+0x70=0x40506, poll, wait. 39-41. Final frame polling and finish(0).",
        "Test Steps / Procedure": "1. Initialize NIC programming and enable all GIC IRQs. 2. Clear transfer buffer and event TRB memory regions (20 DWORDs each). 3. Perform USB controller soft reset via DCTL and poll until reset completes. 4. Configure USB 2.0 PHY settings. 5. Set up event ring by writing event address low, event address high, event size, and event count registers. 6. Read and configure GCTL for device-mode port direction. 7. Read and configure DCFG for device speed settings. 8. Enable device events (disconnect, USB reset, connect done, link state change, wakeup) via DEVTEN. 9. Read and configure GUCTL utility control register. 10. Issue Start New Configuration command followed by 8 Set Endpoint Configuration commands for all endpoints including isochronous endpoint types at offsets 6 and 7, polling each command for completion. 11. Configure transfer resources for 8 endpoints by issuing DEPXFERCFG commands and polling for completion. 12. Enable physical endpoints 0 and 1 via DALEPENA. 13. Set DCTL to run the controller and enable system-level interrupt via sysreg. 14. Wait for link state connect and reset event interrupts. 15. Reconfigure DCFG and wait for additional events as needed. 16. Read DCFG and DSTS to verify device status. Reconfigure DCTL and enable all endpoints via DALEPENA. 17. Execute setup stage: prepare control TRB and issue start transfer command on endpoint 0, wait for completion interrupt. 18. Reconfigure USB 2.0 PHY and wait for events. 19. Set device address by updating DCFG and issuing a start transfer on endpoint 1 with a status TRB. 20. Poll handshake location until host signals readiness. 21. Execute full USB enumeration sequence. 22. Poll second handshake location until host signals readiness. 23. Poll DSTS for a valid frame number to confirm active frame scheduling. 24. Execute Isochronous OUT Transfer 1: prepare isochronous TRB with 1023-byte size and isochronous control type on isochronous endpoint (offset 6), issue start transfer with frame-number parameter, poll for command completion, wait for transfer completion interrupt. 25. Poll DSTS for frame number equal to 2 to synchronize with USB frame schedule. 26. Poll DSTS for frame number equal to 3 to synchronize with next frame. 27. Execute Isochronous OUT Transfer 2: prepare isochronous TRB with 1023-byte size and isochronous control type on isochronous endpoint (offset 7), issue start transfer with frame-number parameter, poll for command completion, wait for transfer completion interrupt. 28. Poll DSTS for frame number equal to 4 to confirm final frame synchronization. 29. Verify test completion via finish call. Interrupt handler: read system interrupt mask and raw status, read and clear event count register, clear system interrupt status, clear GIC IRQ.",
        "Meta Impacted Registers": "Buffer_PointerLO; event_trb_addr; MIZAR_USB_DCTL; MIZAR_USB_GUSB2PHYCFG; MIZAR_USB_GEVNTADRLO; MIZAR_USB_GEVNTADRHI; MIZAR_USB_GEVNTSIZ; MIZAR_USB_GEVNTCOUNT; MIZAR_USB_GCTL; MIZAR_USB_DCFG; MIZAR_USB_DEVTEN; MIZAR_USB_GUCTL; MIZAR_USB_DEPCMDPAR0; MIZAR_USB_DEPCMD; MIZAR_USB_DALEPENA; MIZAR_LSS_SYSREG_INTR_EN0; 0xA0243ffc; MIZAR_USB_DSTS; MIZAR_USB_DEPCMDPAR1; 0xa0243ff4; 0xa0243ff8; Buffer_PointerLO_1; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0",
        "Impacted Registers": "DCTL; GCTL; DCFG; DEVTEN; GUCTL; DALEPENA; DSTS",
        "Meta Validation / Acceptance Criteria": "1. Soft reset validation. 2. Endpoint command completion. 3. Start transfer command completion for isochronous endpoints. 4. Interrupt-driven event processing. 5. Event counter check. 6. Handshake polling. 7. Frame number validation 1: poll MIZAR_USB_DSTS with mask 0x00000FF8 until non-zero. 8. Frame number validation 2-4: poll MIZAR_USB_DSTS with mask (rd_data & 0x00000038) >> 3 until equals 0x2, 0x3, 0x4. 9. IRQ handler validation. 10. Test passes by reaching finish(0).",
        "Validation / Acceptance Criteria": "1. Controller soft reset completes successfully as confirmed by polling DCTL until the expected reset-done value is read. 2. All endpoint configuration commands complete as confirmed by polling the endpoint command register until the command value clears. 3. All start transfer commands complete as confirmed by polling the endpoint command register for each isochronous endpoint. 4. Device events (connect, reset, link state changes) are received and processed via the interrupt handler, confirmed by the interrupt pending flag clearing. 5. Event counter reaches expected thresholds to gate enumeration and transfer progress. 6. Host handshake signals are received at both polling locations before proceeding with enumeration and isochronous transfers. 7. DSTS frame number field becomes non-zero before isochronous transfers begin, confirming active frame scheduling. 8. Two isochronous OUT transfers of 1023 bytes each complete successfully on separate isochronous endpoints with isochronous TRB control type and frame-number-specific start transfer parameters. 9. DSTS frame number field reaches specific values (2, 3, and 4) between and after isochronous transfers, confirming correct frame-level synchronization. 10. Interrupt handler correctly reads system interrupt status, processes and clears event counts, clears system interrupt raw status, and clears GIC IRQ. 11. Test passes by reaching the finish call after all isochronous transfers complete and all frame number validations succeed.",
        "Remarks": "Test operates in USB Full-Speed Device mode with interrupt-driven event handling using GIC IRQ 84. Unlike bulk and interrupt transfer tests, this test uses isochronous TRB control value 0x869 and 1023-byte (0x3ff) transfer size. The start transfer commands include frame-number parameters (0x20506 and 0x40506) to schedule isochronous transfers at specific USB frames. The test performs extensive frame-number polling on DSTS using mask 0x00000038 shifted right by 3 to verify frame numbers 2, 3, and 4 sequentially, ensuring correct isochronous frame-level synchronization. Isochronous endpoints are configured at offsets 0x60 and 0x70 with parameter0 values 0x1ffa and 0x61ffa respectively. Enumeration includes Get Device Descriptor, Get Configuration Descriptor (short and full), Set Configuration, and Set Address sequences. Several Agent 4 register mappings are unresolved including event buffer pointers, PHY config, event ring registers, endpoint command parameter registers, and system-level sysreg interrupt registers. Handshake polling locations are used for host-device synchronization. The test uses conditional waits based on event_counter to handle variable event timing."
    },
    {
        "Index": "4",
        "SS / Module": "USB",
        "Test Case Name": "usb_host_enumeration_fs",
        "Feature": "Host Enumeration Full-Speed",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"usb.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "data_in[512]; data_out[512]",
        "Speed": "Full-Speed",
        "Mode": "Host Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates USB Host mode Full-Speed device enumeration. It begins by calling nic_programming() and GIC_EnableAllIRQ(). It configures MIZAR_USB_GCTL via read-modify-write with set_data using mask 0xFFFFFFFF and value 0x30c11234. It configures MIZAR_USB_GFLADJ via read-modify-write with value 0xa87f000. It configures MIZAR_USB_GUCTL via read-modify-write with value 0x2000010. It reads and writes MIZAR_USB_BASE+0xc2c0 (pipe control) with 0x10c0002. It reads and writes MIZAR_USB_BASE+0xc200 (PHY control) with 0x102407. It reads MIZAR_USB_HCSPARAMS1 for port count, reads MIZAR_USB_SUPTPRT2_DW2 and MIZAR_USB_SUPTPRT3_DW2 for supported protocol capability, reads MIZAR_USB_PORTSC_20 for port status. It configures MIZAR_USB_PORTSC_20 via three read-modify-write operations setting USB_PORTSC_20_WCE, USB_PORTSC_20_WDE, USB_PORTSC_20_WOE to 1. It sets up xHCI data structures including event ring segment table, scratchpad buffer array, device context base address array, command ring pointer via CRCR_LO and CRCR_HI, device context base address pointer via DCBAAP_LO and DCBAAP_HI, and configures max slots via CONFIG. It performs Enable Slot, Address Device (BSR=1 then BSR=0), Configure Endpoint, then Get Device Descriptor, Get Configuration Descriptor (short and full), Set Configuration via EP0 transfer ring.",
        "Test Description": "This test validates USB Host mode Full-Speed device enumeration. The test configures the global controller register GCTL, frame length adjustment register GFLADJ, and utility control register GUCTL via read-modify-write operations. It configures the USB 3.0 pipe control and USB 2.0 PHY control registers. It reads host controller structural parameters from HCSPARAMS1 and HCSPARAMS2, supported protocol capability from SUPTPRT2_DW2 and SUPTPRT3_DW2, page size from PAGESIZE, and doorbell offset from DBOFF. It configures the port status and control register PORTSC_20 with wake-on-connect, wake-on-disconnect, and wake-on-overcurrent enables. It sets up the xHCI data structures including event ring segment table, scratchpad buffer array, device context base address array, command ring pointer via CRCR_LO and CRCR_HI, device context base address pointer via DCBAAP_LO and DCBAAP_HI, and configures max slots via CONFIG. It initializes the interrupter registers including event ring segment table size ERSTSZ, event ring dequeue pointer ERDP_LO and ERDP_HI, event ring segment table base address ERSTBA_LO and ERSTBA_HI, interrupter moderation IMOD, and interrupter management IMAN. It enables interrupts and starts the host controller via USBCMD. It enables system-level interrupts and waits for a port status change event. After detecting port connection, it performs a port reset via PORTSC_20. It then executes the full enumeration sequence: Enable Slot command, Address Device command with BSR=1 (block set address request), Address Device command with BSR=0 (actual address assignment), and Configure Endpoint command. It then performs USB standard requests via the endpoint 0 transfer ring: Get Device Descriptor, Get Configuration Descriptor (short 9-byte read), Set Configuration, and Get Configuration Descriptor (full 60-byte read). It rings the device doorbell, waits for all transfer events to complete, and verifies completion by polling the event ring. An interrupt handler reads system interrupt status, acknowledges the interrupter, clears system interrupt status, and clears the GIC interrupt. The test completes successfully by calling finish.",
        "Meta Test Steps / Procedure": "1. Call nic_programming() for NIC initialization. 2. Call GIC_EnableAllIRQ() to enable all IRQs. 3. Write MIZAR_USB_GCTL via set_data(read_reg(MIZAR_USB_GCTL), 0xFFFFFFFF, 0x30c11234). 4. Write MIZAR_USB_GFLADJ via set_data with value 0xa87f000. 5. Write MIZAR_USB_GUCTL via set_data with value 0x2000010. 6-7. Read and write pipe control and PHY control. 8-12. Read HCSPARAMS1, SUPTPRT2_DW2, SUPTPRT3_DW2, PORTSC_20, DBOFF. 13-19. Set up xHCI data structures. 20-26. Configure interrupter registers and start host. 27-35. Port connect, reset, Enable Slot, Address Device, Configure Endpoint. 36-42. Enumeration transfers and event ring polling.",
        "Test Steps / Procedure": "1. Configure GCTL, GFLADJ, GUCTL. 2. Configure PHY and pipe control. 3. Read HCSPARAMS1, HCSPARAMS2, PAGESIZE, SUPTPRT2_DW2, SUPTPRT3_DW2. 4. Configure PORTSC_20. 5. Set up event ring, scratchpad, DCBA, command ring. 6. Configure CRCR, CONFIG, DCBAAP, interrupter registers. 7. Start host via USBCMD. 8. Wait for port connect, perform port reset. 9. Enable Slot, Address Device, Configure Endpoint. 10. Execute enumeration transfers. 11. Poll event ring for completion.",
        "Meta Impacted Registers": "MIZAR_USB_GCTL; MIZAR_USB_GFLADJ; MIZAR_USB_GUCTL; MIZAR_USB_HCSPARAMS1; MIZAR_USB_SUPTPRT2_DW2; MIZAR_USB_SUPTPRT3_DW2; MIZAR_USB_PORTSC_20; MIZAR_USB_DBOFF; Event_Ring_Segment_Table; MIZAR_USB_HCSPARAMS2; MIZAR_USB_PAGESIZE; Scratchpad_Buffer_Array; Device_Context_Base_Address_Array; MIZAR_USB_CRCR_LO; MIZAR_USB_CRCR_HI; MIZAR_USB_CONFIG; MIZAR_USB_DCBAAP_LO; MIZAR_USB_DCBAAP_HI; MIZAR_USB_ERSTSZ; MIZAR_USB_ERDP_LO; MIZAR_USB_ERDP_HI; MIZAR_USB_ERSTBA_LO; MIZAR_USB_ERSTBA_HI; MIZAR_USB_IMOD; MIZAR_USB_IMAN; MIZAR_USB_USBCMD; MIZAR_LSS_SYSREG_INTR_EN0; MIZAR_USB_USBSTS; Default_Event_Ring_Array; MIZAR_USB_DB; Default_Input_Context; Default_Command_Ring; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0; EP0_TR_Dequeue_Pointer",
        "Impacted Registers": "GCTL; GFLADJ; GUCTL; HCSPARAMS1; SUPTPRT2_DW2; SUPTPRT3_DW2; PORTSC_20; DBOFF; HCSPARAMS2; PAGESIZE; CRCR_LO; CRCR_HI; CONFIG; DCBAAP_LO; DCBAAP_HI; ERSTSZ; ERDP_LO; ERDP_HI; ERSTBA_LO; ERSTBA_HI; IMOD; IMAN; USBCMD; USBSTS; DB; CAPLENGTH",
        "Meta Validation / Acceptance Criteria": "1. Port connection detection. 2. Port reset completion. 3. Enable Slot command completion. 4. Address Device BSR=1 completion. 5. Address Device BSR=0 completion. 6. Configure Endpoint command completion. 7. Enumeration transfer completion: poll Default_Event_Ring_Array+0xf0 until non-zero. 8. Interrupt-driven event processing. 9. Test passes by reaching finish(0).",
        "Validation / Acceptance Criteria": "1. Port connection detected. 2. Port reset completes. 3. Enable Slot, Address Device, Configure Endpoint commands complete. 4. All enumeration transfers complete. 5. Test passes by reaching finish.",
        "Remarks": "Host mode Full-Speed enumeration using xHCI. Slot context 0x38100000. GFLADJ 0xa87f000. The enumeration sequence follows the standard xHCI flow: Enable Slot, Address Device (BSR=1 then BSR=0), Configure Endpoint, followed by standard USB requests (Get Device Descriptor, Get Configuration Descriptor short and full, Set Configuration). Several Agent 4 register mappings are unresolved including Event_Ring_Segment_Table, Scratchpad_Buffer_Array, Device_Context_Base_Address_Array, Default_Event_Ring_Array, Default_Input_Context, Default_Command_Ring, EP0_TR_Dequeue_Pointer, and system-level sysreg interrupt registers."
    },
    {
        "Index": "5",
        "SS / Module": "USB",
        "Test Case Name": "usb_host_enumeration_hs",
        "Feature": "Host Enumeration High-Speed",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"usb.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "data_in[512]; data_out[512]",
        "Speed": "High-Speed",
        "Mode": "Host Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates USB Host mode High-Speed device enumeration. Same xHCI flow as Full-Speed but with High-Speed specific parameters. Includes Get Device Qualifier request (descriptor type 0x06). Slot context uses value 0x38300000 (indicating High-Speed). GFLADJ value is 0xa07f000. The enumeration includes additional Get Device Qualifier and second Get Configuration Descriptor short read. Event ring poll at offset 0x150.",
        "Test Description": "This test validates USB Host mode High-Speed device enumeration. Same xHCI flow as Full-Speed but with High-Speed specific parameters. Includes Get Device Qualifier request.",
        "Meta Test Steps / Procedure": "Same as Full-Speed host enumeration with additional Get Device Qualifier TRBs (setup 0x06000680/0x000a0000, data EP0_TR_Dequeue_Pointer+0x210 size 0xa) and second Get Configuration Descriptor short read. GFLADJ configured with 0xa07f000. Slot context 0x38300000. Event ring poll at Default_Event_Ring_Array+0x150.",
        "Test Steps / Procedure": "Same as Full-Speed host enumeration with additional Get Device Qualifier and second Get Configuration Descriptor short read.",
        "Meta Impacted Registers": "MIZAR_USB_GCTL; MIZAR_USB_GFLADJ; MIZAR_USB_GUCTL; MIZAR_USB_HCSPARAMS1; MIZAR_USB_SUPTPRT2_DW2; MIZAR_USB_SUPTPRT3_DW2; MIZAR_USB_PORTSC_20; MIZAR_USB_DBOFF; Event_Ring_Segment_Table; MIZAR_USB_HCSPARAMS2; MIZAR_USB_PAGESIZE; Scratchpad_Buffer_Array; Device_Context_Base_Address_Array; MIZAR_USB_CRCR_LO; MIZAR_USB_CRCR_HI; MIZAR_USB_CONFIG; MIZAR_USB_DCBAAP_LO; MIZAR_USB_DCBAAP_HI; MIZAR_USB_ERSTSZ; MIZAR_USB_ERDP_LO; MIZAR_USB_ERDP_HI; MIZAR_USB_ERSTBA_LO; MIZAR_USB_ERSTBA_HI; MIZAR_USB_IMOD; MIZAR_USB_IMAN; MIZAR_USB_USBCMD; MIZAR_LSS_SYSREG_INTR_EN0; MIZAR_USB_USBSTS; Default_Event_Ring_Array; MIZAR_USB_DB; Default_Input_Context; Default_Command_Ring; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0; EP0_TR_Dequeue_Pointer",
        "Impacted Registers": "GCTL; GFLADJ; GUCTL; HCSPARAMS1; SUPTPRT2_DW2; SUPTPRT3_DW2; PORTSC_20; DBOFF; HCSPARAMS2; PAGESIZE; CRCR_LO; CRCR_HI; CONFIG; DCBAAP_LO; DCBAAP_HI; ERSTSZ; ERDP_LO; ERDP_HI; ERSTBA_LO; ERSTBA_HI; IMOD; IMAN; USBCMD; USBSTS; DB; CAPLENGTH",
        "Meta Validation / Acceptance Criteria": "Same as Full-Speed host enumeration plus Get Device Qualifier transfer completes. Event ring poll at Default_Event_Ring_Array+0x150 until non-zero.",
        "Validation / Acceptance Criteria": "Same as Full-Speed plus Get Device Qualifier transfer completes.",
        "Remarks": "Slot context 0x38300000 (High-Speed). GFLADJ 0xa07f000. Additional Get Device Qualifier request. Event ring poll at offset 0x150. The enumeration sequence follows the standard xHCI flow: Enable Slot, Address Device (BSR=0 then BSR=1), Configure Endpoint, followed by standard USB requests including Get Device Qualifier."
    },
    {
        "Index": "6",
        "SS / Module": "USB",
        "Test Case Name": "usb_host_enumeration_ls",
        "Feature": "Host Enumeration Low-Speed",
        "Meta Headers": "<stdio.h>; <stdlib.h>; \"usb.h\"",
        "Meta Macros": "NA",
        "Meta Arrays": "data_in[512]; data_out[512]",
        "Speed": "Low-Speed",
        "Mode": "Host Mode",
        "Memory Start Offset": "NA",
        "Memory End Offset": "NA",
        "Meta Test Description": "This testcase validates USB Host mode Low-Speed device enumeration. Same xHCI flow but with Low-Speed parameters. Slot context uses value 0x08200000 (indicating Low-Speed). GFLADJ value is 0xa87f000. No Configure Endpoint command (commented out in source). Third Get Configuration Descriptor requests 24 bytes (0x18) instead of 60 bytes. Event ring poll at offset 0x110.",
        "Test Description": "This test validates USB Host mode Low-Speed device enumeration. Same xHCI flow but with Low-Speed parameters. No Configure Endpoint command (commented out). Third Get Configuration Descriptor requests 24 bytes.",
        "Meta Test Steps / Procedure": "Same as Full-Speed host enumeration without Configure Endpoint command. Third Get Configuration Descriptor requests 24 bytes (0x18) instead of 60 bytes. Slot context 0x08200000. Event ring poll at Default_Event_Ring_Array+0x110.",
        "Test Steps / Procedure": "Same as Full-Speed host enumeration without Configure Endpoint. Third Get Config Descriptor is 24 bytes.",
        "Meta Impacted Registers": "MIZAR_USB_GCTL; MIZAR_USB_GFLADJ; MIZAR_USB_GUCTL; MIZAR_USB_HCSPARAMS1; MIZAR_USB_SUPTPRT2_DW2; MIZAR_USB_SUPTPRT3_DW2; MIZAR_USB_PORTSC_20; MIZAR_USB_DBOFF; Event_Ring_Segment_Table; MIZAR_USB_HCSPARAMS2; MIZAR_USB_PAGESIZE; Scratchpad_Buffer_Array; Device_Context_Base_Address_Array; MIZAR_USB_CRCR_LO; MIZAR_USB_CRCR_HI; MIZAR_USB_CONFIG; MIZAR_USB_DCBAAP_LO; MIZAR_USB_DCBAAP_HI; MIZAR_USB_ERSTSZ; MIZAR_USB_ERDP_LO; MIZAR_USB_ERDP_HI; MIZAR_USB_ERSTBA_LO; MIZAR_USB_ERSTBA_HI; MIZAR_USB_IMOD; MIZAR_USB_IMAN; MIZAR_USB_USBCMD; MIZAR_LSS_SYSREG_INTR_EN0; MIZAR_USB_USBSTS; Default_Event_Ring_Array; MIZAR_USB_DB; Default_Input_Context; Default_Command_Ring; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0; EP0_TR_Dequeue_Pointer",
        "Impacted Registers": "GCTL; GFLADJ; GUCTL; HCSPARAMS1; SUPTPRT2_DW2; SUPTPRT3_DW2; PORTSC_20; DBOFF; HCSPARAMS2; PAGESIZE; CRCR_LO; CRCR_HI; CONFIG; DCBAAP_LO; DCBAAP_HI; ERSTSZ; ERDP_LO; ERDP_HI; ERSTBA_LO; ERSTBA_HI; IMOD; IMAN; USBCMD; USBSTS; DB; CAPLENGTH",
        "Meta Validation / Acceptance Criteria": "Same as Full-Speed host enumeration. All enumeration transfers complete. Event ring poll at Default_Event_Ring_Array+0x110 until non-zero.",
        "Validation / Acceptance Criteria": "Same as Full-Speed. All enumeration transfers complete. Event ring poll at offset 0x110.",
        "Remarks": "Slot context 0x08200000 (Low-Speed). GFLADJ 0xa87f000. Configure Endpoint commented out. Third Get Config Descriptor 24 bytes. Event ring poll at 0x110. The Configure Endpoint command and interrupt endpoint transfer code are commented out in the source, so the test only performs Enable Slot and Address Device commands before enumeration transfers."
    }
]

tp_cols = [
    "Index", "SS / Module", "Feature", "Test Case Name", "Test Description",
    "Speed", "Mode", "Memory Start Offset", "Memory End Offset", "Remarks",
    "Test Steps / Procedure", "Impacted Registers", "Validation / Acceptance Criteria",
    "Code Generation"
]

md_cols = [
    "Index", "Test Case Name", "Meta Test Description", "Meta Test Steps / Procedure",
    "Meta Impacted Registers", "Meta Validation / Acceptance Criteria",
    "Meta Headers", "Meta Macros", "Meta Arrays"
]

wb = Workbook()
ws_tp = wb.active
ws_tp.title = "TestPlan"

header_font = Font(bold=True, color="FFFFFF", size=11)
header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
wrap_align = Alignment(wrap_text=True, vertical="top")

for col_idx, col_name in enumerate(tp_cols, 1):
    cell = ws_tp.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = wrap_align

for row_idx, row_data in enumerate(json_data, 2):
    for col_idx, col_name in enumerate(tp_cols, 1):
        value = row_data.get(col_name, "")
        cell = ws_tp.cell(row=row_idx, column=col_idx, value=value if value else "")
        cell.alignment = wrap_align

ws_tp.freeze_panes = "A2"

for col_idx, col_name in enumerate(tp_cols, 1):
    max_len = len(col_name)
    for row in range(2, len(json_data) + 2):
        val = ws_tp.cell(row=row, column=col_idx).value
        if val:
            max_len = max(max_len, min(len(str(val)), 80))
    width = min(max_len + 2, 60)
    ws_tp.column_dimensions[get_column_letter(col_idx)].width = width

ws_md = wb.create_sheet("MetaData")

for col_idx, col_name in enumerate(md_cols, 1):
    cell = ws_md.cell(row=1, column=col_idx, value=col_name)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = wrap_align

for row_idx, row_data in enumerate(json_data, 2):
    for col_idx, col_name in enumerate(md_cols, 1):
        value = row_data.get(col_name, "")
        cell = ws_md.cell(row=row_idx, column=col_idx, value=value if value else "")
        cell.alignment = wrap_align

ws_md.freeze_panes = "A2"

for col_idx, col_name in enumerate(md_cols, 1):
    max_len = len(col_name)
    for row in range(2, len(json_data) + 2):
        val = ws_md.cell(row=row, column=col_idx).value
        if val:
            max_len = max(max_len, min(len(str(val)), 80))
    width = min(max_len + 2, 60)
    ws_md.column_dimensions[get_column_letter(col_idx)].width = width

ws_md.sheet_state = "veryHidden"

wb.save(FILENAME)
print(f"SUCCESS: Workbook saved as {FILENAME}")
print(f"TestPlan rows: {len(json_data)}")
print(f"MetaData rows: {len(json_data)}")

try:
    wb2 = load_workbook(FILENAME)
    assert "TestPlan" in wb2.sheetnames
    assert "MetaData" in wb2.sheetnames
    print("VALIDATION: PASSED")
except Exception as e:
    print(f"VALIDATION: FAILED - {e}")

print(f"File size: {os.path.getsize(FILENAME)} bytes")
print(f"Full path: {os.path.abspath(FILENAME)}")
