#!/usr/bin/env python3
"""Generate USB TestPlan Excel workbook using openpyxl"""
import json
import os
from datetime import datetime, timezone, timedelta
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

# IST timezone
IST = timezone(timedelta(hours=5, minutes=30))
now_ist = datetime.now(IST)
timestamp = now_ist.strftime("%Y%m%d_%H%M%S")
filename = f"USB_TestPlan_{timestamp}.xlsx"

# Input data
json_data = [
    {"Index":"1","SS / Module":"USB","Test Case Name":"USB_FS_Device_Bulk_Transfer_test","Feature":"Full-Speed Device Bulk Transfer","Meta Headers":"<stdio.h>; <stdlib.h>; \"usb.h\"","Meta Macros":"Buffer_PointerLO; Buffer_PointerLO_1; event_trb_addr; Default_Event_Ring_Array; DWORD; MIZAR_USB_DCTL; MIZAR_USB_GUSB2PHYCFG; MIZAR_USB_GEVNTADRLO; MIZAR_USB_GEVNTADRHI; MIZAR_USB_GEVNTSIZ; MIZAR_USB_GEVNTCOUNT; MIZAR_USB_GCTL; MIZAR_USB_DCFG; MIZAR_USB_DEVTEN; MIZAR_USB_GUCTL; MIZAR_USB_DEPCMDPAR0; MIZAR_USB_DEPCMDPAR1; MIZAR_USB_DEPCMD; MIZAR_USB_DALEPENA; MIZAR_USB_DSTS; MIZAR_LSS_SYSREG_INTR_EN0; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0","Meta Arrays":"buf_data[16]","Speed":"Full-Speed","Mode":"Device Mode","Memory Start Offset":"RAM+0x1100","Memory End Offset":"RAM+0x3000","Meta Test Description":"This testcase validates USB Full-Speed Device mode Bulk Transfer operation.","Test Description":"This test validates USB Full-Speed Device mode Bulk Transfer functionality. The USB controller is soft-reset and the USB2 PHY is configured. The event ring buffer is initialized using GEVNTADRLO, GEVNTADRHI, GEVNTSIZ, and GEVNTCOUNT registers. The global controller is configured via GCTL for device-mode port direction, and device configuration is set through DCFG. Device events are enabled via DEVTEN, and the user control register GUCTL is configured. Multiple endpoints are configured using DEPCMDPAR0, DEPCMDPAR1, and DEPCMD registers with polling for command completion. Transfer resources are allocated for 8 endpoints. Physical endpoints are enabled via DALEPENA, and the controller run state is set through DCTL. System-level interrupts are enabled. The test then performs USB device enumeration including SET ADDRESS, GET DEVICE DESCRIPTOR, GET CONFIGURATION DESCRIPTOR (short and full), and SET CONFIGURATION phases, each using Transfer Request Blocks (TRBs) and endpoint command sequences. After enumeration, all endpoints are enabled and Bulk OUT and Bulk IN transfers are initiated on the configured bulk endpoints. An interrupt handler processes USB events by reading event count from GEVNTCOUNT, acknowledging events, and clearing system-level interrupt status. The test verifies successful completion of the full-speed bulk transfer cycle.","Meta Test Steps / Procedure":"Steps as generated by Agent 5 for folder 1","Test Steps / Procedure":"1. Initialize the NIC and enable all GIC interrupts. 2. Clear the data buffer and event TRB memory regions. 3. Perform a soft reset of the USB controller via DCTL and poll until reset completes. 4. Configure the USB2 PHY via GUSB2PHYCFG. 5. Set up the event ring. 6. Configure the global controller via GCTL. 7. Set device configuration in DCFG, enable device events in DEVTEN, and configure GUCTL. 8. Configure 9 endpoints. 9. Allocate transfer resources for 8 endpoints. 10. Enable physical endpoints via DALEPENA and set run state via DCTL. 11. Enable system-level USB interrupt and wait for link state events. 12-20. Perform enumeration and Bulk OUT/IN transfers. 20. Verify test completion.","Meta Impacted Registers":"Buffer_PointerLO; event_trb_addr; MIZAR_USB_DCTL; MIZAR_USB_GUSB2PHYCFG; MIZAR_USB_GEVNTADRLO; MIZAR_USB_GEVNTADRHI; MIZAR_USB_GEVNTSIZ; MIZAR_USB_GEVNTCOUNT; MIZAR_USB_GCTL; MIZAR_USB_DCFG; MIZAR_USB_DEVTEN; MIZAR_USB_GUCTL; MIZAR_USB_DEPCMDPAR0; MIZAR_USB_DEPCMD; MIZAR_USB_DALEPENA; MIZAR_LSS_SYSREG_INTR_EN0; 0xA0243ffc; MIZAR_USB_DSTS; MIZAR_USB_DEPCMDPAR1; 0xa0243ff4; 0xa0243ff8; MIZAR_LSS_SYSREG_MSK_STS0; MIZAR_LSS_SYSREG_RAW_STCR0","Impacted Registers":"DCTL; GUSB2PHYCFG; GEVNTADRLO; GEVNTADRHI; GEVNTSIZ; GEVNTCOUNT; GCTL; DCFG; DEVTEN; GUCTL; DEPCMDPAR0; DEPCMD; DALEPENA; DSTS; DEPCMDPAR1","Meta Validation / Acceptance Criteria":"Soft reset, endpoint command completion, interrupt-driven event processing validations","Validation / Acceptance Criteria":"1. Soft reset completes. 2. All endpoint commands complete. 3. Transfer resources allocated. 4. Events received via interrupts. 5. Enumeration completes. 6. Bulk OUT/IN transfers complete. 7. Test reaches finish.","Remarks":"Full-Speed Device mode with GIC IRQ 84. Bulk transfers use endpoint offsets +0x40 (OUT) and +0x50 (IN)."},
    {"Index":"2","SS / Module":"USB","Test Case Name":"USB_FS_Device_Interrupt_Transfer_test","Feature":"Full-Speed Device Interrupt Transfer","Speed":"Full-Speed","Mode":"Device Mode","Test Description":"This test validates USB Full-Speed Device mode Interrupt Transfer functionality with interrupt OUT/IN endpoints at offsets +0x20 and +0x30. Includes DSTS frame number validation after interrupt transfers.","Test Steps / Procedure":"Same as folder 1 but with Interrupt OUT/IN transfers on endpoints +0x20 and +0x30 instead of Bulk endpoints.","Impacted Registers":"DCTL; GUSB2PHYCFG; GEVNTADRLO; GEVNTADRHI; GEVNTSIZ; GEVNTCOUNT; GCTL; DCFG; DEVTEN; GUCTL; DEPCMDPAR0; DEPCMD; DALEPENA; DSTS; DEPCMDPAR1","Validation / Acceptance Criteria":"1. Soft reset completes. 2. All endpoint commands complete. 3. Interrupt OUT/IN transfers complete. 4. Valid frame number detected via DSTS polling. 5. Test reaches finish.","Remarks":"Interrupt transfers use TRB control 0x815 (OUT) and 0x813 (IN) with 64-byte transfer length."},
    {"Index":"3","SS / Module":"USB","Test Case Name":"USB_FS_Device_Isochronous_Transfer_test","Feature":"Full-Speed Device Isochronous Transfer","Speed":"Full-Speed","Mode":"Device Mode","Test Description":"This test validates USB Full-Speed Device mode Isochronous Transfer with isochronous OUT/IN endpoints at offsets +0x60 and +0x70. Includes micro-frame number validations via DSTS polling.","Test Steps / Procedure":"Same as folder 1 but with Isochronous OUT (cmd 0x20506) and IN (cmd 0x40506) transfers. TRB control 0x869, 1023-byte length.","Impacted Registers":"DCTL; GUSB2PHYCFG; GEVNTADRLO; GEVNTADRHI; GEVNTSIZ; GEVNTCOUNT; GCTL; DCFG; DEVTEN; GUCTL; DEPCMDPAR0; DEPCMD; DALEPENA; DSTS; DEPCMDPAR1","Validation / Acceptance Criteria":"1. Soft reset completes. 2. All endpoint commands complete. 3. Isochronous OUT/IN transfers complete. 4. Micro-frame numbers 2, 3, 4 validated via DSTS. 5. Test reaches finish.","Remarks":"Isochronous transfers use TRB control 0x869 (isochronous-first type) with 1023-byte transfer length."},
    {"Index":"4","SS / Module":"USB","Test Case Name":"usb_host_enumeration_fs","Feature":"Host Mode Full-Speed Device Enumeration","Speed":"Full-Speed","Mode":"Host Mode","Test Description":"This test validates USB Host mode enumeration of a Full-Speed device using the xHCI host controller. Includes Enable Slot, Address Device, Configure Endpoint, and standard USB requests.","Test Steps / Procedure":"xHCI host controller initialization, port status change detection, port reset, Enable Slot, Address Device (BSR=1 and BSR=0), Configure Endpoint, GET DEVICE DESCRIPTOR, GET CONFIG DESC short/full, SET CONFIGURATION.","Impacted Registers":"GCTL; GFLADJ; GUCTL; HCSPARAMS1; SUPTPRT2_DW2; SUPTPRT3_DW2; PORTSC_20; DBOFF; HCSPARAMS2; PAGESIZE; CRCR_LO; CRCR_HI; CONFIG; DCBAAP_LO; DCBAAP_HI; ERSTSZ; ERDP_LO; ERDP_HI; ERSTBA_LO; ERSTBA_HI; IMOD; IMAN; USBCMD; USBSTS; DB","Validation / Acceptance Criteria":"1. Port status change received. 2. Port reset completes. 3. Enable Slot, Address Device, Configure Endpoint succeed. 4. All enumeration requests complete. 5. Test reaches finish.","Remarks":"Host mode using xHCI. Slot context 0x08100000 (FS speed bits=0x1). EP0 max packet size 64 bytes."},
    {"Index":"5","SS / Module":"USB","Test Case Name":"usb_host_enumeration_hs","Feature":"Host Mode High-Speed Device Enumeration","Speed":"High-Speed","Mode":"Host Mode","Test Description":"This test validates USB Host mode enumeration of a High-Speed device using the xHCI host controller. Includes GET QUALIFIER request (HS-specific).","Test Steps / Procedure":"Same as folder 4 but with HS slot context 0x08300000, GFLADJ 0xa07f000, includes GET QUALIFIER, 3x GET CONFIG DESC.","Impacted Registers":"GCTL; GFLADJ; GUCTL; HCSPARAMS1; SUPTPRT2_DW2; SUPTPRT3_DW2; PORTSC_20; DBOFF; HCSPARAMS2; PAGESIZE; CRCR_LO; CRCR_HI; CONFIG; DCBAAP_LO; DCBAAP_HI; ERSTSZ; ERDP_LO; ERDP_HI; ERSTBA_LO; ERSTBA_HI; IMOD; IMAN; USBCMD; USBSTS; DB","Validation / Acceptance Criteria":"1. Port status change received. 2. Port reset completes. 3. Enable Slot, Address Device succeed with HS slot context. 4. All enumeration requests including GET QUALIFIER complete. 5. Test reaches finish.","Remarks":"Host mode using xHCI. Slot context 0x08300000 (HS speed bits=0x3). GFLADJ=0xa07f000. Includes GET QUALIFIER."},
    {"Index":"6","SS / Module":"USB","Test Case Name":"usb_host_enumeration_ls","Feature":"Host Mode Low-Speed Device Enumeration","Speed":"Low-Speed","Mode":"Host Mode","Test Description":"This test validates USB Host mode enumeration of a Low-Speed device using the xHCI host controller. EP0 max packet size is 8 bytes (LS-specific).","Test Steps / Procedure":"Same as folder 4 but with LS slot context 0x08200000, EP0 max packet size 8 bytes. Configure Endpoint is commented out.","Impacted Registers":"GCTL; GFLADJ; GUCTL; HCSPARAMS1; SUPTPRT2_DW2; SUPTPRT3_DW2; PORTSC_20; DBOFF; HCSPARAMS2; PAGESIZE; CRCR_LO; CRCR_HI; CONFIG; DCBAAP_LO; DCBAAP_HI; ERSTSZ; ERDP_LO; ERDP_HI; ERSTBA_LO; ERSTBA_HI; IMOD; IMAN; USBCMD; USBSTS; DB","Validation / Acceptance Criteria":"1. Port status change received. 2. Port reset completes. 3. Enable Slot, Address Device succeed with LS slot context. 4. All enumeration requests complete. 5. Test reaches finish.","Remarks":"Host mode using xHCI. Slot context 0x08200000 (LS speed bits=0x2). EP0 max packet size 8 bytes. Configure Endpoint commented out."}
]

# Column definitions
testplan_cols = ["Index", "SS / Module", "Feature", "Test Case Name", "Test Description", "Speed", "Mode", "Memory Start Offset", "Memory End Offset", "Remarks", "Test Steps / Procedure", "Impacted Registers", "Validation / Acceptance Criteria", "Code Generation"]
metadata_cols = ["Index", "Test Case Name", "Meta Test Description", "Meta Test Steps / Procedure", "Meta Impacted Registers", "Meta Validation / Acceptance Criteria", "Meta Headers", "Meta Macros", "Meta Arrays"]

# Create workbook
wb = Workbook()
ws_tp = wb.active
ws_tp.title = "TestPlan"
ws_md = wb.create_sheet("MetaData")

# Formatting
header_font = Font(bold=True, color="FFFFFF", size=11)
header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
wrap_align = Alignment(wrap_text=True, vertical="top")
thin_border = Border(
    left=Side(style='thin'), right=Side(style='thin'),
    top=Side(style='thin'), bottom=Side(style='thin')
)

def write_sheet(ws, columns, data):
    # Write headers
    for col_idx, col_name in enumerate(columns, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = wrap_align
        cell.border = thin_border
    # Write data
    for row_idx, row_data in enumerate(data, 2):
        for col_idx, col_name in enumerate(columns, 1):
            value = row_data.get(col_name, "")
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.alignment = wrap_align
            cell.border = thin_border

# Populate sheets
write_sheet(ws_tp, testplan_cols, json_data)
write_sheet(ws_md, metadata_cols, json_data)

# Freeze first row
ws_tp.freeze_panes = "A2"
ws_md.freeze_panes = "A2"

# Auto-size columns
def auto_size(ws, columns):
    for col_idx, col_name in enumerate(columns, 1):
        max_len = len(col_name)
        for row in range(2, ws.max_row + 1):
            val = ws.cell(row=row, column=col_idx).value
            if val:
                max_len = max(max_len, min(len(str(val)), 80))
        ws.column_dimensions[ws.cell(row=1, column=col_idx).column_letter].width = min(max_len + 2, 60)

auto_size(ws_tp, testplan_cols)
auto_size(ws_md, metadata_cols)

# Set MetaData sheet to veryHidden
ws_md.sheet_state = "veryHidden"

# Save
output_path = os.path.join(os.path.dirname(__file__) or ".", filename)
wb.save(output_path)
print(f"GENERATED: {filename}")
print(f"PATH: {output_path}")
print(f"SIZE: {os.path.getsize(output_path)} bytes")
