#include <stdlib.h>
#include <stdio.h>
#include <test_common.h>
#include "pcie.h"

/*
 * Generated by 3_Code_Generation Agent
 * Source: Meta TestPlan JSON (verbatim)
 * Note: Register arrays below are derived strictly from Meta Impacted Registers
 * using RAG mapping identifiers. No additional registers are introduced.
 */

/* Impacted registers array (addresses are expected to be provided via included headers) */
static const unsigned int impacted_registers[] = {
    mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF,
    mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF
};

static const unsigned int impacted_registers_count = (sizeof(impacted_registers) / sizeof(impacted_registers[0]));

/* Skip Registers array (none specified in Meta Arrays) */
static const unsigned int *skip_registers = 0; /* empty */
static const unsigned int skip_registers_count = 0u;
