/* Auto-generated by Test_Stage3 Agent
 * Testcase: test_gpio_negedge_intr_en
 * Description (from plan): Exercise per-pin negative-edge interrupts for GPIO[8..39]:
 *  - Configure each pin, enable one pin at a time
 *  - Generate a falling edge via 0xA0243ffc toggling
 *  - Wait for ISR to clear int_pend
 *  - Verify group status bit set and cleared, and clear system/GIC status
 * Acceptance: No timeouts; proper status observation/clear; finish(0) on success
 */

#include "test_define.c"

/* Globals used for ISR synchronization and simple result accounting */
volatile unsigned int int_pend = 0;            /* 1 => waiting for IRQ; 0 => IRQ observed */
volatile unsigned int g_curr_pin_idx = 0;      /* current pin under test: 0..31 maps to GPIO[8..39] */
volatile unsigned int test_err = 0;            /* cumulative error counter */

/* Helper for debug prints to keep output consistent */
#define LOGI(...) DEBUG_DISPLAY(__VA_ARGS__)

/* Default IRQ handler per CSV. Platform will route GPIO IRQ here. */
void Default_IRQHandler(void)
{
    unsigned int local_idx = g_curr_pin_idx;          /* snapshot the pin index */
    unsigned int local_wr  = (1u << local_idx);       /* bit mask for the pin within group */
    unsigned int base_addr = MIZAR_GPIO_GP0_GPIO_8;   /* base register for GPIO_8 */
    unsigned int raddr     = base_addr + (local_idx * 4u);

    /* A) acknowledge pending and drive pad high to stop further edges */
    int_pend = 0;
    write_reg(0xA0243ffc, 0xFFFFFFFFu);

    /* B) Read per-pin register; check bit0 expected 0 per plan */
    unsigned int rdata = read_reg(raddr);
    if ((rdata & 0x1u) != 0u) {
        LOGI("[ISR] GPIO pin reg bit0 set unexpectedly, idx=%u r=0x%08x\n", local_idx, rdata);
        test_err++;
    }

    /* C) Expect event status (bit1) non-zero -> verify group status then clear */
    if ((rdata & 0x2u) != 0u) {
        unsigned int rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
        if ((rdata_grp & local_wr) == 0u) {
            LOGI("[ISR] Group STS missing bit for idx=%u sts=0x%08x\n", local_idx, rdata_grp);
            test_err++;
        }
        /* Clear per-pin raw/event as described */
        write_reg(raddr, (1u<<20) | (1u<<16));
        write_reg(MIZAR_GPIO_GPIO_INTR_RAW_STCLR1, local_wr);
        /* Verify group status cleared */
        rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
        if (rdata_grp != 0x0u) {
            LOGI("[ISR] Group STS not cleared, sts=0x%08x\n", rdata_grp);
            test_err++;
        }
        /* Clear system raw/GIC side */
    #if defined(GPIO0)
        write_reg(MIZAR_LSS_SYSREG_RAW_STCR1, LSS_SYSREG_RAW_STCR1_GPIO0_INTR);
        GIC_ClearIRQ(87);
    #elif defined(GPIO1)
        write_reg(MIZAR_LSS_SYSREG_RAW_STCR1, LSS_SYSREG_RAW_STCR1_GPIO1_INTR);
        GIC_ClearIRQ(88);
    #else
        LOGI("[ISR] Neither GPIO0 nor GPIO1 defined\n");
        test_err++;
    #endif
    } else {
        LOGI("[ISR] Expected event bit not set for idx=%u r=0x%08x\n", local_idx, rdata);
        test_err++;
    }
}

/* Test entry point */
void test_case(void)
{
    LOGI("[TEST] Start: test_gpio_negedge_intr_en\n");

    /* 1) Initialize interrupt routing and system enable */
#if defined(GPIO0)
    GIC_EnableIRQ(87);
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, LSS_SYSREG_INTR_EN1_GPIO0_INTR);
#elif defined(GPIO1)
    GIC_EnableIRQ(88);
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, LSS_SYSREG_INTR_EN1_GPIO1_INTR);
#else
    LOGI("[TEST] Error: Neither GPIO0 nor GPIO1 defined.\n");
    test_err++;
#endif

    /* 2) Initialize drive: default high */
    write_reg(0xA0243ffc, 0xFFFFFFFFu);

    /* 3) Configure per-pin regs for negedge detection and enable paths */
    for (unsigned int i = 0; i < 32u; ++i) {
        unsigned int addr1 = MIZAR_GPIO_GP0_GPIO_8 + (i * 4u);
        write_reg(addr1, (1u<<20) | (1u<<18) | (1u<<16));
        wait_on(10);
    }

    /* 4) Iterate per pin: enable one, generate falling edge, wait for ISR */
    for (unsigned int i = 0; i < 32u; ++i) {
        unsigned int wr_val = (1u << i);
        unsigned int timeout = 5000u;

        /* a) Clear raw status */
        write_reg(MIZAR_GPIO_GPIO_INTR_RAW_STCLR1, wr_val);

        /* b) Enable only this pin interrupt */
        write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, wr_val);
        wait_on(10);

        /* c) Arm and generate negedge */
        g_curr_pin_idx = i;
        int_pend = 1;
        write_reg(0xA0243ffc, 0xFFFFFFFFu); /* drive high */
        wait_on(30);
        write_reg(0xA0243ffc, ~wr_val);      /* drive target pin low -> falling edge */

        /* d) Poll for ISR completion with timeout */
        while (int_pend && timeout--) {
            wait_on(10);
        }
        if (int_pend != 0u) {
            LOGI("[TEST] Timeout waiting for pin %u IRQ\n", i);
            test_err++;
            /* attempt to recover drive high and proceed */
            write_reg(0xA0243ffc, 0xFFFFFFFFu);
        }
    }

    /* 5) Final result */
    if (test_err == 0u) {
        LOGI("[TEST] PASS: test_gpio_negedge_intr_en\n");
        finish(0);
    } else {
        LOGI("[TEST] FAIL: errors=%u\n", test_err);
        finish(1);
    }
}
