#include <stdio.h>
#include <lss_sysreg.h>
#include <test_common.h>
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

// Generated by Test_Stage3 Agent (IP: GPIO)
// Testcase: test_gpio_negedge_intr_en
// Notes:
// - Header includes and user-provided defines are preserved.
// - Register names and bit usage come only from GP0_RAG/LSS_RAG inputs and CSV context.
// - No register maps or field definitions are invented here.

// Unchanged defines from testcase context
#define CNT 49

// Bit mapping available from GP0_RAG for RAW_STCLR1/INTR1_EN1: Bit0 corresponds to GPIO_8
#define GPIO_BIT_GPIO8   (1u << 0)

// Impacted registers used (limited to those present in RAG inputs)
// - MIZAR_GPIO_GPIO_INTR_RAW_STCLR1 (VRRW, reset 0)
// - MIZAR_GPIO_GP0_INTR1_INTR_EN1   (RW,   reset 0)
static const unsigned long addr_array[2] = {
    MIZAR_GPIO_GPIO_INTR_RAW_STCLR1,
    MIZAR_GPIO_GP0_INTR1_INTR_EN1,
};

static const unsigned int default_value_array[2] = { 0u, 0u };
static const unsigned int skip_array[2] = { 0u, 0u };

// Optional debug print macro
#ifdef DEBUG_DISPLAY
#define DBG_PRINTF(...) printf(__VA_ARGS__)
#else
#define DBG_PRINTF(...)
#endif
