/* Auto-generated by Test_Stage3 Agent for testcase: test_gpio_negedge_intr_en
 * High-level intent: Exercise per-pin negative-edge interrupts for GPIO[8..39].
 * Uses only provided inputs (headers/defines) and CSV-described procedure.
 * NOTE: All headers and defines are placed here; program.c includes only this file.
 */

/* Header includes (unchanged from testcase context) */
#include <stdio.h>
#include <lss_sysreg.h>
#include <test_common.h>
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/* Macro definitions (unchanged from testcase context) */
#define CNT 49

/* No other code here by design. program.c will include only this file. */
