#define MIZAR_PCIE1_SII_BASE 0xE68C1000
#include <pcie1/pcie_sii_rc_def.h>
#include <pcie1/pcie_sii_rc_offset.h>
"test_common.h"
"test_define.c"

#define CNT 153
#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST REG DATA 0x00000000

const unsigned long int addr_array[20]={mizar_PCIE1_SII_CFG_BAR0_START1,mizar_PCIE1_SII_CFG_BAR0_START2,mizar_PCIE1_SII_CFG_BAR0_LIMIT1,mizar_PCIE1_SII_CFG_BAR0_LIMIT2,mizar_PCIE1_SII_CFG_BAR1_START,mizar_PCIE1_SII_CFG_BAR1_LIMIT1,mizar_PCIE1_SII_CFG_BAR2_START1,mizar_PCIE1_SII_CFG_BAR2_START2,mizar_PCIE1_SII_CFG_BAR2_LIMIT1,mizar_PCIE1_SII_CFG_BAR2_LIMIT2,};

const int default_value_array[20]={PCIE1_SII_CFG_BAR0_START1_DEFAULT VAL,PCIE1_SII_CFG_BAR0_START2_DEFAULT VAL,PCIE1_SII_CFG_BAR0_LIMIT1_DEFAULT VAL,PCIE1_SII_CFG_BAR0_LIMIT2_DEFAULT VAL,PCIE1_SII_CFG_BAR1_START_DEFAULT VAL,PCIE1_SII_CFG_BAR1_LIMIT1_DEFAULT VAL,PCIE1_SII_CFG_BAR2_START1_DEFAULT VAL,PCIE1_SII_CFG_BAR2_START2_DEFAULT VAL,PCIE1_SII_CFG_BAR2_LIMIT1_DEFAULT VAL,PCIE1_SII_CFG_BAR2_LIMIT2_DEFAULT VAL,};

const int read_mask_array[20]={PCIE1_SII_CFG_BAR0_START1_READ MASK,PCIE1_SII_CFG_BAR0_START2_READ MASK,PCIE1_SII_CFG_BAR0_LIMIT1_READ MASK,PCIE1_SII_CFG_BAR0_LIMIT2_READ MASK,PCIE1_SII_CFG_BAR1_START_READ MASK,PCIE1_SII_CFG_BAR1_LIMIT1_READ MASK,PCIE1_SII_CFG_BAR2_START1_READ MASK,PCIE1_SII_CFG_BAR2_START2_READ MASK,PCIE1_SII_CFG_BAR2_LIMIT1_READ MASK,PCIE1_SII_CFG_BAR2_LIMIT2_READ MASK,};

const int write_mask_array[20]={PCIE1_SII_CFG_BAR0_START1_WRITE MASK,PCIE1_SII_CFG_BAR0_START2_WRITE MASK,PCIE1_SII_CFG_BAR0_LIMIT1_WRITE MASK,PCIE1_SII_CFG_BAR0_LIMIT2_WRITE MASK,PCIE1_SII_CFG_BAR1_START_WRITE MASK,PCIE1_SII_CFG_BAR1_LIMIT1_WRITE MASK,PCIE1_SII_CFG_BAR2_START1_WRITE MASK,PCIE1_SII_CFG_BAR2_START2_WRITE MASK,PCIE1_SII_CFG_BAR2_LIMIT1_WRITE MASK,PCIE1_SII_CFG_BAR2_LIMIT2_WRITE MASK,};

const int skip_array[20]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,};

const unsigned long int impacted_registers[] = {
    mizar_PCIE1_SII_CFG_BAR0_START1,
    mizar_PCIE1_SII_CFG_BAR0_START2,
    mizar_PCIE1_SII_CFG_BAR0_LIMIT1,
    mizar_PCIE1_SII_CFG_BAR0_LIMIT2,
    mizar_PCIE1_SII_CFG_BAR1_START,
    mizar_PCIE1_SII_CFG_BAR1_LIMIT1,
    mizar_PCIE1_SII_CFG_BAR2_START1,
    mizar_PCIE1_SII_CFG_BAR2_START2,
    mizar_PCIE1_SII_CFG_BAR2_LIMIT1,
    mizar_PCIE1_SII_CFG_BAR2_LIMIT2,
    mizar_PCIE1_SII_PHY_RST_CONTROL
};
