#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include "test_define.c"
#include <pcie.h>

#define CNT 775, #define SOFT_RST_REG ADDRESS 0x00000000, #define SOFT_RST_REG_DATA 0x00000000

/* Impacted Registers Address Array (from RAG-mapped macros) */
const unsigned long int addr_array[] = {
    mizar_PCIE1_DBI_USP_TYPE1_DEV_ID_VEND_ID_REG,
    mizar_PCIE1_DBI_USP_TYPE1_STATUS_COMMAND_REG,
    mizar_PCIE1_DBI_USP_TYPE1_CLASS_CODE_REV_ID_REG,
    mizar_PCIE1_DBI_USP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG,
    mizar_PCIE1_DBI_USP_BAR0_REG,
    mizar_PCIE1_DBI_USP_BAR1_REG,
    mizar_PCIE1_DBI_USP_SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG,
    mizar_PCIE1_DBI_USP_SEC_STAT_IO_LIMIT_IO_BASE_REG,
    mizar_PCIE1_DBI_USP_MEM_LIMIT_MEM_BASE_REG,
    mizar_PCIE1_DBI_USP_PREF_MEM_LIMIT_PREF_MEM_BASE_REG,
    mizar_PCIE1_DBI_USP_PREF_BASE_UPPER_REG,
    mizar_PCIE1_DBI_USP_PREF_LIMIT_UPPER_REG,
    mizar_PCIE1_DBI_USP_IO_LIMIT_UPPER_IO_BASE_UPPER_REG,
    mizar_PCIE1_DBI_USP_CAP_ID_NXT_PTR_REG,
    mizar_PCIE1_DBI_USP_DEVICE_CONTROL_DEVICE_STATUS,
    mizar_PCIE1_DBI_USP_PL_DEBUG1_OFF
};

/* Default values, Read masks, Write masks (macro-referenced; values provided by platform headers) */
const unsigned int default_value_array[] = {
    PCIE1_DBI_USP_TYPE1_DEV_ID_VEND_ID_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_TYPE1_STATUS_COMMAND_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_TYPE1_CLASS_CODE_REV_ID_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_BAR0_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_BAR1_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_SEC_STAT_IO_LIMIT_IO_BASE_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_MEM_LIMIT_MEM_BASE_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_PREF_MEM_LIMIT_PREF_MEM_BASE_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_PREF_BASE_UPPER_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_PREF_LIMIT_UPPER_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_IO_LIMIT_UPPER_IO_BASE_UPPER_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_CAP_ID_NXT_PTR_REG_DEFAULT_VAL,
    PCIE1_DBI_USP_DEVICE_CONTROL_DEVICE_STATUS_DEFAULT_VAL,
    PCIE1_DBI_USP_PL_DEBUG1_OFF_DEFAULT_VAL
};

const unsigned int read_mask_array[] = {
    PCIE1_DBI_USP_TYPE1_DEV_ID_VEND_ID_REG_READ_MASK,
    PCIE1_DBI_USP_TYPE1_STATUS_COMMAND_REG_READ_MASK,
    PCIE1_DBI_USP_TYPE1_CLASS_CODE_REV_ID_REG_READ_MASK,
    PCIE1_DBI_USP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG_READ_MASK,
    PCIE1_DBI_USP_BAR0_REG_READ_MASK,
    PCIE1_DBI_USP_BAR1_REG_READ_MASK,
    PCIE1_DBI_USP_SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG_READ_MASK,
    PCIE1_DBI_USP_SEC_STAT_IO_LIMIT_IO_BASE_REG_READ_MASK,
    PCIE1_DBI_USP_MEM_LIMIT_MEM_BASE_REG_READ_MASK,
    PCIE1_DBI_USP_PREF_MEM_LIMIT_PREF_MEM_BASE_REG_READ_MASK,
    PCIE1_DBI_USP_PREF_BASE_UPPER_REG_READ_MASK,
    PCIE1_DBI_USP_PREF_LIMIT_UPPER_REG_READ_MASK,
    PCIE1_DBI_USP_IO_LIMIT_UPPER_IO_BASE_UPPER_REG_READ_MASK,
    PCIE1_DBI_USP_CAP_ID_NXT_PTR_REG_READ_MASK,
    PCIE1_DBI_USP_DEVICE_CONTROL_DEVICE_STATUS_READ_MASK,
    PCIE1_DBI_USP_PL_DEBUG1_OFF_READ_MASK
};

const unsigned int write_mask_array[] = {
    PCIE1_DBI_USP_TYPE1_DEV_ID_VEND_ID_REG_WRITE_MASK,
    PCIE1_DBI_USP_TYPE1_STATUS_COMMAND_REG_WRITE_MASK,
    PCIE1_DBI_USP_TYPE1_CLASS_CODE_REV_ID_REG_WRITE_MASK,
    PCIE1_DBI_USP_TYPE1_BIST_HDR_TYPE_LAT_CACHE_LINE_SIZE_REG_WRITE_MASK,
    PCIE1_DBI_USP_BAR0_REG_WRITE_MASK,
    PCIE1_DBI_USP_BAR1_REG_WRITE_MASK,
    PCIE1_DBI_USP_SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG_WRITE_MASK,
    PCIE1_DBI_USP_SEC_STAT_IO_LIMIT_IO_BASE_REG_WRITE_MASK,
    PCIE1_DBI_USP_MEM_LIMIT_MEM_BASE_REG_WRITE_MASK,
    PCIE1_DBI_USP_PREF_MEM_LIMIT_PREF_MEM_BASE_REG_WRITE_MASK,
    PCIE1_DBI_USP_PREF_BASE_UPPER_REG_WRITE_MASK,
    PCIE1_DBI_USP_PREF_LIMIT_UPPER_REG_WRITE_MASK,
    PCIE1_DBI_USP_IO_LIMIT_UPPER_IO_BASE_UPPER_REG_WRITE_MASK,
    PCIE1_DBI_USP_CAP_ID_NXT_PTR_REG_WRITE_MASK,
    PCIE1_DBI_USP_DEVICE_CONTROL_DEVICE_STATUS_WRITE_MASK,
    PCIE1_DBI_USP_PL_DEBUG1_OFF_WRITE_MASK
};

/* Skip array: derived from Meta Arrays (no explicit skip list provided → all zeros) */
const unsigned int skip_array[] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
};
