#!/usr/bin/env python3
"""
PCIE TestPlan XLSX Generator - Agent 7
Generates PCIE_TestPlan_20250704_183000.xlsx with TestPlan + MetaData sheets.
Outputs base64-encoded XLSX to stdout for GitHub upload.
"""
import sys, io, base64
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils import get_column_letter

wb = Workbook()
ws_tp = wb.active
ws_tp.title = "TestPlan"
ws_md = wb.create_sheet("MetaData")

TP_COLS = ["Index","SS / Module","Feature","Test Case Name","Test Description","Speed","Mode","Memory Start Offset","Memory End Offset","Remarks","Test Steps / Procedure","Impacted Registers","Validation / Acceptance Criteria","Code Generation"]
MD_COLS = ["Index","Test Case Name","Meta Test Description","Meta Test Steps / Procedure","Meta Impacted Registers","Meta Validation / Acceptance Criteria","Meta Headers","Meta Macros","Meta Arrays"]

hdr_font = Font(bold=True, color="FFFFFF", size=11)
hdr_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
hdr_align = Alignment(horizontal="center", vertical="top", wrap_text=True)
cell_align = Alignment(vertical="top", wrap_text=True)

for ci, col in enumerate(TP_COLS, 1):
    c = ws_tp.cell(row=1, column=ci, value=col)
    c.font, c.fill, c.alignment = hdr_font, hdr_fill, hdr_align

for ci, col in enumerate(MD_COLS, 1):
    c = ws_md.cell(row=1, column=ci, value=col)
    c.font, c.fill, c.alignment = hdr_font, hdr_fill, hdr_align

# === ROW DATA ===
ROWS = [
  {
    "idx":"1","mod":"PCIE","feat":"PCIe Device Enumeration","tc":"pcie_device_enumerate_test",
    "desc":"Verifies PCIe device enumeration by performing link training, configuring cache coherency via the COHERENCY_CONTROL_3_OFF register for both PCIe controller instances, polling the SII link status registers until link-up is confirmed, reading the TYPE1_DEV_ID_VEND_ID_REG to retrieve the endpoint Vendor ID, enabling IO, Memory, and Bus Master access via TYPE1_STATUS_COMMAND_REG, programming memory base addresses, performing BAR sizing and assignment on BAR0_REG, BAR1_REG, SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG, SEC_STAT_IO_LIMIT_IO_BASE_REG, MEM_LIMIT_MEM_BASE_REG, and PREF_MEM_LIMIT_PREF_MEM_BASE_REG for both PCIe slave ports, and polling a system handshake register for the expected completion value.",
    "regs":"COHERENCY_CONTROL_3_OFF; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG; BAR0_REG; BAR1_REG; SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG; SEC_STAT_IO_LIMIT_IO_BASE_REG; MEM_LIMIT_MEM_BASE_REG; PREF_MEM_LIMIT_PREF_MEM_BASE_REG",
    "val":"The test passes when all of the following conditions are met: 1. PCIe link training completes successfully for the configured controller mode. 2. The SII0 link status register reports link-up with the expected bit pattern confirming data link layer active and link-up status for PCIE0. 3. The SII1 link status register reports link-up with the expected bit pattern for PCIE1. 4. The TYPE1_DEV_ID_VEND_ID_REG returns a valid Vendor ID from the endpoint device. 5. TYPE1_STATUS_COMMAND_REG is successfully written to enable IO, Memory, and Bus Master access. 6. BAR sizing returns valid size information for all BARs on both PCIe slave ports. 7. BAR programming with actual address values completes and read-back confirms correct values. 8. The system handshake register returns the expected completion value, confirming the remote endpoint has completed its enumeration sequence. 9. The test calls finish(0) indicating successful completion.",
    "rem":"The testcase uses conditional compilation (DM0_RC, DM1_RC, DM0_EP, DM1_EP) to select between Root Complex and Endpoint modes and between dual-mode controller instances. Polling with wait_on() delays is used for link status confirmation and completion handshake. Several system-level registers used for configuration could not be mapped to named registers in the specification. The SII link status register at the polled offset could not be mapped to a named register. One coherency control macro for the second PCIe instance could not be resolved from the available headers.",
    "steps":"Initialization:\n1. Initialize the system by writing to the system control register.\n\nConfiguration:\n1. Perform PCIe link training for the configured controller mode (Root Complex or Endpoint).\n2. Enable cache coherency by programming the COHERENCY_CONTROL_3_OFF register for both PCIe controller instances with appropriate bit field values.\n3. Enable IO space, Memory space, and Bus Master access by writing to TYPE1_STATUS_COMMAND_REG.\n4. Program memory base addresses for both PCIe controller instances.\n5. Write to system-level configuration registers to enable required system settings.\n6. Disable cache coherency by clearing the relevant bit fields in COHERENCY_CONTROL_3_OFF for both instances.\n\nExecution:\n1. Wait for the coherency settings to take effect.\n2. Poll the SII0 link status register until PCIE0 link-up is confirmed.\n3. Poll the SII1 link status register until PCIE1 link-up is confirmed.\n4. In Root Complex mode, read the TYPE1_DEV_ID_VEND_ID_REG from the endpoint to retrieve the Vendor ID.\n5. Perform BAR sizing on PCIe slave port 1 by writing all-ones to BAR0_REG, BAR1_REG, SEC_LAT_TIMER_SUB_BUS_SEC_BUS_PRI_BUS_REG, SEC_STAT_IO_LIMIT_IO_BASE_REG, MEM_LIMIT_MEM_BASE_REG, and PREF_MEM_LIMIT_PREF_MEM_BASE_REG, then reading back to determine sizes.\n6. Program actual BAR values for PCIe slave port 1 and verify by reading back.\n7. Repeat BAR sizing and programming for PCIe slave port 0.\n8. Poll the system handshake register until the expected completion value is received.\n9. Confirm test completion.",
    "mdesc":"This testcase performs PCIe device enumeration across two PCIe controller instances (DM0 and DM1). It begins by writing 0x0 to 0xE6004100 to initialize the system. Link training is invoked conditionally based on compile-time defines (DM0_RC, DM1_RC, DM0_EP, DM1_EP) using link_training_dm0_x4(4) or link_training_dm1_x4(4). Cache coherency programming is performed by read-modify-write operations on mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF and mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF, setting bit fields [11:14], [3:6], [27:30], and [19:22] to 0xF using set_data(). After a wait_on(20), the same coherency registers are programmed again. The SII0 link status register at offset 0xC0 is polled via read_sii0_reg() until bits matching mask 0xD1 are all set, confirming link-up for PCIE0. Similarly, SII1 link status at 0xC0 is polled via read_sii1_reg() for PCIE1 link-up. Under DM0_RC, the Vendor ID is read from the endpoint via read_pcie_slv0_reg(0x0), the command register at offset 0x4 is written with 0x7 via write_pcie_slv0_reg() to enable IO, Memory, and Bus Master, and memory base programming functions mem_base_program_dm0_x4() and mem_base_program_dm1_x4() are called. System-level configuration registers at 0xE690000C through 0xE6900034 are written with 0x1. Cache coherency is then disabled by writing 0x0 to bit fields [19:22] and [27:30] of both coherency control registers. After wait_on(30), BAR sizing is performed on PCIe slave port 1 by writing 0xFFFFFFFF to offsets 0x10-0x24 via write_pcie_slv1_reg(), reading back via read_pcie_slv1_reg(), then programming actual BAR values. The same BAR sizing and programming sequence is repeated for PCIe slave port 0. Finally, the test polls 0xE6004100 via read_reg() in a while loop waiting for the value 0x12345678 as the completion handshake, with wait_on(5) between iterations, and calls finish(0) upon success.",
    "msteps":"1. Write 0x0 to 0xE6004100 to initialize the system. 2. Invoke link_training_dm0_x4(4) or link_training_dm1_x4(4) based on compile-time defines (DM0_RC, DM1_RC, DM0_EP, DM1_EP). 3. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, apply set_data() to set bit fields [11:14] and [3:6] to 0xF, write back. 4. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF again, set bit fields [27:30] and [19:22] to 0xF, write back. 5. Repeat steps 3-4 for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 6. Call wait_on(20). 7. Read mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF, set all four bit field groups to 0xF, write back. 8. Repeat step 7 for mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF. 9. Poll read_sii0_reg(0xC0) until (data_rd & 0xD1) == 0xD1. 10. Poll read_sii1_reg(0xC0) until (data_rd & 0xD1) == 0xD1. 11. Read Vendor ID, write 0x7 to enable IO/Memory/Bus Master, call mem_base_program functions. 12. Write 0x1 to system registers. 13-16. Disable cache and wait. 17-21. BAR sizing and programming for both slave ports. 22-24. Poll handshake and finish(0).",
    "mregs":"0xE6004100; mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF; mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF; 0xC0; 0x0; 0x4; 0xE690000C; 0xE6900010; 0xE6900014; 0xE6900018; 0xE6900030; 0xE6900034; 0x10; 0x14; 0x18; 0x1c; 0x20; 0x24"
  },
  {
    "idx":"2","mod":"PCIE","feat":"PCIe DMA Write and Read","tc":"pcie_dma_write_test",
    "desc":"Verifies PCIe DMA write and read data transfer operations across four DMA channels for both PCIe controller instances. The test performs link training, confirms link-up by polling the SII link status register, reads the TYPE1_DEV_ID_VEND_ID_REG to retrieve the endpoint Vendor ID, enables IO, Memory, and Bus Master access via TYPE1_STATUS_COMMAND_REG, configures BARs and memory base addresses, preloads source data into memory, unmasks DMA interrupts via DMA_WRITE_INT_MASK_OFF and DMA_READ_INT_MASK_OFF, sequentially programs and triggers DMA write transfers on channels 0 through 3 using DMA_WRITE_DOORBELL_OFF, waits for each transfer to complete via interrupt-driven handshake, then programs and triggers DMA read-back transfers on channels 0 through 3 using DMA_READ_DOORBELL_OFF. The interrupt handler reads DMA_WRITE_INT_STATUS_OFF and DMA_READ_INT_STATUS_OFF to determine which channels completed, then clears the interrupts via DMA_WRITE_INT_CLEAR_OFF and DMA_READ_INT_CLEAR_OFF. The test confirms successful completion of all DMA transfers across all channels.",
    "regs":"TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG; DMA_WRITE_INT_MASK_OFF; DMA_READ_INT_MASK_OFF; DMA_WRITE_DOORBELL_OFF; DMA_READ_DOORBELL_OFF; DMA_WRITE_INT_STATUS_OFF; DMA_READ_INT_STATUS_OFF; DMA_WRITE_INT_CLEAR_OFF; DMA_READ_INT_CLEAR_OFF",
    "val":"The test passes when all of the following conditions are met: 1. PCIe link training completes successfully for the configured controller mode. 2. The SII link status register reports link-up with the expected bit pattern. 3. The TYPE1_DEV_ID_VEND_ID_REG returns a valid Vendor ID. 4. TYPE1_STATUS_COMMAND_REG is successfully written to enable IO, Memory, and Bus Master access. 5. The system handshake register returns the expected completion value. 6. All four DMA write channel transfers complete successfully, each confirmed by an interrupt where DMA_WRITE_INT_STATUS_OFF reports the corresponding channel completion and the interrupt is cleared via DMA_WRITE_INT_CLEAR_OFF. 7. All four DMA read channel transfers complete successfully, each confirmed by an interrupt where DMA_READ_INT_STATUS_OFF reports the corresponding channel completion and the interrupt is cleared via DMA_READ_INT_CLEAR_OFF. 8. The test calls finish(0) indicating successful completion of all DMA operations.",
    "rem":"The testcase uses conditional compilation to select between two PCIe controller instances and between Root Complex and Endpoint modes. DMA transfers are performed sequentially across four channels, with each channel waiting for interrupt-driven completion before the next channel is triggered. The interrupt handler uses a shared flag to synchronize between the main test flow and the ISR. Source data is preloaded with two distinct patterns for verification purposes. Several register macros for the second PCIe controller instance could not be resolved from the available headers. The SII link status register and the system control register could not be mapped to named registers in the specification.",
    "steps":"Initialization:\n1. Initialize the system by writing to the system control register.\n2. Preload known data patterns into source memory regions.\n\nConfiguration:\n1. Perform PCIe link training for the configured controller mode.\n2. Enable IO space, Memory space, and Bus Master access by writing to TYPE1_STATUS_COMMAND_REG.\n3. Configure BARs and program memory base addresses for the active controller.\n4. Unmask DMA write and read interrupts by writing to DMA_WRITE_INT_MASK_OFF and DMA_READ_INT_MASK_OFF.\n\nExecution:\n1. Poll the SII link status register until link-up is confirmed for the active PCIe controller instance.\n2. Read the TYPE1_DEV_ID_VEND_ID_REG from the endpoint to retrieve the Vendor ID.\n3. Poll the system handshake register until the expected completion value is received.\n4. Program DMA write channel 0 with source address, destination address, and transfer length, then trigger the transfer by writing to DMA_WRITE_DOORBELL_OFF and wait for interrupt-driven completion.\n5. Repeat DMA write transfer for channels 1, 2, and 3, triggering each sequentially via DMA_WRITE_DOORBELL_OFF and waiting for completion.\n6. Program DMA read channel 0 with remote source address, local destination address, and transfer length, then trigger the transfer by writing to DMA_READ_DOORBELL_OFF and wait for interrupt-driven completion.\n7. Repeat DMA read transfer for channels 1, 2, and 3, triggering each sequentially via DMA_READ_DOORBELL_OFF and waiting for completion.\n8. Confirm test completion after all DMA write and read transfers on all four channels have completed successfully.\n\nInterrupt:\n1. Enable GIC interrupts for DMA completion notification.\n2. In the interrupt handler, read DMA_WRITE_INT_STATUS_OFF and DMA_READ_INT_STATUS_OFF to identify completed channels, then clear interrupts via DMA_WRITE_INT_CLEAR_OFF and DMA_READ_INT_CLEAR_OFF.",
    "mdesc":"This testcase validates PCIe DMA write and read operations across four DMA channels on two PCIe controller instances (DM0 and DM1). The test begins by writing 0x0 to 0xE6004100 to initialize the system. Link training is invoked conditionally. Under DM0_RC, the SII0 link status register at offset 0xC0 is polled. DMA write and read channels 0-3 are programmed and triggered via doorbell registers. The Default_IRQHandler reads interrupt status and clears interrupts.",
    "msteps":"1. Write 0x0 to 0xE6004100. 2. Invoke link training. 3. Poll SII link status. 4. Read Vendor ID, enable IO/Memory/Bus Master. 5. Configure BARs and memory base. 6-7. Same for DM1_RC. 8. Call non_secure_prot_nic(). 9. Poll handshake. 10-11. Preload source data. 12. Enable GIC interrupts. 13. Unmask DMA interrupts. 14-17. Program and trigger DMA write channels 0-3. 18-20. Program and trigger DMA read channels 0-3. 21-22. IRQ handler reads status and clears interrupts. 23. finish(0).",
    "mregs":"0xE6004100; 0xC0; 0x0; 0x4; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_MASK_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_MASK_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_DOORBELL_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_DOORBELL_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_MASK_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_MASK_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_DOORBELL_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_DOORBELL_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_STATUS_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_STATUS_OFF; mizar_PCIE0_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; mizar_PCIE0_DBI_DSP_DMA_READ_INT_CLEAR_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_STATUS_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_STATUS_OFF; mizar_PCIE1_DBI_DSP_DMA_WRITE_INT_CLEAR_OFF; mizar_PCIE1_DBI_DSP_DMA_READ_INT_CLEAR_OFF"
  },
  {
    "idx":"3","mod":"PCIE","feat":"PCIe Memory Write and Read","tc":"pcie_mem_wr_rd_test",
    "desc":"Verifies PCIe memory write and read data integrity across both PCIe controller instances in Root Complex and Endpoint modes. The test performs link training, configures cache coherency via the COHERENCY_CONTROL_3_OFF register for both controller instances, polls the SII link status registers until link-up is confirmed, reads the TYPE1_DEV_ID_VEND_ID_REG to retrieve the endpoint Vendor ID, enables IO, Memory, and Bus Master access via TYPE1_STATUS_COMMAND_REG, configures BARs and memory base addresses, writes a synchronization signal to a system control register, disables cache coherency in a staged sequence, then performs memory write-read verification at multiple target addresses through the PCIe slave ports. The test confirms data integrity by writing known patterns and reading them back, and polls a system handshake register for the expected completion value.",
    "regs":"COHERENCY_CONTROL_3_OFF; TYPE1_DEV_ID_VEND_ID_REG; TYPE1_STATUS_COMMAND_REG",
    "val":"The test passes when all of the following conditions are met: 1. PCIe link training completes successfully. 2. The SII link status register reports link-up. 3. The TYPE1_DEV_ID_VEND_ID_REG returns a valid Vendor ID. 4. TYPE1_STATUS_COMMAND_REG is successfully written. 5. All memory write-read operations complete successfully with data integrity confirmed. 6. The system handshake register returns the expected completion value. 7. The test calls finish(0) indicating successful completion.",
    "rem":"The testcase uses conditional compilation to select between Root Complex and Endpoint modes and between dual-mode controller instances. In Root Complex mode, three memory addresses are tested with distinct data patterns. In Endpoint mode, five BAR1 addresses are tested with a uniform data pattern. Cache coherency is enabled before link-up and disabled in a staged two-step sequence after BAR and memory base configuration. The SII link status register and the system control register could not be mapped to named registers in the specification. One coherency control macro for the second PCIe instance could not be resolved from the available headers.",
    "steps":"Initialization:\n1. Initialize the system by writing to the system control register.\n\nConfiguration:\n1. Perform PCIe link training for the configured controller mode (Root Complex or Endpoint).\n2. Enable cache coherency by programming the COHERENCY_CONTROL_3_OFF register for both PCIe controller instances with appropriate bit field values.\n3. Re-program the COHERENCY_CONTROL_3_OFF register for both instances to consolidate all coherency bit fields.\n4. Enable IO space, Memory space, and Bus Master access by writing to TYPE1_STATUS_COMMAND_REG.\n5. Configure BARs and program memory base addresses for the active controller.\n6. Call the non-secure protection NIC configuration function.\n7. Write a synchronization signal to the system control register.\n8. Disable cache coherency in a staged sequence by clearing the relevant bit fields in COHERENCY_CONTROL_3_OFF for both instances.\n\nExecution:\n1. Wait for the coherency settings to take effect.\n2. Poll the SII link status register until link-up is confirmed for the active PCIe controller instance.\n3. In Root Complex mode, read the TYPE1_DEV_ID_VEND_ID_REG from the endpoint to retrieve the Vendor ID.\n4. Wait for the cache disable settings to take effect.\n5. Perform memory write-read verification at multiple target addresses through the PCIe slave port, writing known data patterns and reading them back.\n6. Poll the system handshake register until the expected completion value is received.\n7. Confirm test completion.",
    "mdesc":"This testcase validates PCIe memory write and read operations across both PCIe controller instances (DM0 and DM1) in Root Complex and Endpoint modes. The test begins by writing 0x0 to 0xE6004100 to initialize the system. Cache coherency programming is performed. Link status is polled. Memory write-read tests are performed at multiple addresses with known data patterns.",
    "msteps":"1. Write 0x0 to 0xE6004100. 2. Link training. 3-5. Cache coherency programming. 6. wait_on(20). 7-8. Re-program coherency. 9-10. Poll link status. 11. EP wait. 12-15. Configure BARs and memory base. 16-17. NIC config and sync signal. 18-22. Staged cache disable. 23. wait_on(30). 24-27. Memory write-read tests. 28-30. Poll handshake and finish(0).",
    "mregs":"0xE6004100; mizar_PCIE0_DBI_DSP_COHERENCY_CONTROL_3_OFF; mizar_PCIE1_DBI_DSP_COHERENCY_CONTROL_3_OFF; 0xC0; 0x0; 0x4"
  },
  {
    "idx":"4","mod":"PCIE","feat":"PCIe Register Write/Read Verification","tc":"pcie_reg_wr_rd_test",
    "desc":"Verifies the reset default values and write-read data integrity of PCIe DBI controller registers, SII registers, and PHY registers across two PCIe controller instances. The test first reads all target registers and compares them against their expected default values of zero. It then writes the PHY reset control registers to bring the PHY out of reset before checking PHY register defaults. In the write-read phase, the test iterates through multiple data patterns and writes each pattern to all DBI controller registers (MSI_CAP_OFF_08H_REG, MSI_CAP_OFF_10H_REG, FILTER_MASK_2_OFF, AXI_MSTR_MSG_ADDR_HIGH_OFF, UTILITY_OFF), SII registers, and PHY registers, applying appropriate write masks. After each write, the test reads back every register and compares the read value against the expected written value, accounting for write masks. The test reports pass if all default value checks and all write-read comparisons succeed with zero errors across both controller instances.",
    "regs":"MSI_CAP_OFF_08H_REG; MSI_CAP_OFF_10H_REG; FILTER_MASK_2_OFF; AXI_MSTR_MSG_ADDR_HIGH_OFF; UTILITY_OFF",
    "val":"The test passes when all of the following conditions are met: 1. All five DBI controller registers for both PCIe instances read back their expected default value of zero. 2. All three SII registers for both instances read back their expected default value of zero. 3. All three PHY registers for both instances read back their expected default value of zero after PHY reset is released. 4. For each of the three write-read data patterns, all five DBI controller registers for both instances read back the exact value that was written. 5. For each data pattern, all SII registers read back the written value masked with the applicable write mask. 6. For each PHY-specific data pattern, all PHY registers read back the written value masked with the PHY write mask after half-word extraction. 7. Both error counters remain zero, and the test completes with a pass indication.",
    "rem":"The testcase covers three register groups: DBI controller registers, SII registers, and PHY registers across two PCIe controller instances. Write masks are applied to SII and PHY registers to account for read-only or reserved bit fields. PHY registers use half-word access with bit extraction based on address alignment. The PHY reset control registers are written before PHY register access to ensure the PHY is out of reset. Only three of the six defined data patterns are used in the write-read loop. Several SII register macros, PHY reset control macros, and PHY register addresses for both controller instances could not be mapped to named registers in the specification.",
    "steps":"Initialization:\n1. Write to the PHY reset control registers for both instances to bring the PHY out of reset.\n\nExecution:\n1. Read all five DBI controller registers for both PCIe controller instances and verify that each register contains its expected default value of zero.\n2. Read all three SII registers for both PCIe controller instances and verify that each register contains its expected default value of zero.\n3. Read all three PHY registers for both instances, extract the relevant half-word, and verify that each contains its expected default value of zero.\n4. For each of three data patterns, write the pattern to all five DBI controller registers (MSI_CAP_OFF_08H_REG, MSI_CAP_OFF_10H_REG, FILTER_MASK_2_OFF, AXI_MSTR_MSG_ADDR_HIGH_OFF, UTILITY_OFF) for both instances.\n5. For each data pattern, write the pattern masked with the appropriate write mask to all three SII registers for both instances.\n6. For each data pattern, write the PHY-specific pattern masked with the PHY write mask to all three PHY registers for both instances.\n7. After each write iteration, read back all DBI controller registers and verify the read value matches the written value.\n8. After each write iteration, read back all SII registers and verify the read value matches the written value accounting for the write mask.\n9. After each write iteration, read back all PHY registers, extract the relevant half-word, and verify the read value matches the written value accounting for the PHY write mask.\n10. Confirm that all default value checks and all write-read comparisons passed with zero errors across both controller instances.",
    "mdesc":"This testcase validates the reset default values and write-read integrity of PCIe registers across multiple register groups on two PCIe controller instances (PCIE0 and PCIE1), SII registers, and PHY registers. Register address arrays are defined for DBI controller, SII, and PHY registers. Default values and write masks are initialized. The test calls chk_rst_val() then chk_rd_wr() and finishes with error status.",
    "msteps":"1. Declare register address arrays. 2-3. Initialize defaults and write masks. 4. Call chk_rst_val(). 5-8. Read and verify DBI and SII register defaults. 9. Write PHY reset control. 10-11. Read and verify PHY defaults. 12. Call chk_rd_wr(). 13. Define check values. 14-20. Write patterns to all register groups. 21-26. Read back and verify all register groups. 27. End loop. 28. finish(err2 || err1).",
    "mregs":"mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_08H_REG; mizar_PCIE0_DBI_DSP_MSI_CAP_OFF_10H_REG; mizar_PCIE0_DBI_DSP_FILTER_MASK_2_OFF; mizar_PCIE0_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF; mizar_PCIE0_DBI_DSP_UTILITY_OFF; mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_08H_REG; mizar_PCIE1_DBI_DSP_MSI_CAP_OFF_10H_REG; mizar_PCIE1_DBI_DSP_FILTER_MASK_2_OFF; mizar_PCIE1_DBI_DSP_AXI_MSTR_MSG_ADDR_HIGH_OFF; mizar_PCIE1_DBI_DSP_UTILITY_OFF; mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER2; mizar_PCIE0_SII_PCIE0_TRANSMIT_HEADER3; mizar_PCIE0_SII_PHY_CONTROL_23; mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER2; mizar_PCIE1_SII_PCIE1_TRANSMIT_HEADER3; mizar_PCIE1_SII_PHY_CONTROL_23; mizar_PCIE0_SII_PHY_RST_CONTROL; mizar_PCIE1_SII_PHY_RST_CONTROL; 0xE68860B8; 0xE68862B8; 0xE68864B8; 0xE68A60B8; 0xE68A62B8; 0xE68A64B8"
  }
]

for ri, r in enumerate(ROWS, 2):
    ws_tp.cell(row=ri, column=1, value=r["idx"]).alignment = cell_align
    ws_tp.cell(row=ri, column=2, value=r["mod"]).alignment = cell_align
    ws_tp.cell(row=ri, column=3, value=r["feat"]).alignment = cell_align
    ws_tp.cell(row=ri, column=4, value=r["tc"]).alignment = cell_align
    ws_tp.cell(row=ri, column=5, value=r["desc"]).alignment = cell_align
    ws_tp.cell(row=ri, column=6, value="").alignment = cell_align
    ws_tp.cell(row=ri, column=7, value="").alignment = cell_align
    ws_tp.cell(row=ri, column=8, value="").alignment = cell_align
    ws_tp.cell(row=ri, column=9, value="").alignment = cell_align
    ws_tp.cell(row=ri, column=10, value=r["rem"]).alignment = cell_align
    ws_tp.cell(row=ri, column=11, value=r["steps"]).alignment = cell_align
    ws_tp.cell(row=ri, column=12, value=r["regs"]).alignment = cell_align
    ws_tp.cell(row=ri, column=13, value=r["val"]).alignment = cell_align
    ws_tp.cell(row=ri, column=14, value="").alignment = cell_align

    ws_md.cell(row=ri, column=1, value=r["idx"]).alignment = cell_align
    ws_md.cell(row=ri, column=2, value=r["tc"]).alignment = cell_align
    ws_md.cell(row=ri, column=3, value=r["mdesc"]).alignment = cell_align
    ws_md.cell(row=ri, column=4, value=r["msteps"]).alignment = cell_align
    ws_md.cell(row=ri, column=5, value=r["mregs"]).alignment = cell_align
    ws_md.cell(row=ri, column=6, value=r["val"]).alignment = cell_align
    ws_md.cell(row=ri, column=7, value="").alignment = cell_align
    ws_md.cell(row=ri, column=8, value="").alignment = cell_align
    ws_md.cell(row=ri, column=9, value="").alignment = cell_align

dv = DataValidation(type="list", formula1='"Required,Not Required"', allow_blank=True)
dv.error = "Please select Required or Not Required"
dv.errorTitle = "Invalid Input"
dv.prompt = "Select Code Generation status"
dv.promptTitle = "Code Generation"
dv.sqref = f"{get_column_letter(14)}2:{get_column_letter(14)}1000"
ws_tp.add_data_validation(dv)

TP_W = {1:8,2:15,3:30,4:35,5:60,6:10,7:10,8:20,9:20,10:50,11:90,12:60,13:70,14:18}
for c,w in TP_W.items(): ws_tp.column_dimensions[get_column_letter(c)].width = w
MD_W = {1:8,2:35,3:80,4:80,5:80,6:70,7:30,8:30,9:30}
for c,w in MD_W.items(): ws_md.column_dimensions[get_column_letter(c)].width = w

ws_tp.freeze_panes = "A2"
ws_md.freeze_panes = "A2"
ws_md.sheet_state = "veryHidden"
wb.active = 0

buf = io.BytesIO()
wb.save(buf)
buf.seek(0)
b64 = base64.b64encode(buf.read()).decode("ascii")
print(b64)
